In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
def missing_values(df):
    for feature in df.columns:
        missing_values = df[feature].isna().sum()
        percentage = missing_values/len(df) * 100
        print(f'{feature} - {missing_values} - {round(percentage, 1)} %')
        
def fill_with_mode(df, feature_list):
    for feature in feature_list:
        mode = df[feature].mode()[0]
        df[feature].fillna(value=mode, inplace=True)

def fill_with_mean(df, feature_list):
    for feature in feature_list:
        df[feature] = pd.to_numeric(df[feature], errors='coerce')
        mean = df[feature].mean()
        df[feature].fillna(value=mean, inplace=True)

In [3]:
df_dk = pd.read_csv("Data/y/Denmark.csv")

In [4]:
df_dk = df_dk.loc[6:22]

In [5]:
df_dk

,Unnamed: 0,REF_AREA_LABEL,TIME_PERIOD,HI,LF,UR,URFF,YUA,FDI,QOR,...,EIA,EBSG,GDPC,GDP,EIS,NINA,LBGD,EMP,LTU,FEM
6,6,Denmark,2006,NaN,2.93,3.90,4.53,7.69,0.84,6.36,...,3.088325,3.938871,309942.332478,2.087455e+12,73.580644,1.362713,5.490254,:,:,NaN
7,7,Denmark,2007,NaN,2.93,3.80,4.20,7.49,3.69,6.42,...,2.963823,2.747300,319173.149269,2.108062e+12,73.529373,1.734853,5.548536,:,:,:
8,8,Denmark,2008,NaN,2.92,3.68,4.07,9.47,0.62,6.23,...,2.705862,3.471527,329422.223703,2.099268e+12,74.038959,1.614779,3.835619,:,:,:
9,9,Denmark,2009,NaN,2.91,6.41,5.67,13.44,1.17,6.06,...,2.759311,4.602963,313144.896657,1.994840e+12,76.669794,1.614948,-2.111442,76.1,0.6,73.1
10,10,Denmark,2010,NaN,2.89,7.75,6.76,15.55,-3.57,6.17,...,2.543765,6.793833,326784.316443,2.026416e+12,77.590382,1.782949,-2.441067,74.9,1.4,72.0
11,11,Denmark,2011,NaN,2.89,7.77,7.62,16.31,3.94,6.29,...,2.394463,6.154324,331838.652835,2.052979e+12,77.570639,1.709736,-1.887012,74.8,1.8,71.4
12,12,Denmark,2012,NaN,2.88,7.80,7.79,15.77,-5.00,5.73,...,2.637166,5.799405,338534.135302,2.052867e+12,77.594093,2.043067,-3.257951,74.3,2.1,71.1
13,13,Denmark,2013,7.69,2.85,7.38,7.67,14.77,0.20,5.45,...,2.593595,6.229005,344715.698783,2.081457e+12,77.765169,2.004696,-1.181728,74.3,1.8,71.2
14,14,Denmark,2014,NaN,2.87,6.93,7.14,14.20,1.86,5.43,...,2.480217,6.455948,350893.947080,2.108058e+12,78.149649,2.200518,1.252108,74.7,1.7,71.0
15,15,Denmark,2015,7.53,2.90,6.28,6.53,12.15,0.61,5.59,...,2.491587,6.498281,357211.575191,2.152420e+12,78.083956,2.024130,-1.143677,75.4,1.6,71.5
16,16,Denmark,2016,7.53,2.94,5.99,6.38,12.15,2.50,5.70,...,2.334158,6.035122,366884.878867,2.218565e+12,78.617617,2.175615,-0.070663,76.0,1.2,72.5
17,17,Denmark,2017,7.52,2.97,5.83,6.05,12.38,1.09,5.50,...,2.110610,6.476226,379808.676526,2.286375e+12,78.951173,NaN,1.457031,76.6,1.2,73.2
18,18,Denmark,2018,7.56,2.99,5.13,5.35,10.52,2.47,5.50,...,2.191696,5.152751,387242.522658,2.328902e+12,78.898577,NaN,0.801500,77.5,1.0,73.9
19,19,Denmark,2019,7.60,3.03,5.02,5.27,10.04,-1.10,5.60,...,2.222962,6.009741,396193.582956,2.368759e+12,79.231066,NaN,4.079333,78.3,0.8,74.7
20,20,Denmark,2020,7.62,3.03,5.64,5.98,11.59,0.36,NaN,...,2.114530,5.640362,398976.348406,2.326592e+12,78.996916,NaN,0.081707,77.8,0.9,74.3
21,21,Denmark,2021,7.64,3.08,5.04,5.14,10.81,4.16,NaN,...,2.044519,6.236804,438387.741596,2.498343e+12,78.620328,NaN,3.868870,79.0,1.0,75.5
22,22,Denmark,2022,7.59,3.15,4.43,4.49,10.53,7.67,NaN,...,2.117067,9.553789,481824.514568,2.536822e+12,78.808652,NaN,3.323468,80.1,0.5,77.4

In [6]:
df_dk = df_dk.copy()
df_dk['LFG'] = df_dk['LF'].diff()
df_dk['EPFRG'] = df_dk['EPFR'].diff()
df_dk['GGAG'] = df_dk['GGA'].diff()
df_dk = df_dk.drop(6)

In [7]:
df_dk = df_dk.drop(["Unnamed: 0", "REF_AREA_LABEL", "HI", "OCTB", "NINA", "LF", "EPFR", "GGA", "EIA", "GDP"], axis=1)

In [8]:
df_dk["EMP"] = df_dk["EMP"].replace(':', np.nan)
df_dk["LTU"] = df_dk["LTU"].replace(':', np.nan)
df_dk["FEM"] = df_dk["FEM"].replace(':', np.nan)

In [9]:
missing_values(df_dk)

TIME_PERIOD - 0 - 0.0 %
UR - 0 - 0.0 %
URFF - 0 - 0.0 %
YUA - 0 - 0.0 %
FDI - 0 - 0.0 %
QOR - 3 - 18.8 %
QOA - 3 - 18.8 %
EIAP - 0 - 0.0 %
PS - 0 - 0.0 %
PDPS - 1 - 6.2 %
P65 - 0 - 0.0 %
P014 - 0 - 0.0 %
PGP - 0 - 0.0 %
VABI - 0 - 0.0 %
GCFP - 0 - 0.0 %
GGFC - 0 - 0.0 %
GDPCG - 0 - 0.0 %
EII - 0 - 0.0 %
EBSG - 0 - 0.0 %
GDPC - 0 - 0.0 %
EIS - 0 - 0.0 %
LBGD - 0 - 0.0 %
EMP - 2 - 12.5 %
LTU - 2 - 12.5 %
FEM - 2 - 12.5 %
LFG - 0 - 0.0 %
EPFRG - 1 - 6.2 %
GGAG - 2 - 12.5 %

In [10]:
fill_with_mode(df_dk, ["QOR", "QOA"])

In [11]:
fill_with_mean(df_dk, ["EMP", "LTU", "FEM", "EPFRG", "GGAG", "PDPS"])

In [12]:
dk_context_2007_2015 = pd.read_csv("Data/Context/Denmark_2007_2015.csv")

In [13]:
dk_context_2007_2015 = dk_context_2007_2015[["TIME_PERIOD", "ROL", "GE", "COC", "VAA", "CPI"]]

In [14]:
dk_context_2007_2015

   TIME_PERIOD   ROL    GE   COC   VAA   CPI
0         2007  2.00  2.35  2.43  1.48  94.0
1         2008  1.95  2.24  2.38  1.54  93.0
2         2009  1.92  2.23  2.44  1.54  93.0
3         2010  1.90  2.10  2.35  1.54  93.0
4         2011  1.92  2.10  2.39  1.55  94.0
5         2012  1.88  1.99  2.38  1.67  90.0
6         2013  1.90  1.94  2.40  1.67  91.0
7         2014  2.10  1.78  2.25  1.52  92.0
8         2015  2.02  1.79  2.19  1.55  91.0

In [15]:
eu_payments = pd.read_csv("Raw_Data/Variables/Historic_EU_payments_annual_timeseries_-_regionalised_and_modelled_20251209.csv")

In [16]:
eu_payments = eu_payments.drop(['NUTS1_ID', 'NUTS2 code+name', 'NUTS2_ID', 'NUTS2_name', 'Modelled_annual_expenditure',
                  'Standard_Deviation_of_annual_expenditure', 'Standard_Error_of_modelled_annual_expenditure'], axis=1)

In [17]:
dk_eu_payments = eu_payments[eu_payments['Country'] == 'DK'].copy()

In [18]:
dk_eu_payments

     Country  Fund  Year Programming_Period EU_Payment_annual
833       DK  ERDF  2007          2007-2013         1,194,717
834       DK  ERDF  2008          2007-2013         1,792,076
835       DK  ERDF  2009          2007-2013         2,228,417
836       DK  ERDF  2010          2007-2013         4,678,038
837       DK  ERDF  2011          2007-2013        15,425,586
...      ...   ...   ...                ...               ...
2483      DK   ESF  2018          2014-2020         2,077,670
2484      DK   ESF  2019          2014-2020         2,615,692
2485      DK   ESF  2020          2014-2020         2,376,965
2486      DK   ESF  2021          2014-2020         4,074,111
2487      DK   ESF  2022          2014-2020         3,321,554

[180 rows x 5 columns]

In [19]:
dk_eu_payments['EU_Payment_annual'] = pd.to_numeric(dk_eu_payments['EU_Payment_annual'].str.replace(',', ''))

In [20]:
dk_eu_payments_2007_2015 = dk_eu_payments[dk_eu_payments['Programming_Period'] == '2007-2013'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

In [21]:
dk_eu_payments_2007_2015 = dk_eu_payments_2007_2015.rename({"Year":"TIME_PERIOD"}, axis=1)

In [22]:
dk_eu_payments_2007_2015

   TIME_PERIOD  EU_Payment_annual
0         2007           10191540
1         2008           15287312
2         2009           33350959
3         2010           41600829
4         2011           94651644
5         2012           35523496
6         2013           46669931
7         2014          134429401
8         2015           72393232
9         2017           25478856

In [23]:
dk_eu_payments_2007_2015 = dk_eu_payments_2007_2015.loc[0:8]

In [24]:
df_dk_2007_2015 = df_dk.loc[7:15]

In [25]:
df_dk_2007_2015

,TIME_PERIOD,UR,URFF,YUA,FDI,QOR,QOA,EIAP,PS,PDPS,...,EBSG,GDPC,EIS,LBGD,EMP,LTU,FEM,LFG,EPFRG,GGAG
7,2007,3.80,4.20,7.49,3.69,6.42,6.45,2.96,5.46,137.0,...,2.747300,319173.149269,73.529373,5.548536,76.414286,1.257143,73.057143,0.00,1099.00,-4900.0
8,2008,3.68,4.07,9.47,0.62,6.23,6.44,2.71,5.49,137.0,...,3.471527,329422.223703,74.038959,3.835619,76.414286,1.257143,73.057143,-0.01,-207.00,-3557.0
9,2009,6.41,5.67,13.44,1.17,6.06,6.43,2.76,5.52,138.0,...,4.602963,313144.896657,76.669794,-2.111442,76.100000,0.600000,73.100000,-0.01,-25.80,-2932.0
10,2010,7.75,6.76,15.55,-3.57,6.17,6.37,2.54,5.55,139.0,...,6.793833,326784.316443,77.590382,-2.441067,74.900000,1.400000,72.000000,-0.02,2364.18,251.0
11,2011,7.77,7.62,16.31,3.94,6.29,6.32,2.39,5.57,139.0,...,6.154324,331838.652835,77.570639,-1.887012,74.800000,1.800000,71.400000,0.00,1755.68,-5488.0
12,2012,7.80,7.79,15.77,-5.00,5.73,5.97,2.64,5.59,140.0,...,5.799405,338534.135302,77.594093,-3.257951,74.300000,2.100000,71.100000,-0.01,656.38,-5127.0
13,2013,7.38,7.67,14.77,0.20,5.45,5.64,2.59,5.61,140.0,...,6.229005,344715.698783,77.765169,-1.181728,74.300000,1.800000,71.200000,-0.03,1134.28,1404.0
14,2014,6.93,7.14,14.20,1.86,5.43,5.56,2.48,5.64,141.0,...,6.455948,350893.947080,78.149649,1.252108,74.700000,1.700000,71.000000,0.02,2013.96,-4198.0
15,2015,6.28,6.53,12.15,0.61,5.59,5.58,2.49,5.68,142.0,...,6.498281,357211.575191,78.083956,-1.143677,75.400000,1.600000,71.500000,0.03,950.39,-2024.0

In [26]:
df_dk_2007_2015 = pd.merge(df_dk_2007_2015, dk_context_2007_2015, on='TIME_PERIOD', how='outer')

In [27]:
df_dk_2007_2015 = pd.merge(df_dk_2007_2015, dk_eu_payments_2007_2015, on='TIME_PERIOD', how='outer')

In [28]:
df_dk_2007_2015['EUPC'] = df_dk_2007_2015['EU_Payment_annual'] / df_dk_2007_2015['PS']

In [29]:
df_dk_2007_2015 = df_dk_2007_2015.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [30]:
df_dk_2007_2015.to_csv('Data/y/dk_2007_2015_bn.csv', index=True)

In [31]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_dk_2007_2015.values)

df_dk_2007_2015_scaled = pd.DataFrame(scaled_features, index=df_dk_2007_2015.index, columns=df_dk_2007_2015.columns)

In [32]:
df_dk_2007_2015_scaled.to_csv('Data/y/dk_2007_2015_tcdf.csv')

In [33]:
df_dk_2007_2015_scaled

,UR,URFF,YUA,FDI,QOR,QOA,EIAP,PDPS,P65,P014,...,FEM,LFG,EPFRG,GGAG,ROL,GE,COC,VAA,CPI,EUPC
0,-1.713828,-1.611191,-2.019567,1.173421,1.358899,0.978300,2.094124,-1.373606,-1.445918,1.457446,...,1.323882,0.188982,0.020307,-0.852555,0.671500,1.551791,0.933008,-1.346568,1.25,-1.156710
1,-1.792257,-1.707124,-1.323999,0.081416,0.831979,0.951538,0.564326,-1.373606,-1.195834,1.157200,...,1.323882,-0.377964,-1.571716,-0.264682,-0.065512,0.967657,0.296866,-0.363937,0.50,-1.019475
2,-0.007988,-0.526404,0.070650,0.277052,0.360524,0.924776,0.870285,-0.755483,-0.874299,0.819422,...,1.374440,-0.377964,-1.350832,0.008901,-0.507719,0.914554,1.060236,-0.363937,0.50,-0.532527
3,0.867807,0.277961,0.811886,-1.408974,0.665583,0.764204,-0.475937,-0.137361,-0.463448,0.444114,...,0.076774,-0.944911,1.562571,1.402200,-0.802524,0.224213,-0.084819,-0.363937,0.50,-0.315189
4,0.880878,0.912598,1.078872,1.262346,0.998375,0.630394,-1.393816,-0.137361,0.000992,0.050041,...,-0.631044,0.188982,0.820805,-1.109941,-0.507719,0.224213,0.424094,-0.200165,1.25,1.104643
5,0.900486,1.038050,0.889172,-1.917628,-0.554653,-0.306276,0.135982,0.480762,0.465433,-0.362798,...,-0.984953,-0.377964,-0.519250,-0.951920,-1.097329,-0.359921,0.296866,1.765096,-1.75,-0.485736
6,0.625983,0.949496,0.537875,-0.067979,-1.331167,-1.189423,-0.169978,0.480762,0.867352,-0.794402,...,-0.866983,-1.511858,0.063314,1.906904,-0.802524,-0.625437,0.551323,1.765096,-1.00,-0.192092
7,0.331873,0.558382,0.337635,0.522486,-1.386632,-1.403519,-0.843089,1.098885,1.197819,-1.207241,...,-1.102923,1.322876,1.135650,-0.545267,2.145524,-1.475087,-1.357102,-0.691481,-0.25,2.127476
8,-0.092953,0.108233,-0.382523,0.077859,-0.942910,-1.349995,-0.781897,1.717007,1.447902,-1.563783,...,-0.513074,1.889822,-0.160849,0.406361,0.966305,-1.421984,-2.120472,-0.200165,-1.00,0.469610

In [34]:
column_index = df_dk_2007_2015_scaled.columns.get_loc('QOA')
print(column_index)

5

18,5,0

In [35]:
dk_context_2016_2022 = pd.read_csv("Data/Context/Denmark_2016_2022.csv")

dk_context_2016_2022 = dk_context_2016_2022[["TIME_PERIOD", "DI", "COC", "CPI", "ROL", "VAA"]]

df_dk_2016_2022 = df_dk.loc[15:22]
dk_eu_payments_2016_2022 = dk_eu_payments[dk_eu_payments['Programming_Period'] == '2014-2020'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

In [36]:
dk_eu_payments_2016_2022 = dk_eu_payments_2016_2022.loc[1:7]
dk_eu_payments_2016_2022

   Year  EU_Payment_annual
1  2016            2300472
2  2017           33510236
3  2018           39263352
4  2019           51874270
5  2020           52197125
6  2021           80908322
7  2022           75033080

In [37]:
dk_eu_payments_2016_2022 = dk_eu_payments_2016_2022.rename({"Year":"TIME_PERIOD"}, axis=1)

df_dk_2016_2022 = pd.merge(df_dk_2016_2022, dk_context_2016_2022, on='TIME_PERIOD', how='outer')

df_dk_2016_2022 = pd.merge(df_dk_2016_2022, dk_eu_payments_2016_2022, on='TIME_PERIOD', how='outer')

df_dk_2016_2022['EUPC'] = df_dk_2016_2022['EU_Payment_annual'] / df_dk_2016_2022['PS']

df_dk_2016_2022 = df_dk_2016_2022.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

# fill_with_mode(df_dk_2016_2022, ["DI", "CPI"])
# fill_with_mean(df_dk_2016_2022, ["COC", "ROL", "VAA"])
df_dk_2016_2022 = df_dk_2016_2022.drop(0)

In [38]:
df_dk_2016_2022

,UR,URFF,YUA,FDI,QOR,QOA,EIAP,PDPS,P65,P014,...,FEM,LFG,EPFRG,GGAG,DI,COC,CPI,ROL,VAA,EUPC
1,5.99,6.38,12.15,2.50,5.7,5.8,2.33,143.000000,18.94,16.77,...,72.5,0.04,-548.050,1635.000000,9.20,2.20,90.0,1.88,1.54,4.014785e+05
2,5.83,6.05,12.38,1.09,5.5,6.1,2.11,144.000000,19.18,16.67,...,73.2,0.03,3409.890,-2276.000000,9.22,2.19,88.0,1.80,1.52,5.817749e+06
3,5.13,5.35,10.52,2.47,5.5,5.8,2.19,145.000000,19.44,16.55,...,73.9,0.02,-1035.440,-555.000000,9.22,2.16,88.0,1.77,1.57,6.781235e+06
4,5.02,5.27,10.04,-1.10,5.6,5.8,2.22,145.000000,19.71,16.43,...,74.7,0.04,2311.730,-3538.000000,9.22,2.12,87.0,1.83,1.54,8.928446e+06
5,5.64,5.98,11.59,0.36,5.5,5.8,2.11,146.000000,20.00,16.31,...,74.3,0.00,372.670,-2434.000000,9.15,2.24,88.0,1.81,1.51,8.953195e+06
6,5.04,5.14,10.81,4.16,5.5,5.8,2.04,146.000000,20.25,16.17,...,75.5,0.05,2650.040,-2409.928571,9.09,2.33,88.0,1.90,1.54,1.380688e+07
7,4.43,4.49,10.53,7.67,5.5,5.8,2.12,141.466667,20.40,16.04,...,77.4,0.07,1126.794,-2409.928571,9.28,2.40,90.0,1.90,1.59,1.271747e+07

In [39]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_dk_2016_2022.values)

df_dk_2016_2022_scaled = pd.DataFrame(scaled_features, index=df_dk_2016_2022.index, columns=df_dk_2016_2022.columns)

In [40]:
df_dk_2016_2022_scaled.to_csv('Data/y/dk_2016_2022_tcdf.csv')

In [41]:
column_index = df_dk_2016_2022_scaled.columns.get_loc('EUPC')
print(column_index)

31

====================================================================

In [42]:
df_de = pd.read_csv("Data/y/Germany.csv")

In [43]:
df_de = df_de.loc[6:22]

In [44]:
df_de

,Unnamed: 0,REF_AREA_LABEL,TIME_PERIOD,HI,LF,UR,URFF,YUA,FDI,QOR,...,EIA,EBSG,GDPC,GDP,EIS,NINA,LBGD,EMP,LTU,FEM
6,6,Germany,2006,NaN,41.69,10.28,10.27,13.40,2.87,6.55,...,2.267958,5.179706,29452.349191,3.019797e+12,68.079555,0.636513,-1.173821,:,:,NaN
7,7,Germany,2007,NaN,41.80,8.73,8.77,11.82,1.46,6.55,...,2.258529,6.389770,30902.298694,3.107073e+12,67.844959,0.528878,-0.168868,:,:,:
8,8,Germany,2008,NaN,41.80,7.51,7.72,10.93,0.81,6.54,...,1.784493,5.783688,31539.117534,3.135360e+12,68.872285,0.581297,-0.295519,:,:,:
9,9,Germany,2009,NaN,41.82,7.88,7.49,11.31,1.63,6.49,...,1.682380,4.768184,30461.535107,2.961499e+12,69.521232,0.729682,-2.070729,73.2,3.6,67.8
10,10,Germany,2010,NaN,41.86,7.04,6.59,10.42,2.48,6.42,...,1.647158,5.103897,31990.195768,3.084305e+12,70.042845,0.529175,-3.199506,74.0,3.3,68.8
11,11,Germany,2011,NaN,41.52,5.97,5.71,8.93,2.55,6.15,...,1.644381,4.852664,34229.966763,3.200212e+12,70.119648,0.702075,-0.370659,75.4,2.8,70.3
12,12,Germany,2012,NaN,41.76,5.37,5.23,8.12,1.82,6.09,...,1.560606,6.037145,34819.413660,3.215391e+12,70.246157,0.727771,0.092987,75.8,2.5,70.7
13,13,Germany,2013,6.51,42.18,5.32,4.99,7.82,1.76,6.01,...,1.446238,5.772928,35554.076381,3.227809e+12,70.775316,0.652183,0.204270,76.3,2.4,71.5
14,14,Germany,2014,NaN,42.45,4.98,4.63,7.61,0.44,5.88,...,1.428273,6.537450,36861.914611,3.297837e+12,70.519282,0.588466,0.684115,76.7,2.2,72.2
15,15,Germany,2015,6.75,42.69,4.61,4.20,7.33,1.82,5.72,...,1.393993,7.417530,37774.244301,3.352341e+12,70.915917,0.624469,0.679371,77.0,2.1,72.7
16,16,Germany,2016,6.99,43.12,4.10,3.72,7.08,1.64,5.60,...,1.308278,7.263048,38811.920567,3.429267e+12,71.310002,0.644347,0.736708,77.6,1.7,73.6
17,17,Germany,2017,6.95,43.39,3.78,3.32,6.77,2.89,5.50,...,1.276623,7.085326,40300.397055,3.522407e+12,71.318137,NaN,0.636665,78.3,1.6,74.3
18,18,Germany,2018,6.97,43.61,3.38,2.90,6.22,4.00,5.50,...,1.249539,5.987124,41385.895136,3.561733e+12,71.410475,NaN,1.111879,79.0,1.4,75.0
19,19,Germany,2019,6.99,43.98,3.16,2.72,5.86,1.91,5.30,...,1.204148,5.638862,42541.268417,3.596919e+12,71.613724,NaN,0.767070,79.7,1.2,75.7
20,20,Germany,2020,7.16,43.37,3.88,3.49,7.86,4.49,NaN,...,1.220721,5.345110,41481.287516,3.449620e+12,71.407459,NaN,-3.657127,78.3,1.1,74.6
21,21,Germany,2021,7.03,43.28,3.59,3.14,6.66,2.93,NaN,...,1.246156,5.158549,44190.304259,3.576221e+12,71.251982,NaN,-3.522981,79.6,1.2,75.9
22,22,Germany,2022,6.89,43.95,3.12,2.80,6.04,2.09,NaN,...,1.240232,2.496908,47183.115441,3.625206e+12,71.892018,NaN,-2.692237,80.8,1.1,77.0

In [45]:
df_de = df_de.copy()
df_de['LFG'] = df_de['LF'].diff()
df_de['EPFRG'] = df_de['EPFR'].diff()
df_de['GGAG'] = df_de['GGA'].diff()
df_de = df_de.drop(6)

In [46]:
df_de = df_de.drop(["Unnamed: 0", "REF_AREA_LABEL", "HI", "OCTB", "NINA", "LF", "EPFR", "GGA", "EIA", "GDP"], axis=1)

In [47]:
df_de["EMP"] = df_de["EMP"].replace(':', np.nan)
df_de["LTU"] = df_de["LTU"].replace(':', np.nan)
df_de["FEM"] = df_de["FEM"].replace(':', np.nan)

In [48]:
missing_values(df_de)

TIME_PERIOD - 0 - 0.0 %
UR - 0 - 0.0 %
URFF - 0 - 0.0 %
YUA - 0 - 0.0 %
FDI - 0 - 0.0 %
QOR - 3 - 18.8 %
QOA - 3 - 18.8 %
EIAP - 0 - 0.0 %
PS - 0 - 0.0 %
PDPS - 1 - 6.2 %
P65 - 0 - 0.0 %
P014 - 0 - 0.0 %
PGP - 0 - 0.0 %
VABI - 0 - 0.0 %
GCFP - 0 - 0.0 %
GGFC - 0 - 0.0 %
GDPCG - 0 - 0.0 %
EII - 0 - 0.0 %
EBSG - 0 - 0.0 %
GDPC - 0 - 0.0 %
EIS - 0 - 0.0 %
LBGD - 0 - 0.0 %
EMP - 2 - 12.5 %
LTU - 2 - 12.5 %
FEM - 2 - 12.5 %
LFG - 0 - 0.0 %
EPFRG - 1 - 6.2 %
GGAG - 2 - 12.5 %

In [49]:
df_de = df_de.copy()
fill_with_mode(df_de, ["QOR"])

In [50]:
fill_with_mean(df_de, ["EMP", "LTU", "FEM", "QOA", "PDPS", "EPFRG", "GGAG"])

In [51]:
de_context_2007_2015 = pd.read_csv("Data/Context/Germany_2007_2015.csv")

In [52]:
de_context_2007_2015 = de_context_2007_2015[["TIME_PERIOD", "PMSI", "JI", "DBP", "PR", "DWCP"]]

In [53]:
de_context_2007_2015["DBPG"] = de_context_2007_2015["DBP"].diff()
de_context_2007_2015 = de_context_2007_2015.drop(0)
de_context_2007_2015 = de_context_2007_2015.drop(["DBP"], axis=1)
de_context_2007_2015

   TIME_PERIOD  PMSI     JI  PR       DWCP  DBPG
1         2007  50.0  0.952  90  82.709673   0.0
2         2008  50.0  0.952  90  82.821877   0.0
3         2009  50.0  0.952  90  82.758552   0.0
4         2010  50.0  0.952  90  82.888440   0.0
5         2011  50.0  0.952  90  82.852483   0.0
6         2012  50.0  0.952  90  82.818229   0.0
7         2013  50.0  0.952  90  82.870361   0.0
8         2014  50.0  0.952  90  82.919183   0.0
9         2015  50.0  0.952  90  82.829850   0.0

In [54]:
de_eu_payments = eu_payments[eu_payments['Country'] == 'DE'].copy()

In [55]:
de_eu_payments

     Country  Fund  Year Programming_Period EU_Payment_annual
0         DE  ERDF  2007          2007-2013         1,017,013
1         DE  ERDF  2008          2007-2013         1,525,519
2         DE  ERDF  2009          2007-2013         1,271,266
3         DE  ERDF  2010          2007-2013         3,453,592
4         DE  ERDF  2011          2007-2013         2,385,830
...      ...   ...   ...                ...               ...
2403      DE   ESF  2018          2014-2020        52,908,298
2404      DE   ESF  2019          2014-2020       149,834,127
2405      DE   ESF  2020          2014-2020        93,167,064
2406      DE   ESF  2021          2014-2020        96,597,249
2407      DE   ESF  2022          2014-2020       112,397,843

[1441 rows x 5 columns]

In [56]:
de_eu_payments['EU_Payment_annual'] = pd.to_numeric(de_eu_payments['EU_Payment_annual'].str.replace(',', ''))

In [57]:
de_eu_payments_2007_2015 = de_eu_payments[de_eu_payments['Programming_Period'] == '2007-2013'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

In [58]:
de_eu_payments_2007_2015 = de_eu_payments_2007_2015.rename({"Year":"TIME_PERIOD"}, axis=1)

In [59]:
de_eu_payments_2007_2015 = de_eu_payments_2007_2015.loc[0:8]

In [60]:
de_eu_payments_2007_2015

   TIME_PERIOD  EU_Payment_annual
0         2007          509772297
1         2008          822140887
2         2009         3112147864
3         2010         2845429356
4         2011         3199322121
5         2012         3291270489
6         2013         4250139425
7         2014         3182120645
8         2015         2285834656

In [61]:
df_de_2007_2015 = df_de.loc[7:15]

In [62]:
df_de_2007_2015 = pd.merge(df_de_2007_2015, de_context_2007_2015, on='TIME_PERIOD', how='outer')

In [63]:
df_de_2007_2015 = pd.merge(df_de_2007_2015, de_eu_payments_2007_2015, on='TIME_PERIOD', how='outer')

In [64]:
df_de_2007_2015['EUPC'] = df_de_2007_2015['EU_Payment_annual'] / df_de_2007_2015['PS']

In [65]:
df_de_2007_2015 = df_de_2007_2015.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [66]:
df_de_2007_2015

,UR,URFF,YUA,FDI,QOR,QOA,EIAP,PDPS,P65,P014,...,FEM,LFG,EPFRG,GGAG,PMSI,JI,PR,DWCP,DBPG,EUPC
0,8.73,8.77,11.82,1.46,6.55,6.71,2.26,236.0,19.99,13.99,...,72.864286,0.11,15719.0,-28436.0,50.0,0.952,90,82.709673,0.0,6.196333e+06
1,7.51,7.72,10.93,0.81,6.54,6.67,1.78,236.0,20.29,13.84,...,72.864286,0.00,5641.0,2834.0,50.0,0.952,90,82.821877,0.0,1.001268e+07
2,7.88,7.49,11.31,1.63,6.49,6.61,1.68,235.0,20.52,13.76,...,67.800000,0.02,3068.0,-56474.0,50.0,0.952,90,82.758552,0.0,3.799936e+07
3,7.04,6.59,10.42,2.48,6.42,6.61,1.65,235.0,20.57,13.70,...,68.800000,0.04,7319.0,30446.0,50.0,0.952,90,82.888440,0.0,3.479371e+07
4,5.97,5.71,8.93,2.55,6.15,6.45,1.64,230.0,20.52,13.58,...,70.300000,-0.34,22139.0,-29687.0,50.0,0.952,90,82.852483,0.0,3.985701e+07
5,5.37,5.23,8.12,1.82,6.09,6.35,1.56,231.0,20.64,13.39,...,70.700000,0.24,14921.0,13203.0,50.0,0.952,90,82.818229,0.0,4.092093e+07
6,5.32,4.99,7.82,1.76,6.01,6.08,1.45,231.0,20.81,13.23,...,71.500000,0.42,8054.0,16374.0,50.0,0.952,90,82.870361,0.0,5.269857e+07
7,4.98,4.63,7.61,0.44,5.88,5.94,1.43,232.0,20.96,13.18,...,72.200000,0.27,13598.0,-40820.0,50.0,0.952,90,82.919183,0.0,3.929514e+07
8,4.61,4.20,7.33,1.82,5.72,5.95,1.39,234.0,21.05,13.21,...,72.700000,0.24,26869.0,4675.0,50.0,0.952,90,82.829850,0.0,2.798182e+07

In [67]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_de_2007_2015.values)

df_de_2007_2015_scaled = pd.DataFrame(scaled_features, index=df_de_2007_2015.index, columns=df_de_2007_2015.columns)

In [68]:
df_de_2007_2015_scaled.to_csv('Data/y/de_2007_2015_tcdf.csv')

In [69]:
df_de.columns.equals(df_dk.columns)

True

In [70]:
column_index = df_de_2007_2015_scaled.columns.get_loc('DWCP')
print(column_index)

29

In [71]:
6,0,0
24,3,0
1,6,0
18,8,0
15,18,0
29,25,0
6,29,0
23,29,3

(23, 29, 3)

In [72]:
de_context_2016_2022 = pd.read_csv("Data/Context/Germany_2016_2022.csv")

de_context_2016_2022 = de_context_2016_2022[["TIME_PERIOD", "DI", "COC", "CPI", "ROL", "VAA"]]

df_de_2016_2022 = df_de.loc[16:22]

In [73]:
de_eu_payments_2016_2022 = de_eu_payments[de_eu_payments['Programming_Period'] == '2014-2020'].groupby('Year')['EU_Payment_annual'].sum().reset_index()
de_eu_payments_2016_2022 = de_eu_payments_2016_2022.rename({"Year":"TIME_PERIOD"}, axis=1)
de_eu_payments_2016_2022 = de_eu_payments_2016_2022.loc[1:7]
de_eu_payments_2016_2022

   TIME_PERIOD  EU_Payment_annual
1         2016          193569759
2         2017         1413679591
3         2018         1874091083
4         2019         2294983953
5         2020         2150651412
6         2021         2695323886
7         2022         2941191622

In [74]:
df_de_2016_2022 = pd.merge(df_de_2016_2022, de_context_2016_2022, on='TIME_PERIOD', how='outer')

df_de_2016_2022 = pd.merge(df_de_2016_2022, de_eu_payments_2016_2022, on='TIME_PERIOD', how='outer')

df_de_2016_2022['EUPC'] = df_de_2016_2022['EU_Payment_annual'] / df_de_2016_2022['PS']

df_de_2016_2022 = df_de_2016_2022.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [75]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_de_2016_2022.values)

df_de_2016_2022_scaled = pd.DataFrame(scaled_features, index=df_de_2016_2022.index, columns=df_de_2016_2022.columns)

In [76]:
df_de_2016_2022_scaled.to_csv('Data/y/de_2016_2022_tcdf.csv')

In [77]:
column_index = df_de_2016_2022_scaled.columns.get_loc('EPFRG')
print(column_index)

24

===================================================================================================================

In [78]:
df_pl = pd.read_csv("Data/y/Poland.csv")

In [79]:
df_pl = df_pl.loc[6:22]

In [80]:
df_pl

,Unnamed: 0,REF_AREA_LABEL,TIME_PERIOD,HI,LF,UR,URFF,YUA,FDI,QOR,...,EIA,EBSG,GDPC,GDP,EIS,NINA,LBGD,EMP,LTU,FEM
6,6,Poland,2006,NaN,17.28,13.79,14.83,29.54,6.21,3.20,...,15.789906,-2.384721,28142.090823,1.313753e+12,54.230174,1.838500,-3.262140,:,:,NaN
7,7,Poland,2007,NaN,17.27,9.55,10.23,21.39,5.83,2.57,...,14.744292,-3.803166,31201.797665,1.402569e+12,54.531280,2.446382,-1.872662,:,:,:
8,8,Poland,2008,NaN,17.50,7.07,7.85,17.10,2.72,1.91,...,13.971372,-5.237136,33846.381917,1.464054e+12,54.138756,2.544367,-3.397579,:,:,:
9,9,Poland,2009,NaN,17.81,8.13,8.55,20.47,3.18,2.06,...,13.284544,-0.960496,36057.305377,1.502341e+12,55.604948,2.384192,-6.157262,62.6,2.6,55.6
10,10,Poland,2010,NaN,18.03,9.58,9.87,23.58,3.94,2.23,...,13.054421,-2.441439,37895.481599,1.549949e+12,56.642149,2.757119,-6.142614,62.2,3.1,55.6
11,11,Poland,2011,NaN,18.10,9.58,10.24,25.53,3.57,2.33,...,12.908103,-2.287307,41087.789260,1.631406e+12,56.418280,3.145783,-4.112383,62.5,3.7,55.8
12,12,Poland,2012,NaN,18.23,10.03,10.77,26.31,1.53,2.62,...,12.578914,-0.784100,42619.735974,1.656070e+12,57.005312,2.489764,-3.437896,62.9,4.2,56.2
13,13,Poland,2013,5.82,18.27,10.29,11.01,27.16,0.26,3.05,...,11.998832,1.117069,43053.616233,1.667401e+12,57.460898,1.935317,-4.023830,63.2,4.5,56.3
14,14,Poland,2014,NaN,18.39,8.97,9.52,23.73,3.85,3.55,...,11.490861,0.407324,44990.974498,1.732772e+12,57.966922,2.013741,-3.367862,64.9,3.9,58.2
15,15,Poland,2015,5.79,18.34,7.47,7.64,20.68,3.30,3.81,...,11.534171,2.067846,47637.139301,1.809564e+12,57.928061,2.243049,-2.532527,66.3,3.0,59.9
16,16,Poland,2016,5.84,18.39,6.14,6.18,17.59,3.82,4.00,...,10.584147,2.946955,49142.895037,1.864415e+12,57.966782,2.062852,-2.650770,68.2,2.2,61.5
17,17,Poland,2017,5.97,18.46,4.87,4.86,14.76,2.38,4.10,...,10.222043,2.819160,52583.150743,1.960478e+12,58.110881,NaN,-1.585809,70.0,1.5,63.0
18,18,Poland,2018,6.12,18.43,3.84,3.82,11.68,3.35,4.10,...,9.618488,2.022689,56553.025366,2.082927e+12,58.565010,NaN,0.071103,71.4,1.0,64.5
19,19,Poland,2019,6.18,18.38,3.27,3.57,9.83,3.15,4.30,...,9.153886,3.644753,60948.243108,2.178335e+12,58.712268,NaN,-0.525643,72.6,0.7,65.3
20,20,Poland,2020,6.17,18.13,3.15,3.28,10.83,3.31,NaN,...,9.591750,5.608680,62984.456554,2.133993e+12,58.725043,NaN,-7.027947,72.8,0.6,65.4
21,21,Poland,2021,6.12,18.23,3.27,3.28,11.81,5.44,NaN,...,8.398854,3.201669,71968.788552,2.281819e+12,60.667970,NaN,-2.303009,75.5,0.9,68.5
22,22,Poland,2022,6.26,18.26,2.81,2.85,10.55,6.01,NaN,...,8.253308,1.683700,84212.458240,2.401739e+12,60.913014,NaN,-3.005692,76.7,0.9,70.3

In [81]:
df_pl = df_pl.copy()
df_pl['LFG'] = df_pl['LF'].diff()
df_pl['EPFRG'] = df_pl['EPFR'].diff()
df_pl['GGAG'] = df_pl['GGA'].diff()
df_pl = df_pl.drop(6)

In [82]:
df_pl = df_pl.drop(["Unnamed: 0", "REF_AREA_LABEL", "HI", "OCTB", "NINA", "LF", "EPFR", "GGA", "EIA", "GDP"], axis=1)

In [83]:
df_pl["EMP"] = df_pl["EMP"].replace(':', np.nan)
df_pl["LTU"] = df_pl["LTU"].replace(':', np.nan)
df_pl["FEM"] = df_pl["FEM"].replace(':', np.nan)

In [84]:
missing_values(df_pl)

TIME_PERIOD - 0 - 0.0 %
UR - 0 - 0.0 %
URFF - 0 - 0.0 %
YUA - 0 - 0.0 %
FDI - 0 - 0.0 %
QOR - 3 - 18.8 %
QOA - 3 - 18.8 %
EIAP - 0 - 0.0 %
PS - 0 - 0.0 %
PDPS - 1 - 6.2 %
P65 - 0 - 0.0 %
P014 - 0 - 0.0 %
PGP - 0 - 0.0 %
VABI - 0 - 0.0 %
GCFP - 0 - 0.0 %
GGFC - 0 - 0.0 %
GDPCG - 0 - 0.0 %
EII - 0 - 0.0 %
EBSG - 0 - 0.0 %
GDPC - 0 - 0.0 %
EIS - 0 - 0.0 %
LBGD - 0 - 0.0 %
EMP - 2 - 12.5 %
LTU - 2 - 12.5 %
FEM - 2 - 12.5 %
LFG - 0 - 0.0 %
EPFRG - 1 - 6.2 %
GGAG - 2 - 12.5 %

In [85]:
df_pl = df_pl.copy()
fill_with_mode(df_pl, ["QOR", "QOA", "FEM", "PDPS"])

In [86]:
fill_with_mean(df_pl, ["EMP", "LTU", "EPFRG", "GGAG"])

In [87]:
pl_context_2007_2015 = pd.read_csv("Data/Context/Poland_2007_2015.csv")

In [88]:
pl_context_2007_2015 = pl_context_2007_2015[["TIME_PERIOD", "PR", "RQ", "COC", "ROL", "CPI"]]

In [89]:
pl_eu_payments = eu_payments[eu_payments['Country'] == 'PL'].copy()

In [90]:
pl_eu_payments

     Country Fund  Year Programming_Period EU_Payment_annual
1125      PL   CF  2007          2007-2013        45,219,844
1126      PL   CF  2008          2007-2013        72,351,752
1127      PL   CF  2009          2007-2013       129,326,232
1128      PL   CF  2010          2007-2013       108,332,216
1129      PL   CF  2011          2007-2013       207,533,488
...      ...  ...   ...                ...               ...
3022      PL  ESF  2018          2014-2020       110,564,312
3023      PL  ESF  2019          2014-2020        98,266,373
3024      PL  ESF  2020          2014-2020       103,054,231
3025      PL  ESF  2021          2014-2020       111,579,443
3026      PL  ESF  2022          2014-2020       114,688,295

[897 rows x 5 columns]

In [91]:
pl_eu_payments['EU_Payment_annual'] = pd.to_numeric(pl_eu_payments['EU_Payment_annual'].str.replace(',', ''))

In [92]:
pl_eu_payments_2007_2015 = pl_eu_payments[pl_eu_payments['Programming_Period'] == '2007-2013'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

In [93]:
pl_eu_payments_2007_2015 = pl_eu_payments_2007_2015.rename({"Year":"TIME_PERIOD"}, axis=1)

In [94]:
pl_eu_payments_2007_2015

    TIME_PERIOD  EU_Payment_annual
0          2007         1400802662
1          2008         2192935247
2          2009         5155672523
3          2010         6850960177
4          2011         9415548745
5          2012        10098196875
6          2013        10475714683
7          2014        11686980907
8          2015         6458114981
9          2016           91344706
10         2017         1942750121
11         2018         1322743760
12         2019           93430136

In [95]:
pl_eu_payments_2007_2015 = pl_eu_payments_2007_2015.loc[0:8]

In [96]:
df_pl_2007_2015 = df_pl.loc[7:15]

In [97]:
df_pl_2007_2015 = pd.merge(df_pl_2007_2015, pl_context_2007_2015, on='TIME_PERIOD', how='outer')

In [98]:
df_pl_2007_2015 = pd.merge(df_pl_2007_2015, pl_eu_payments_2007_2015, on='TIME_PERIOD', how='outer')

In [99]:
df_pl_2007_2015['EUPC'] = df_pl_2007_2015['EU_Payment_annual'] / df_pl_2007_2015['PS']

In [100]:
df_pl_2007_2015 = df_pl_2007_2015.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [101]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_pl_2007_2015.values)

df_pl_2007_2015_scaled = pd.DataFrame(scaled_features, index=df_pl_2007_2015.index, columns=df_pl_2007_2015.columns)

In [102]:
df_pl_2007_2015_scaled.to_csv('Data/y/pl_2007_2015_tcdf.csv')

In [103]:
df_de.columns.equals(df_pl.columns)

True

In [104]:
column_index = df_pl_2007_2015_scaled.columns.get_loc('GGAG')
print(column_index)

25

In [105]:
pl_context_2016_2022 = pd.read_csv("Data/Context/Poland_2016_2022.csv")

pl_context_2016_2022 = pl_context_2016_2022[["TIME_PERIOD", "JI", "FOP", "DBD", "PT", "PR"]]

pl_context_2016_2022["DBDC"] = pl_context_2016_2022["DBD"].diff()

pl_context_2016_2022 = pl_context_2016_2022.drop(["DBD"], axis=1)

pl_context_2016_2022 = pl_context_2016_2022.loc[2:8]

df_pl_2016_2022 = df_pl.loc[16:22]

In [106]:
pl_context_2016_2022

   TIME_PERIOD     JI    FOP         PT  PR  DBDC
2         2016  0.783  0.745  79.141239  65   0.0
3         2017  0.690  0.709  79.105836  61   0.0
4         2018  0.595  0.709  79.495816  62   0.0
5         2019  0.572  0.704  76.490761  62   0.0
6         2020  0.570  0.707  76.831746  63   0.0
7         2021  0.542  0.641  76.516572  63   0.0
8         2022  0.570  0.616  76.516572  72   0.0

In [107]:
pl_eu_payments_2016_2022 = pl_eu_payments[pl_eu_payments['Programming_Period'] == '2014-2020'].groupby('Year')['EU_Payment_annual'].sum().reset_index()
pl_eu_payments_2016_2022 = pl_eu_payments_2016_2022.rename({"Year":"TIME_PERIOD"}, axis=1)
pl_eu_payments_2016_2022 = pl_eu_payments_2016_2022.loc[1:7]
pl_eu_payments_2016_2022

   TIME_PERIOD  EU_Payment_annual
1         2016         2804505749
2         2017         4638222529
3         2018         9582436519
4         2019        10639507736
5         2020        12091039828
6         2021        13811714640
7         2022        11413018878

In [108]:
df_pl_2016_2022 = pd.merge(df_pl_2016_2022, pl_context_2016_2022, on='TIME_PERIOD', how='outer')

df_pl_2016_2022 = pd.merge(df_pl_2016_2022, pl_eu_payments_2016_2022, on='TIME_PERIOD', how='outer')

df_pl_2016_2022['EUPC'] = df_pl_2016_2022['EU_Payment_annual'] / df_pl_2016_2022['PS']
df_pl_2016_2022 = df_pl_2016_2022.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [109]:
df_pl_2016_2022.columns

Index(['UR', 'URFF', 'YUA', 'FDI', 'QOR', 'QOA', 'EIAP', 'PDPS', 'P65', 'P014',
       'PGP', 'VABI', 'GCFP', 'GGFC', 'GDPCG', 'EII', 'EBSG', 'GDPC', 'EIS',
       'LBGD', 'EMP', 'LTU', 'FEM', 'LFG', 'EPFRG', 'GGAG', 'JI', 'FOP', 'PT',
       'PR', 'DBDC', 'EUPC'],
      dtype='object')

In [110]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_pl_2016_2022.values)

df_pl_2016_2022_scaled = pd.DataFrame(scaled_features, index=df_pl_2016_2022.index, columns=df_pl_2016_2022.columns)

In [111]:
df_pl_2016_2022_scaled.to_csv('Data/y/pl_2016_2022_tcdf.csv')

In [112]:
column_index = df_pl_2016_2022_scaled.columns.get_loc('FOP')
print(column_index)

27

4,27,0

==================================================================================================================

In [113]:
df_lt = pd.read_csv("Data/y/Lithuania.csv")

In [114]:
df_lt = df_lt.loc[6:22]

In [115]:
df_lt

,Unnamed: 0,REF_AREA_LABEL,TIME_PERIOD,HI,LF,UR,URFF,YUA,FDI,QOR,...,EIA,EBSG,GDPC,GDP,EIS,NINA,LBGD,EMP,LTU,FEM
6,6,Lithuania,2006,NaN,1.51,5.78,5.61,9.98,7.50,4.92,...,13.832556,-10.283491,7339.529632,3.546242e+10,56.596662,3.118363,0.075001,:,:,NaN
7,7,Lithuania,2007,NaN,1.51,4.25,4.33,8.39,6.55,4.97,...,11.325410,-13.094653,8985.274630,3.939093e+10,58.126069,3.723648,-0.493558,:,:,:
8,8,Lithuania,2008,NaN,1.51,5.83,5.63,13.35,3.61,5.21,...,8.064581,-11.598256,10219.116755,4.041488e+10,61.418727,3.480952,-2.844590,:,:,:
9,9,Lithuania,2009,NaN,1.52,13.78,10.52,29.58,-0.96,5.28,...,8.983906,-1.755188,8528.034573,3.441787e+10,64.167134,2.773311,-8.626258,67.0,3.3,67.2
10,10,Lithuania,2010,NaN,1.49,17.81,14.52,35.74,3.01,5.27,...,8.830495,-2.029481,8931.519313,3.456490e+10,66.610059,2.591630,-7.016844,64.3,7.4,65.0
11,11,Lithuania,2011,NaN,1.48,15.39,12.91,32.59,4.36,5.23,...,8.486140,-2.706873,10259.331961,3.675066e+10,66.955836,2.373246,-5.541350,66.9,8.0,66.6
12,12,Lithuania,2012,NaN,1.47,13.36,11.57,26.68,1.59,5.17,...,8.796753,0.613211,11120.403233,3.836141e+10,66.119954,1.956453,-2.893765,68.5,6.6,67.9
13,13,Lithuania,2013,5.43,1.47,11.77,10.48,21.90,1.66,5.02,...,8.422800,1.457239,11776.792571,3.991386e+10,66.052053,2.151628,-2.417272,69.9,5.1,68.6
14,14,Lithuania,2014,NaN,1.48,10.70,9.22,19.26,0.74,4.94,...,9.165997,1.930309,12395.979849,4.141963e+10,66.110306,2.113033,-1.911556,71.8,4.8,70.6
15,15,Lithuania,2015,5.83,1.47,9.12,8.16,16.30,2.50,4.96,...,9.069029,-0.986813,12861.323296,4.259297e+10,65.858411,2.545603,-1.093729,73.3,3.9,72.2
16,16,Lithuania,2016,5.81,1.48,7.86,6.65,14.45,2.74,4.90,...,7.975508,0.728400,13491.939909,4.373102e+10,66.887072,1.972772,-0.460837,75.2,3.0,74.3
17,17,Lithuania,2017,5.90,1.47,7.07,5.67,13.27,2.90,4.70,...,7.784081,2.294288,14871.586227,4.574800e+10,67.082072,NaN,0.165584,76.0,2.7,75.5
18,18,Lithuania,2018,5.95,1.47,6.15,5.41,11.12,2.40,4.70,...,7.182582,1.856906,16298.029583,4.799806e+10,67.050133,NaN,0.413734,77.8,2.0,76.7
19,19,Lithuania,2019,6.15,1.48,6.26,5.49,11.85,6.23,4.80,...,6.436241,5.262450,17516.070462,5.024310e+10,67.864065,NaN,0.441721,78.2,1.9,77.4
20,20,Lithuania,2020,6.26,1.49,8.49,7.69,19.56,7.94,NaN,...,5.689861,9.072805,17885.411844,5.026461e+10,68.945663,NaN,-6.374068,76.7,2.5,75.8
21,21,Lithuania,2021,6.45,1.49,7.11,6.61,14.30,3.74,NaN,...,5.312821,4.453149,20182.333587,5.347150e+10,68.433746,NaN,-1.419204,77.4,2.6,76.7
22,22,Lithuania,2022,6.76,1.51,5.95,5.48,11.87,3.41,NaN,...,5.455592,-2.091914,23822.056413,5.482835e+10,68.817155,NaN,-0.897036,79.0,2.3,78.6

In [116]:
df_lt = df_lt.copy()
df_lt['LFG'] = df_lt['LF'].diff()
df_lt['EPFRG'] = df_lt['EPFR'].diff()
df_lt['GGAG'] = df_lt['GGA'].diff()
df_lt = df_lt.drop(6)

In [117]:
df_lt = df_lt.drop(["Unnamed: 0", "REF_AREA_LABEL", "HI", "OCTB", "NINA", "LF", "EPFR", "GGA", "EIA", "GDP"], axis=1)

In [118]:
df_lt["EMP"] = df_lt["EMP"].replace(':', np.nan)
df_lt["LTU"] = df_lt["LTU"].replace(':', np.nan)
df_lt["FEM"] = df_lt["FEM"].replace(':', np.nan)

In [119]:
missing_values(df_lt)

TIME_PERIOD - 0 - 0.0 %
UR - 0 - 0.0 %
URFF - 0 - 0.0 %
YUA - 0 - 0.0 %
FDI - 0 - 0.0 %
QOR - 3 - 18.8 %
QOA - 3 - 18.8 %
EIAP - 0 - 0.0 %
PS - 0 - 0.0 %
PDPS - 1 - 6.2 %
P65 - 0 - 0.0 %
P014 - 0 - 0.0 %
PGP - 0 - 0.0 %
VABI - 0 - 0.0 %
GCFP - 0 - 0.0 %
GGFC - 0 - 0.0 %
GDPCG - 0 - 0.0 %
EII - 0 - 0.0 %
EBSG - 0 - 0.0 %
GDPC - 0 - 0.0 %
EIS - 0 - 0.0 %
LBGD - 0 - 0.0 %
EMP - 2 - 12.5 %
LTU - 2 - 12.5 %
FEM - 2 - 12.5 %
LFG - 0 - 0.0 %
EPFRG - 1 - 6.2 %
GGAG - 2 - 12.5 %

In [120]:
df_lt = df_lt.copy()
fill_with_mode(df_lt, ["QOR", "QOA"])

In [121]:
fill_with_mean(df_lt, ["EMP", "LTU", "FEM"])

In [122]:
lt_context_2007_2015 = pd.read_csv("Data/Context/Lithuania_2007_2015.csv")

In [123]:
lt_context_2007_2015 = lt_context_2007_2015[["TIME_PERIOD", "PR", "RQ", "COC", "ROL", "CPI"]]

In [124]:
lt_eu_payments = eu_payments[eu_payments['Country'] == 'LT'].copy()

In [125]:
lt_eu_payments['EU_Payment_annual'] = pd.to_numeric(lt_eu_payments['EU_Payment_annual'].str.replace(',', ''))

In [126]:
lt_eu_payments_2007_2015 = lt_eu_payments[lt_eu_payments['Programming_Period'] == '2007-2013'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

In [127]:
lt_eu_payments_2007_2015 = lt_eu_payments_2007_2015.rename({"Year":"TIME_PERIOD"}, axis=1)

In [128]:
lt_eu_payments_2007_2015

    TIME_PERIOD  EU_Payment_annual
0          2007          147036030
1          2008          226317129
2          2009         1067875010
3          2010          871817905
4          2011          937791043
5          2012         1013987411
6          2013         1072505603
7          2014         1013149415
8          2015           86238312
9          2017           50722512
10         2018          287359288

In [129]:
lt_eu_payments_2007_2015 = lt_eu_payments_2007_2015.loc[0:8]

In [130]:
lt_eu_payments_2007_2015

   TIME_PERIOD  EU_Payment_annual
0         2007          147036030
1         2008          226317129
2         2009         1067875010
3         2010          871817905
4         2011          937791043
5         2012         1013987411
6         2013         1072505603
7         2014         1013149415
8         2015           86238312

In [131]:
df_lt_2007_2015 = df_lt.loc[7:15]

In [132]:
df_lt_2007_2015 = pd.merge(df_lt_2007_2015, lt_context_2007_2015, on='TIME_PERIOD', how='outer')

In [133]:
df_lt_2007_2015 = pd.merge(df_lt_2007_2015, lt_eu_payments_2007_2015, on='TIME_PERIOD', how='outer')

In [134]:
df_lt_2007_2015['EUPC'] = df_lt_2007_2015['EU_Payment_annual'] / df_lt_2007_2015['PS']

In [135]:
df_lt_2007_2015 = df_lt_2007_2015.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [136]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_lt_2007_2015.values)

df_lt_2007_2015_scaled = pd.DataFrame(scaled_features, index=df_lt_2007_2015.index, columns=df_lt_2007_2015.columns)

In [137]:
df_lt_2007_2015_scaled.to_csv('Data/y/lt_2007_2015_tcdf.csv')

In [138]:
df_pl.columns.equals(df_lt.columns)

True

In [139]:
column_index = df_lt_2007_2015_scaled.columns.get_loc('GGAG')
print(column_index)

25

In [140]:
lt_context_2016_2022 = pd.read_csv("Data/Context/Lithuania_2016_2022.csv")

lt_context_2016_2022 = lt_context_2016_2022[["TIME_PERIOD", "EC", "DI", "SSB", "COC", "CPI"]]

In [141]:
df_lt

,TIME_PERIOD,UR,URFF,YUA,FDI,QOR,QOA,EIAP,PS,PDPS,...,EBSG,GDPC,EIS,LBGD,EMP,LTU,FEM,LFG,EPFRG,GGAG
7,2007,4.25,4.33,8.39,6.55,4.97,4.40,11.33,3.23,52.0,...,-13.094653,8985.274630,58.126069,-0.493558,73.0,4.007143,72.364286,0.00,122.00,1013.0
8,2008,5.83,5.63,13.35,3.61,5.21,4.61,8.06,3.20,51.0,...,-11.598256,10219.116755,61.418727,-2.844590,73.0,4.007143,72.364286,0.00,40.09,-563.0
9,2009,13.78,10.52,29.58,-0.96,5.28,4.22,8.98,3.16,50.0,...,-1.755188,8528.034573,64.167134,-8.626258,67.0,3.300000,67.200000,0.01,60.00,-3576.0
10,2010,17.81,14.52,35.74,3.01,5.27,3.57,8.83,3.10,49.0,...,-2.029481,8931.519313,66.610059,-7.016844,64.3,7.400000,65.000000,-0.03,111.00,806.0
11,2011,15.39,12.91,32.59,4.36,5.23,3.73,8.49,3.03,48.0,...,-2.706873,10259.331961,66.955836,-5.541350,66.9,8.000000,66.600000,-0.01,261.18,-532.0
12,2012,13.36,11.57,26.68,1.59,5.17,4.23,8.80,2.99,48.0,...,0.613211,11120.403233,66.119954,-2.893765,68.5,6.600000,67.900000,-0.01,127.73,-81.0
13,2013,11.77,10.48,21.90,1.66,5.02,4.32,8.42,2.96,47.0,...,1.457239,11776.792571,66.052053,-2.417272,69.9,5.100000,68.600000,0.00,245.00,-892.0
14,2014,10.70,9.22,19.26,0.74,4.94,4.19,9.17,2.94,47.0,...,1.930309,12395.979849,66.110306,-1.911556,71.8,4.800000,70.600000,0.01,107.00,-452.0
15,2015,9.12,8.16,16.30,2.50,4.96,4.12,9.07,2.91,46.0,...,-0.986813,12861.323296,65.858411,-1.093729,73.3,3.900000,72.200000,-0.01,217.00,260.0
16,2016,7.86,6.65,14.45,2.74,4.90,4.40,7.98,2.88,46.0,...,0.728400,13491.939909,66.887072,-0.460837,75.2,3.000000,74.300000,0.01,312.00,25.0
17,2017,7.07,5.67,13.27,2.90,4.70,4.40,7.78,2.84,45.0,...,2.294288,14871.586227,67.082072,0.165584,76.0,2.700000,75.500000,-0.01,294.85,-79.0
18,2018,6.15,5.41,11.12,2.40,4.70,4.60,7.18,2.82,45.0,...,1.856906,16298.029583,67.050133,0.413734,77.8,2.000000,76.700000,0.00,-161.65,86.0
19,2019,6.26,5.49,11.85,6.23,4.80,4.90,6.44,2.81,45.0,...,5.262450,17516.070462,67.864065,0.441721,78.2,1.900000,77.400000,0.01,350.20,128.0
20,2020,8.49,7.69,19.56,7.94,4.70,4.40,5.69,2.81,45.0,...,9.072805,17885.411844,68.945663,-6.374068,76.7,2.500000,75.800000,0.01,150.30,5.0
21,2021,7.11,6.61,14.30,3.74,4.70,4.40,5.31,2.81,45.0,...,4.453149,20182.333587,68.433746,-1.419204,77.4,2.600000,76.700000,0.00,-35.80,NaN
22,2022,5.95,5.48,11.87,3.41,4.70,4.40,5.46,2.83,NaN,...,-2.091914,23822.056413,68.817155,-0.897036,79.0,2.300000,78.600000,0.02,NaN,NaN

In [142]:
df_lt_2016_2022 = df_lt.loc[16:22]

In [143]:
lt_eu_payments_2016_2022 = lt_eu_payments[lt_eu_payments['Programming_Period'] == '2014-2020'].groupby('Year')['EU_Payment_annual'].sum().reset_index()
lt_eu_payments_2016_2022 = lt_eu_payments_2016_2022.rename({"Year":"TIME_PERIOD"}, axis=1)

In [144]:
lt_eu_payments_2016_2022 = lt_eu_payments_2016_2022.loc[1:7]
lt_eu_payments_2016_2022

   TIME_PERIOD  EU_Payment_annual
1         2016          332852729
2         2017          434501955
3         2018          809554069
4         2019          529282582
5         2020         1445805827
6         2021         1139822052
7         2022          937545028

In [145]:
df_lt_2016_2022

,TIME_PERIOD,UR,URFF,YUA,FDI,QOR,QOA,EIAP,PS,PDPS,...,EBSG,GDPC,EIS,LBGD,EMP,LTU,FEM,LFG,EPFRG,GGAG
16,2016,7.86,6.65,14.45,2.74,4.9,4.4,7.98,2.88,46.0,...,0.728400,13491.939909,66.887072,-0.460837,75.2,3.0,74.3,0.01,312.00,25.0
17,2017,7.07,5.67,13.27,2.90,4.7,4.4,7.78,2.84,45.0,...,2.294288,14871.586227,67.082072,0.165584,76.0,2.7,75.5,-0.01,294.85,-79.0
18,2018,6.15,5.41,11.12,2.40,4.7,4.6,7.18,2.82,45.0,...,1.856906,16298.029583,67.050133,0.413734,77.8,2.0,76.7,0.00,-161.65,86.0
19,2019,6.26,5.49,11.85,6.23,4.8,4.9,6.44,2.81,45.0,...,5.262450,17516.070462,67.864065,0.441721,78.2,1.9,77.4,0.01,350.20,128.0
20,2020,8.49,7.69,19.56,7.94,4.7,4.4,5.69,2.81,45.0,...,9.072805,17885.411844,68.945663,-6.374068,76.7,2.5,75.8,0.01,150.30,5.0
21,2021,7.11,6.61,14.30,3.74,4.7,4.4,5.31,2.81,45.0,...,4.453149,20182.333587,68.433746,-1.419204,77.4,2.6,76.7,0.00,-35.80,NaN
22,2022,5.95,5.48,11.87,3.41,4.7,4.4,5.46,2.83,NaN,...,-2.091914,23822.056413,68.817155,-0.897036,79.0,2.3,78.6,0.02,NaN,NaN

In [146]:
df_lt_2016_2022 = pd.merge(df_lt_2016_2022, lt_context_2016_2022, on='TIME_PERIOD', how='outer')

df_lt_2016_2022 = pd.merge(df_lt_2016_2022, lt_eu_payments_2016_2022, on='TIME_PERIOD', how='outer')

df_lt_2016_2022['EUPC'] = df_lt_2016_2022['EU_Payment_annual'] / df_lt_2016_2022['PS']
fill_with_mode(df_lt_2016_2022, ["PDPS"])
fill_with_mean(df_lt_2016_2022, ["EPFRG", "GGAG"])
df_lt_2016_2022
df_lt_2016_2022 = df_lt_2016_2022.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [147]:
df_lt_2016_2022.to_csv('Data/y/lt_2016_2022_bn.csv', index=True)

In [148]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_lt_2016_2022.values)

df_lt_2016_2022_scaled = pd.DataFrame(scaled_features, index=df_lt_2016_2022.index, columns=df_lt_2016_2022.columns)

In [149]:
df_lt_2016_2022_scaled.to_csv('Data/y/lt_2016_2022_tcdf.csv')

In [150]:
column_index = df_lt_2007_2015_scaled.columns.get_loc('EUPC')
print(column_index)

31

In [151]:
24,31,2

(24, 31, 2)

===================================================================================================================

In [152]:
df_lv = pd.read_csv("Data/y/Latvia.csv")

In [153]:
df_lv = df_lv.loc[6:22]

In [154]:
df_lv = df_lv.copy()
df_lv['LFG'] = df_lv['LF'].diff()
df_lv['EPFRG'] = df_lv['EPFR'].diff()
df_lv['GGAG'] = df_lv['GGA'].diff()
df_lv = df_lv.drop(6)

In [155]:
df_lv = df_lv.drop(["Unnamed: 0", "REF_AREA_LABEL", "HI", "OCTB", "NINA", "LF", "EPFR", "GGA", "EIA", "GDP"], axis=1)

In [156]:
df_lv["EMP"] = df_lv["EMP"].replace(':', np.nan)
df_lv["LTU"] = df_lv["LTU"].replace(':', np.nan)
df_lv["FEM"] = df_lv["FEM"].replace(':', np.nan)

In [157]:
missing_values(df_lv)

TIME_PERIOD - 0 - 0.0 %
UR - 0 - 0.0 %
URFF - 0 - 0.0 %
YUA - 0 - 0.0 %
FDI - 0 - 0.0 %
QOR - 3 - 18.8 %
QOA - 3 - 18.8 %
EIAP - 0 - 0.0 %
PS - 0 - 0.0 %
PDPS - 1 - 6.2 %
P65 - 0 - 0.0 %
P014 - 0 - 0.0 %
PGP - 0 - 0.0 %
VABI - 0 - 0.0 %
GCFP - 0 - 0.0 %
GGFC - 0 - 0.0 %
GDPCG - 0 - 0.0 %
EII - 0 - 0.0 %
EBSG - 0 - 0.0 %
GDPC - 0 - 0.0 %
EIS - 0 - 0.0 %
LBGD - 0 - 0.0 %
EMP - 2 - 12.5 %
LTU - 2 - 12.5 %
FEM - 2 - 12.5 %
LFG - 0 - 0.0 %
EPFRG - 1 - 6.2 %
GGAG - 2 - 12.5 %

In [158]:
# df_lv = df_lv.copy()
# fill_with_mode(df_lv, ["QOR", "QOA"])

In [159]:
fill_with_mean(df_lv, ["EMP", "LTU", "FEM", "QOR", "QOA", "PDPS", "EPFRG", "GGAG"])

In [160]:
lv_context_2007_2015 = pd.read_csv("Data/Context/Latvia_2007_2015.csv")

In [161]:
lv_context_2007_2015 = lv_context_2007_2015[["TIME_PERIOD", "PR", "RQ", "COC", "ROL", "CPI"]]

In [162]:
lv_context_2007_2015

   TIME_PERIOD  PR    RQ   COC   ROL   CPI
0         2007  50  0.95  0.34  0.72  48.0
1         2008  55  0.97  0.23  0.78  50.0
2         2009  55  0.92  0.20  0.79  45.0
3         2010  55  0.93  0.20  0.76  43.0
4         2011  50  0.95  0.28  0.74  42.0
5         2012  50  1.01  0.24  0.78  49.0
6         2013  50  1.04  0.32  0.76  53.0
7         2014  50  1.17  0.41  0.87  55.0
8         2015  50  1.07  0.43  0.77  55.0

In [163]:
lv_eu_payments = eu_payments[eu_payments['Country'] == 'LV'].copy()

lv_eu_payments['EU_Payment_annual'] = pd.to_numeric(lv_eu_payments['EU_Payment_annual'].str.replace(',', ''))

lv_eu_payments_2007_2015 = lv_eu_payments[lv_eu_payments['Programming_Period'] == '2007-2013'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

lv_eu_payments_2007_2015 = lv_eu_payments_2007_2015.rename({"Year":"TIME_PERIOD"}, axis=1)

In [164]:
lv_eu_payments_2007_2015 = lv_eu_payments_2007_2015.loc[0:8]

In [165]:
df_lv_2007_2015 = df_lv.loc[7:15]

df_lv_2007_2015 = pd.merge(df_lv_2007_2015, lv_context_2007_2015, on='TIME_PERIOD', how='outer')

df_lv_2007_2015 = pd.merge(df_lv_2007_2015, lv_eu_payments_2007_2015, on='TIME_PERIOD', how='outer')

df_lv_2007_2015['EUPC'] = df_lv_2007_2015['EU_Payment_annual'] / df_lv_2007_2015['PS']

df_lv_2007_2015 = df_lv_2007_2015.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [166]:
df_lv_2007_2015

,UR,URFF,YUA,FDI,QOR,QOA,EIAP,PDPS,P65,P014,...,FEM,LFG,EPFRG,GGAG,PR,RQ,COC,ROL,CPI,EUPC
0,6.05,5.57,10.56,9.22,3.11,5.39,10.18,35.0,17.51,14.11,...,70.435714,0.02,6.80,424.0,50,0.95,0.34,0.72,48.0,4.468538e+07
1,7.74,7.07,13.65,4.20,2.85,5.59,7.96,35.0,17.72,14.04,...,70.435714,0.01,7.81,-338.0,55,0.97,0.23,0.78,50.0,6.940880e+07
2,17.51,14.13,33.43,-0.58,3.19,5.48,8.75,34.0,17.98,14.12,...,66.200000,-0.05,-3.95,-780.0,55,0.92,0.20,0.79,45.0,1.985811e+08
3,19.48,16.29,36.24,2.02,3.11,5.44,8.61,34.0,18.25,14.18,...,64.200000,-0.04,16.38,1140.0,55,0.93,0.20,0.76,43.0,2.209354e+08
4,16.21,13.79,31.07,5.72,3.10,5.17,8.90,33.0,18.48,14.24,...,65.100000,-0.03,75.29,-641.0,50,0.95,0.28,0.74,42.0,2.485579e+08
5,15.05,13.94,28.56,3.99,3.16,5.27,8.37,33.0,18.68,14.36,...,66.200000,0.01,212.38,-201.0,50,1.01,0.24,0.78,49.0,3.518108e+08
6,11.87,11.14,23.24,3.39,3.00,5.39,8.06,32.0,18.93,14.57,...,67.500000,-0.02,218.90,-72.0,50,1.04,0.32,0.76,53.0,3.102758e+08
7,10.85,9.83,19.59,3.45,3.09,5.35,7.50,32.0,19.24,14.85,...,68.400000,-0.01,187.31,-55.0,50,1.17,0.41,0.87,55.0,3.581094e+08
8,9.87,8.64,16.32,3.09,3.31,5.37,7.94,32.0,19.52,15.12,...,70.500000,0.00,107.29,44.0,50,1.07,0.43,0.77,55.0,3.044853e+08

In [167]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_lv_2007_2015.values)

df_lv_2007_2015_scaled = pd.DataFrame(scaled_features, index=df_lv_2007_2015.index, columns=df_lv_2007_2015.columns)

In [168]:
df_lv_2007_2015_scaled

,UR,URFF,YUA,FDI,QOR,QOA,EIAP,PDPS,P65,P014,...,FEM,LFG,EPFRG,GGAG,PR,RQ,COC,ROL,CPI,EUPC
0,-1.548218,-1.628482,-1.509014,2.151868,0.065078,0.058977,2.319340,1.443376,-1.506411,-0.819843,...,1.215229,1.401768,-0.970065,0.881472,-0.707107,-0.668001,0.559704,-1.379324,-0.193009,-1.756634
1,-1.156919,-1.191154,-1.152224,0.146476,-2.110373,1.828280,-0.699579,1.443376,-1.179907,-1.018497,...,1.215229,0.966736,-0.958568,-0.526010,1.414214,-0.406609,-0.791777,0.140747,0.241262,-1.527342
2,1.105209,0.867207,1.131697,-1.763041,0.734447,0.855163,0.374721,0.577350,-0.775664,-0.791463,...,-0.641535,-1.643452,-1.092428,-1.342423,1.414214,-1.060088,-1.160362,0.394093,-0.844416,-0.329361
3,1.561339,1.496960,1.456156,-0.724391,0.065078,0.501303,0.184338,0.577350,-0.355872,-0.621188,...,-1.518254,-1.208421,-0.861019,2.203987,1.414214,-0.929393,-1.160362,-0.365943,-1.278687,-0.122041
4,0.804209,0.768079,0.859196,0.753687,-0.018594,-1.887257,0.578702,-0.288675,0.001728,-0.450913,...,-1.123730,-0.773389,-0.190469,-1.085678,-0.707107,-0.668001,-0.177467,-0.872634,-1.495823,0.134138
5,0.535625,0.811812,0.569376,0.062585,0.483433,-1.002605,-0.142031,-0.288675,0.312684,-0.110363,...,-0.641535,0.966736,1.369974,-0.272959,-0.707107,0.116174,-0.668915,0.140747,0.024126,1.091736
6,-0.200666,-0.004535,-0.044904,-0.177103,-0.855305,0.058977,-0.563592,-1.154701,0.701380,0.485599,...,-0.071668,-0.338358,1.444189,-0.034684,-0.707107,0.508262,0.313980,-0.365943,0.892668,0.706528
7,-0.436835,-0.386469,-0.466355,-0.153134,-0.102265,-0.294884,-1.325121,-1.154701,1.183362,1.280216,...,0.322855,0.096674,1.084612,-0.003284,-0.707107,2.207307,1.419737,2.420855,1.326939,1.150151
8,-0.663743,-0.733416,-0.843929,-0.296947,1.738501,-0.117954,-0.726777,-1.154701,1.618701,2.046453,...,1.243409,0.531705,0.173775,0.179578,-0.707107,0.900349,1.665461,-0.112598,1.326939,0.652825

In [169]:
df_lv_2007_2015_scaled.to_csv('Data/y/lv_2007_2015_tcdf.csv')

In [170]:
df_lv.columns.equals(df_lv.columns)

True

In [171]:
column_index = df_lv_2007_2015_scaled.columns.get_loc('ROL')
print(column_index)

29

In [172]:
df_lv

,TIME_PERIOD,UR,URFF,YUA,FDI,QOR,QOA,EIAP,PS,PDPS,...,EBSG,GDPC,EIS,LBGD,EMP,LTU,FEM,LFG,EPFRG,GGAG
7,2007,6.05,5.57,10.56,9.22,3.110000,5.390000,10.18,2.20,35.000000,...,-20.108026,9775.522707,61.186668,0.134663,71.978571,5.014286,70.435714,0.02,6.800000,424.000000
8,2008,7.74,7.07,13.65,4.20,2.850000,5.590000,7.96,2.18,35.000000,...,-13.299099,10725.051692,62.643879,-3.172711,71.978571,5.014286,70.435714,0.01,7.810000,-338.000000
9,2009,17.51,14.13,33.43,-0.58,3.190000,5.480000,8.75,2.14,34.000000,...,-2.039931,8629.945617,66.906110,-7.966839,66.300000,5.000000,66.200000,-0.05,-3.950000,-780.000000
10,2010,19.48,16.29,36.24,2.02,3.110000,5.440000,8.61,2.10,34.000000,...,-2.131443,8447.759415,68.311167,-8.375610,63.900000,9.700000,64.200000,-0.04,16.380000,1140.000000
11,2011,16.21,13.79,31.07,5.72,3.100000,5.170000,8.90,2.06,33.000000,...,-6.131271,9281.534430,68.196401,-3.827185,66.100000,9.800000,65.100000,-0.03,75.290000,-641.000000
12,2012,15.05,13.94,28.56,3.99,3.160000,5.270000,8.37,2.03,33.000000,...,-5.548474,10374.147811,68.149704,-1.006694,67.900000,8.600000,66.200000,0.01,212.380000,-201.000000
13,2013,11.87,11.14,23.24,3.39,3.000000,5.390000,8.06,2.01,32.000000,...,-4.525224,10909.112726,68.022089,-0.749488,69.500000,6.300000,67.500000,-0.02,218.900000,-72.000000
14,2014,10.85,9.83,19.59,3.45,3.090000,5.350000,7.50,1.99,32.000000,...,-2.898049,11430.790829,68.648829,-1.357478,70.600000,5.100000,68.400000,-0.01,187.310000,-55.000000
15,2015,9.87,8.64,16.32,3.09,3.310000,5.370000,7.94,1.98,32.000000,...,-1.188889,12007.048703,68.415218,-1.740458,72.500000,4.900000,70.500000,0.00,107.290000,44.000000
16,2016,9.64,8.40,17.27,1.24,3.200000,5.100000,7.69,1.96,31.000000,...,0.526321,12502.021651,68.194066,-0.184948,73.000000,4.400000,71.700000,-0.01,35.050000,-165.000000
17,2017,8.72,7.67,16.97,4.05,3.000000,5.200000,6.87,1.94,31.000000,...,-0.434095,13395.368666,69.825091,0.031418,74.600000,3.600000,72.600000,0.00,129.910000,-62.000000
18,2018,7.41,6.42,12.19,1.32,3.500000,5.500000,6.97,1.93,31.000000,...,-0.494458,14608.666887,69.367243,-0.633990,76.800000,3.400000,74.700000,-0.01,-14.100000,536.000000
19,2019,6.31,5.42,12.41,3.37,3.600000,5.700000,7.29,1.91,31.000000,...,-0.217946,15449.190677,68.987216,-0.746684,77.300000,2.700000,75.500000,-0.01,17.510000,-152.000000
20,2020,8.10,7.07,14.87,2.81,3.170769,5.380769,7.22,1.90,31.000000,...,1.435286,15377.597610,69.141874,-3.934799,76.900000,2.400000,75.100000,0.00,-38.580000,-649.000000
21,2021,7.51,6.54,14.78,9.78,3.170769,5.380769,6.79,1.88,30.000000,...,-3.174062,17131.308205,69.702903,-6.941226,75.300000,2.300000,72.900000,-0.03,-35.700000,-69.357143
22,2022,6.82,5.51,15.27,3.20,3.170769,5.380769,6.78,1.88,32.333333,...,-4.888329,19208.258774,69.582521,-4.914751,77.000000,2.000000,75.500000,0.01,61.486667,-69.357143

In [173]:
df_lv_2016_2022 = df_lv.loc[16:22]

In [174]:
lv_context_2016_2022 = pd.read_csv("Data/Context/Latvia_2016_2022.csv")

lv_context_2016_2022 = lv_context_2016_2022[["TIME_PERIOD", "EC", "DI", "SSB", "COC", "CPI"]]
lv_context_2016_2022 = lv_context_2016_2022.loc[0:6]

In [175]:
lv_context_2016_2022

   TIME_PERIOD         EC    DI        SSB   COC   CPI
0         2016  71.655374  7.31  94.107515  0.40  57.0
1         2017  71.655374  7.25  94.112781  0.50  58.0
2         2018  73.507226  7.38  94.113949  0.30  58.0
3         2019  73.507226  7.49  94.116764  0.48  56.0
4         2020  73.507226  7.24  94.114435  0.69  57.0
5         2021  72.766485  7.31  94.117799  0.72  59.0
6         2022  72.766485  7.37  94.117799  0.69  59.0

In [176]:
lv_eu_payments_2016_2022 = lv_eu_payments[lv_eu_payments['Programming_Period'] == '2014-2020'].groupby('Year')['EU_Payment_annual'].sum().reset_index()
lv_eu_payments_2016_2022 = lv_eu_payments_2016_2022.rename({"Year":"TIME_PERIOD"}, axis=1)
lv_eu_payments_2016_2022 = lv_eu_payments_2016_2022.loc[1:7]
lv_eu_payments_2016_2022

   TIME_PERIOD  EU_Payment_annual
1         2016          155094196
2         2017          160481758
3         2018          342377779
4         2019          728058421
5         2020          591900430
6         2021          564767158
7         2022          578719541

In [177]:

df_lv_2016_2022 = pd.merge(df_lv_2016_2022, lv_context_2016_2022, on='TIME_PERIOD', how='outer')

df_lv_2016_2022 = pd.merge(df_lv_2016_2022, lv_eu_payments_2016_2022, on='TIME_PERIOD', how='outer')

df_lv_2016_2022['EUPC'] = df_lv_2016_2022['EU_Payment_annual'] / df_lv_2016_2022['PS']

df_lv_2016_2022 = df_lv_2016_2022.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [178]:
df_lv_2016_2022

,UR,URFF,YUA,FDI,QOR,QOA,EIAP,PDPS,P65,P014,...,FEM,LFG,EPFRG,GGAG,EC,DI,SSB,COC,CPI,EUPC
0,9.64,8.40,17.27,1.24,3.200000,5.100000,7.69,31.000000,19.78,15.41,...,71.7,-0.01,35.050000,-165.000000,71.655374,7.31,94.107515,0.40,57.0,7.912969e+07
1,8.72,7.67,16.97,4.05,3.000000,5.200000,6.87,31.000000,20.01,15.67,...,72.6,0.00,129.910000,-62.000000,71.655374,7.25,94.112781,0.50,58.0,8.272256e+07
2,7.41,6.42,12.19,1.32,3.500000,5.500000,6.97,31.000000,20.20,15.83,...,74.7,-0.01,-14.100000,536.000000,73.507226,7.38,94.113949,0.30,58.0,1.773978e+08
3,6.31,5.42,12.41,3.37,3.600000,5.700000,7.29,31.000000,20.41,15.94,...,75.5,-0.01,17.510000,-152.000000,73.507226,7.49,94.116764,0.48,56.0,3.811824e+08
4,8.10,7.07,14.87,2.81,3.170769,5.380769,7.22,31.000000,20.67,16.00,...,75.1,0.00,-38.580000,-649.000000,73.507226,7.24,94.114435,0.69,57.0,3.115265e+08
5,7.51,6.54,14.78,9.78,3.170769,5.380769,6.79,30.000000,20.85,16.00,...,72.9,-0.03,-35.700000,-69.357143,72.766485,7.31,94.117799,0.72,59.0,3.004081e+08
6,6.82,5.51,15.27,3.20,3.170769,5.380769,6.78,32.333333,21.01,15.93,...,75.5,0.01,61.486667,-69.357143,72.766485,7.37,94.117799,0.69,59.0,3.078295e+08

In [179]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_lv_2016_2022.values)

df_lv_2016_2022_scaled = pd.DataFrame(scaled_features, index=df_lv_2016_2022.index, columns=df_lv_2016_2022.columns)

In [180]:
df_lv_2016_2022_scaled.to_csv('Data/y/lv_2016_2022_tcdf.csv')

In [181]:
column_index = df_lv_2016_2022_scaled.columns.get_loc('LFG')
print(column_index)

23

===================================================================================================================

In [182]:
df_ee = pd.read_csv("Data/y/Estonia.csv")

df_ee = df_ee.loc[6:22]

df_ee

,Unnamed: 0,REF_AREA_LABEL,TIME_PERIOD,HI,LF,UR,URFF,YUA,FDI,QOR,...,EIA,EBSG,GDPC,GDP,EIS,NINA,LBGD,EMP,LTU,FEM
6,6,Estonia,2006,NaN,0.69,5.91,5.59,12.12,10.33,3.68,...,5.063969,-10.108028,10076.523786,2.296909e+10,61.394965,3.219881,3.066797,:,:,NaN
7,7,Estonia,2007,NaN,0.69,4.59,3.76,10.10,13.51,3.78,...,4.776478,-8.790011,12234.211743,2.470806e+10,60.095527,3.837102,3.169094,:,:,:
8,8,Estonia,2008,NaN,0.70,5.45,5.14,12.03,8.12,4.00,...,3.901565,-3.904339,12429.172307,2.344169e+10,60.831163,4.286809,-2.025402,:,:,:
9,9,Estonia,2009,NaN,0.69,13.55,10.30,27.41,9.51,4.22,...,4.054426,4.963764,10590.021094,2.001212e+10,64.503623,4.371720,-2.239512,70.5,3.7,69.9
10,10,Estonia,2010,NaN,0.68,16.71,14.09,32.94,13.28,4.53,...,4.216992,6.420120,11071.755760,2.050237e+10,65.465353,2.214769,-0.609832,67.6,7.5,67.4
11,11,Estonia,2011,NaN,0.69,12.33,11.58,22.39,4.80,4.49,...,4.412399,5.793163,12612.147903,2.206198e+10,63.153093,2.237984,0.526226,71.0,7.0,68.6
12,12,Estonia,2012,NaN,0.68,10.02,9.10,20.86,7.69,4.22,...,4.493347,1.640113,13674.010506,2.287210e+10,64.403281,4.377116,-0.123296,73.1,5.4,71.1
13,13,Estonia,2013,5.43,0.68,8.63,8.15,18.70,4.31,4.20,...,4.262017,2.306589,14539.662078,2.327385e+10,65.464427,3.191025,0.273440,74.1,3.8,71.6
14,14,Estonia,2014,NaN,0.68,7.35,6.81,14.98,6.59,4.39,...,3.858264,3.225526,15492.493600,2.404719e+10,65.993575,3.643242,0.975175,75.0,3.3,71.9
15,15,Estonia,2015,5.43,0.68,6.41,6.32,14.34,-3.07,4.53,...,4.031562,3.561763,15972.915607,2.448921e+10,64.701793,3.682012,0.119938,76.7,2.4,73.7
16,16,Estonia,2016,5.52,0.69,6.88,6.16,14.13,3.77,4.70,...,3.899799,3.207492,16863.602095,2.524667e+10,65.884179,3.286678,-0.181622,77.0,2.2,73.7
17,17,Estonia,2017,5.61,0.70,5.81,5.24,12.18,6.32,4.70,...,3.625912,3.975466,18457.882440,2.666923e+10,66.200409,NaN,-0.229889,79.2,2.0,76.8
18,18,Estonia,2018,5.74,0.70,5.41,5.26,12.08,4.08,4.70,...,3.432038,2.315765,19999.192119,2.765592e+10,66.410718,NaN,-0.760256,79.7,1.3,76.8
19,19,Estonia,2019,5.89,0.70,4.51,4.93,11.62,9.77,4.70,...,3.340088,3.686161,21457.612416,2.868655e+10,67.284038,NaN,0.196333,80.5,0.9,77.5
20,20,Estonia,2020,6.19,0.70,6.96,6.77,18.42,12.01,NaN,...,3.082246,-1.083534,20954.364802,2.785929e+10,67.203161,NaN,-5.358715,79.1,1.2,76.9
21,21,Estonia,2021,6.34,0.70,6.18,5.54,16.62,20.31,NaN,...,2.684173,-1.302298,23634.746178,2.985247e+10,68.295247,NaN,-2.149653,79.3,1.6,77.5
22,22,Estonia,2022,6.46,0.74,5.57,5.06,18.39,4.89,NaN,...,2.603676,-1.236321,27017.885739,2.987051e+10,68.785368,NaN,-0.692318,81.9,1.3,80.4

In [183]:
df_ee = df_ee.copy()
df_ee['LFG'] = df_ee['LF'].diff()
df_ee['EPFRG'] = df_ee['EPFR'].diff()
df_ee['GGAG'] = df_ee['GGA'].diff()
df_ee = df_ee.drop(6)

In [184]:
df_ee = df_ee.drop(["Unnamed: 0", "REF_AREA_LABEL", "HI", "OCTB", "NINA", "LF", "EPFR", "GGA", "EIA", "GDP"], axis=1)

In [185]:
df_ee["EMP"] = df_ee["EMP"].replace(':', np.nan)
df_ee["LTU"] = df_ee["LTU"].replace(':', np.nan)
df_ee["FEM"] = df_ee["FEM"].replace(':', np.nan)

In [186]:
missing_values(df_ee)

TIME_PERIOD - 0 - 0.0 %
UR - 0 - 0.0 %
URFF - 0 - 0.0 %
YUA - 0 - 0.0 %
FDI - 0 - 0.0 %
QOR - 3 - 18.8 %
QOA - 3 - 18.8 %
EIAP - 0 - 0.0 %
PS - 0 - 0.0 %
PDPS - 1 - 6.2 %
P65 - 0 - 0.0 %
P014 - 0 - 0.0 %
PGP - 0 - 0.0 %
VABI - 0 - 0.0 %
GCFP - 0 - 0.0 %
GGFC - 0 - 0.0 %
GDPCG - 0 - 0.0 %
EII - 0 - 0.0 %
EBSG - 0 - 0.0 %
GDPC - 0 - 0.0 %
EIS - 0 - 0.0 %
LBGD - 0 - 0.0 %
EMP - 2 - 12.5 %
LTU - 2 - 12.5 %
FEM - 2 - 12.5 %
LFG - 0 - 0.0 %
EPFRG - 1 - 6.2 %
GGAG - 2 - 12.5 %

In [187]:
df_ee = df_ee.copy()
fill_with_mode(df_ee, ["QOR", "QOA", "PDPS"])

In [188]:
fill_with_mean(df_ee, ["EMP", "LTU", "FEM", "EPFRG", "GGAG"])

In [189]:
ee_context_2007_2015 = pd.read_csv("Data/Context/Estonia_2007_2015.csv")

In [190]:
ee_context_2007_2015 = ee_context_2007_2015[["TIME_PERIOD", "PMSI", "JI", "DBP", "DWCP", "PR"]]
ee_context_2007_2015["DBPG"] = ee_context_2007_2015["DBP"].diff()
ee_context_2007_2015 = ee_context_2007_2015.drop(0)
ee_context_2007_2015 = ee_context_2007_2015.drop(["DBP"], axis=1)
ee_context_2007_2015

   TIME_PERIOD       PMSI     JI       DWCP  PR  DBPG
1         2007  56.666667  0.955  86.112980  90   0.0
2         2008  56.666667  0.955  86.252845  90   0.0
3         2009  56.666667  0.955  85.403987  90   0.0
4         2010  56.666667  0.955  85.415456  80   0.0
5         2011  56.666667  0.955  85.358224  80   0.0
6         2012  56.666667  0.955  85.374812  80   0.0
7         2013  56.666667  0.955  85.428313  85   0.0
8         2014  56.666667  0.955  85.462140  90   0.0
9         2015  56.666667  0.955  85.640301  90   0.0

In [191]:
ee_eu_payments = eu_payments[eu_payments['Country'] == 'EE'].copy()

ee_eu_payments['EU_Payment_annual'] = pd.to_numeric(ee_eu_payments['EU_Payment_annual'].str.replace(',', ''))

ee_eu_payments_2007_2015 = ee_eu_payments[ee_eu_payments['Programming_Period'] == '2007-2013'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

ee_eu_payments_2007_2015  = ee_eu_payments_2007_2015.rename({"Year":"TIME_PERIOD"}, axis=1)

ee_eu_payments_2007_2015 = ee_eu_payments_2007_2015.loc[0:8]

In [192]:
ee_eu_payments_2007_2015

   TIME_PERIOD  EU_Payment_annual
0         2007           73827848
1         2008          113621099
2         2009          474611080
3         2010          527916818
4         2011          239059742
5         2012          658762433
6         2013          678590982
7         2014          376167074
8         2015           90729480

In [193]:
df_ee_2007_2015 = df_ee.loc[7:15]

df_ee_2007_2015 = pd.merge(df_ee_2007_2015, ee_context_2007_2015, on='TIME_PERIOD', how='outer')

df_ee_2007_2015 = pd.merge(df_ee_2007_2015, ee_eu_payments_2007_2015, on='TIME_PERIOD', how='outer')

df_ee_2007_2015['EUPC'] = df_ee_2007_2015['EU_Payment_annual'] / df_ee_2007_2015['PS']

df_ee_2007_2015 = df_ee_2007_2015.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [194]:
df_ee_2007_2015

,UR,URFF,YUA,FDI,QOR,QOA,EIAP,PDPS,P65,P014,...,FEM,LFG,EPFRG,GGAG,PMSI,JI,DWCP,PR,DBPG,EUPC
0,4.59,3.76,10.10,13.51,3.78,4.99,4.78,32.0,17.37,14.85,...,73.842857,0.00,8.80,3732.0,56.666667,0.955,86.112980,90,0.0,5.509541e+07
1,5.45,5.14,12.03,8.12,4.00,5.10,3.90,32.0,17.44,14.89,...,73.842857,0.01,44.91,-2269.0,56.666667,0.955,86.252845,90,0.0,8.479186e+07
2,13.55,10.30,27.41,9.51,4.22,4.87,4.05,31.0,17.43,15.04,...,69.900000,-0.01,340.12,-3519.0,56.666667,0.955,85.403987,90,0.0,3.568504e+08
3,16.71,14.09,32.94,13.28,4.53,4.55,4.22,31.0,17.44,15.24,...,67.400000,-0.01,507.33,4528.0,56.666667,0.955,85.415456,80,0.0,3.969299e+08
4,12.33,11.58,22.39,4.80,4.49,4.39,4.41,31.0,17.57,15.43,...,68.600000,0.01,132.91,-34.0,56.666667,0.955,85.358224,80,0.0,1.797442e+08
5,10.02,9.10,20.86,7.69,4.22,4.46,4.49,31.0,17.86,15.59,...,71.100000,-0.01,285.06,-1474.0,56.666667,0.955,85.374812,80,0.0,4.990624e+08
6,8.63,8.15,18.70,4.31,4.20,4.14,4.26,30.0,18.20,15.74,...,71.600000,0.00,-239.99,1866.0,56.666667,0.955,85.428313,85,0.0,5.140841e+08
7,7.35,6.81,14.98,6.59,4.39,3.78,3.86,30.0,18.56,15.89,...,71.900000,0.00,169.83,-1231.0,56.666667,0.955,85.462140,90,0.0,2.871504e+08
8,6.41,6.32,14.34,-3.07,4.53,3.73,4.03,30.0,18.89,16.01,...,73.700000,0.00,173.78,-3206.0,56.666667,0.955,85.640301,90,0.0,6.873445e+07

In [195]:
df_ee_2007_2015.to_csv('Data/y/ee_2007_2015_bn.csv', index=True)

In [196]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_ee_2007_2015.values)

df_ee_2007_2015_scaled = pd.DataFrame(scaled_features, index=df_ee_2007_2015.index, columns=df_ee_2007_2015.columns)

In [197]:
df_ee_2007_2015_scaled.to_csv('Data/y/ee_2007_2015_tcdf.csv')

In [198]:
df_lv.columns.equals(df_ee.columns)

True

In [199]:
column_index = df_ee_2007_2015_scaled.columns.get_loc('EUPC')
print(column_index)

31

In [200]:
24,3,1
3,23,1
24,24,1
18,31,1

(18, 31, 1)

In [201]:
df_ee_2016_2022 = df_ee.loc[16:22]

In [202]:
df_ee_2016_2022

,TIME_PERIOD,UR,URFF,YUA,FDI,QOR,QOA,EIAP,PS,PDPS,...,EBSG,GDPC,EIS,LBGD,EMP,LTU,FEM,LFG,EPFRG,GGAG
16,2016,6.88,6.16,14.13,3.77,4.7,4.5,3.90,1.32,30.0,...,3.207492,16863.602095,65.884179,-0.181622,77.0,2.2,73.7,0.01,14.140000,1404.000000
17,2017,5.81,5.24,12.18,6.32,4.7,5.1,3.63,1.32,31.0,...,3.975466,18457.882440,66.200409,-0.229889,79.2,2.0,76.8,0.01,279.830000,902.000000
18,2018,5.41,5.26,12.08,4.08,4.7,4.6,3.43,1.32,31.0,...,2.315765,19999.192119,66.410718,-0.760256,79.7,1.3,76.8,0.00,141.280000,-1081.000000
19,2019,4.51,4.93,11.62,9.77,4.7,4.6,3.34,1.33,31.0,...,3.686161,21457.612416,67.284038,0.196333,80.5,0.9,77.5,0.00,149.720000,-5643.000000
20,2020,6.96,6.77,18.42,12.01,4.7,4.6,3.08,1.33,31.0,...,-1.083534,20954.364802,67.203161,-5.358715,79.1,1.2,76.9,0.00,817.170000,-2976.000000
21,2021,6.18,5.54,16.62,20.31,4.7,4.6,2.68,1.33,31.0,...,-1.302298,23634.746178,68.295247,-2.149653,79.3,1.6,77.5,0.00,-85.160000,-642.928571
22,2022,5.57,5.06,18.39,4.89,4.7,4.6,2.60,1.35,31.0,...,-1.236321,27017.885739,68.785368,-0.692318,81.9,1.3,80.4,0.04,182.648667,-642.928571

In [203]:
ee_context_2016_2022 = pd.read_csv("Data/Context/Estonia_2016_2022.csv")

ee_context_2016_2022 = ee_context_2016_2022[["TIME_PERIOD", "EC", "DI", "SSB", "COC", "CPI"]]

ee_context_2016_2022

   TIME_PERIOD         EC    DI        SSB   COC   CPI
0         2016  77.575862  7.85  94.560514  1.23  70.0
1         2017  77.428880  7.79  94.623643  1.20  71.0
2         2018  77.616357  7.97  94.652164  1.47  73.0
3         2019  77.691347  7.90  94.752132  1.53  74.0
4         2020  77.575862  7.84  94.661131  1.58  75.0
5         2021  77.571362  7.84  94.689166  1.51  74.0
6         2022  77.571362  7.96  94.689166  1.54  74.0

In [204]:
ee_eu_payments_2016_2022 = ee_eu_payments[ee_eu_payments['Programming_Period'] == '2014-2020'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

ee_eu_payments_2016_2022  = ee_eu_payments_2016_2022.rename({"Year":"TIME_PERIOD"}, axis=1)

ee_eu_payments_2016_2022 = ee_eu_payments_2016_2022.loc[2:8]

ee_eu_payments_2016_2022

   TIME_PERIOD  EU_Payment_annual
2         2016          192914599
3         2017          284117863
4         2018          435232587
5         2019          500627021
6         2020          511141090
7         2021          570113413
8         2022          546809658

In [205]:
df_ee_2016_2022 = pd.merge(df_ee_2016_2022, ee_context_2016_2022, on='TIME_PERIOD', how='outer')

df_ee_2016_2022 = pd.merge(df_ee_2016_2022, ee_eu_payments_2016_2022, on='TIME_PERIOD', how='outer')

df_ee_2016_2022['EUPC'] = df_ee_2016_2022['EU_Payment_annual'] / df_ee_2016_2022['PS']

df_ee_2016_2022 = df_ee_2016_2022.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [206]:
df_ee_2016_2022

,UR,URFF,YUA,FDI,QOR,QOA,EIAP,PDPS,P65,P014,...,FEM,LFG,EPFRG,GGAG,EC,DI,SSB,COC,CPI,EUPC
0,6.88,6.16,14.13,3.77,4.7,4.5,3.90,30.0,19.19,16.15,...,73.7,0.01,14.140000,1404.000000,77.575862,7.85,94.560514,1.23,70.0,1.461474e+08
1,5.81,5.24,12.18,6.32,4.7,5.1,3.63,31.0,19.47,16.28,...,76.8,0.01,279.830000,902.000000,77.428880,7.79,94.623643,1.20,71.0,2.152408e+08
2,5.41,5.26,12.08,4.08,4.7,4.6,3.43,31.0,19.68,16.36,...,76.8,0.00,141.280000,-1081.000000,77.616357,7.97,94.652164,1.47,73.0,3.297217e+08
3,4.51,4.93,11.62,9.77,4.7,4.6,3.34,31.0,19.90,16.43,...,77.5,0.00,149.720000,-5643.000000,77.691347,7.90,94.752132,1.53,74.0,3.764113e+08
4,6.96,6.77,18.42,12.01,4.7,4.6,3.08,31.0,20.20,16.44,...,76.9,0.00,817.170000,-2976.000000,77.575862,7.84,94.661131,1.58,75.0,3.843166e+08
5,6.18,5.54,16.62,20.31,4.7,4.6,2.68,31.0,20.43,16.38,...,77.5,0.00,-85.160000,-642.928571,77.571362,7.84,94.689166,1.51,74.0,4.286567e+08
6,5.57,5.06,18.39,4.89,4.7,4.6,2.60,31.0,20.63,16.23,...,80.4,0.04,182.648667,-642.928571,77.571362,7.96,94.689166,1.54,74.0,4.050442e+08

In [207]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_ee_2016_2022.values)

df_ee_2016_2022_scaled = pd.DataFrame(scaled_features, index=df_ee_2016_2022.index, columns=df_ee_2016_2022.columns)

In [208]:
df_ee_2016_2022_scaled.to_csv('Data/y/ee_2016_2022_tcdf.csv')

In [209]:
column_index = df_ee_2016_2022_scaled.columns.get_loc('P014')
print(column_index)

9

In [210]:
12,7,1
12,9,1
18,9,0

(18, 9, 0)

===================================================================================================================

In [211]:
df_fi = pd.read_csv("Data/y/Finland.csv")

df_fi = df_fi.loc[6:22]

df_fi

,Unnamed: 0,REF_AREA_LABEL,TIME_PERIOD,HI,LF,UR,URFF,YUA,FDI,QOR,...,EIA,EBSG,GDPC,GDP,EIS,NINA,LBGD,EMP,LTU,FEM
6,6,Finland,2006,NaN,2.72,8.94,9.14,25.77,2.14,5.45,...,4.670056,4.165775,32824.193528,2.220008e+11,69.637846,1.520488,4.305193,:,:,NaN
7,7,Finland,2007,NaN,2.68,6.85,7.19,16.43,8.57,5.64,...,4.536961,4.794744,35369.427763,2.337953e+11,69.745498,1.650190,5.292982,:,:,:
8,8,Finland,2008,NaN,2.72,6.37,6.69,16.34,6.79,5.84,...,4.520778,3.615903,36559.083931,2.356292e+11,70.330602,1.635209,4.569814,:,:,:
9,9,Finland,2009,NaN,2.69,8.25,7.57,21.38,-3.48,5.89,...,4.626857,2.038683,34039.968375,2.165997e+11,71.428577,1.816013,-1.860401,72.6,1.7,71.5
10,10,Finland,2010,NaN,2.67,8.39,7.64,21.29,4.90,5.86,...,4.439422,1.364890,35080.114078,2.234622e+11,72.260118,1.599064,-2.369424,71.9,2.5,70.3
11,11,Finland,2011,NaN,2.69,7.78,7.10,19.93,-2.18,5.83,...,4.230618,-0.781159,36682.446617,2.288039e+11,72.774767,1.606380,-0.488730,72.7,2.2,70.7
12,12,Finland,2012,NaN,2.70,7.69,7.05,18.87,1.92,6.09,...,4.159666,-1.560551,37011.280629,2.253195e+11,73.055165,1.762605,-1.104413,73.0,2.1,71.3
13,13,Finland,2013,7.39,2.69,8.19,7.52,19.82,-1.83,6.10,...,4.132272,-0.984781,37414.607025,2.231120e+11,73.020367,1.773043,-1.825088,72.5,2.1,71.0
14,14,Finland,2014,NaN,2.68,8.66,7.95,20.45,6.42,5.87,...,4.255833,-1.015764,37691.943183,2.220454e+11,73.848894,1.721723,-2.267616,72.2,2.4,71.2
15,15,Finland,2015,7.41,2.69,9.38,8.84,22.30,7.54,5.78,...,4.223626,-0.398683,38359.487336,2.230812e+11,74.072208,1.472224,-1.810725,71.8,2.9,70.7
16,16,Finland,2016,7.41,2.69,8.82,8.58,20.06,2.19,5.70,...,3.864636,-1.055550,39254.796323,2.288187e+11,73.979307,1.541867,-1.298460,72.4,2.9,70.8
17,17,Finland,2017,7.47,2.71,8.64,8.39,20.04,6.66,5.40,...,3.762985,0.393848,40794.711317,2.363774e+11,74.081069,NaN,-0.443691,73.2,2.6,71.3
18,18,Finland,2018,7.63,2.75,7.36,7.30,16.96,-3.84,5.30,...,3.711875,-0.845174,42045.861455,2.391974e+11,73.950902,NaN,-0.006899,75.3,2.0,73.4
19,19,Finland,2019,7.77,2.75,6.70,6.17,17.13,6.10,5.30,...,3.778319,0.672486,43197.214723,2.424259e+11,74.581431,NaN,0.316119,76.2,1.5,74.5
20,20,Finland,2020,7.84,2.74,7.76,7.49,21.19,-0.94,NaN,...,3.655230,0.244091,42749.825799,2.363870e+11,74.395815,NaN,-5.502841,75.5,1.5,73.8
21,21,Finland,2021,7.82,2.80,7.62,7.04,17.06,8.01,NaN,...,4.108225,0.054268,44895.007541,2.427135e+11,74.478112,NaN,-2.322281,76.8,1.8,75.8
22,22,Finland,2022,7.80,2.85,6.72,6.37,14.14,4.67,NaN,...,3.759701,-1.992973,47899.554112,2.445655e+11,74.855666,NaN,-0.031939,78.4,1.5,77.8

In [212]:
df_fi = df_fi.copy()
df_fi['LFG'] = df_fi['LF'].diff()
df_fi['EPFRG'] = df_fi['EPFR'].diff()
df_fi['GGAG'] = df_fi['GGA'].diff()
df_fi = df_fi.drop(6)

In [213]:
df_fi = df_fi.drop(["Unnamed: 0", "REF_AREA_LABEL", "HI", "OCTB", "NINA", "LF", "EPFR", "GGA", "EIA", "GDP"], axis=1)

In [214]:
df_fi["EMP"] = df_fi["EMP"].replace(':', np.nan)
df_fi["LTU"] = df_fi["LTU"].replace(':', np.nan)
df_fi["FEM"] = df_fi["FEM"].replace(':', np.nan)

In [215]:
missing_values(df_fi)

TIME_PERIOD - 0 - 0.0 %
UR - 0 - 0.0 %
URFF - 0 - 0.0 %
YUA - 0 - 0.0 %
FDI - 0 - 0.0 %
QOR - 3 - 18.8 %
QOA - 3 - 18.8 %
EIAP - 0 - 0.0 %
PS - 0 - 0.0 %
PDPS - 1 - 6.2 %
P65 - 0 - 0.0 %
P014 - 0 - 0.0 %
PGP - 0 - 0.0 %
VABI - 0 - 0.0 %
GCFP - 0 - 0.0 %
GGFC - 0 - 0.0 %
GDPCG - 0 - 0.0 %
EII - 0 - 0.0 %
EBSG - 0 - 0.0 %
GDPC - 0 - 0.0 %
EIS - 0 - 0.0 %
LBGD - 0 - 0.0 %
EMP - 2 - 12.5 %
LTU - 2 - 12.5 %
FEM - 2 - 12.5 %
LFG - 0 - 0.0 %
EPFRG - 1 - 6.2 %
GGAG - 2 - 12.5 %

In [216]:
df_fi = df_fi.copy()
fill_with_mode(df_fi, ["QOR", "QOA", "PDPS"])

fill_with_mean(df_fi, ["EMP", "LTU", "FEM", "EPFRG", "GGAG"])

In [217]:
fi_context_2007_2015 = pd.read_csv("Data/Context/Finland_2007_2015.csv")

fi_context_2007_2015 = fi_context_2007_2015[["TIME_PERIOD", "DI", "GE", "CPI", "RQ", "VAA"]]

fi_context_2007_2015

   TIME_PERIOD    DI    GE   CPI    RQ   VAA
0         2007  9.03  1.97  94.0  1.55  1.46
1         2008  9.25  2.04  90.0  1.61  1.46
2         2009  9.03  2.23  89.0  1.81  1.47
3         2010  9.19  2.22  92.0  1.87  1.49
4         2011  9.06  2.24  94.0  1.81  1.51
5         2012  9.06  2.21  90.0  1.82  1.60
6         2013  9.03  2.18  89.0  1.84  1.57
7         2014  9.03  2.03  89.0  1.88  1.54
8         2015  9.03  1.84  90.0  1.83  1.54

In [218]:
fi_eu_payments = eu_payments[eu_payments['Country'] == 'FI'].copy()

fi_eu_payments['EU_Payment_annual'] = pd.to_numeric(fi_eu_payments['EU_Payment_annual'].str.replace(',', ''))

fi_eu_payments_2007_2015 = fi_eu_payments[fi_eu_payments['Programming_Period'] == '2007-2013'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

fi_eu_payments_2007_2015  = fi_eu_payments_2007_2015.rename({"Year":"TIME_PERIOD"}, axis=1)

fi_eu_payments_2007_2015 = fi_eu_payments_2007_2015.loc[0:8]

fi_eu_payments_2007_2015 = fi_eu_payments_2007_2015.rename({"Year":"TIME_PERIOD"}, axis=1)

In [219]:
fi_eu_payments_2007_2015

   TIME_PERIOD  EU_Payment_annual
0         2007           31919318
1         2008           47878976
2         2009          184114804
3         2010          147719657
4         2011          241478104
5         2012          220369451
6         2013          334713129
7         2014          215151249
8         2015           92469029

In [220]:
df_fi_2007_2015 = df_fi.loc[7:15]

In [221]:
df_fi_2007_2015 = pd.merge(df_fi_2007_2015, fi_context_2007_2015, on='TIME_PERIOD', how='outer')

df_fi_2007_2015 = pd.merge(df_fi_2007_2015, fi_eu_payments_2007_2015, on='TIME_PERIOD', how='outer')

df_fi_2007_2015['EUPC'] = df_fi_2007_2015['EU_Payment_annual'] / df_fi_2007_2015['PS']

df_fi_2007_2015 = df_fi_2007_2015.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [222]:
df_fi_2007_2015

,UR,URFF,YUA,FDI,QOR,QOA,EIAP,PDPS,P65,P014,...,FEM,LFG,EPFRG,GGAG,DI,GE,CPI,RQ,VAA,EUPC
0,6.85,7.19,16.43,8.57,5.64,6.31,4.54,17.0,16.49,16.98,...,72.435714,-0.04,-825.28,-2010.0,9.03,1.97,94.0,1.55,1.46,6.033898e+06
1,6.37,6.69,16.34,6.79,5.84,6.43,4.52,17.0,16.63,16.80,...,72.435714,0.04,522.16,-8272.0,9.25,2.04,90.0,1.61,1.46,9.016756e+06
2,8.25,7.57,21.38,-3.48,5.89,6.33,4.63,18.0,16.88,16.67,...,71.500000,-0.03,-1655.62,-3519.0,9.03,2.23,89.0,1.81,1.47,3.447843e+07
3,8.39,7.64,21.29,4.90,5.86,6.15,4.44,18.0,17.26,16.56,...,70.300000,-0.02,2260.08,8024.0,9.19,2.22,92.0,1.87,1.49,2.755964e+07
4,7.78,7.10,19.93,-2.18,5.83,6.16,4.23,18.0,17.82,16.49,...,70.700000,0.02,457.68,-7687.0,9.06,2.24,94.0,1.81,1.51,4.480113e+07
5,7.69,7.05,18.87,1.92,6.09,6.20,4.16,18.0,18.45,16.44,...,71.300000,0.01,-29.53,-5657.0,9.06,2.21,90.0,1.82,1.60,4.073372e+07
6,8.19,7.52,19.82,-1.83,6.10,6.22,4.13,18.0,19.07,16.42,...,71.000000,-0.01,1090.54,770.0,9.03,2.18,89.0,1.84,1.57,6.152815e+07
7,8.66,7.95,20.45,6.42,5.87,6.17,4.26,18.0,19.67,16.40,...,71.200000,-0.01,82.22,-4059.0,9.03,2.03,89.0,1.88,1.54,3.940499e+07
8,9.38,8.84,22.30,7.54,5.78,6.05,4.22,18.0,20.21,16.36,...,70.700000,0.01,884.41,-3477.0,9.03,1.84,90.0,1.83,1.54,1.687391e+07

In [223]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_fi_2007_2015.values)

df_fi_2007_2015_scaled = pd.DataFrame(scaled_features, index=df_fi_2007_2015.index, columns=df_fi_2007_2015.columns)

In [224]:
df_fi_2007_2015_scaled.to_csv('Data/y/fi_2007_2015_tcdf.csv')

In [225]:
df_ee.columns.equals(df_fi.columns)

True

In [226]:
column_index = df_fi_2007_2015_scaled.columns.get_loc('DI')
print(column_index)

26

In [227]:
28,3,3
28,23,2
24,24,4
23,26,0

(23, 26, 0)

In [228]:
df_fi_2016_2022 = df_fi.loc[16:22]

In [229]:
df_fi_2016_2022

,TIME_PERIOD,UR,URFF,YUA,FDI,QOR,QOA,EIAP,PS,PDPS,...,EBSG,GDPC,EIS,LBGD,EMP,LTU,FEM,LFG,EPFRG,GGAG
16,2016,8.82,8.58,20.06,2.19,5.7,6.2,3.86,5.50,18.0,...,-1.055550,39254.796323,73.979307,-1.298460,72.4,2.9,70.8,0.00,854.870,2692.000000
17,2017,8.64,8.39,20.04,6.66,5.4,6.3,3.76,5.51,18.0,...,0.393848,40794.711317,74.081069,-0.443691,73.2,2.6,71.3,0.02,2089.940,-2859.000000
18,2018,7.36,7.30,16.96,-3.84,5.3,6.2,3.71,5.52,18.0,...,-0.845174,42045.861455,73.950902,-0.006899,75.3,2.0,73.4,0.04,2134.820,1157.000000
19,2019,6.70,6.17,17.13,6.10,5.3,6.3,3.78,5.52,18.0,...,0.672486,43197.214723,74.581431,0.316119,76.2,1.5,74.5,0.00,624.410,-3437.000000
20,2020,7.76,7.49,21.19,-0.94,5.3,6.2,3.66,5.53,18.0,...,0.244091,42749.825799,74.395815,-5.502841,75.5,1.5,73.8,-0.01,582.080,-5023.000000
21,2021,7.62,7.04,17.06,8.01,5.3,6.2,4.11,5.54,18.0,...,0.054268,44895.007541,74.478112,-2.322281,76.8,1.8,75.8,0.06,2337.900,-2382.642857
22,2022,6.72,6.37,14.14,4.67,5.3,6.2,3.76,5.56,18.0,...,-1.992973,47899.554112,74.855666,-0.031939,78.4,1.5,77.8,0.05,760.712,-2382.642857

In [230]:
fi_context_2016_2022 = pd.read_csv("Data/Context/Finland_2016_2022.csv")

fi_context_2016_2022 = fi_context_2016_2022[["TIME_PERIOD", "DI", "COC", "CPI", "VAA", "ROL"]]

In [231]:
fi_context_2016_2022

   TIME_PERIOD    DI   COC   CPI   VAA   ROL
0         2016  9.03  2.19  89.0  1.53  2.01
1         2017  9.03  2.16  85.0  1.56  2.02
2         2018  9.14  2.17  85.0  1.59  2.03
3         2019  9.25  2.11  86.0  1.56  2.01
4         2020  9.20  2.17  85.0  1.61  2.02
5         2021  9.27  2.24  88.0  1.61  2.01
6         2022  9.29  2.25  87.0  1.61  1.96

In [232]:
fi_eu_payments_2016_2022 = fi_eu_payments[fi_eu_payments['Programming_Period'] == '2014-2020'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

fi_eu_payments_2016_2022  = fi_eu_payments_2016_2022.rename({"Year":"TIME_PERIOD"}, axis=1)

fi_eu_payments_2016_2022 = fi_eu_payments_2016_2022.loc[2:8]

fi_eu_payments_2016_2022

   TIME_PERIOD  EU_Payment_annual
2         2016           99461071
3         2017          137852680
4         2018          185187826
5         2019          155710017
6         2020          146257401
7         2021          226744273
8         2022          181427308

In [233]:
df_fi_2016_2022 = pd.merge(df_fi_2016_2022, fi_context_2016_2022, on='TIME_PERIOD', how='outer')

df_fi_2016_2022 = pd.merge(df_fi_2016_2022, fi_eu_payments_2016_2022, on='TIME_PERIOD', how='outer')

df_fi_2016_2022['EUPC'] = df_fi_2016_2022['EU_Payment_annual'] / df_fi_2016_2022['PS']

df_fi_2016_2022 = df_fi_2016_2022.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [234]:
df_fi_2016_2022

,UR,URFF,YUA,FDI,QOR,QOA,EIAP,PDPS,P65,P014,...,FEM,LFG,EPFRG,GGAG,DI,COC,CPI,VAA,ROL,EUPC
0,8.82,8.58,20.06,2.19,5.7,6.2,3.86,18.0,20.68,16.29,...,70.8,0.00,854.870,2692.000000,9.03,2.19,89.0,1.53,2.01,1.808383e+07
1,8.64,8.39,20.04,6.66,5.4,6.3,3.76,18.0,21.15,16.20,...,71.3,0.02,2089.940,-2859.000000,9.03,2.16,85.0,1.56,2.02,2.501864e+07
2,7.36,7.30,16.96,-3.84,5.3,6.2,3.71,18.0,21.62,16.07,...,73.4,0.04,2134.820,1157.000000,9.14,2.17,85.0,1.59,2.03,3.354852e+07
3,6.70,6.17,17.13,6.10,5.3,6.3,3.78,18.0,22.06,15.88,...,74.5,0.00,624.410,-3437.000000,9.25,2.11,86.0,1.56,2.01,2.820834e+07
4,7.76,7.49,21.19,-0.94,5.3,6.2,3.66,18.0,22.49,15.66,...,73.8,-0.01,582.080,-5023.000000,9.20,2.17,85.0,1.61,2.02,2.644799e+07
5,7.62,7.04,17.06,8.01,5.3,6.2,4.11,18.0,22.87,15.45,...,75.8,0.06,2337.900,-2382.642857,9.27,2.24,88.0,1.61,2.01,4.092857e+07
6,6.72,6.37,14.14,4.67,5.3,6.2,3.76,18.0,23.23,15.22,...,77.8,0.05,760.712,-2382.642857,9.29,2.25,87.0,1.61,1.96,3.263081e+07

In [235]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_fi_2016_2022.values)

df_fi_2016_2022_scaled = pd.DataFrame(scaled_features, index=df_fi_2016_2022.index, columns=df_fi_2016_2022.columns)

In [236]:
df_fi_2016_2022_scaled.to_csv('Data/y/fi_2016_2022_tcdf.csv')

===================================================================================================================

In [237]:
df_se = pd.read_csv("Data/y/Sweden.csv")

df_se = df_se.loc[6:22]

df_se

,Unnamed: 0,REF_AREA_LABEL,TIME_PERIOD,HI,LF,UR,URFF,YUA,FDI,QOR,...,EIA,EBSG,GDPC,GDP,EIS,NINA,LBGD,EMP,LTU,FEM
6,6,Sweden,2006,NaN,4.77,7.07,7.26,21.48,5.22,5.50,...,2.226741,6.865310,343319.451947,4.093849e+12,75.860085,2.498465,1.972020,78.4,1.0,NaN
7,7,Sweden,2007,NaN,4.84,6.16,6.47,19.26,9.42,5.65,...,2.251167,5.900063,362059.214096,4.225872e+12,76.103068,2.407499,3.214195,79.7,0.8,76.5
8,8,Sweden,2008,NaN,4.90,6.24,6.57,20.21,8.05,5.63,...,2.122367,5.218714,367898.323980,4.186862e+12,76.553322,2.438199,2.032230,80.0,0.8,76.7
9,9,Sweden,2009,NaN,4.91,8.35,8.01,25.02,2.06,5.69,...,2.177660,4.958800,357492.674906,4.008687e+12,77.662551,2.561376,-0.614954,77.9,1.1,75.1
10,10,Sweden,2010,NaN,4.94,8.61,8.52,24.76,0.13,5.71,...,2.100519,4.661454,378703.698372,4.239216e+12,77.996697,2.592290,-0.240938,77.7,1.5,74.4
11,11,Sweden,2011,NaN,5.00,7.80,7.76,22.78,1.22,5.66,...,1.989988,4.436392,392078.684225,4.373341e+12,78.085683,2.433631,0.015331,79.0,1.4,76.0
12,12,Sweden,2012,NaN,5.03,7.98,7.71,23.61,0.78,5.58,...,2.058833,4.367928,391255.979647,4.355215e+12,78.297872,2.455194,-0.914026,79.1,1.4,76.4
13,13,Sweden,2013,7.48,5.09,8.05,7.89,23.52,0.25,5.52,...,2.033299,3.831176,396337.894577,4.404765e+12,78.807199,2.346443,-1.371356,79.4,1.4,76.7
14,14,Sweden,2014,NaN,5.13,7.95,7.70,22.82,-1.05,5.50,...,1.974281,3.093335,408791.051257,4.505888e+12,79.421139,2.229543,-1.129253,79.6,1.3,77.2
15,15,Sweden,2015,7.36,5.18,7.43,7.29,20.36,1.95,5.36,...,2.036107,3.259861,431846.583992,4.704604e+12,79.676015,2.098638,0.377740,80.1,1.3,77.9
16,16,Sweden,2016,7.29,5.25,6.99,6.59,18.90,3.01,5.30,...,1.885519,2.557094,443685.809403,4.815150e+12,79.915037,2.109440,1.576112,80.8,1.2,78.7
17,17,Sweden,2017,7.28,5.33,6.72,6.44,17.88,4.53,5.50,...,1.830963,1.867221,455661.623564,4.903034e+12,80.003899,NaN,1.661827,81.4,1.1,79.2
18,18,Sweden,2018,7.31,5.40,6.36,6.24,17.40,-0.13,5.60,...,1.731348,1.652194,470977.219742,4.996337e+12,80.089851,NaN,1.473616,82.0,0.9,79.7
19,19,Sweden,2019,7.34,5.46,6.83,6.96,20.09,2.98,5.30,...,1.688915,3.961344,489687.550802,5.123726e+12,79.890515,NaN,1.471518,81.7,0.8,79.1
20,20,Sweden,2020,7.36,5.47,8.29,8.28,23.90,3.40,NaN,...,1.727511,4.189104,484957.369733,5.020978e+12,79.959705,NaN,-2.994377,80.2,1.0,77.5
21,21,Sweden,2021,7.38,5.52,8.72,9.05,24.60,9.10,NaN,...,1.972657,4.321306,524671.194591,5.319099e+12,79.882330,NaN,-0.653958,80.4,1.8,77.7
22,22,Sweden,2022,7.40,5.60,7.39,7.91,21.61,9.30,NaN,...,1.860571,1.905541,559287.117187,5.396720e+12,80.900552,NaN,0.754005,82.0,1.9,79.1

In [238]:
df_se = df_se.copy()
df_se['LFG'] = df_se['LF'].diff()
df_se['EPFRG'] = df_se['EPFR'].diff()
df_se['GGAG'] = df_se['GGA'].diff()
df_se = df_se.drop(6)

In [239]:
df_se = df_se.drop(["Unnamed: 0", "REF_AREA_LABEL", "HI", "OCTB", "NINA", "LF", "EPFR", "GGA", "EIA", "GDP"], axis=1)

In [240]:
df_se["EMP"] = df_se["EMP"].replace(':', np.nan)
df_se["LTU"] = df_se["LTU"].replace(':', np.nan)
df_se["FEM"] = df_se["FEM"].replace(':', np.nan)

In [241]:
missing_values(df_se)

TIME_PERIOD - 0 - 0.0 %
UR - 0 - 0.0 %
URFF - 0 - 0.0 %
YUA - 0 - 0.0 %
FDI - 0 - 0.0 %
QOR - 3 - 18.8 %
QOA - 3 - 18.8 %
EIAP - 0 - 0.0 %
PS - 0 - 0.0 %
PDPS - 1 - 6.2 %
P65 - 0 - 0.0 %
P014 - 0 - 0.0 %
PGP - 0 - 0.0 %
VABI - 0 - 0.0 %
GCFP - 0 - 0.0 %
GGFC - 0 - 0.0 %
GDPCG - 0 - 0.0 %
EII - 0 - 0.0 %
EBSG - 0 - 0.0 %
GDPC - 0 - 0.0 %
EIS - 0 - 0.0 %
LBGD - 0 - 0.0 %
EMP - 0 - 0.0 %
LTU - 0 - 0.0 %
FEM - 0 - 0.0 %
LFG - 0 - 0.0 %
EPFRG - 1 - 6.2 %
GGAG - 2 - 12.5 %

In [242]:
df_se = df_se.copy()
fill_with_mode(df_se, ["QOR"])

fill_with_mean(df_se, ["QOA", "FEM", "EPFRG", "GGAG", "PDPS"])

In [243]:
se_context_2007_2015 = pd.read_csv("Data/Context/Sweden_2007_2015.csv")

se_context_2007_2015 = se_context_2007_2015[["TIME_PERIOD", "DI", "GE", "CPI", "RQ", "VAA"]]

se_eu_payments = eu_payments[eu_payments['Country'] == 'SE'].copy()

se_eu_payments['EU_Payment_annual'] = pd.to_numeric(se_eu_payments['EU_Payment_annual'].str.replace(',', ''))

se_eu_payments_2007_2015 = se_eu_payments[se_eu_payments['Programming_Period'] == '2007-2013'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

se_eu_payments_2007_2015  = se_eu_payments_2007_2015.rename({"Year":"TIME_PERIOD"}, axis=1)

se_eu_payments_2007_2015 = se_eu_payments_2007_2015.loc[0:8]

In [244]:
se_eu_payments_2007_2015

   TIME_PERIOD  EU_Payment_annual
0         2007           32521830
1         2008           48782752
2         2009          181387148
3         2010          175258079
4         2011          318545277
5         2012          110051001
6         2013          250369417
7         2014          344723150
8         2015           78408753

In [245]:
df_se_2007_2015 = df_se.loc[7:15]

df_se_2007_2015 = pd.merge(df_se_2007_2015, se_context_2007_2015, on='TIME_PERIOD', how='outer')

df_se_2007_2015 = pd.merge(df_se_2007_2015, se_eu_payments_2007_2015, on='TIME_PERIOD', how='outer')

df_se_2007_2015['EUPC'] = df_se_2007_2015['EU_Payment_annual'] / df_se_2007_2015['PS']

df_se_2007_2015 = df_se_2007_2015.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [246]:
df_se_2007_2015.to_csv('Data/y/se_2007_2015_bn.csv')

In [247]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_se_2007_2015.values)

df_se_2007_2015_scaled = pd.DataFrame(scaled_features, index=df_se_2007_2015.index, columns=df_se_2007_2015.columns)

In [248]:
df_se_2007_2015_scaled.to_csv('Data/y/se_2007_2015_tcdf.csv')

In [249]:
df_fi.columns.equals(df_se.columns)

True

In [250]:
column_index = df_se_2007_2015_scaled.columns.get_loc('EUPC')
print(column_index)

31

In [251]:
13,6,3
13,7,0
19,14,0
26,24,3
12,25,0
6,25,1
24,26,0
24,31,0

(24, 31, 0)

In [252]:
se_context_2016_2022 = pd.read_csv("Data/Context/Sweden_2016_2022.csv")

se_context_2016_2022 = se_context_2016_2022[["TIME_PERIOD", "DI", "COC", "CPI", "VAA", "ROL"]]

df_se_2016_2022 = df_se.loc[16:22]

se_eu_payments_2016_2022 = se_eu_payments[se_eu_payments['Programming_Period'] == '2014-2020'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

se_eu_payments_2016_2022  = se_eu_payments_2016_2022.rename({"Year":"TIME_PERIOD"}, axis=1)

se_eu_payments_2016_2022 = se_eu_payments_2016_2022.loc[1:7]

df_se_2016_2022 = pd.merge(df_se_2016_2022, se_context_2016_2022, on='TIME_PERIOD', how='outer')

df_se_2016_2022 = pd.merge(df_se_2016_2022, se_eu_payments_2016_2022, on='TIME_PERIOD', how='outer')

df_se_2016_2022['EUPC'] = df_se_2016_2022['EU_Payment_annual'] / df_se_2016_2022['PS']

df_se_2016_2022 = df_se_2016_2022.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [253]:
df_se_2016_2022.to_csv('Data/y/se_2016_2022_bn.csv')

In [254]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_se_2016_2022.values)

df_se_2016_2022_scaled = pd.DataFrame(scaled_features, index=df_se_2016_2022.index, columns=df_se_2016_2022.columns)

In [255]:
df_se_2016_2022_scaled.to_csv('Data/y/se_2016_2022_tcdf.csv')

In [256]:
column_index = df_se_2016_2022_scaled.columns.get_loc('EUPC')
print(column_index)

31

In [257]:
18,12,1
18,17,2
5,28,0
24,28,1
18,31,1

(18, 31, 1)