In [6]:
import pandas as pd
import numpy as np

In [7]:
dk = pd.read_csv("Data/Context/Denmark.csv")

In [8]:
dk = dk.drop(["Unnamed: 0"], axis=1)

In [9]:
dk_2007_2015= dk.loc[7:15]

In [10]:
dk_2007_2015

,TIME_PERIOD,ROL,GE,COC,RQ,VAA,CPI,FOP,JI,IUI,...,WTDA,EDBS,DBP,DBD,SSB,DWCP,PMSI,PT,EC,ELFE
7,2007,2.00,2.35,2.43,1.93,1.48,94.0,0.992,0.989,85.0,...,6.08,NaN,5.0,6.5,89.822480,91.587770,63.333333,89.509231,69.613929,NaN
8,2008,1.95,2.24,2.38,1.87,1.54,93.0,0.992,0.989,85.0,...,6.05,NaN,5.0,6.5,90.069128,91.588822,63.333333,89.265890,69.613929,NaN
9,2009,1.92,2.23,2.44,1.88,1.54,93.0,0.992,0.989,86.8,...,5.90,NaN,5.0,6.5,90.102783,91.588966,63.333333,90.558650,69.613929,NaN
10,2010,1.90,2.10,2.35,1.87,1.54,93.0,0.992,0.989,88.7,...,5.80,82.577079,5.0,6.5,90.196051,91.589364,63.333333,90.980440,69.613929,NaN
11,2011,1.92,2.10,2.39,1.90,1.55,94.0,0.991,0.989,89.8,...,6.05,83.600512,5.0,6.0,91.112127,91.588840,63.333333,91.037842,68.794257,NaN
12,2012,1.88,1.99,2.38,1.80,1.67,90.0,0.992,0.989,92.3,...,6.16,84.623198,5.0,6.0,91.170983,91.589232,63.333333,91.680405,68.794257,NaN
13,2013,1.90,1.94,2.40,1.80,1.67,91.0,0.992,0.989,94.6,...,6.01,84.727210,5.0,6.0,91.198876,91.589587,63.333333,91.832348,68.794257,NaN
14,2014,2.10,1.78,2.25,1.68,1.52,92.0,0.992,0.989,96.0,...,6.10,84.065592,5.0,6.0,91.219461,89.537592,72.000000,91.834965,65.925404,NaN
15,2015,2.02,1.79,2.19,1.72,1.55,91.0,0.992,0.989,96.3,...,6.10,84.273573,5.0,6.0,91.802316,85.715078,72.000000,91.834965,68.365447,8.1

In [11]:
def missing_values(df):
    for feature in df.columns:
        missing_values = df[feature].isna().sum()
        percentage = missing_values/len(df) * 100
        print(f'{feature} - {missing_values} - {round(percentage, 1)} %')

In [36]:
missing_values(dk_2007_2015)

TIME_PERIOD - 0 - 0.0 %
ROL - 0 - 0.0 %
GE - 0 - 0.0 %
COC - 0 - 0.0 %
RQ - 0 - 0.0 %
VAA - 0 - 0.0 %
CPI - 0 - 0.0 %
FOP - 0 - 0.0 %
JI - 0 - 0.0 %
IUI - 0 - 0.0 %
CFI - 4 - 44.4 %
PR - 0 - 0.0 %
DI - 2 - 22.2 %
SOARS - 0 - 0.0 %
TOGP - 0 - 0.0 %
IPAB - 3 - 33.3 %
PTIP - 0 - 0.0 %
QOES - 0 - 0.0 %
AOLT - 0 - 0.0 %
FLTA - 0 - 0.0 %
EBOF - 0 - 0.0 %
FOWD - 0 - 0.0 %
QOMS - 0 - 0.0 %
CLER - 0 - 0.0 %
WTDA - 0 - 0.0 %
EDBS - 3 - 33.3 %
DBP - 0 - 0.0 %
DBD - 0 - 0.0 %
SSB - 0 - 0.0 %
DWCP - 0 - 0.0 %
PMSI - 0 - 0.0 %
PT - 0 - 0.0 %
EC - 0 - 0.0 %
ELFE - 8 - 88.9 %

In [12]:
mode = dk_2007_2015['DI'].mode()[0]
dk_2007_2015['DI'].fillna(value=mode, inplace=True)

/var/folders/41/w_0mz3gn2vn0w0dz8wywr8_r0000gn/T/ipykernel_93823/1347846478.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dk_2007_2015['DI'].fillna(value=mode, inplace=True)

In [14]:
dk_2007_2015 = dk_2007_2015.drop(["ELFE", "CFI", "IPAB", "EDBS"], axis=1)

In [15]:
def fill_with_mean(df):
    for feature in df.columns:
        mean = df[feature].mean()
        df[feature].fillna(value=mean, inplace=True)

In [16]:
continuous_data = ['DBP', "DBD", "EDBS", "SSB", "DWCP", "PT", "EC", "IUI", "PMSI"]

In [17]:
def handle_outliers(df, continuous_features):

    print("Original Shape:", df.shape)
    
    outlier_summary = {}
    
    for feature in continuous_features:
        if feature in df.columns:
            Q1 = df[feature].quantile(0.25)
            Q3 = df[feature].quantile(0.75)
            IQR = Q3 - Q1
            lower_bound = Q1 - 1.5 * IQR
            upper_bound = Q3 + 1.5 * IQR
            
            outlier_mask = (df[feature] < lower_bound) | (df[feature] > upper_bound)
            num_outliers = outlier_mask.sum()
            
            if num_outliers > 0:
                non_outlier_mean = df.loc[~outlier_mask, feature].mean()
                
                df.loc[outlier_mask, feature] = non_outlier_mean
                
                print(f"{feature}: Found {num_outliers} outliers, replaced with mean = {non_outlier_mean:.2f}")
            else:
                print(f"{feature}: No outliers found")
    
    print("\nFinal Shape:", df.shape)
    print(f"Total features processed: {len(continuous_features)}")
    
    return df

In [18]:
dk_2007_2015_no_o = handle_outliers(dk_2007_2015, continuous_data)

Original Shape: (9, 30)
DBP: No outliers found
DBD: No outliers found
SSB: No outliers found
DWCP: Found 2 outliers, replaced with mean = 91.59
PT: No outliers found
EC: Found 1 outliers, replaced with mean = 69.15
IUI: No outliers found
PMSI: Found 2 outliers, replaced with mean = 63.33

Final Shape: (9, 30)
Total features processed: 9

In [19]:
dk_2007_2015_no_o

,TIME_PERIOD,ROL,GE,COC,RQ,VAA,CPI,FOP,JI,IUI,...,QOMS,CLER,WTDA,DBP,DBD,SSB,DWCP,PMSI,PT,EC
7,2007,2.00,2.35,2.43,1.93,1.48,94.0,0.992,0.989,85.0,...,5.63,6.32,6.08,5.0,6.5,89.822480,91.587770,63.333333,89.509231,69.613929
8,2008,1.95,2.24,2.38,1.87,1.54,93.0,0.992,0.989,85.0,...,5.63,6.22,6.05,5.0,6.5,90.069128,91.588822,63.333333,89.265890,69.613929
9,2009,1.92,2.23,2.44,1.88,1.54,93.0,0.992,0.989,86.8,...,5.64,5.98,5.90,5.0,6.5,90.102783,91.588966,63.333333,90.558650,69.613929
10,2010,1.90,2.10,2.35,1.87,1.54,93.0,0.992,0.989,88.7,...,5.41,5.72,5.80,5.0,6.5,90.196051,91.589364,63.333333,90.980440,69.613929
11,2011,1.92,2.10,2.39,1.90,1.55,94.0,0.991,0.989,89.8,...,5.22,5.94,6.05,5.0,6.0,91.112127,91.588840,63.333333,91.037842,68.794257
12,2012,1.88,1.99,2.38,1.80,1.67,90.0,0.992,0.989,92.3,...,5.08,5.95,6.16,5.0,6.0,91.170983,91.589232,63.333333,91.680405,68.794257
13,2013,1.90,1.94,2.40,1.80,1.67,91.0,0.992,0.989,94.6,...,5.15,5.84,6.01,5.0,6.0,91.198876,91.589587,63.333333,91.832348,68.794257
14,2014,2.10,1.78,2.25,1.68,1.52,92.0,0.992,0.989,96.0,...,5.21,5.96,6.10,5.0,6.0,91.219461,91.588940,63.333333,91.834965,69.150492
15,2015,2.02,1.79,2.19,1.72,1.55,91.0,0.992,0.989,96.3,...,5.35,6.06,6.10,5.0,6.0,91.802316,91.588940,63.333333,91.834965,68.365447

In [20]:
dk_2007_2015_no_o.to_csv('Data/Context/Denmark_2007_2015.csv')

In [21]:
dk_2007_2015_no_o = dk_2007_2015_no_o.drop(["TIME_PERIOD"], axis=1)

In [22]:
dk_2007_2015_l = dk_2007_2015_no_o.loc[13]

In [24]:
dk_2007_2015_l.to_csv('Data/Context/Denmark_2007_2013_last.csv')

,TIME_PERIOD,ROL,GE,COC,RQ,VAA,CPI,FOP,JI,IUI,...,WTDA,EDBS,DBP,DBD,SSB,DWCP,PMSI,PT,EC,ELFE
0,2000,1.81,1.90,2.32,1.71,1.54,NaN,0.992,0.989,39.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2001,NaN,NaN,NaN,NaN,NaN,95.0,0.992,0.989,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2002,1.88,2.02,2.31,1.71,1.53,95.0,0.992,0.989,64.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2003,1.92,2.09,2.36,1.73,1.60,95.0,0.992,0.989,76.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2004,1.93,2.29,2.41,1.75,1.80,95.0,0.992,0.989,80.9,...,NaN,NaN,6.0,7.5,87.778648,NaN,NaN,NaN,70.168156,NaN
5,2005,1.94,2.11,2.28,1.65,1.74,95.0,0.992,0.989,82.7,...,NaN,NaN,6.0,7.5,87.840351,NaN,NaN,NaN,69.126490,NaN
6,2006,1.98,2.22,2.46,1.80,1.57,95.0,0.992,0.989,86.7,...,NaN,NaN,5.0,6.5,89.675327,91.587142,63.333333,88.663705,69.613929,NaN
7,2007,2.00,2.35,2.43,1.93,1.48,94.0,0.992,0.989,85.0,...,6.08,NaN,5.0,6.5,89.822480,91.587770,63.333333,89.509231,69.613929,NaN
8,2008,1.95,2.24,2.38,1.87,1.54,93.0,0.992,0.989,85.0,...,6.05,NaN,5.0,6.5,90.069128,91.588822,63.333333,89.265890,69.613929,NaN
9,2009,1.92,2.23,2.44,1.88,1.54,93.0,0.992,0.989,86.8,...,5.90,NaN,5.0,6.5,90.102783,91.588966,63.333333,90.558650,69.613929,NaN
10,2010,1.90,2.10,2.35,1.87,1.54,93.0,0.992,0.989,88.7,...,5.80,82.577079,5.0,6.5,90.196051,91.589364,63.333333,90.980440,69.613929,NaN
11,2011,1.92,2.10,2.39,1.90,1.55,94.0,0.991,0.989,89.8,...,6.05,83.600512,5.0,6.0,91.112127,91.588840,63.333333,91.037842,68.794257,NaN
12,2012,1.88,1.99,2.38,1.80,1.67,90.0,0.992,0.989,92.3,...,6.16,84.623198,5.0,6.0,91.170983,91.589232,63.333333,91.680405,68.794257,NaN
13,2013,1.90,1.94,2.40,1.80,1.67,91.0,0.992,0.989,94.6,...,6.01,84.727210,5.0,6.0,91.198876,91.589587,63.333333,91.832348,68.794257,NaN
14,2014,2.10,1.78,2.25,1.68,1.52,92.0,0.992,0.989,96.0,...,6.10,84.065592,5.0,6.0,91.219461,89.537592,72.000000,91.834965,65.925404,NaN
15,2015,2.02,1.79,2.19,1.72,1.55,91.0,0.992,0.989,96.3,...,6.10,84.273573,5.0,6.0,91.802316,85.715078,72.000000,91.834965,68.365447,8.1
16,2016,1.88,1.82,2.20,1.56,1.54,90.0,0.988,0.989,97.0,...,6.10,84.446565,5.0,6.0,91.819264,86.301441,72.000000,91.142197,68.365447,7.5
17,2017,1.80,1.75,2.19,1.61,1.52,88.0,0.988,0.985,97.1,...,NaN,84.532354,5.0,6.0,91.841026,87.044147,72.000000,91.142197,68.365447,8.8
18,2018,1.77,1.81,2.16,1.63,1.57,88.0,0.988,0.985,97.3,...,NaN,84.517791,5.0,6.0,91.866931,86.786174,72.000000,91.142197,68.365447,10.4
19,2019,1.83,1.87,2.12,1.55,1.54,87.0,0.984,0.985,98.0,...,NaN,85.107470,5.0,6.0,91.889599,86.904664,72.000000,91.142197,73.921002,9.9
20,2020,1.81,1.84,2.24,1.79,1.51,88.0,0.988,0.987,96.5,...,NaN,85.225742,5.0,6.0,92.076386,87.879698,72.000000,91.142197,73.921002,9.3
21,2021,1.90,1.96,2.33,1.80,1.54,88.0,0.988,0.985,98.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.8
22,2022,1.90,1.99,2.40,1.84,1.59,90.0,0.988,0.987,97.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
23,2023,1.91,2.02,2.38,1.84,1.66,90.0,0.988,0.988,98.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.4
24,2024,NaN,NaN,NaN,NaN,NaN,90.0,0.988,0.984,99.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.4
25,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
dk_2016_2022 = dk.loc[16:22]

In [41]:

missing_values(dk_2016_2022)

TIME_PERIOD - 0 - 0.0 %
ROL - 0 - 0.0 %
GE - 0 - 0.0 %
COC - 0 - 0.0 %
RQ - 0 - 0.0 %
VAA - 0 - 0.0 %
CPI - 0 - 0.0 %
FOP - 0 - 0.0 %
JI - 0 - 0.0 %
IUI - 0 - 0.0 %
CFI - 0 - 0.0 %
PR - 0 - 0.0 %
DI - 0 - 0.0 %
SOARS - 0 - 0.0 %
TOGP - 0 - 0.0 %
IPAB - 0 - 0.0 %
PTIP - 0 - 0.0 %
QOES - 0 - 0.0 %
AOLT - 0 - 0.0 %
FLTA - 0 - 0.0 %
EBOF - 0 - 0.0 %
FOWD - 0 - 0.0 %
QOMS - 0 - 0.0 %
CLER - 0 - 0.0 %
WTDA - 0 - 0.0 %
EDBS - 0 - 0.0 %
DBP - 0 - 0.0 %
DBD - 0 - 0.0 %
SSB - 0 - 0.0 %
DWCP - 0 - 0.0 %
PMSI - 0 - 0.0 %
PT - 0 - 0.0 %
EC - 0 - 0.0 %
ELFE - 0 - 0.0 %

In [42]:
dk_2016_2022 = dk_2016_2022.drop(["SOARS", "TOGP", "IPAB", "PTIP", "QOES", "AOLT", "FLTA", "EBOF",
                                 "FOWD", "QOMS", "CLER", "WTDA"], axis=1)

In [43]:
fill_with_mean(dk_2016_2022)

In [44]:
continuous_data = ['DBP', "DBD", "EDBS", "SSB", "DWCP", "PT", "EC", "IUI", "PMSI"]

In [45]:
dk_2016_2022_no_o = handle_outliers(dk_2016_2022, continuous_data)

Original Shape: (7, 22)
DBP: No outliers found
DBD: No outliers found
EDBS: No outliers found
SSB: No outliers found
DWCP: Found 1 outliers, replaced with mean = 86.97
PT: No outliers found
EC: No outliers found
IUI: No outliers found
PMSI: No outliers found

Final Shape: (7, 22)
Total features processed: 9

In [46]:
dk_2016_2022_no_o.to_csv('Data/Context/Denmark_2016_2022.csv')

In [49]:
dk_2016_2022_no_o = dk_2016_2022_no_o.drop(["TIME_PERIOD"], axis=1)

In [50]:
dk_2016_2022_no_o

,ROL,GE,COC,RQ,VAA,CPI,FOP,JI,IUI,CFI,...,DI,EDBS,DBP,DBD,SSB,DWCP,PMSI,PT,EC,ELFE
16,1.88,1.82,2.20,1.56,1.54,90.0,0.988,0.989,97.0,58.5,...,9.20,84.446565,5.0,6.0,91.819264,86.940287,72.0,91.142197,68.365447,7.5
17,1.80,1.75,2.19,1.61,1.52,88.0,0.988,0.985,97.1,58.7,...,9.22,84.532354,5.0,6.0,91.841026,87.044147,72.0,91.142197,68.365447,8.8
18,1.77,1.81,2.16,1.63,1.57,88.0,0.988,0.985,97.3,58.4,...,9.22,84.517791,5.0,6.0,91.866931,86.965972,72.0,91.142197,68.365447,10.4
19,1.83,1.87,2.12,1.55,1.54,87.0,0.984,0.985,98.0,58.4,...,9.22,85.107470,5.0,6.0,91.889599,86.904664,72.0,91.142197,73.921002,9.9
20,1.81,1.84,2.24,1.79,1.51,88.0,0.988,0.987,96.5,57.5,...,9.15,85.225742,5.0,6.0,91.869017,86.940287,72.0,91.142197,73.921002,9.3
21,1.90,1.96,2.33,1.80,1.54,88.0,0.988,0.985,98.9,57.3,...,9.09,84.765984,5.0,6.0,91.898641,86.983225,72.0,91.142197,70.587669,9.8
22,1.90,1.99,2.40,1.84,1.59,90.0,0.988,0.987,97.9,55.9,...,9.28,84.765984,5.0,6.0,91.898641,86.983225,72.0,91.142197,70.587669,10.0

In [52]:
dk_2016_2022_l = dk_2016_2022_no_o.loc[20]

In [53]:
dk_2016_2022_l

ROL      1.810000
GE       1.840000
COC      2.240000
RQ       1.790000
VAA      1.510000
CPI     88.000000
FOP      0.988000
JI       0.987000
IUI     96.500000
CFI     57.500000
PR      86.000000
DI       9.150000
EDBS    85.225742
DBP      5.000000
DBD      6.000000
SSB     91.869017
DWCP    86.940287
PMSI    72.000000
PT      91.142197
EC      73.921002
ELFE     9.300000
Name: 20, dtype: float64

In [54]:
dk_2016_2022_l.to_csv('Data/Context/Denmark_2014_2020_last.csv')