In [1]:
import pandas as pd
import numpy as np

In [2]:
de = pd.read_csv("Data/Context/Germany.csv")

In [3]:
de = de.drop(["Unnamed: 0"], axis=1)

In [4]:
de_2007_2013 = de.loc[7:13]

In [5]:
de_2007_2013

,TIME_PERIOD,ROL,GE,COC,RQ,VAA,CPI,FOP,JI,IUI,...,WTDA,EDBS,DBP,DBD,SSB,DWCP,PMSI,PT,EC,ELFE
7,2007,1.76,1.63,1.73,1.62,1.34,78.0,0.986,0.952,75.2,...,5.38,NaN,9.0,27.0,78.044700,82.709673,50.0,77.197929,76.735165,NaN
8,2008,1.73,1.51,1.75,1.49,1.34,79.0,0.986,0.952,78.0,...,5.36,NaN,9.0,23.0,79.197611,82.821877,50.0,76.399686,76.735165,NaN
9,2009,1.65,1.58,1.75,1.52,1.33,80.0,0.986,0.952,79.0,...,5.18,NaN,9.0,22.5,79.363510,82.758552,50.0,76.198556,76.735165,NaN
10,2010,1.64,1.52,1.77,1.57,1.30,79.0,0.986,0.952,82.0,...,5.01,79.277568,9.0,22.5,79.567065,82.888440,50.0,78.957718,76.735165,NaN
11,2011,1.62,1.50,1.74,1.55,1.35,80.0,0.986,0.952,81.3,...,4.81,79.213356,9.0,17.5,80.744231,82.852483,50.0,76.428017,76.735165,NaN
12,2012,1.67,1.53,1.82,1.53,1.39,79.0,0.983,0.952,82.4,...,4.88,79.298046,9.0,17.5,80.867728,82.818229,50.0,76.817402,76.735165,NaN
13,2013,1.64,1.51,1.80,1.54,1.41,78.0,0.983,0.952,84.2,...,4.90,79.187647,9.0,17.5,80.918824,82.870361,50.0,79.063708,76.735165,NaN

In [6]:
def missing_values(df):
    for feature in df.columns:
        missing_values = df[feature].isna().sum()
        percentage = missing_values/len(df) * 100
        print(f'{feature} - {missing_values} - {round(percentage, 1)} %')

In [7]:
missing_values(de_2007_2013)

TIME_PERIOD - 0 - 0.0 %
ROL - 0 - 0.0 %
GE - 0 - 0.0 %
COC - 0 - 0.0 %
RQ - 0 - 0.0 %
VAA - 0 - 0.0 %
CPI - 0 - 0.0 %
FOP - 0 - 0.0 %
JI - 0 - 0.0 %
IUI - 0 - 0.0 %
CFI - 4 - 57.1 %
PR - 0 - 0.0 %
DI - 2 - 28.6 %
SOARS - 0 - 0.0 %
TOGP - 0 - 0.0 %
IPAB - 3 - 42.9 %
PTIP - 0 - 0.0 %
QOES - 0 - 0.0 %
AOLT - 0 - 0.0 %
FLTA - 0 - 0.0 %
EBOF - 0 - 0.0 %
FOWD - 0 - 0.0 %
QOMS - 0 - 0.0 %
CLER - 0 - 0.0 %
WTDA - 0 - 0.0 %
EDBS - 3 - 42.9 %
DBP - 0 - 0.0 %
DBD - 0 - 0.0 %
SSB - 0 - 0.0 %
DWCP - 0 - 0.0 %
PMSI - 0 - 0.0 %
PT - 0 - 0.0 %
EC - 0 - 0.0 %
ELFE - 7 - 100.0 %

In [8]:
de_2007_2013 = de_2007_2013.drop(["ELFE", "CFI", "IPAB", "EDBS"], axis=1)

In [9]:
def fill_with_mean(df):
    for feature in df.columns:
        mean = df[feature].mean()
        df[feature].fillna(value=mean, inplace=True)

In [10]:
fill_with_mean(de_2007_2013)

In [11]:
continuous_data = ['DBP', "DBD", "EDBS", "SSB", "DWCP", "PT", "EC", "IUI", "PMSI"]

In [12]:
def handle_outliers(df, continuous_features):

    print("Original Shape:", df.shape)
    
    outlier_summary = {}
    
    for feature in continuous_features:
        if feature in df.columns:
            Q1 = df[feature].quantile(0.25)
            Q3 = df[feature].quantile(0.75)
            IQR = Q3 - Q1
            lower_bound = Q1 - 1.5 * IQR
            upper_bound = Q3 + 1.5 * IQR
            
            outlier_mask = (df[feature] < lower_bound) | (df[feature] > upper_bound)
            num_outliers = outlier_mask.sum()
            
            if num_outliers > 0:
                non_outlier_mean = df.loc[~outlier_mask, feature].mean()
                
                df.loc[outlier_mask, feature] = non_outlier_mean
                
                print(f"{feature}: Found {num_outliers} outliers, replaced with mean = {non_outlier_mean:.2f}")
            else:
                print(f"{feature}: No outliers found")
    
    print("\nFinal Shape:", df.shape)
    print(f"Total features processed: {len(continuous_features)}")
    
    return df

In [13]:
de_2007_2013_no_o = handle_outliers(de_2007_2013, continuous_data)

Original Shape: (7, 30)
DBP: No outliers found
DBD: No outliers found
SSB: No outliers found
DWCP: No outliers found
PT: No outliers found
EC: No outliers found
IUI: No outliers found
PMSI: No outliers found

Final Shape: (7, 30)
Total features processed: 9

In [14]:
de_2007_2013_no_o

,TIME_PERIOD,ROL,GE,COC,RQ,VAA,CPI,FOP,JI,IUI,...,QOMS,CLER,WTDA,DBP,DBD,SSB,DWCP,PMSI,PT,EC
7,2007,1.76,1.63,1.73,1.62,1.34,78.0,0.986,0.952,75.2,...,5.11,5.10,5.38,9.0,27.0,78.044700,82.709673,50.0,77.197929,76.735165
8,2008,1.73,1.51,1.75,1.49,1.34,79.0,0.986,0.952,78.0,...,5.14,4.96,5.36,9.0,23.0,79.197611,82.821877,50.0,76.399686,76.735165
9,2009,1.65,1.58,1.75,1.52,1.33,80.0,0.986,0.952,79.0,...,4.96,5.03,5.18,9.0,22.5,79.363510,82.758552,50.0,76.198556,76.735165
10,2010,1.64,1.52,1.77,1.57,1.30,79.0,0.986,0.952,82.0,...,4.93,5.25,5.01,9.0,22.5,79.567065,82.888440,50.0,78.957718,76.735165
11,2011,1.62,1.50,1.74,1.55,1.35,80.0,0.986,0.952,81.3,...,4.78,5.12,4.81,9.0,17.5,80.744231,82.852483,50.0,76.428017,76.735165
12,2012,1.67,1.53,1.82,1.53,1.39,79.0,0.983,0.952,82.4,...,4.95,5.17,4.88,9.0,17.5,80.867728,82.818229,50.0,76.817402,76.735165
13,2013,1.64,1.51,1.80,1.54,1.41,78.0,0.983,0.952,84.2,...,5.10,5.20,4.90,9.0,17.5,80.918824,82.870361,50.0,79.063708,76.735165

In [15]:
de_2007_2013_no_o.to_csv('Data/Context/Germany_2007_2013.csv')

In [16]:
de_2007_2013_no_o = de_2007_2013_no_o.drop(["TIME_PERIOD"], axis=1)

In [17]:
de_2007_2013_l = de_2007_2013_no_o.loc[13]

In [18]:
de_2007_2013_l.to_csv('Data/Context/Germany_2007_2013_last.csv')

In [19]:
de_2014_2020 = de.loc[14:20]

In [20]:

missing_values(de_2014_2020)

TIME_PERIOD - 0 - 0.0 %
ROL - 0 - 0.0 %
GE - 0 - 0.0 %
COC - 0 - 0.0 %
RQ - 0 - 0.0 %
VAA - 0 - 0.0 %
CPI - 0 - 0.0 %
FOP - 0 - 0.0 %
JI - 0 - 0.0 %
IUI - 0 - 0.0 %
CFI - 0 - 0.0 %
PR - 0 - 0.0 %
DI - 0 - 0.0 %
SOARS - 3 - 42.9 %
TOGP - 3 - 42.9 %
IPAB - 3 - 42.9 %
PTIP - 3 - 42.9 %
QOES - 3 - 42.9 %
AOLT - 3 - 42.9 %
FLTA - 3 - 42.9 %
EBOF - 3 - 42.9 %
FOWD - 3 - 42.9 %
QOMS - 3 - 42.9 %
CLER - 3 - 42.9 %
WTDA - 4 - 57.1 %
EDBS - 0 - 0.0 %
DBP - 0 - 0.0 %
DBD - 0 - 0.0 %
SSB - 0 - 0.0 %
DWCP - 0 - 0.0 %
PMSI - 0 - 0.0 %
PT - 0 - 0.0 %
EC - 0 - 0.0 %
ELFE - 1 - 14.3 %

In [21]:
de_2014_2020 = de_2014_2020.drop(["SOARS", "TOGP", "IPAB", "PTIP", "QOES", "AOLT", "FLTA", "EBOF",
                                 "FOWD", "QOMS", "CLER", "WTDA"], axis=1)

In [22]:
fill_with_mean(de_2014_2020)

In [23]:
continuous_data = ['DBP', "DBD", "EDBS", "SSB", "DWCP", "PT", "EC", "IUI", "PMSI"]

In [24]:
de_2014_2020_no_o = handle_outliers(de_2014_2020, continuous_data)

Original Shape: (7, 22)
DBP: No outliers found
DBD: No outliers found
EDBS: No outliers found
SSB: No outliers found
DWCP: Found 1 outliers, replaced with mean = 78.14
PT: No outliers found
EC: Found 1 outliers, replaced with mean = 71.28
IUI: No outliers found
PMSI: No outliers found

Final Shape: (7, 22)
Total features processed: 9

In [25]:
de_2014_2020_no_o.to_csv('Data/Context/Germany_2014_2020.csv')

In [26]:
de_2014_2020_no_o = de_2014_2020_no_o.drop(["TIME_PERIOD"], axis=1)

In [27]:
de_2014_2020_no_o

,ROL,GE,COC,RQ,VAA,CPI,FOP,JI,IUI,CFI,...,DI,EDBS,DBP,DBD,SSB,DWCP,PMSI,PT,EC,ELFE
14,1.85,1.66,1.81,1.70,1.44,79.0,0.983,0.952,86.2,56.0,...,8.64,79.316127,9.0,17.5,80.997172,78.136613,62.0,76.843778,71.284598,10.2
15,1.76,1.66,1.78,1.71,1.42,81.0,0.976,0.952,87.6,57.1,...,8.64,78.851145,9.0,17.5,80.627202,78.084024,62.0,77.020556,71.486986,10.1
16,1.58,1.66,1.78,1.81,1.36,81.0,0.976,0.952,84.2,57.9,...,8.63,79.425123,9.0,13.5,81.991794,78.113460,62.0,82.167297,70.940538,10.3
17,1.57,1.61,1.80,1.78,1.43,81.0,0.971,0.919,84.4,58.4,...,8.61,79.428673,9.0,13.0,82.202748,78.144349,62.0,82.157760,70.394090,10.1
18,1.59,1.52,1.90,1.76,1.44,80.0,0.973,0.919,87.0,58.0,...,8.68,79.023990,9.0,13.0,82.214093,78.114656,60.0,82.140949,70.394090,10.3
19,1.58,1.50,1.87,1.71,1.35,80.0,0.973,0.919,88.1,58.2,...,8.68,79.022313,9.0,13.0,82.338520,78.161160,60.0,82.105637,70.394090,10.3
20,1.52,1.31,1.83,1.58,1.37,80.0,0.965,0.919,89.8,56.5,...,8.67,78.553096,9.0,13.0,82.418073,78.202031,60.0,82.330087,74.097794,10.1

In [28]:
de_2014_2020_l = de_2014_2020_no_o.loc[20]

In [29]:
de_2014_2020_l

ROL      1.520000
GE       1.310000
COC      1.830000
RQ       1.580000
VAA      1.370000
CPI     80.000000
FOP      0.965000
JI       0.919000
IUI     89.800000
CFI     56.500000
PR      81.000000
DI       8.670000
EDBS    78.553096
DBP      9.000000
DBD     13.000000
SSB     82.418073
DWCP    78.202031
PMSI    60.000000
PT      82.330087
EC      74.097794
ELFE    10.100000
Name: 20, dtype: float64

In [30]:
de_2014_2020_l.to_csv('Data/Context/Germany_2014_2020_last.csv')