In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
def missing_values(df):
    for feature in df.columns:
        missing_values = df[feature].isna().sum()
        percentage = missing_values/len(df) * 100
        print(f'{feature} - {missing_values} - {round(percentage, 1)} %')
        
def fill_with_mode(df, feature_list):
    for feature in feature_list:
        mode = df[feature].mode()[0]
        df[feature].fillna(value=mode, inplace=True)

def fill_with_mean(df, feature_list):
    for feature in feature_list:
        df[feature] = pd.to_numeric(df[feature], errors='coerce')
        mean = df[feature].mean()
        df[feature].fillna(value=mean, inplace=True)

In [3]:
df_dk = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/Denmark.csv")

In [4]:
df_dk = df_dk.loc[6:22]

In [5]:
df_dk = df_dk.copy()
df_dk['PAG'] = df_dk['PA'].diff()
df_dk['EPFRG'] = df_dk['EPFR'].diff()
df_dk['GGAG'] = df_dk['GGA'].diff()
df_dk = df_dk.drop(6)

In [6]:
df_dk = df_dk[["TIME_PERIOD", "GDPC", "GDPCG", "VABI", "EMP", "PAG", "QOA", "QOR", "YUA", "GGAG", "REST", "CO2",
             "EBSG", "FDI", "GGFC", "LBGD", "PC", "ARP", "PS"]]

In [7]:
df_dk

,TIME_PERIOD,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,REST,CO2,EBSG,FDI,GGFC,LBGD,PC,ARP,PS
7,2007,319173.149269,0.540322,22.06,:,157.0,6.45,6.42,7.49,-4900.0,17.747,53.8693,2.747300,3.69,24.277939,5.548536,5.3,11.7,5.46
8,2008,329422.223703,-1.000559,22.61,:,-26.0,6.44,6.23,9.47,-3557.0,18.543,50.6018,3.471527,0.62,24.986449,3.835619,6.5,11.8,5.49
9,2009,313144.896657,-5.481583,19.85,76.1,-116.0,6.43,6.06,13.44,-2932.0,19.948,48.4089,4.602963,1.17,27.815694,-2.111442,4.2,13.1,5.52
10,2010,326784.316443,1.132669,19.37,74.9,108.0,6.37,6.17,15.55,251.0,21.888,48.5600,6.793833,-3.57,27.336108,-2.441067,4.7,13.3,5.55
11,2011,331838.652835,0.894526,19.85,74.8,-52.0,6.32,6.29,16.31,-5488.0,23.389,43.4849,6.154324,3.94,26.540559,-1.887012,3.6,12.1,5.57
12,2012,338534.135302,-0.380977,19.85,74.3,-168.0,5.97,5.73,15.77,-5127.0,25.465,38.5966,5.799405,-5.00,26.500323,-3.257951,4.0,12.0,5.59
13,2013,344715.698783,0.970846,19.73,74.3,-65.0,5.64,5.45,14.77,1404.0,27.173,40.3352,6.229005,0.20,25.928504,-1.181728,4.4,11.9,5.61
14,2014,350893.947080,0.765766,19.40,74.7,36.0,5.56,5.43,14.20,-4198.0,29.310,36.1972,6.455948,1.86,25.797420,1.252108,5.8,12.1,5.64
15,2015,357211.575191,1.385666,19.56,75.4,85.0,5.58,5.59,12.15,-2024.0,30.469,34.0712,6.498281,0.61,25.546356,-1.143677,8.4,12.2,5.68
16,2016,366884.878867,2.271802,20.23,76.0,90.0,5.80,5.70,12.15,1635.0,31.715,35.6784,6.035122,2.50,24.942915,-0.070663,7.2,11.9,5.73
17,2017,379808.676526,2.395591,20.42,76.6,-62.0,6.10,5.50,12.38,-2276.0,34.387,33.5457,6.476226,1.09,24.449662,1.457031,5.6,12.4,5.76
18,2018,387242.522658,1.356196,20.58,77.5,-228.0,5.80,5.50,10.52,-555.0,35.159,33.5379,5.152751,2.47,24.381107,0.801500,4.3,12.7,5.79
19,2019,396193.582956,1.347792,20.64,78.3,89.0,5.80,5.60,10.04,-3538.0,37.020,30.0794,6.009741,-1.10,24.204777,4.079333,2.9,12.5,5.81
20,2020,398976.348406,-2.066138,19.56,77.8,-90.0,NaN,NaN,11.59,-2434.0,31.681,27.7879,5.640362,0.36,24.679988,0.081707,3.0,12.1,5.83
21,2021,438387.741596,6.917664,19.80,79.0,-171.0,NaN,NaN,10.81,NaN,41.494,29.5641,6.236804,4.16,23.845550,3.868870,5.7,12.3,5.86
22,2022,481824.514568,0.743682,20.84,80.1,NaN,NaN,NaN,10.53,NaN,41.368,28.4942,9.553789,7.67,21.681084,3.323468,10.0,12.4,5.90

In [8]:
df_dk["EMP"] = df_dk["EMP"].replace(':', np.nan)

In [9]:
missing_values(df_dk)

TIME_PERIOD - 0 - 0.0 %
GDPC - 0 - 0.0 %
GDPCG - 0 - 0.0 %
VABI - 0 - 0.0 %
EMP - 2 - 12.5 %
PAG - 1 - 6.2 %
QOA - 3 - 18.8 %
QOR - 3 - 18.8 %
YUA - 0 - 0.0 %
GGAG - 2 - 12.5 %
REST - 0 - 0.0 %
CO2 - 0 - 0.0 %
EBSG - 0 - 0.0 %
FDI - 0 - 0.0 %
GGFC - 0 - 0.0 %
LBGD - 0 - 0.0 %
PC - 0 - 0.0 %
ARP - 0 - 0.0 %
PS - 0 - 0.0 %

In [10]:
fill_with_mode(df_dk, ["QOA"])

In [11]:
fill_with_mean(df_dk, ["EMP", "PAG", "GGAG", "QOR"])

In [12]:
dk_context_2007_2015 = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Denmark_2007_2015.csv")

In [13]:
dk_context_2007_2015 = dk_context_2007_2015[['TIME_PERIOD', 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT']]

In [14]:
dk_context_2007_2015

   TIME_PERIOD   ROL    GE   COC    RQ        SSB         PT
0         2007  2.00  2.35  2.43  1.93  89.822480  89.509231
1         2008  1.95  2.24  2.38  1.87  90.069128  89.265890
2         2009  1.92  2.23  2.44  1.88  90.102783  90.558650
3         2010  1.90  2.10  2.35  1.87  90.196051  90.980440
4         2011  1.92  2.10  2.39  1.90  91.112127  91.037842
5         2012  1.88  1.99  2.38  1.80  91.170983  91.680405
6         2013  1.90  1.94  2.40  1.80  91.198876  91.832348
7         2014  2.10  1.78  2.25  1.68  91.219461  91.834965
8         2015  2.02  1.79  2.19  1.72  91.802316  91.834965

In [15]:
eu_payments = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Raw_Data/Variables/Historic_EU_payments_annual_timeseries_-_regionalised_and_modelled_20251209.csv")

In [16]:
eu_payments = eu_payments.drop(['NUTS1_ID', 'NUTS2 code+name', 'NUTS2_ID', 'NUTS2_name', 'Modelled_annual_expenditure',
                  'Standard_Deviation_of_annual_expenditure', 'Standard_Error_of_modelled_annual_expenditure'], axis=1)

In [17]:
dk_eu_payments = eu_payments[eu_payments['Country'] == 'DK'].copy()

In [18]:
dk_eu_payments

     Country  Fund  Year Programming_Period EU_Payment_annual
833       DK  ERDF  2007          2007-2013         1,194,717
834       DK  ERDF  2008          2007-2013         1,792,076
835       DK  ERDF  2009          2007-2013         2,228,417
836       DK  ERDF  2010          2007-2013         4,678,038
837       DK  ERDF  2011          2007-2013        15,425,586
...      ...   ...   ...                ...               ...
2483      DK   ESF  2018          2014-2020         2,077,670
2484      DK   ESF  2019          2014-2020         2,615,692
2485      DK   ESF  2020          2014-2020         2,376,965
2486      DK   ESF  2021          2014-2020         4,074,111
2487      DK   ESF  2022          2014-2020         3,321,554

[180 rows x 5 columns]

In [19]:
dk_eu_payments['EU_Payment_annual'] = pd.to_numeric(dk_eu_payments['EU_Payment_annual'].str.replace(',', ''))

In [20]:
dk_eu_payments_2007_2015 = dk_eu_payments[dk_eu_payments['Programming_Period'] == '2007-2013'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

In [21]:
dk_eu_payments_2007_2015 = dk_eu_payments_2007_2015.rename({"Year":"TIME_PERIOD"}, axis=1)

In [22]:
dk_eu_payments_2007_2015

   TIME_PERIOD  EU_Payment_annual
0         2007           10191540
1         2008           15287312
2         2009           33350959
3         2010           41600829
4         2011           94651644
5         2012           35523496
6         2013           46669931
7         2014          134429401
8         2015           72393232
9         2017           25478856

In [23]:
dk_eu_payments_2007_2015 = dk_eu_payments_2007_2015.loc[0:8]

In [24]:
df_dk_2007_2015 = df_dk.loc[7:15]

In [25]:
df_dk_2007_2015

,TIME_PERIOD,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,REST,CO2,EBSG,FDI,GGFC,LBGD,PC,ARP,PS
7,2007,319173.149269,0.540322,22.06,76.414286,157.0,6.45,6.42,7.49,-4900.0,17.747,53.8693,2.747300,3.69,24.277939,5.548536,5.3,11.7,5.46
8,2008,329422.223703,-1.000559,22.61,76.414286,-26.0,6.44,6.23,9.47,-3557.0,18.543,50.6018,3.471527,0.62,24.986449,3.835619,6.5,11.8,5.49
9,2009,313144.896657,-5.481583,19.85,76.100000,-116.0,6.43,6.06,13.44,-2932.0,19.948,48.4089,4.602963,1.17,27.815694,-2.111442,4.2,13.1,5.52
10,2010,326784.316443,1.132669,19.37,74.900000,108.0,6.37,6.17,15.55,251.0,21.888,48.5600,6.793833,-3.57,27.336108,-2.441067,4.7,13.3,5.55
11,2011,331838.652835,0.894526,19.85,74.800000,-52.0,6.32,6.29,16.31,-5488.0,23.389,43.4849,6.154324,3.94,26.540559,-1.887012,3.6,12.1,5.57
12,2012,338534.135302,-0.380977,19.85,74.300000,-168.0,5.97,5.73,15.77,-5127.0,25.465,38.5966,5.799405,-5.00,26.500323,-3.257951,4.0,12.0,5.59
13,2013,344715.698783,0.970846,19.73,74.300000,-65.0,5.64,5.45,14.77,1404.0,27.173,40.3352,6.229005,0.20,25.928504,-1.181728,4.4,11.9,5.61
14,2014,350893.947080,0.765766,19.40,74.700000,36.0,5.56,5.43,14.20,-4198.0,29.310,36.1972,6.455948,1.86,25.797420,1.252108,5.8,12.1,5.64
15,2015,357211.575191,1.385666,19.56,75.400000,85.0,5.58,5.59,12.15,-2024.0,30.469,34.0712,6.498281,0.61,25.546356,-1.143677,8.4,12.2,5.68

In [26]:
df_dk_2007_2015 = pd.merge(df_dk_2007_2015, dk_context_2007_2015, on='TIME_PERIOD', how='outer')

In [27]:
df_dk_2007_2015 = pd.merge(df_dk_2007_2015, dk_eu_payments_2007_2015, on='TIME_PERIOD', how='outer')

In [28]:
df_dk_2007_2015['EUPC'] = df_dk_2007_2015['EU_Payment_annual'] / (df_dk_2007_2015['PS'] * 1000000)

In [29]:
df_dk_2007_2015 = df_dk_2007_2015.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [30]:
df_dk_2007_2015

,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,REST,...,LBGD,PC,ARP,ROL,GE,COC,RQ,SSB,PT,EUPC
0,319173.149269,0.540322,22.06,76.414286,157.0,6.45,6.42,7.49,-4900.0,17.747,...,5.548536,5.3,11.7,2.00,2.35,2.43,1.93,89.822480,89.509231,1.866582
1,329422.223703,-1.000559,22.61,76.414286,-26.0,6.44,6.23,9.47,-3557.0,18.543,...,3.835619,6.5,11.8,1.95,2.24,2.38,1.87,90.069128,89.265890,2.784574
2,313144.896657,-5.481583,19.85,76.100000,-116.0,6.43,6.06,13.44,-2932.0,19.948,...,-2.111442,4.2,13.1,1.92,2.23,2.44,1.88,90.102783,90.558650,6.041840
3,326784.316443,1.132669,19.37,74.900000,108.0,6.37,6.17,15.55,251.0,21.888,...,-2.441067,4.7,13.3,1.90,2.10,2.35,1.87,90.196051,90.980440,7.495645
4,331838.652835,0.894526,19.85,74.800000,-52.0,6.32,6.29,16.31,-5488.0,23.389,...,-1.887012,3.6,12.1,1.92,2.10,2.39,1.90,91.112127,91.037842,16.993114
5,338534.135302,-0.380977,19.85,74.300000,-168.0,5.97,5.73,15.77,-5127.0,25.465,...,-3.257951,4.0,12.0,1.88,1.99,2.38,1.80,91.170983,91.680405,6.354829
6,344715.698783,0.970846,19.73,74.300000,-65.0,5.64,5.45,14.77,1404.0,27.173,...,-1.181728,4.4,11.9,1.90,1.94,2.40,1.80,91.198876,91.832348,8.319061
7,350893.947080,0.765766,19.40,74.700000,36.0,5.56,5.43,14.20,-4198.0,29.310,...,1.252108,5.8,12.1,2.10,1.78,2.25,1.68,91.219461,91.834965,23.835000
8,357211.575191,1.385666,19.56,75.400000,85.0,5.58,5.59,12.15,-2024.0,30.469,...,-1.143677,8.4,12.2,2.02,1.79,2.19,1.72,91.802316,91.834965,12.745287

In [31]:
df_dk_2007_2015.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/data/y/dk_2007_2015_bn.csv', index=True)

In [32]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_dk_2007_2015.values)

df_dk_2007_2015_scaled = pd.DataFrame(scaled_features, index=df_dk_2007_2015.index, columns=df_dk_2007_2015.columns)

In [33]:
df_dk_2007_2015

,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,REST,...,LBGD,PC,ARP,ROL,GE,COC,RQ,SSB,PT,EUPC
0,319173.149269,0.540322,22.06,76.414286,157.0,6.45,6.42,7.49,-4900.0,17.747,...,5.548536,5.3,11.7,2.00,2.35,2.43,1.93,89.822480,89.509231,1.866582
1,329422.223703,-1.000559,22.61,76.414286,-26.0,6.44,6.23,9.47,-3557.0,18.543,...,3.835619,6.5,11.8,1.95,2.24,2.38,1.87,90.069128,89.265890,2.784574
2,313144.896657,-5.481583,19.85,76.100000,-116.0,6.43,6.06,13.44,-2932.0,19.948,...,-2.111442,4.2,13.1,1.92,2.23,2.44,1.88,90.102783,90.558650,6.041840
3,326784.316443,1.132669,19.37,74.900000,108.0,6.37,6.17,15.55,251.0,21.888,...,-2.441067,4.7,13.3,1.90,2.10,2.35,1.87,90.196051,90.980440,7.495645
4,331838.652835,0.894526,19.85,74.800000,-52.0,6.32,6.29,16.31,-5488.0,23.389,...,-1.887012,3.6,12.1,1.92,2.10,2.39,1.90,91.112127,91.037842,16.993114
5,338534.135302,-0.380977,19.85,74.300000,-168.0,5.97,5.73,15.77,-5127.0,25.465,...,-3.257951,4.0,12.0,1.88,1.99,2.38,1.80,91.170983,91.680405,6.354829
6,344715.698783,0.970846,19.73,74.300000,-65.0,5.64,5.45,14.77,1404.0,27.173,...,-1.181728,4.4,11.9,1.90,1.94,2.40,1.80,91.198876,91.832348,8.319061
7,350893.947080,0.765766,19.40,74.700000,36.0,5.56,5.43,14.20,-4198.0,29.310,...,1.252108,5.8,12.1,2.10,1.78,2.25,1.68,91.219461,91.834965,23.835000
8,357211.575191,1.385666,19.56,75.400000,85.0,5.58,5.59,12.15,-2024.0,30.469,...,-1.143677,8.4,12.2,2.02,1.79,2.19,1.72,91.802316,91.834965,12.745287

In [34]:
df_dk_2007_2015_scaled.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/dk_2007_2015_tcdf.csv')

In [35]:
df_dk_2007_2015_scaled

,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,REST,...,LBGD,PC,ARP,ROL,GE,COC,RQ,SSB,PT,EUPC
0,-1.128903,0.331387,1.593497,1.428665,1.581379,0.978300,1.358899,-2.019567,-0.852555,-1.378142,...,1.986745,0.062527,-1.020391,0.671500,1.551791,0.933008,1.284986,-1.401943,-1.530951,-1.156710
1,-0.380615,-0.429960,2.078603,1.428665,-0.209908,0.951538,0.831979,-1.323999,-0.264682,-1.196013,...,1.389977,0.906637,-0.832972,-0.065512,0.967657,0.296866,0.530755,-1.026628,-1.789829,-1.019475
2,-1.569027,-2.644026,-0.355744,1.040100,-1.090868,0.924776,0.360524,0.070650,0.008901,-0.874543,...,-0.681934,-0.711241,1.603471,-0.507719,0.914554,1.060236,0.656460,-0.975415,-0.414531,-0.532527
3,-0.573210,0.624065,-0.779109,-0.443514,1.101745,0.764204,0.665583,0.811886,1.402200,-0.430661,...,-0.796773,-0.359529,1.978308,-0.802524,0.224213,-0.084819,0.530755,-0.833493,0.034188,-0.315189
4,-0.204191,0.506399,-0.355744,-0.567149,-0.464408,0.630394,0.998375,1.078872,-1.109941,-0.087225,...,-0.603745,-1.133297,-0.270716,-0.507719,0.224213,0.424094,0.907871,0.560470,0.095254,1.104643
5,0.284648,-0.123825,-0.355744,-1.185321,-1.599868,-0.306276,-0.554653,0.889172,-0.951920,0.387773,...,-1.081370,-0.851927,-0.458135,-1.097329,-0.359921,0.296866,-0.349181,0.650030,0.778843,-0.485736
6,0.735965,0.544109,-0.461585,-1.185321,-0.591657,-1.189423,-1.331167,0.537875,1.906904,0.778572,...,-0.358029,-0.570556,-0.645553,-0.802524,-0.625437,0.551323,-0.349181,0.692474,0.940486,-0.192092
7,1.187041,0.442779,-0.752648,-0.690783,0.396976,-1.403519,-1.386632,0.337635,-0.545267,1.267528,...,0.489901,0.414240,-0.270716,2.145524,-1.475087,-1.357102,-1.857643,0.723796,0.943270,2.127476
8,1.648292,0.749071,-0.611527,0.174658,0.876610,-1.349995,-0.942910,-0.382523,0.406361,1.532712,...,-0.344772,2.243146,-0.083297,0.966305,-1.421984,-2.120472,-1.354823,1.610709,0.943270,0.469610

In [286]:
column_index = df_dk_2007_2015_scaled.columns.get_loc('PAG')
print(column_index)

4

13,4,1

In [37]:
dk_context_2016_2022 = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Denmark_2016_2022.csv")

dk_context_2016_2022 = dk_context_2016_2022[["TIME_PERIOD", 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT']]

df_dk_2016_2022 = df_dk.loc[16:22]
dk_eu_payments_2016_2022 = dk_eu_payments[dk_eu_payments['Programming_Period'] == '2014-2020'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

In [38]:
dk_eu_payments_2016_2022 = dk_eu_payments_2016_2022.loc[1:7]
dk_eu_payments_2016_2022

   Year  EU_Payment_annual
1  2016            2300472
2  2017           33510236
3  2018           39263352
4  2019           51874270
5  2020           52197125
6  2021           80908322
7  2022           75033080

In [39]:
dk_eu_payments_2016_2022 = dk_eu_payments_2016_2022.rename({"Year":"TIME_PERIOD"}, axis=1)

df_dk_2016_2022 = pd.merge(df_dk_2016_2022, dk_context_2016_2022, on='TIME_PERIOD', how='outer')

df_dk_2016_2022 = pd.merge(df_dk_2016_2022, dk_eu_payments_2016_2022, on='TIME_PERIOD', how='outer')

df_dk_2016_2022['EUPC'] = df_dk_2016_2022['EU_Payment_annual'] / (df_dk_2016_2022['PS'] * 1000000)

df_dk_2016_2022 = df_dk_2016_2022.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [40]:
df_dk_2016_2022

,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,REST,...,LBGD,PC,ARP,ROL,GE,COC,RQ,SSB,PT,EUPC
0,366884.878867,2.271802,20.23,76.0,90.000000,5.8,5.700000,12.15,1635.000000,31.715,...,-0.070663,7.2,11.9,1.88,1.82,2.20,1.56,91.819264,91.142197,0.401479
1,379808.676526,2.395591,20.42,76.6,-62.000000,6.1,5.500000,12.38,-2276.000000,34.387,...,1.457031,5.6,12.4,1.80,1.75,2.19,1.61,91.841026,91.142197,5.817749
2,387242.522658,1.356196,20.58,77.5,-228.000000,5.8,5.500000,10.52,-555.000000,35.159,...,0.801500,4.3,12.7,1.77,1.81,2.16,1.63,91.866931,91.142197,6.781235
3,396193.582956,1.347792,20.64,78.3,89.000000,5.8,5.600000,10.04,-3538.000000,37.020,...,4.079333,2.9,12.5,1.83,1.87,2.12,1.55,91.889599,91.142197,8.928446
4,398976.348406,-2.066138,19.56,77.8,-90.000000,5.8,5.820769,11.59,-2434.000000,31.681,...,0.081707,3.0,12.1,1.81,1.84,2.24,1.79,91.869017,91.142197,8.953195
5,438387.741596,6.917664,19.80,79.0,-171.000000,5.8,5.820769,10.81,-2409.928571,41.494,...,3.868870,5.7,12.3,1.90,1.96,2.33,1.80,91.898641,91.142197,13.806881
6,481824.514568,0.743682,20.84,80.1,-27.533333,5.8,5.820769,10.53,-2409.928571,41.368,...,3.323468,10.0,12.4,1.90,1.99,2.40,1.84,91.898641,91.142197,12.717471

In [41]:
df_dk_2016_2022.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/dk_2016_2022_bn.csv')

In [42]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_dk_2016_2022.values)

df_dk_2016_2022_scaled = pd.DataFrame(scaled_features, index=df_dk_2016_2022.index, columns=df_dk_2016_2022.columns)

In [287]:
df_dk_2016_2022_scaled

,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,REST,...,LBGD,PC,ARP,ROL,GE,COC,RQ,SSB,PT,EUPC
0,-1.089924,0.168812,-0.152350,-1.470893,1.318172,-0.408248,0.143763,1.208346,2.105841,-1.163297,...,-1.209561,0.720850,-1.761661,0.799671,-0.543393,-0.375459,-1.079054,-1.784377,1.421085e-14,-1.872485
1,-0.739183,0.218635,0.288140,-1.006401,-0.044130,2.449490,-1.317960,1.485080,-0.354448,-0.457294,...,-0.288004,0.030806,0.293610,-0.858906,-1.430934,-0.484967,-0.639904,-1.003904,1.421085e-14,-0.572150
2,-0.537435,-0.199699,0.659078,-0.309662,-1.531906,-0.408248,-1.317960,-0.752853,0.728180,-0.253314,...,-0.683442,-0.529856,1.526773,-1.480872,-0.670184,-0.813494,-0.464244,-0.074828,1.421085e-14,-0.340837
3,-0.294511,-0.203081,0.798180,0.309662,1.309209,-0.408248,-0.587099,-1.330384,-1.148334,0.238404,...,1.293858,-1.133645,0.704664,-0.236940,0.090565,-1.251529,-1.166884,0.738173,1.421085e-14,0.174663
4,-0.218989,-1.577114,-1.705653,-0.077415,-0.295080,-0.408248,1.026419,0.534560,-0.453841,-1.172281,...,-1.117646,-1.090517,-0.939552,-0.651584,-0.289809,0.062576,0.941036,0.000000,1.421085e-14,0.180605
5,0.850602,2.038670,-1.149246,0.851570,-1.021043,-0.408248,1.026419,-0.403928,-0.438699,1.420537,...,1.166900,0.073933,-0.117444,1.214315,1.231690,1.048155,1.028866,1.062468,1.421085e-14,1.345874
6,2.029439,-0.446223,1.261852,1.703140,0.264778,-0.408248,1.026419,-0.740821,-0.438699,1.387245,...,0.837895,1.928428,0.293610,1.214315,1.612065,1.814717,1.380185,1.062468,1.421085e-14,1.084330

In [43]:
df_dk_2016_2022_scaled.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/dk_2016_2022_tcdf.csv')

In [289]:
column_index = df_dk_2016_2022_scaled.columns.get_loc('GGAG')
print(column_index)

8

In [ ]:
10,8,0

====================================================================

In [45]:
df_de = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/Germany.csv")

In [46]:
df_de = df_de.loc[6:22]

In [47]:
df_de = df_de.copy()
# df_de['LFG'] = df_de['LF'].diff()
# df_de['EPFRG'] = df_de['EPFR'].diff()
df_de['GGAG'] = df_de['GGA'].diff()
df_de['PAG'] = df_de['PA'].diff()
df_de = df_de.drop(6)

In [48]:
# df_de = df_de.drop(["Unnamed: 0", "REF_AREA_LABEL", "HI", "OCTB", "NINA", "LF", "EPFR", "GGA", "EIA", "GDP",
#                    "UR", "URFF", "YUA", "P014", "P65"], axis=1)

In [49]:
df_de = df_de[["TIME_PERIOD", "GDPC", "GDPCG", "VABI", "EMP", "PAG", "QOA", "QOR", "YUA", "GGAG", "REST", "CO2",
             "EBSG", "FDI", "GGFC", "LBGD", "PC", "ARP", "PS"]]

In [50]:
df_de

,TIME_PERIOD,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,REST,CO2,EBSG,FDI,GGFC,LBGD,PC,ARP,PS
7,2007,30902.298694,3.027782,26.46,:,-159.0,6.71,6.55,11.82,-28436.0,10.039,826.5971,6.389770,1.46,17.555365,-0.168868,-1.2,15.2,82.27
8,2008,31539.117534,1.102460,26.06,:,1387.0,6.67,6.54,10.93,2834.0,10.072,829.9111,5.783688,0.81,17.951098,-0.295519,-2.6,15.2,82.11
9,2009,30461.535107,-5.305528,23.87,73.2,-1381.0,6.61,6.49,11.31,-56474.0,10.851,768.1326,4.768184,1.63,19.597935,-2.070729,-2.4,15.5,81.90
10,2010,31990.195768,4.306441,26.06,74.0,-812.0,6.61,6.42,10.42,30446.0,11.667,814.9620,5.103897,2.48,19.176892,-3.199506,-0.6,15.6,81.78
11,2011,34229.966763,5.699283,26.31,75.4,-61.0,6.45,6.15,8.93,-29687.0,12.470,788.1211,4.852664,2.55,18.693432,-0.370659,1.3,15.8,80.27
12,2012,34819.413660,0.285850,26.58,75.8,-366.0,6.35,6.09,8.12,13203.0,13.549,800.0321,6.037145,1.82,18.897792,0.092987,2.4,16.1,80.43
13,2013,35554.076381,0.112644,25.91,76.3,733.0,6.08,6.01,7.82,16374.0,13.757,817.8158,5.772928,1.76,19.247998,0.204270,3.0,16.1,80.65
14,2014,36861.914611,1.744464,26.01,76.7,801.0,5.94,5.88,7.61,-40820.0,14.381,778.7527,6.537450,0.44,19.210129,0.684115,5.3,16.7,80.98
15,2015,37774.244301,0.776508,25.92,77.0,-770.0,5.95,5.72,7.33,4675.0,14.901,784.9143,7.417530,1.82,19.312236,0.679371,12.0,16.7,81.69
16,2016,38811.920567,1.472293,26.22,77.6,1096.0,5.90,5.60,7.08,3007.0,14.885,789.2489,7.263048,1.64,19.519072,0.736708,4.2,16.5,82.35
17,2017,40300.397055,2.332866,26.12,78.3,-695.0,5.80,5.50,6.77,-17289.0,15.472,774.4767,7.085326,2.89,19.459550,0.636665,3.3,16.1,82.66
18,2018,41385.895136,0.813017,25.94,79.0,-1168.0,5.60,5.50,6.22,-28666.0,16.660,746.6974,5.987124,4.00,19.502234,1.111879,2.7,16.0,82.91
19,2019,42541.268417,0.760402,25.63,79.7,15.0,5.50,5.30,5.86,-50838.0,17.266,696.5002,5.638862,1.91,19.903024,0.767070,1.8,14.8,83.09
20,2020,41481.287516,-4.173453,25.38,78.3,-4372.0,NaN,NaN,7.86,-58901.0,19.090,642.0878,5.345110,4.49,21.731321,-3.657127,-0.1,16.1,83.16
21,2021,44190.304259,3.626129,25.31,79.6,-2438.0,NaN,NaN,6.66,NaN,19.302,670.6670,5.158549,2.93,21.674219,-3.522981,1.0,16.0,83.20
22,2022,47183.115441,0.641609,25.69,80.8,NaN,NaN,NaN,6.04,NaN,20.829,658.0886,2.496908,2.09,21.521327,-2.692237,-1.4,14.8,83.80

In [51]:
df_de["EMP"] = df_de["EMP"].replace(':', np.nan)
# df_de["LTU"] = df_de["LTU"].replace(':', np.nan)
# df_de["FEM"] = df_de["FEM"].replace(':', np.nan)

In [52]:
missing_values(df_de)

TIME_PERIOD - 0 - 0.0 %
GDPC - 0 - 0.0 %
GDPCG - 0 - 0.0 %
VABI - 0 - 0.0 %
EMP - 2 - 12.5 %
PAG - 1 - 6.2 %
QOA - 3 - 18.8 %
QOR - 3 - 18.8 %
YUA - 0 - 0.0 %
GGAG - 2 - 12.5 %
REST - 0 - 0.0 %
CO2 - 0 - 0.0 %
EBSG - 0 - 0.0 %
FDI - 0 - 0.0 %
GGFC - 0 - 0.0 %
LBGD - 0 - 0.0 %
PC - 0 - 0.0 %
ARP - 0 - 0.0 %
PS - 0 - 0.0 %

In [53]:
df_de = df_de.copy()
fill_with_mode(df_de, ["QOR"])

In [54]:
fill_with_mean(df_de, ["EMP", "GGAG", "QOA", "PAG"])

In [55]:
de_context_2007_2015 = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Germany_2007_2015.csv")

In [56]:
de_context_2007_2015 = de_context_2007_2015[["TIME_PERIOD", 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT']]

In [57]:
# de_context_2007_2015["DBPG"] = de_context_2007_2015["DBP"].diff()
# de_context_2007_2015 = de_context_2007_2015.drop(0)
# de_context_2007_2015 = de_context_2007_2015.drop(["DBP"], axis=1)
# de_context_2007_2015

In [58]:
de_context_2007_2015 = de_context_2007_2015.loc[1:9]

In [59]:
de_eu_payments = eu_payments[eu_payments['Country'] == 'DE'].copy()

In [60]:
de_eu_payments

     Country  Fund  Year Programming_Period EU_Payment_annual
0         DE  ERDF  2007          2007-2013         1,017,013
1         DE  ERDF  2008          2007-2013         1,525,519
2         DE  ERDF  2009          2007-2013         1,271,266
3         DE  ERDF  2010          2007-2013         3,453,592
4         DE  ERDF  2011          2007-2013         2,385,830
...      ...   ...   ...                ...               ...
2403      DE   ESF  2018          2014-2020        52,908,298
2404      DE   ESF  2019          2014-2020       149,834,127
2405      DE   ESF  2020          2014-2020        93,167,064
2406      DE   ESF  2021          2014-2020        96,597,249
2407      DE   ESF  2022          2014-2020       112,397,843

[1441 rows x 5 columns]

In [61]:
de_eu_payments['EU_Payment_annual'] = pd.to_numeric(de_eu_payments['EU_Payment_annual'].str.replace(',', ''))

In [62]:
de_eu_payments_2007_2015 = de_eu_payments[de_eu_payments['Programming_Period'] == '2007-2013'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

In [63]:
de_eu_payments_2007_2015 = de_eu_payments_2007_2015.rename({"Year":"TIME_PERIOD"}, axis=1)

In [64]:
de_eu_payments_2007_2015 = de_eu_payments_2007_2015.loc[0:8]

In [65]:
de_eu_payments_2007_2015

   TIME_PERIOD  EU_Payment_annual
0         2007          509772297
1         2008          822140887
2         2009         3112147864
3         2010         2845429356
4         2011         3199322121
5         2012         3291270489
6         2013         4250139425
7         2014         3182120645
8         2015         2285834656

In [66]:
df_de_2007_2015 = df_de.loc[7:15]

In [67]:
df_de_2007_2015 = pd.merge(df_de_2007_2015, de_context_2007_2015, on='TIME_PERIOD', how='outer')

In [68]:
df_de_2007_2015 = pd.merge(df_de_2007_2015, de_eu_payments_2007_2015, on='TIME_PERIOD', how='outer')

In [69]:
df_de_2007_2015['EUPC'] = df_de_2007_2015['EU_Payment_annual'] / (df_de_2007_2015['PS'] * 1000000)

In [70]:
df_de_2007_2015

,TIME_PERIOD,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,...,ARP,PS,ROL,GE,COC,RQ,SSB,PT,EU_Payment_annual,EUPC
0,2007,30902.298694,3.027782,26.46,77.264286,-159.0,6.71,6.55,11.82,-28436.0,...,15.2,82.27,1.76,1.63,1.73,1.62,78.044700,77.197929,509772297,6.196333
1,2008,31539.117534,1.102460,26.06,77.264286,1387.0,6.67,6.54,10.93,2834.0,...,15.2,82.11,1.73,1.51,1.75,1.49,79.197611,76.399686,822140887,10.012677
2,2009,30461.535107,-5.305528,23.87,73.200000,-1381.0,6.61,6.49,11.31,-56474.0,...,15.5,81.90,1.65,1.58,1.75,1.52,79.363510,76.198556,3112147864,37.999363
3,2010,31990.195768,4.306441,26.06,74.000000,-812.0,6.61,6.42,10.42,30446.0,...,15.6,81.78,1.64,1.52,1.77,1.57,79.567065,76.740193,2845429356,34.793707
4,2011,34229.966763,5.699283,26.31,75.400000,-61.0,6.45,6.15,8.93,-29687.0,...,15.8,80.27,1.62,1.50,1.74,1.55,80.744231,76.428017,3199322121,39.857009
5,2012,34819.413660,0.285850,26.58,75.800000,-366.0,6.35,6.09,8.12,13203.0,...,16.1,80.43,1.67,1.53,1.82,1.53,80.867728,76.817402,3291270489,40.920931
6,2013,35554.076381,0.112644,25.91,76.300000,733.0,6.08,6.01,7.82,16374.0,...,16.1,80.65,1.64,1.51,1.80,1.54,80.918824,76.740193,4250139425,52.698567
7,2014,36861.914611,1.744464,26.01,76.700000,801.0,5.94,5.88,7.61,-40820.0,...,16.7,80.98,1.85,1.66,1.81,1.70,80.997172,76.843778,3182120645,39.295143
8,2015,37774.244301,0.776508,25.92,77.000000,-770.0,5.95,5.72,7.33,4675.0,...,16.7,81.69,1.76,1.66,1.78,1.71,80.627202,77.020556,2285834656,27.981817

In [71]:
df_de_2007_2015 = df_de_2007_2015.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [72]:
df_de_2007_2015.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/de_2007_2015_bn.csv')

In [73]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_de_2007_2015.values)

df_de_2007_2015_scaled = pd.DataFrame(scaled_features, index=df_de_2007_2015.index, columns=df_de_2007_2015.columns)

In [74]:
df_de_2007_2015_scaled.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/de_2007_2015_tcdf.csv')

In [75]:
df_de_2007_2015_scaled

,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,REST,...,LBGD,PC,ARP,ROL,GE,COC,RQ,SSB,PT,EUPC
0,-1.144460,0.585168,0.730101,1.009816,-0.105960,1.145107,1.190162,1.480989,-0.665381,-1.361771,...,0.264719,-0.715857,-1.262099,0.794843,1.001388,-1.385717,0.523380,-2.039153,1.634716,-1.822342
1,-0.892295,-0.069003,0.200189,1.009816,1.730069,1.008604,1.155609,0.943971,0.448992,-1.342815,...,0.161550,-1.037993,-1.262099,0.382136,-0.895979,-0.729325,-1.226205,-0.858802,-1.037404,-1.554841
2,-1.318991,-2.246256,-2.701077,-1.957063,-1.557207,0.803850,0.982843,1.173260,-1.664575,-0.895338,...,-1.284531,-0.991974,-0.703465,-0.718416,0.210819,-0.729325,-0.822454,-0.688955,-1.710687,0.406844
3,-0.713679,1.019620,0.200189,-1.373072,-0.881463,0.803850,0.740972,0.636242,1.433005,-0.426607,...,-2.204029,-0.577799,-0.517254,-0.855985,-0.737865,-0.072932,-0.149537,-0.480555,0.102443,0.182148
4,0.173214,1.492869,0.531384,-0.351089,0.010424,0.257839,-0.191962,-0.262810,-0.709963,0.034657,...,0.100341,-0.140615,-0.144831,-1.131123,-1.054093,-1.057521,-0.418704,0.724627,-0.942566,0.537053
5,0.406621,-0.346464,0.889074,-0.059094,-0.351793,-0.083418,-0.399280,-0.751557,0.818514,0.654462,...,0.478026,0.112492,0.413803,-0.443278,-0.579751,1.568049,-0.687871,0.851063,0.360900,0.611627
6,0.697529,-0.405314,0.001472,0.305900,0.953379,-1.004812,-0.675705,-0.932574,0.931519,0.773942,...,0.568676,0.250550,0.413803,-0.855985,-0.895979,0.911656,-0.553287,0.903375,0.102443,1.437163
7,1.215400,0.149132,0.133950,0.597895,1.034135,-1.482572,-1.124895,-1.059286,-1.106711,1.132384,...,0.959556,0.779773,1.531071,2.032964,1.475730,1.239852,1.600048,0.983588,0.449196,0.497670
8,1.576660,-0.179752,0.014720,0.816891,-0.831584,-1.448446,-1.677744,-1.228235,0.514600,1.431085,...,0.955692,2.321423,1.531071,0.794843,1.475730,0.255264,1.734631,0.604813,1.040961,-0.295321

In [76]:
df_de.columns.equals(df_dk.columns)

True

In [304]:
column_index = df_de_2007_2015_scaled.columns.get_loc('PT')
print(column_index)

22

In [78]:
12,4,0
22,4,1
13,7,0
21,12,1
8,17,3
21,18,1
16,21,1
21,22,1

(3, 24, 0)

In [79]:
de_context_2016_2022 = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Germany_2016_2022.csv")

de_context_2016_2022 = de_context_2016_2022[["TIME_PERIOD", 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT']]

df_de_2016_2022 = df_de.loc[16:22]

In [80]:
de_eu_payments_2016_2022 = de_eu_payments[de_eu_payments['Programming_Period'] == '2014-2020'].groupby('Year')['EU_Payment_annual'].sum().reset_index()
de_eu_payments_2016_2022 = de_eu_payments_2016_2022.rename({"Year":"TIME_PERIOD"}, axis=1)
de_eu_payments_2016_2022 = de_eu_payments_2016_2022.loc[1:7]
de_eu_payments_2016_2022

   TIME_PERIOD  EU_Payment_annual
1         2016          193569759
2         2017         1413679591
3         2018         1874091083
4         2019         2294983953
5         2020         2150651412
6         2021         2695323886
7         2022         2941191622

In [81]:
df_de_2016_2022 = pd.merge(df_de_2016_2022, de_context_2016_2022, on='TIME_PERIOD', how='outer')

df_de_2016_2022 = pd.merge(df_de_2016_2022, de_eu_payments_2016_2022, on='TIME_PERIOD', how='outer')

df_de_2016_2022['EUPC'] = df_de_2016_2022['EU_Payment_annual'] / (df_de_2016_2022['PS'] * 1000000)

df_de_2016_2022 = df_de_2016_2022.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [82]:
df_de_2016_2022

,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,REST,...,LBGD,PC,ARP,ROL,GE,COC,RQ,SSB,PT,EUPC
0,38811.920567,1.472293,26.22,77.6,1096.0,5.900000,5.6,7.08,3007.000000,14.885,...,0.736708,4.2,16.5,1.58,1.66,1.78,1.81,82.244290,82.167297,2.350574
1,40300.397055,2.332866,26.12,78.3,-695.0,5.800000,5.5,6.77,-17289.000000,15.472,...,0.636665,3.3,16.1,1.57,1.61,1.80,1.78,82.202748,82.157760,17.102342
2,41385.895136,0.813017,25.94,79.0,-1168.0,5.600000,5.5,6.22,-28666.000000,16.660,...,1.111879,2.7,16.0,1.59,1.52,1.90,1.76,82.214093,82.140949,22.603921
3,42541.268417,0.760402,25.63,79.7,15.0,5.500000,5.3,5.86,-50838.000000,17.266,...,0.767070,1.8,14.8,1.58,1.50,1.87,1.71,82.338520,82.105637,27.620459
4,41481.287516,-4.173453,25.38,78.3,-4372.0,6.166923,5.5,7.86,-58901.000000,19.090,...,-3.657127,-0.1,16.1,1.52,1.31,1.83,1.58,82.244290,82.155389,25.861609
5,44190.304259,3.626129,25.31,79.6,-2438.0,6.166923,5.5,6.66,-17183.714286,19.302,...,-3.522981,1.0,16.0,1.57,1.29,1.78,1.63,82.233046,82.180346,32.395720
6,47183.115441,0.641609,25.69,80.8,-546.0,6.166923,5.5,6.04,-17183.714286,20.829,...,-2.692237,-1.4,14.8,1.53,1.29,1.82,1.52,82.233046,82.180346,35.097752

In [83]:
df_de_2016_2022.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/data/y/de_2016_2022_bn.csv', index=True)

In [84]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_de_2016_2022.values)

df_de_2016_2022_scaled = pd.DataFrame(scaled_features, index=df_de_2016_2022.index, columns=df_de_2016_2022.columns)

In [85]:
df_de_2016_2022_scaled.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/de_2016_2022_tcdf.csv')

In [310]:
column_index = df_de_2016_2022_scaled.columns.get_loc('SSB')
print(column_index)

21

In [87]:
21,12,1
6,16,0
12,21,2

(17, 26, 0)

===================================================================================================================

In [88]:
df_pl = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/Poland.csv")

In [89]:
df_pl = df_pl.loc[6:22]

In [90]:
df_pl

,Unnamed: 0,REF_AREA_LABEL,TIME_PERIOD,HI,LF,UR,URFF,YUA,FDI,QOR,...,NINA,LBGD,PA,CO2,EMP,LTU,FEM,REST,PC,ARP
6,6,Poland,2006,NaN,17.28,13.79,14.83,29.54,6.21,3.20,...,1.838500,-3.262140,2157.0,330.7509,:,:,NaN,NaN,-0.8,19.1
7,7,Poland,2007,NaN,17.27,9.55,10.23,21.39,5.83,2.57,...,2.446382,-1.872662,2392.0,330.3011,:,:,:,6.903,-0.3,17.3
8,8,Poland,2008,NaN,17.50,7.07,7.85,17.10,2.72,1.91,...,2.544367,-3.397579,2488.0,324.5779,:,:,:,7.686,0.5,16.9
9,9,Poland,2009,NaN,17.81,8.13,8.55,20.47,3.18,2.06,...,2.384192,-6.157262,2899.0,311.3787,62.6,2.6,55.6,8.676,0.8,17.1
10,10,Poland,2010,NaN,18.03,9.58,9.87,23.58,3.94,2.23,...,2.757119,-6.142614,3203.0,329.3834,62.2,3.1,55.6,9.281,1.0,17.6
11,11,Poland,2011,NaN,18.10,9.58,10.24,25.53,3.57,2.33,...,3.145783,-4.112383,3879.0,326.9383,62.5,3.7,55.8,10.337,0.0,17.7
12,12,Poland,2012,NaN,18.23,10.03,10.77,26.31,1.53,2.62,...,2.489764,-3.437896,4410.0,319.7269,62.9,4.2,56.2,10.955,0.0,17.1
13,13,Poland,2013,5.82,18.27,10.29,11.01,27.16,0.26,3.05,...,1.935317,-4.023830,4237.0,315.0899,63.2,4.5,56.3,11.452,-1.2,17.3
14,14,Poland,2014,NaN,18.39,8.97,9.52,23.73,3.85,3.55,...,2.013741,-3.367862,3941.0,302.5703,64.9,3.9,58.2,11.605,-0.3,17.0
15,15,Poland,2015,5.79,18.34,7.47,7.64,20.68,3.30,3.81,...,2.243049,-2.532527,4676.0,305.7942,66.3,3.0,59.9,11.881,-1.0,17.6
16,16,Poland,2016,5.84,18.39,6.14,6.18,17.59,3.82,4.00,...,2.062852,-2.650770,4261.0,316.7280,68.2,2.2,61.5,11.396,0.2,17.3
17,17,Poland,2017,5.97,18.46,4.87,4.86,14.76,2.38,4.10,...,NaN,-1.585809,3924.0,330.2221,70.0,1.5,63.0,11.059,0.1,15.0
18,18,Poland,2018,6.12,18.43,3.84,3.82,11.68,3.35,4.10,...,NaN,0.071103,4207.0,329.6329,71.4,1.0,64.5,14.936,-0.1,14.8
19,19,Poland,2019,6.18,18.38,3.27,3.57,9.83,3.15,4.30,...,NaN,-0.525643,3887.0,312.0707,72.6,0.7,65.3,15.377,-0.4,15.4
20,20,Poland,2020,6.17,18.13,3.15,3.28,10.83,3.31,NaN,...,NaN,-7.027947,4010.0,296.8799,72.8,0.6,65.4,16.102,-23.6,14.8
21,21,Poland,2021,6.12,18.23,3.27,3.28,11.81,5.44,NaN,...,NaN,-2.303009,3377.0,324.0123,75.5,0.9,68.5,15.604,-5.0,14.8
22,22,Poland,2022,6.26,18.26,2.81,2.85,10.55,6.01,NaN,...,NaN,-3.005692,NaN,307.9616,76.7,0.9,70.3,16.644,-3.7,13.7

In [91]:
df_pl = df_pl.copy()
# df_pl['LFG'] = df_pl['LF'].diff()
# df_pl['EPFRG'] = df_pl['EPFR'].diff()
df_pl['GGAG'] = df_pl['GGA'].diff()
df_pl['PAG'] = df_pl['PA'].diff()
df_pl = df_pl.drop(6)

In [92]:
# df_pl = df_pl.drop(["Unnamed: 0", "REF_AREA_LABEL", "HI", "OCTB", "NINA", "LF", "EPFR", "GGA", "EIA", "GDP",
#                    "UR", "URFF", "YUA", "P014", "P65"], axis=1)

In [93]:
df_pl = df_pl[["TIME_PERIOD", "GDPC", "GDPCG", "VABI", "EMP", "PAG", "QOA", "QOR", "YUA", "GGAG", "REST", "CO2",
             "EBSG", "FDI", "GGFC", "LBGD", "PC", "ARP", "PS"]]

In [94]:
df_pl

,TIME_PERIOD,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,REST,CO2,EBSG,FDI,GGFC,LBGD,PC,ARP,PS
7,2007,31201.797665,6.818440,29.28,:,235.0,3.63,2.57,21.39,535.0,6.903,330.3011,-3.803166,5.83,18.166685,-1.872662,-0.3,17.3,38.12
8,2008,33846.381917,4.369536,28.82,:,96.0,3.69,1.91,17.10,-6200.0,7.686,324.5779,-5.237136,2.72,18.626276,-3.397579,0.5,16.9,38.13
9,2009,36057.305377,2.545617,29.96,62.6,411.0,3.74,2.06,20.47,-14768.0,8.676,311.3787,-0.960496,3.18,18.707747,-6.157262,0.8,17.1,38.15
10,2010,37895.481599,3.464009,29.70,62.2,304.0,3.65,2.23,23.58,18440.0,9.281,329.3834,-2.441439,3.94,19.149239,-6.142614,1.0,17.6,38.04
11,2011,41087.789260,5.198882,30.39,62.5,676.0,3.65,2.33,25.53,-3920.0,10.337,326.9383,-2.287307,3.57,18.077861,-4.112383,0.0,17.7,38.06
12,2012,42619.735974,1.512024,30.23,62.9,531.0,3.81,2.62,26.31,-6980.0,10.955,319.7269,-0.784100,1.53,18.008657,-3.437896,0.0,17.1,38.06
13,2013,43053.616233,0.745032,28.68,63.2,-173.0,3.91,3.05,27.16,-5791.0,11.452,315.0899,1.117069,0.26,18.330801,-4.023830,-1.2,17.3,38.04
14,2014,44990.974498,3.998318,29.94,64.9,-296.0,4.02,3.55,23.73,-13172.0,11.605,302.5703,0.407324,3.85,18.238027,-3.367862,-0.3,17.0,38.01
15,2015,47637.139301,4.501385,30.99,66.3,735.0,4.07,3.81,20.68,3157.0,11.881,305.7942,2.067846,3.30,17.905031,-2.532527,-1.0,17.6,37.99
16,2016,49142.895037,3.075475,30.67,68.2,-415.0,4.30,4.00,17.59,10799.0,11.396,316.7280,2.946955,3.82,17.821550,-2.650770,0.2,17.3,37.97
17,2017,52583.150743,5.139335,28.81,70.0,-337.0,4.50,4.10,14.76,13375.0,11.059,330.2221,2.819160,2.38,17.566841,-1.585809,0.1,15.0,37.97
18,2018,56553.025366,6.246071,28.86,71.4,283.0,4.80,4.10,11.68,-1790.0,14.936,329.6329,2.022689,3.35,17.469653,0.071103,-0.1,14.8,37.97
19,2019,60948.243108,4.606007,28.83,72.6,-320.0,4.80,4.30,9.83,-17545.0,15.377,312.0707,3.644753,3.15,17.818308,-0.525643,-0.4,15.4,37.97
20,2020,62984.456554,-0.861202,28.57,72.8,123.0,NaN,NaN,10.83,-16997.0,16.102,296.8799,5.608680,3.31,18.837162,-7.027947,-23.6,14.8,37.52
21,2021,71968.788552,8.471718,28.49,75.5,-633.0,NaN,NaN,11.81,NaN,15.604,324.0123,3.201669,5.44,18.523151,-2.303009,-5.0,14.8,36.98
22,2022,84212.458240,5.712276,29.18,76.7,NaN,NaN,NaN,10.55,NaN,16.644,307.9616,1.683700,6.01,18.119129,-3.005692,-3.7,13.7,36.82

In [95]:
df_pl["EMP"] = df_pl["EMP"].replace(':', np.nan)
# df_pl["LTU"] = df_pl["LTU"].replace(':', np.nan)
# df_pl["FEM"] = df_pl["FEM"].replace(':', np.nan)

In [96]:
missing_values(df_pl)

TIME_PERIOD - 0 - 0.0 %
GDPC - 0 - 0.0 %
GDPCG - 0 - 0.0 %
VABI - 0 - 0.0 %
EMP - 2 - 12.5 %
PAG - 1 - 6.2 %
QOA - 3 - 18.8 %
QOR - 3 - 18.8 %
YUA - 0 - 0.0 %
GGAG - 2 - 12.5 %
REST - 0 - 0.0 %
CO2 - 0 - 0.0 %
EBSG - 0 - 0.0 %
FDI - 0 - 0.0 %
GGFC - 0 - 0.0 %
LBGD - 0 - 0.0 %
PC - 0 - 0.0 %
ARP - 0 - 0.0 %
PS - 0 - 0.0 %

In [97]:
df_pl = df_pl.copy()
fill_with_mode(df_pl, ["QOR", "QOA"])

In [98]:
fill_with_mean(df_pl, ["EMP", "PAG", "GGAG"])

In [99]:
pl_context_2007_2015 = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Poland_2007_2015.csv")

In [100]:
pl_context_2007_2015 = pl_context_2007_2015[["TIME_PERIOD", 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT']]

In [101]:
pl_eu_payments = eu_payments[eu_payments['Country'] == 'PL'].copy()

In [102]:
pl_eu_payments

     Country Fund  Year Programming_Period EU_Payment_annual
1125      PL   CF  2007          2007-2013        45,219,844
1126      PL   CF  2008          2007-2013        72,351,752
1127      PL   CF  2009          2007-2013       129,326,232
1128      PL   CF  2010          2007-2013       108,332,216
1129      PL   CF  2011          2007-2013       207,533,488
...      ...  ...   ...                ...               ...
3022      PL  ESF  2018          2014-2020       110,564,312
3023      PL  ESF  2019          2014-2020        98,266,373
3024      PL  ESF  2020          2014-2020       103,054,231
3025      PL  ESF  2021          2014-2020       111,579,443
3026      PL  ESF  2022          2014-2020       114,688,295

[897 rows x 5 columns]

In [103]:
pl_eu_payments['EU_Payment_annual'] = pd.to_numeric(pl_eu_payments['EU_Payment_annual'].str.replace(',', ''))

In [104]:
pl_eu_payments_2007_2015 = pl_eu_payments[pl_eu_payments['Programming_Period'] == '2007-2013'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

In [105]:
pl_eu_payments_2007_2015 = pl_eu_payments_2007_2015.rename({"Year":"TIME_PERIOD"}, axis=1)

In [106]:
pl_eu_payments_2007_2015

    TIME_PERIOD  EU_Payment_annual
0          2007         1400802662
1          2008         2192935247
2          2009         5155672523
3          2010         6850960177
4          2011         9415548745
5          2012        10098196875
6          2013        10475714683
7          2014        11686980907
8          2015         6458114981
9          2016           91344706
10         2017         1942750121
11         2018         1322743760
12         2019           93430136

In [107]:
pl_eu_payments_2007_2015 = pl_eu_payments_2007_2015.loc[0:8]

In [108]:
df_pl_2007_2015 = df_pl.loc[7:15]

In [109]:
df_pl_2007_2015 = pd.merge(df_pl_2007_2015, pl_context_2007_2015, on='TIME_PERIOD', how='outer')

In [110]:
df_pl_2007_2015 = pd.merge(df_pl_2007_2015, pl_eu_payments_2007_2015, on='TIME_PERIOD', how='outer')

In [111]:
df_pl_2007_2015['EUPC'] = df_pl_2007_2015['EU_Payment_annual'] / (df_pl_2007_2015['PS'] * 1000000)

In [112]:
df_pl_2007_2015 = df_pl_2007_2015.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [113]:
df_pl_2007_2015.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/pl_2007_2015_bn.csv')

In [114]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_pl_2007_2015.values)

df_pl_2007_2015_scaled = pd.DataFrame(scaled_features, index=df_pl_2007_2015.index, columns=df_pl_2007_2015.columns)

In [115]:
df_pl_2007_2015_scaled.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/pl_2007_2015_tcdf.csv')

In [116]:
df_de.columns.equals(df_pl.columns)

True

In [329]:
column_index = df_pl_2007_2015_scaled.columns.get_loc('COC')
print(column_index)

19

20,1,1
17,2,3
4,2,1
2,4,0
15,7,0
1,12,0
20,12,0
16,15,0
2,16,1
12,19,0

In [118]:
pl_context_2016_2022 = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Poland_2016_2022.csv")

pl_context_2016_2022 = pl_context_2016_2022[["TIME_PERIOD", 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT']]

# pl_context_2016_2022["DBDC"] = pl_context_2016_2022["DBD"].diff()

# pl_context_2016_2022 = pl_context_2016_2022.drop(["DBD"], axis=1)

pl_context_2016_2022 = pl_context_2016_2022.loc[2:8]

df_pl_2016_2022 = df_pl.loc[16:22]

In [119]:
pl_context_2016_2022

   TIME_PERIOD   ROL    GE   COC    RQ        SSB         PT
2         2016  0.59  0.65  0.76  0.91  82.711080  79.141239
3         2017  0.40  0.55  0.70  0.81  82.752840  79.105836
4         2018  0.38  0.55  0.62  0.87  82.780110  79.495816
5         2019  0.39  0.51  0.61  1.01  82.848012  76.490761
6         2020  0.52  0.32  0.62  0.85  82.757531  76.831746
7         2021  0.43  0.25  0.55  0.83  82.726573  76.516572
8         2022  0.43  0.26  0.51  0.72  82.726573  76.516572

In [120]:
pl_eu_payments_2016_2022 = pl_eu_payments[pl_eu_payments['Programming_Period'] == '2014-2020'].groupby('Year')['EU_Payment_annual'].sum().reset_index()
pl_eu_payments_2016_2022 = pl_eu_payments_2016_2022.rename({"Year":"TIME_PERIOD"}, axis=1)
pl_eu_payments_2016_2022 = pl_eu_payments_2016_2022.loc[1:7]
pl_eu_payments_2016_2022

   TIME_PERIOD  EU_Payment_annual
1         2016         2804505749
2         2017         4638222529
3         2018         9582436519
4         2019        10639507736
5         2020        12091039828
6         2021        13811714640
7         2022        11413018878

In [121]:
df_pl_2016_2022 = pd.merge(df_pl_2016_2022, pl_context_2016_2022, on='TIME_PERIOD', how='outer')

df_pl_2016_2022 = pd.merge(df_pl_2016_2022, pl_eu_payments_2016_2022, on='TIME_PERIOD', how='outer')

df_pl_2016_2022['EUPC'] = df_pl_2016_2022['EU_Payment_annual'] / (df_pl_2016_2022['PS'] * 1000000)
df_pl_2016_2022 = df_pl_2016_2022.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [122]:
df_pl_2016_2022.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/pl_2016_2022_bn.csv')

In [123]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_pl_2016_2022.values)

df_pl_2016_2022_scaled = pd.DataFrame(scaled_features, index=df_pl_2016_2022.index, columns=df_pl_2016_2022.columns)

In [124]:
df_pl_2016_2022_scaled.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/pl_2016_2022_tcdf.csv')

In [334]:
column_index = df_pl_2016_2022_scaled.columns.get_loc('FDI')
print(column_index)

12

6,4,1
1,14,0

==================================================================================================================

In [126]:
df_lt = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/Lithuania.csv")

In [127]:
df_lt = df_lt.loc[6:22]

In [128]:
df_lt

,Unnamed: 0,REF_AREA_LABEL,TIME_PERIOD,HI,LF,UR,URFF,YUA,FDI,QOR,...,NINA,LBGD,PA,CO2,EMP,LTU,FEM,REST,PC,ARP
6,6,Lithuania,2006,NaN,1.51,5.78,5.61,9.98,7.50,4.92,...,3.118363,0.075001,65.0,14.1941,:,:,NaN,NaN,-12.2,20.0
7,7,Lithuania,2007,NaN,1.51,4.25,4.33,8.39,6.55,4.97,...,3.723648,-0.493558,62.0,15.5684,:,:,:,16.482,-11.6,19.1
8,8,Lithuania,2008,NaN,1.51,5.83,5.63,13.35,3.61,5.21,...,3.480952,-2.844590,87.0,15.8313,:,:,:,17.824,-9.0,20.9
9,9,Lithuania,2009,NaN,1.52,13.78,10.52,29.58,-0.96,5.28,...,2.773311,-8.626258,91.0,13.2105,67.0,3.3,67.2,19.798,-13.2,20.3
10,10,Lithuania,2010,NaN,1.49,17.81,14.52,35.74,3.01,5.27,...,2.591630,-7.016844,108.0,14.0410,64.3,7.4,65.0,19.639,-28.9,20.5
11,11,Lithuania,2011,NaN,1.48,15.39,12.91,32.59,4.36,5.23,...,2.373246,-5.541350,93.0,14.3203,66.9,8.0,66.6,19.943,-16.2,19.2
12,12,Lithuania,2012,NaN,1.47,13.36,11.57,26.68,1.59,5.17,...,1.956453,-2.893765,109.0,14.4911,68.5,6.6,67.9,21.437,-9.7,18.6
13,13,Lithuania,2013,5.43,1.47,11.77,10.48,21.90,1.66,5.02,...,2.151628,-2.417272,117.0,13.3644,69.9,5.1,68.6,22.689,-9.0,20.6
14,14,Lithuania,2014,NaN,1.48,10.70,9.22,19.26,0.74,4.94,...,2.113033,-1.911556,123.0,13.2117,71.8,4.8,70.6,23.592,-7.2,19.1
15,15,Lithuania,2015,5.83,1.47,9.12,8.16,16.30,2.50,4.96,...,2.545603,-1.093729,101.0,13.6606,73.3,3.9,72.2,25.748,-10.7,22.2
16,16,Lithuania,2016,5.81,1.48,7.86,6.65,14.45,2.74,4.90,...,1.972772,-0.460837,95.0,13.5202,75.2,3.0,74.3,25.612,-12.7,21.9
17,17,Lithuania,2017,5.90,1.47,7.07,5.67,13.27,2.90,4.70,...,NaN,0.165584,81.0,13.9642,76.0,2.7,75.5,26.038,-11.6,22.9
18,18,Lithuania,2018,5.95,1.47,6.15,5.41,11.12,2.40,4.70,...,NaN,0.413734,81.0,14.0184,77.8,2.0,76.7,24.695,-5.0,22.9
19,19,Lithuania,2019,6.15,1.48,6.26,5.49,11.85,6.23,4.80,...,NaN,0.441721,90.0,14.2965,78.2,1.9,77.4,25.474,-0.8,20.6
20,20,Lithuania,2020,6.26,1.49,8.49,7.69,19.56,7.94,NaN,...,NaN,-6.374068,95.0,14.2541,76.7,2.5,75.8,26.773,0.3,20.9
21,21,Lithuania,2021,6.45,1.49,7.11,6.61,14.30,3.74,NaN,...,NaN,-1.419204,81.0,14.3318,77.4,2.6,76.7,28.167,-1.7,20.0
22,22,Lithuania,2022,6.76,1.51,5.95,5.48,11.87,3.41,NaN,...,NaN,-0.897036,NaN,13.1703,79.0,2.3,78.6,29.599,18.1,20.9

In [129]:
df_lt = df_lt.copy()
# df_lt['LFG'] = df_lt['LF'].diff()
# df_lt['EPFRG'] = df_lt['EPFR'].diff()
df_lt['GGAG'] = df_lt['GGA'].diff()
df_lt['PAG'] = df_lt['PA'].diff()
df_lt = df_lt.drop(6)

In [130]:
# df_lt = df_lt.drop(["Unnamed: 0", "REF_AREA_LABEL", "HI", "OCTB", "NINA", "LF", "EPFR", "GGA", "EIA", "GDP",
#                    "UR", "URFF", "YUA", "P014", "P65"], axis=1)

In [131]:
df_lt = df_lt[["TIME_PERIOD", "GDPC", "GDPCG", "VABI", "EMP", "PAG", "QOA", "QOR", "YUA", "GGAG", "REST", "CO2",
             "EBSG", "FDI", "GGFC", "LBGD", "PC", "ARP", "PS"]]

In [132]:
df_lt["EMP"] = df_lt["EMP"].replace(':', np.nan)
# df_lt["LTU"] = df_lt["LTU"].replace(':', np.nan)
# df_lt["FEM"] = df_lt["FEM"].replace(':', np.nan)

In [133]:
missing_values(df_lt)

TIME_PERIOD - 0 - 0.0 %
GDPC - 0 - 0.0 %
GDPCG - 0 - 0.0 %
VABI - 0 - 0.0 %
EMP - 2 - 12.5 %
PAG - 1 - 6.2 %
QOA - 3 - 18.8 %
QOR - 3 - 18.8 %
YUA - 0 - 0.0 %
GGAG - 2 - 12.5 %
REST - 0 - 0.0 %
CO2 - 0 - 0.0 %
EBSG - 0 - 0.0 %
FDI - 0 - 0.0 %
GGFC - 0 - 0.0 %
LBGD - 0 - 0.0 %
PC - 0 - 0.0 %
ARP - 0 - 0.0 %
PS - 0 - 0.0 %

In [134]:
df_lt = df_lt.copy()
fill_with_mode(df_lt, ["QOR", "QOA"])

In [135]:
fill_with_mean(df_lt, ["EMP", "PAG", "GGAG"])

In [136]:
lt_context_2007_2015 = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Lithuania_2007_2015.csv")

In [137]:
lt_context_2007_2015 = lt_context_2007_2015[["TIME_PERIOD", 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT']]

In [138]:
lt_eu_payments = eu_payments[eu_payments['Country'] == 'LT'].copy()

In [139]:
lt_eu_payments['EU_Payment_annual'] = pd.to_numeric(lt_eu_payments['EU_Payment_annual'].str.replace(',', ''))

In [140]:
lt_eu_payments_2007_2015 = lt_eu_payments[lt_eu_payments['Programming_Period'] == '2007-2013'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

In [141]:
lt_eu_payments_2007_2015 = lt_eu_payments_2007_2015.rename({"Year":"TIME_PERIOD"}, axis=1)

In [142]:
lt_eu_payments_2007_2015

    TIME_PERIOD  EU_Payment_annual
0          2007          147036030
1          2008          226317129
2          2009         1067875010
3          2010          871817905
4          2011          937791043
5          2012         1013987411
6          2013         1072505603
7          2014         1013149415
8          2015           86238312
9          2017           50722512
10         2018          287359288

In [143]:
lt_eu_payments_2007_2015 = lt_eu_payments_2007_2015.loc[0:8]

In [144]:
lt_eu_payments_2007_2015

   TIME_PERIOD  EU_Payment_annual
0         2007          147036030
1         2008          226317129
2         2009         1067875010
3         2010          871817905
4         2011          937791043
5         2012         1013987411
6         2013         1072505603
7         2014         1013149415
8         2015           86238312

In [145]:
df_lt_2007_2015 = df_lt.loc[7:15]

In [146]:
df_lt_2007_2015 = pd.merge(df_lt_2007_2015, lt_context_2007_2015, on='TIME_PERIOD', how='outer')

In [147]:
df_lt_2007_2015 = pd.merge(df_lt_2007_2015, lt_eu_payments_2007_2015, on='TIME_PERIOD', how='outer')

In [148]:
df_lt_2007_2015['EUPC'] = df_lt_2007_2015['EU_Payment_annual'] / (df_lt_2007_2015['PS'] * 1000000)

In [149]:
df_lt_2007_2015 = df_lt_2007_2015.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [150]:
df_lt_2007_2015.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/lt_2007_2015_bn.csv')

In [151]:
df_lt_2007_2015

,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,REST,...,LBGD,PC,ARP,ROL,GE,COC,RQ,SSB,PT,EUPC
0,8985.274630,12.405345,29.65,73.0,-3.0,4.40,4.97,8.39,1013.0,16.482,...,-0.493558,-11.6,19.1,0.69,0.66,0.10,1.01,81.367724,79.207745,45.521991
1,10219.116755,3.660125,29.20,73.0,25.0,4.61,5.21,13.35,-563.0,17.824,...,-2.844590,-9.0,20.9,0.68,0.56,0.11,1.04,81.503460,79.492010,70.724103
2,8528.034573,-13.887757,25.02,67.0,4.0,4.22,5.28,29.58,-3576.0,19.798,...,-8.626258,-13.2,20.3,0.72,0.69,0.23,0.95,82.186109,79.791757,337.935130
3,8931.519313,2.555336,26.21,64.3,17.0,3.57,5.27,35.74,806.0,19.639,...,-7.016844,-28.9,20.5,0.78,0.74,0.37,0.96,82.520151,80.789148,281.231582
4,10259.331961,8.752239,28.35,66.9,-15.0,3.73,5.23,32.59,-532.0,19.943,...,-5.541350,-16.2,19.2,0.77,0.70,0.32,0.93,84.636537,80.127684,309.501994
5,11120.403233,5.743976,28.20,68.5,16.0,4.23,5.17,26.68,-81.0,21.437,...,-2.893765,-9.7,18.6,0.84,0.83,0.39,1.12,84.670001,81.101556,339.126224
6,11776.792571,5.026825,27.62,69.9,8.0,4.32,5.02,21.90,-892.0,22.689,...,-2.417272,-9.0,20.6,0.83,0.83,0.42,1.15,84.317188,81.028515,362.332974
7,12395.979849,4.620353,27.73,71.8,6.0,4.19,4.94,19.26,-452.0,23.592,...,-1.911556,-7.2,19.1,0.94,0.98,0.55,1.19,83.028739,81.075004,344.608645
8,12861.323296,3.756324,26.96,73.3,-22.0,4.12,4.96,16.30,260.0,25.748,...,-1.093729,-10.7,22.2,0.98,1.15,0.58,1.26,83.028739,81.549466,29.635159

In [152]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_lt_2007_2015.values)

df_lt_2007_2015_scaled = pd.DataFrame(scaled_features, index=df_lt_2007_2015.index, columns=df_lt_2007_2015.columns)

In [153]:
df_lt_2007_2015_scaled.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/lt_2007_2015_tcdf.csv')

In [154]:
df_pl.columns.equals(df_lt.columns)

True

In [340]:
column_index = df_lt_2007_2015_scaled.columns.get_loc('ARP')
print(column_index)

16

In [156]:
12,4,0
12,0,0
16,16,1
8,16,2

(0, 25, 3)

In [157]:
lt_context_2016_2022 = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Lithuania_2016_2022.csv")

lt_context_2016_2022 = lt_context_2016_2022[["TIME_PERIOD", 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT']]

In [158]:
df_lt

,TIME_PERIOD,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,REST,CO2,EBSG,FDI,GGFC,LBGD,PC,ARP,PS
7,2007,8985.274630,12.405345,29.65,73.0,-3.000000,4.40,4.97,8.39,1013.000000,16.482,15.5684,-13.094653,6.55,17.451336,-0.493558,-11.6,19.1,3.23
8,2008,10219.116755,3.660125,29.20,73.0,25.000000,4.61,5.21,13.35,-563.000000,17.824,15.8313,-11.598256,3.61,18.666542,-2.844590,-9.0,20.9,3.20
9,2009,8528.034573,-13.887757,25.02,67.0,4.000000,4.22,5.28,29.58,-3576.000000,19.798,13.2105,-1.755188,-0.96,21.205413,-8.626258,-13.2,20.3,3.16
10,2010,8931.519313,2.555336,26.21,64.3,17.000000,3.57,5.27,35.74,806.000000,19.639,14.0410,-2.029481,3.01,20.110710,-7.016844,-28.9,20.5,3.10
11,2011,10259.331961,8.752239,28.35,66.9,-15.000000,3.73,5.23,32.59,-532.000000,19.943,14.3203,-2.706873,4.36,18.467399,-5.541350,-16.2,19.2,3.03
12,2012,11120.403233,5.743976,28.20,68.5,16.000000,4.23,5.17,26.68,-81.000000,21.437,14.4911,0.613211,1.59,17.543879,-2.893765,-9.7,18.6,2.99
13,2013,11776.792571,5.026825,27.62,69.9,8.000000,4.32,5.02,21.90,-892.000000,22.689,13.3644,1.457239,1.66,16.735544,-2.417272,-9.0,20.6,2.96
14,2014,12395.979849,4.620353,27.73,71.8,6.000000,4.19,4.94,19.26,-452.000000,23.592,13.2117,1.930309,0.74,16.691874,-1.911556,-7.2,19.1,2.94
15,2015,12861.323296,3.756324,26.96,73.3,-22.000000,4.12,4.96,16.30,260.000000,25.748,13.6606,-0.986813,2.50,17.168991,-1.093729,-10.7,22.2,2.91
16,2016,13491.939909,3.877441,26.00,75.2,-6.000000,4.40,4.90,14.45,25.000000,25.612,13.5202,0.728400,2.74,17.029185,-0.460837,-12.7,21.9,2.88
17,2017,14871.586227,5.888726,25.72,76.0,-14.000000,4.40,4.70,13.27,-79.000000,26.038,13.9642,2.294288,2.90,16.299364,0.165584,-11.6,22.9,2.84
18,2018,16298.029583,5.790665,25.58,77.8,0.000000,4.60,4.70,11.12,86.000000,24.695,14.0184,1.856906,2.40,16.217817,0.413734,-5.0,22.9,2.82
19,2019,17516.070462,4.979384,25.26,78.2,9.000000,4.90,4.80,11.85,128.000000,25.474,14.2965,5.262450,6.23,16.795948,0.441721,-0.8,20.6,2.81
20,2020,17885.411844,0.068446,24.79,76.7,5.000000,4.40,4.70,19.56,5.000000,26.773,14.2541,9.072805,7.94,18.360545,-6.374068,0.3,20.9,2.81
21,2021,20182.333587,6.455358,24.86,77.4,-14.000000,4.40,4.70,14.30,-275.142857,28.167,14.3318,4.453149,3.74,17.497495,-1.419204,-1.7,20.0,2.81
22,2022,23822.056413,1.695286,25.64,79.0,1.066667,4.40,4.70,11.87,-275.142857,29.599,13.1703,-2.091914,3.41,16.744046,-0.897036,18.1,20.9,2.83

In [159]:
df_lt_2016_2022 = df_lt.loc[16:22]

In [160]:
lt_eu_payments_2016_2022 = lt_eu_payments[lt_eu_payments['Programming_Period'] == '2014-2020'].groupby('Year')['EU_Payment_annual'].sum().reset_index()
lt_eu_payments_2016_2022 = lt_eu_payments_2016_2022.rename({"Year":"TIME_PERIOD"}, axis=1)

In [161]:
lt_eu_payments_2016_2022 = lt_eu_payments_2016_2022.loc[1:7]
lt_eu_payments_2016_2022

   TIME_PERIOD  EU_Payment_annual
1         2016          332852729
2         2017          434501955
3         2018          809554069
4         2019          529282582
5         2020         1445805827
6         2021         1139822052
7         2022          937545028

In [162]:
df_lt_2016_2022

,TIME_PERIOD,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,REST,CO2,EBSG,FDI,GGFC,LBGD,PC,ARP,PS
16,2016,13491.939909,3.877441,26.00,75.2,-6.000000,4.4,4.9,14.45,25.000000,25.612,13.5202,0.728400,2.74,17.029185,-0.460837,-12.7,21.9,2.88
17,2017,14871.586227,5.888726,25.72,76.0,-14.000000,4.4,4.7,13.27,-79.000000,26.038,13.9642,2.294288,2.90,16.299364,0.165584,-11.6,22.9,2.84
18,2018,16298.029583,5.790665,25.58,77.8,0.000000,4.6,4.7,11.12,86.000000,24.695,14.0184,1.856906,2.40,16.217817,0.413734,-5.0,22.9,2.82
19,2019,17516.070462,4.979384,25.26,78.2,9.000000,4.9,4.8,11.85,128.000000,25.474,14.2965,5.262450,6.23,16.795948,0.441721,-0.8,20.6,2.81
20,2020,17885.411844,0.068446,24.79,76.7,5.000000,4.4,4.7,19.56,5.000000,26.773,14.2541,9.072805,7.94,18.360545,-6.374068,0.3,20.9,2.81
21,2021,20182.333587,6.455358,24.86,77.4,-14.000000,4.4,4.7,14.30,-275.142857,28.167,14.3318,4.453149,3.74,17.497495,-1.419204,-1.7,20.0,2.81
22,2022,23822.056413,1.695286,25.64,79.0,1.066667,4.4,4.7,11.87,-275.142857,29.599,13.1703,-2.091914,3.41,16.744046,-0.897036,18.1,20.9,2.83

In [163]:
df_lt_2016_2022 = pd.merge(df_lt_2016_2022, lt_context_2016_2022, on='TIME_PERIOD', how='outer')

df_lt_2016_2022 = pd.merge(df_lt_2016_2022, lt_eu_payments_2016_2022, on='TIME_PERIOD', how='outer')

df_lt_2016_2022['EUPC'] = df_lt_2016_2022['EU_Payment_annual'] /(df_lt_2016_2022['PS'] * 1000000)
# # fill_with_mode(df_lt_2016_2022, ["PDPS"])
# fill_with_mean(df_lt_2016_2022, [ "GGAG"])
df_lt_2016_2022
df_lt_2016_2022 = df_lt_2016_2022.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [164]:
df_lt_2016_2022.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/lt_2016_2022_bn.csv', index=True)

In [165]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_lt_2016_2022.values)

df_lt_2016_2022_scaled = pd.DataFrame(scaled_features, index=df_lt_2016_2022.index, columns=df_lt_2016_2022.columns)

In [166]:
df_lt_2016_2022_scaled.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/lt_2016_2022_tcdf.csv')

In [167]:
df_lt_2016_2022_scaled

,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,REST,...,LBGD,PC,ARP,ROL,GE,COC,RQ,SSB,PT,EUPC
0,-1.325279,-0.103863,1.411254,-1.634729,-0.396320,-0.564076,2.157277,0.255824,0.527984,-0.636154,...,0.315077,-1.140150,0.432038,0.138039,0.838054,8.219949e-02,-0.572892,-1.439853e+00,-1.417170e+00,-1.269104
1,-0.893231,0.802577,0.744734,-0.976133,-1.358483,-0.564076,-0.588348,-0.190922,-0.158045,-0.367987,...,0.596791,-1.023870,1.377122,-0.634981,-2.249514,-1.232992e+00,-0.196932,-9.354275e-01,-1.404279e+00,-0.988911
2,-0.446529,0.758384,0.411474,0.505707,0.325303,0.564076,-0.588348,-1.004907,0.930366,-1.213405,...,0.708389,-0.326189,1.377122,-1.408002,0.838054,-1.643990e+00,-0.948852,-2.860967e-01,4.524547e-01,0.015073
3,-0.065089,0.392757,-0.350263,0.835005,1.407737,2.256304,0.784465,-0.728531,1.207416,-0.723025,...,0.720975,0.117790,-0.796570,-0.055216,0.220541,9.125977e-16,-0.196932,8.678250e-01,1.117978e+00,-0.724118
4,0.050573,-1.820490,-1.469065,-0.399862,0.926655,-0.564076,-0.588348,2.190459,0.396055,0.094695,...,-2.344221,0.234071,-0.513045,-0.828236,0.220541,9.041944e-01,-1.074172,1.793552e+00,1.251016e+00,1.718146
5,0.769873,1.057946,-1.302435,0.176410,-1.358483,-0.564076,-0.588348,0.199034,-1.451888,0.972217,...,-0.115920,0.022652,-1.363620,1.490826,0.529297,1.232992e+00,1.306910,1.342070e-13,-1.103769e-14,0.902789
6,1.909682,-1.087311,0.554300,1.493601,0.453591,-0.564076,-0.588348,-0.720959,-1.451888,1.873660,...,0.118909,2.115696,-0.513045,1.297570,-0.396973,6.575959e-01,1.682870,1.342070e-13,-1.103769e-14,0.346125

In [349]:
column_index = df_lt_2016_2022_scaled.columns.get_loc("GE")
print(column_index)

18

In [169]:
18,6,0
23,6,1
1,10,3
23,14,2
6,18,3

(19, 26, 1)

===================================================================================================================

In [170]:
df_lv = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/Latvia.csv")

In [171]:
df_lv = df_lv.loc[6:22]

In [172]:
df_lv = df_lv.copy()
# df_lv['LFG'] = df_lv['LF'].diff()
# df_lv['EPFRG'] = df_lv['EPFR'].diff()
df_lv['GGAG'] = df_lv['GGA'].diff()
df_lv['PAG'] = df_lv['PA'].diff()
df_lv = df_lv.drop(6)

In [173]:
# df_lv = df_lv.drop(["Unnamed: 0", "REF_AREA_LABEL", "HI", "OCTB", "NINA", "LF", "EPFR", "GGA", "EIA", "GDP",
#                    "UR", "URFF", "YUA", "P014", "P65"], axis=1)

In [174]:
df_lv = df_lv[["TIME_PERIOD", "GDPC", "GDPCG", "VABI", "EMP", "PAG", "QOA", "QOR", "YUA", "GGAG", "REST", "CO2",
             "EBSG", "FDI", "GGFC", "LBGD", "PC", "ARP", "PS"]]

In [175]:
df_lv["EMP"] = df_lv["EMP"].replace(':', np.nan)
# df_lv["LTU"] = df_lv["LTU"].replace(':', np.nan)
# df_lv["FEM"] = df_lv["FEM"].replace(':', np.nan)

In [176]:
missing_values(df_lv)

TIME_PERIOD - 0 - 0.0 %
GDPC - 0 - 0.0 %
GDPCG - 0 - 0.0 %
VABI - 0 - 0.0 %
EMP - 2 - 12.5 %
PAG - 1 - 6.2 %
QOA - 3 - 18.8 %
QOR - 3 - 18.8 %
YUA - 0 - 0.0 %
GGAG - 2 - 12.5 %
REST - 0 - 0.0 %
CO2 - 0 - 0.0 %
EBSG - 0 - 0.0 %
FDI - 0 - 0.0 %
GGFC - 0 - 0.0 %
LBGD - 0 - 0.0 %
PC - 0 - 0.0 %
ARP - 0 - 0.0 %
PS - 0 - 0.0 %

In [177]:
# df_lv = df_lv.copy()
# fill_with_mode(df_lv, ["QOR", "QOA"])

In [178]:
fill_with_mean(df_lv, ["EMP", "PAG", "QOR", "QOA", "GGAG"])

In [179]:
lv_context_2007_2015 = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Latvia_2007_2015.csv")

In [180]:
lv_context_2007_2015 = lv_context_2007_2015[["TIME_PERIOD", 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT']]

In [181]:
lv_context_2007_2015

   TIME_PERIOD   ROL    GE   COC    RQ        SSB         PT
0         2007  0.72  0.43  0.34  0.95  88.154100  81.115239
1         2008  0.78  0.52  0.23  0.97  88.467773  83.228626
2         2009  0.79  0.62  0.20  0.92  89.002428  83.043921
3         2010  0.76  0.72  0.20  0.93  89.196552  82.613206
4         2011  0.74  0.69  0.28  0.95  89.163024  81.896887
5         2012  0.78  0.83  0.24  1.01  91.495552  82.315191
6         2013  0.76  0.88  0.32  1.04  91.532399  84.229882
7         2014  0.87  0.95  0.41  1.17  92.332633  84.865341
8         2015  0.77  1.05  0.43  1.07  92.038243  86.462455

In [182]:
lv_eu_payments = eu_payments[eu_payments['Country'] == 'LV'].copy()

lv_eu_payments['EU_Payment_annual'] = pd.to_numeric(lv_eu_payments['EU_Payment_annual'].str.replace(',', ''))

lv_eu_payments_2007_2015 = lv_eu_payments[lv_eu_payments['Programming_Period'] == '2007-2013'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

lv_eu_payments_2007_2015 = lv_eu_payments_2007_2015.rename({"Year":"TIME_PERIOD"}, axis=1)

In [183]:
lv_eu_payments_2007_2015 = lv_eu_payments_2007_2015.loc[0:8]

In [184]:
df_lv_2007_2015 = df_lv.loc[7:15]

df_lv_2007_2015 = pd.merge(df_lv_2007_2015, lv_context_2007_2015, on='TIME_PERIOD', how='outer')

df_lv_2007_2015 = pd.merge(df_lv_2007_2015, lv_eu_payments_2007_2015, on='TIME_PERIOD', how='outer')

df_lv_2007_2015['EUPC'] = df_lv_2007_2015['EU_Payment_annual'] / (df_lv_2007_2015['PS'] * 1000000)

df_lv_2007_2015 = df_lv_2007_2015.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [185]:
df_lv_2007_2015

,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,REST,...,LBGD,PC,ARP,ROL,GE,COC,RQ,SSB,PT,EUPC
0,9775.522707,11.319401,22.75,71.978571,25.0,5.39,3.11,10.56,424.0,29.615,...,0.134663,-7.7,21.2,0.72,0.43,0.34,0.95,88.154100,81.115239,44.685377
1,10725.051692,-2.368037,22.84,71.978571,67.0,5.59,2.85,13.65,-338.0,29.811,...,-3.172711,-13.3,25.9,0.78,0.52,0.23,0.97,88.467773,83.228626,69.408798
2,8629.945617,-14.642313,21.52,66.300000,34.0,5.48,3.19,33.43,-780.0,34.317,...,-7.966839,-19.8,26.4,0.79,0.62,0.20,0.92,89.002428,83.043921,198.581136
3,8447.759415,-1.635144,20.86,63.900000,-62.0,5.44,3.11,36.24,1140.0,30.375,...,-8.375610,-21.9,20.9,0.76,0.72,0.20,0.93,89.196552,82.613206,220.935379
4,9281.534430,4.929580,21.42,66.100000,-5.0,5.17,3.10,31.07,-641.0,33.478,...,-3.827185,-14.5,19.0,0.74,0.69,0.28,0.95,89.163024,81.896887,248.557865
5,10374.147811,8.644500,21.42,67.900000,20.0,5.27,3.16,28.56,-201.0,35.709,...,-1.006694,-10.3,19.2,0.78,0.83,0.24,1.01,91.495552,82.315191,351.810791
6,10909.112726,3.195452,20.82,69.500000,32.0,5.39,3.00,23.24,-72.0,37.037,...,-0.749488,-11.1,19.4,0.76,0.88,0.32,1.04,91.532399,84.229882,310.275825
7,11430.790829,3.060974,19.62,70.600000,-122.0,5.35,3.09,19.59,-55.0,38.629,...,-1.357478,-7.7,21.2,0.87,0.95,0.41,1.17,92.332633,84.865341,358.109379
8,12007.048703,4.636452,19.78,72.500000,33.0,5.37,3.31,16.32,44.0,37.538,...,-1.740458,-8.7,22.5,0.77,1.05,0.43,1.07,92.038243,86.462455,304.485269

In [186]:
df_lv_2007_2015.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/lv_2007_2015_bn.csv')

In [187]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_lv_2007_2015.values)

df_lv_2007_2015_scaled = pd.DataFrame(scaled_features, index=df_lv_2007_2015.index, columns=df_lv_2007_2015.columns)

In [188]:
df_lv_2007_2015_scaled

,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,REST,...,LBGD,PC,ARP,ROL,GE,COC,RQ,SSB,PT,EUPC
0,-0.344481,1.319398,1.442023,1.036212,0.408177,0.058977,0.065078,-1.509014,0.881472,-1.357472,...,1.109830,1.043978,-0.210298,-1.379324,-1.637323,0.559704,-0.668001,-1.277039,-1.416326,-1.756634
1,0.472981,-0.598759,1.527157,1.036212,1.168232,1.828280,-2.110373,-1.152224,-0.526010,-1.297568,...,-0.018675,-0.107368,1.605135,0.140747,-1.167028,-0.791777,-0.406609,-1.076706,-0.051182,-1.527342
2,-1.330722,-2.318875,0.278525,-0.921564,0.571046,0.855163,0.734447,1.131697,-1.342423,0.079600,...,-1.654474,-1.443750,1.798267,0.394093,-0.644478,-1.160362,-1.060088,-0.735239,-0.170492,-0.329361
3,-1.487568,-0.496051,-0.345791,-1.749001,-1.166221,0.501303,0.065078,1.456156,2.203987,-1.125193,...,-1.793951,-1.875505,-0.326177,-0.365943,-0.121928,-1.160362,-0.929393,-0.611258,-0.448713,-0.122041
4,-0.769761,0.423929,0.183932,-0.990517,-0.134719,-1.887257,-0.018594,0.859196,-1.085678,-0.176824,...,-0.241988,-0.354084,-1.060076,-0.872634,-0.278693,-0.177467,-0.668001,-0.632671,-0.911420,0.134138
5,0.170883,0.944537,0.183932,-0.369939,0.317695,-1.002605,0.483433,0.569376,-0.272959,0.505036,...,0.720389,0.509425,-0.982824,0.140747,0.452876,-0.668915,0.116174,0.857041,-0.641216,1.091736
6,0.631441,0.180908,-0.383629,0.181686,0.534853,0.058977,-0.855305,-0.044904,-0.034684,0.910913,...,0.808150,0.344947,-0.905571,-0.365943,0.714151,0.313980,0.508262,0.880574,0.595581,0.706528
7,1.080560,0.162062,-1.518749,0.560928,-2.252013,-0.294884,-0.102265,-0.466355,-0.003284,1.397475,...,0.600698,1.043978,-0.210298,2.420855,1.079936,1.419737,2.207307,1.391658,1.006056,1.150151
8,1.576668,0.382850,-1.367400,1.215983,0.552950,-0.117954,1.738501,-0.843929,0.179578,1.064033,...,0.470022,0.838380,0.291843,-0.112598,1.602486,1.665461,0.900349,1.203641,2.037714,0.652825

In [189]:
df_lv_2007_2015_scaled.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/lv_2007_2015_tcdf.csv')

In [190]:
df_lv.columns.equals(df_lv.columns)

True

In [383]:
column_index = df_lv_2007_2015_scaled.columns.get_loc('QOR')
print(column_index)

6

In [192]:
10,1,0
17,4,1
5,4,0
12,5,0
17,6,3
13,6,2
22,11,0
12,13,0
12,17,3
12,18,0
17,20,2
17,21,0
17,23,0

(20, 24, 3)

In [193]:
df_lv

,TIME_PERIOD,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,REST,CO2,EBSG,FDI,GGFC,LBGD,PC,ARP,PS
7,2007,9775.522707,11.319401,22.75,71.978571,25.000000,5.390000,3.110000,10.56,424.000000,29.615,8.9143,-20.108026,9.22,18.600884,0.134663,-7.7,21.2,2.20
8,2008,10725.051692,-2.368037,22.84,71.978571,67.000000,5.590000,2.850000,13.65,-338.000000,29.811,8.4787,-13.299099,4.20,20.701069,-3.172711,-13.3,25.9,2.18
9,2009,8629.945617,-14.642313,21.52,66.300000,34.000000,5.480000,3.190000,33.43,-780.000000,34.317,7.7519,-2.039931,-0.58,19.573897,-7.966839,-19.8,26.4,2.14
10,2010,8447.759415,-1.635144,20.86,63.900000,-62.000000,5.440000,3.110000,36.24,1140.000000,30.375,8.8799,-2.131443,2.02,18.789970,-8.375610,-21.9,20.9,2.10
11,2011,9281.534430,4.929580,21.42,66.100000,-5.000000,5.170000,3.100000,31.07,-641.000000,33.478,8.2334,-6.131271,5.72,19.255704,-3.827185,-14.5,19.0,2.06
12,2012,10374.147811,8.644500,21.42,67.900000,20.000000,5.270000,3.160000,28.56,-201.000000,35.709,8.0274,-5.548474,3.99,17.988056,-1.006694,-10.3,19.2,2.03
13,2013,10909.112726,3.195452,20.82,69.500000,32.000000,5.390000,3.000000,23.24,-72.000000,37.037,7.7794,-4.525224,3.39,18.281111,-0.749488,-11.1,19.4,2.01
14,2014,11430.790829,3.060974,19.62,70.600000,-122.000000,5.350000,3.090000,19.59,-55.000000,38.629,7.5739,-2.898049,3.45,18.488335,-1.357478,-7.7,21.2,1.99
15,2015,12007.048703,4.636452,19.78,72.500000,33.000000,5.370000,3.310000,16.32,44.000000,37.538,7.6480,-1.188889,3.09,18.709564,-1.740458,-8.7,22.5,1.98
16,2016,12502.021651,3.493186,19.17,73.000000,-41.000000,5.100000,3.200000,17.27,-165.000000,37.138,7.4806,0.526321,1.24,18.476344,-0.184948,-9.6,21.8,1.96
17,2017,13395.368666,4.319359,19.78,74.600000,-5.000000,5.200000,3.000000,16.97,-62.000000,39.008,7.4321,-0.434095,4.05,18.670316,0.031418,-8.1,22.1,1.94
18,2018,14608.666887,5.125604,19.35,76.800000,-4.000000,5.500000,3.500000,12.19,536.000000,40.019,8.1079,-0.494458,1.32,18.535268,-0.633990,-7.5,23.3,1.93
19,2019,15449.190677,1.377746,19.60,77.300000,-4.000000,5.700000,3.600000,12.41,-152.000000,40.929,7.9078,-0.217946,3.37,19.808901,-0.746684,-6.4,22.9,1.91
20,2020,15377.597610,-2.789964,20.33,76.900000,11.000000,5.380769,3.170769,14.87,-649.000000,42.132,7.2771,1.435286,2.81,20.889693,-3.934799,-7.6,21.6,1.90
21,2021,17131.308205,7.848196,21.09,75.300000,11.000000,5.380769,3.170769,14.78,-69.357143,42.112,7.5304,-3.174062,9.78,21.731000,-6.941226,-9.3,23.4,1.88
22,2022,19208.258774,2.083420,20.72,77.000000,-0.666667,5.380769,3.170769,15.27,-69.357143,43.786,6.9268,-4.888329,3.20,20.486894,-4.914751,3.9,22.5,1.88

In [194]:
df_lv_2016_2022 = df_lv.loc[16:22]

In [195]:
lv_context_2016_2022 = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Latvia_2016_2022.csv")

lv_context_2016_2022 = lv_context_2016_2022[["TIME_PERIOD", 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT']]
lv_context_2016_2022 = lv_context_2016_2022.loc[0:6]

In [196]:
lv_context_2016_2022

   TIME_PERIOD   ROL    GE   COC    RQ        SSB         PT
0         2016  0.93  0.97  0.40  1.07  94.107515  89.093857
1         2017  0.90  0.87  0.50  1.14  94.112781  90.040534
2         2018  0.92  1.00  0.30  1.13  94.113949  90.040534
3         2019  0.98  1.07  0.48  1.18  94.116764  89.990298
4         2020  0.92  0.84  0.69  1.18  94.114435  89.188135
5         2021  0.95  0.83  0.72  1.22  94.117799  89.670672
6         2022  0.92  0.69  0.69  1.17  94.117799  89.670672

In [197]:
lv_eu_payments_2016_2022 = lv_eu_payments[lv_eu_payments['Programming_Period'] == '2014-2020'].groupby('Year')['EU_Payment_annual'].sum().reset_index()
lv_eu_payments_2016_2022 = lv_eu_payments_2016_2022.rename({"Year":"TIME_PERIOD"}, axis=1)
lv_eu_payments_2016_2022 = lv_eu_payments_2016_2022.loc[1:7]
lv_eu_payments_2016_2022

   TIME_PERIOD  EU_Payment_annual
1         2016          155094196
2         2017          160481758
3         2018          342377779
4         2019          728058421
5         2020          591900430
6         2021          564767158
7         2022          578719541

In [198]:

df_lv_2016_2022 = pd.merge(df_lv_2016_2022, lv_context_2016_2022, on='TIME_PERIOD', how='outer')

df_lv_2016_2022 = pd.merge(df_lv_2016_2022, lv_eu_payments_2016_2022, on='TIME_PERIOD', how='outer')

df_lv_2016_2022['EUPC'] = df_lv_2016_2022['EU_Payment_annual'] / (df_lv_2016_2022['PS'] * 1000000)

df_lv_2016_2022 = df_lv_2016_2022.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [199]:
df_lv_2016_2022.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/lv_2016_2022_bn.csv')

In [200]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_lv_2016_2022.values)

df_lv_2016_2022_scaled = pd.DataFrame(scaled_features, index=df_lv_2016_2022.index, columns=df_lv_2016_2022.columns)

In [201]:
df_lv_2016_2022_scaled.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/lv_2016_2022_tcdf.csv')

In [384]:
df_lv_2016_2022_scaled

,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,REST,...,LBGD,PC,ARP,ROL,GE,COC,RQ,SSB,PT,EUPC
0,-1.378611,0.138313,-1.248792,-1.915588,-2.248362,-1.538948,-0.300871,1.333990,-0.234275,-1.746946,...,0.893983,-0.748394,-1.078830,-0.059131,0.630500,-0.926592,-1.932470,-2.060814,-1.572961e+00,-1.387164
1,-0.950943,0.405411,-0.337281,-0.837468,-0.020627,-0.984317,-1.322484,1.170454,0.087901,-0.837990,...,0.978448,-0.400689,-0.625721,-1.300887,-0.218250,-0.264741,-0.354286,-0.492417,1.008607e+00,-1.355048
2,-0.370106,0.666067,-0.979821,0.644947,0.041254,0.679575,1.231549,-1.435227,1.958397,-0.346570,...,0.718687,-0.261607,1.186713,-0.473050,0.885125,-1.588444,-0.579741,-0.144667,1.008607e+00,-0.508762
3,0.032274,-0.545600,-0.606251,0.981859,0.041254,1.788836,1.742356,-1.315300,-0.193612,0.095756,...,0.674694,-0.006623,0.582568,2.010462,1.479250,-0.397111,0.547533,0.693673,8.716146e-01,1.312833
4,-0.001999,-1.893003,0.484574,0.712329,0.969477,0.018285,-0.450183,0.025699,-1.748188,0.680502,...,-0.569874,-0.284787,-1.380902,-0.473050,-0.472875,0.992777,0.547533,0.000000,-1.315868e+00,0.690191
5,0.837548,1.546269,1.620227,-0.365791,0.969477,0.018285,-0.450183,-0.023362,0.064888,0.670781,...,-1.743514,-0.678853,1.337749,0.768706,-0.557750,1.191333,1.449352,1.002113,3.875269e-14,0.590805
6,1.831837,-0.317458,1.067343,0.779712,0.247526,0.018285,-0.450183,0.243747,0.064888,1.484467,...,-0.952424,2.380951,-0.021577,-0.473050,-1.746000,0.992777,0.322078,1.002113,3.875269e-14,0.657144

In [202]:
column_index = df_lv_2016_2022_scaled.columns.get_loc('SSB')
print(column_index)

21

In [203]:
5,15,1
5,17,1
11,23,0

(11, 23, 0)

===================================================================================================================

In [204]:
df_ee = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/Estonia.csv")

df_ee = df_ee.loc[6:22]

df_ee

,Unnamed: 0,REF_AREA_LABEL,TIME_PERIOD,HI,LF,UR,URFF,YUA,FDI,QOR,...,NINA,LBGD,PA,CO2,EMP,LTU,FEM,REST,PC,ARP
6,6,Estonia,2006,NaN,0.69,5.91,5.59,12.12,10.33,3.68,...,3.219881,3.066797,36.0,19.4325,:,:,NaN,NaN,-5.8,18.3
7,7,Estonia,2007,NaN,0.69,4.59,3.76,10.10,13.51,3.78,...,3.837102,3.169094,44.0,23.0337,:,:,:,17.139,-3.3,19.4
8,8,Estonia,2008,NaN,0.70,5.45,5.14,12.03,8.12,4.00,...,4.286809,-2.025402,62.0,20.8808,:,:,:,18.811,-2.0,19.5
9,9,Estonia,2009,NaN,0.69,13.55,10.30,27.41,9.51,4.22,...,4.371720,-2.239512,76.0,17.4389,70.5,3.7,69.9,23.009,-1.8,19.7
10,10,Estonia,2010,NaN,0.68,16.71,14.09,32.94,13.28,4.53,...,2.214769,-0.609832,84.0,22.2156,67.6,7.5,67.4,24.575,-2.7,15.8
11,11,Estonia,2011,NaN,0.69,12.33,11.58,22.39,4.80,4.49,...,2.237984,0.526226,62.0,22.3356,71.0,7.0,68.6,25.515,-3.3,17.5
12,12,Estonia,2012,NaN,0.68,10.02,9.10,20.86,7.69,4.22,...,4.377116,-0.123296,20.0,21.2301,73.1,5.4,71.1,25.586,-3.8,17.5
13,13,Estonia,2013,5.43,0.68,8.63,8.15,18.70,4.31,4.20,...,3.191025,0.273440,25.0,23.6366,74.1,3.8,71.6,25.356,-3.3,18.6
14,14,Estonia,2014,NaN,0.68,7.35,6.81,14.98,6.59,4.39,...,3.643242,0.975175,44.0,22.7514,75.0,3.3,71.9,26.130,-1.9,21.8
15,15,Estonia,2015,5.43,0.68,6.41,6.32,14.34,-3.07,4.53,...,3.682012,0.119938,30.0,21.0222,76.7,2.4,73.7,28.987,0.8,21.6
16,16,Estonia,2016,5.52,0.69,6.88,6.16,14.13,3.77,4.70,...,3.286678,-0.181622,29.0,20.5878,77.0,2.2,73.7,29.232,-0.2,21.7
17,17,Estonia,2017,5.61,0.70,5.81,5.24,12.18,6.32,4.70,...,NaN,-0.229889,37.0,21.9647,79.2,2.0,76.8,29.538,2.7,21.0
18,18,Estonia,2018,5.74,0.70,5.41,5.26,12.08,4.08,4.70,...,NaN,-0.760256,24.0,23.6488,79.7,1.3,76.8,29.970,4.3,21.9
19,19,Estonia,2019,5.89,0.70,4.51,4.93,11.62,9.77,4.70,...,NaN,0.196333,31.0,15.4629,80.5,0.9,77.5,31.730,3.1,21.7
20,20,Estonia,2020,6.19,0.70,6.96,6.77,18.42,12.01,NaN,...,NaN,-5.358715,21.0,12.1329,79.1,1.2,76.9,30.069,0.8,20.7
21,21,Estonia,2021,6.34,0.70,6.18,5.54,16.62,20.31,NaN,...,NaN,-2.149653,25.0,12.9256,79.3,1.6,77.5,37.342,1.3,20.6
22,22,Estonia,2022,6.46,0.74,5.57,5.06,18.39,4.89,NaN,...,NaN,-0.692318,NaN,15.0182,81.9,1.3,80.4,38.542,25.3,22.8

In [205]:
df_ee = df_ee.copy()
# df_ee['LFG'] = df_ee['LF'].diff()
# df_ee['EPFRG'] = df_ee['EPFR'].diff()
df_ee['PAG'] = df_ee['PA'].diff()
df_ee['GGAG'] = df_ee['GGA'].diff()
df_ee = df_ee.drop(6)

In [206]:
# df_ee = df_ee.drop(["Unnamed: 0", "REF_AREA_LABEL", "HI", "OCTB", "NINA", "LF", "EPFR", "GGA", "EIA", "GDP", "UR", "URFF", "YUA", "P014", "P65"], axis=1)

In [207]:
df_ee = df_ee[["TIME_PERIOD", "GDPC", "GDPCG", "VABI", "EMP", "PAG", "QOA", "QOR", "YUA", "GGAG", "REST", "CO2",
             "EBSG", "FDI", "GGFC", "LBGD", "PC", "ARP", "PS"]]

In [208]:
df_ee["EMP"] = df_ee["EMP"].replace(':', np.nan)
# df_ee["LTU"] = df_ee["LTU"].replace(':', np.nan)
# df_ee["FEM"] = df_ee["FEM"].replace(':', np.nan)

In [209]:
missing_values(df_ee)

TIME_PERIOD - 0 - 0.0 %
GDPC - 0 - 0.0 %
GDPCG - 0 - 0.0 %
VABI - 0 - 0.0 %
EMP - 2 - 12.5 %
PAG - 1 - 6.2 %
QOA - 3 - 18.8 %
QOR - 3 - 18.8 %
YUA - 0 - 0.0 %
GGAG - 2 - 12.5 %
REST - 0 - 0.0 %
CO2 - 0 - 0.0 %
EBSG - 0 - 0.0 %
FDI - 0 - 0.0 %
GGFC - 0 - 0.0 %
LBGD - 0 - 0.0 %
PC - 0 - 0.0 %
ARP - 0 - 0.0 %
PS - 0 - 0.0 %

In [210]:
df_ee = df_ee.copy()
fill_with_mode(df_ee, ["QOR", "QOA"])

In [211]:
fill_with_mean(df_ee, ["EMP", "PAG", "GGAG"])

In [212]:
ee_context_2007_2015 = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Estonia_2007_2015.csv")

In [213]:
ee_context_2007_2015 = ee_context_2007_2015[["TIME_PERIOD", 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT']]
ee_context_2007_2015 = ee_context_2007_2015.loc[1:9]
ee_context_2007_2015

   TIME_PERIOD   ROL    GE   COC    RQ        SSB         PT
1         2007  1.12  1.01  0.97  1.32  90.390419  84.956550
2         2008  1.16  1.16  0.95  1.39  90.095031  85.314565
3         2009  1.12  1.00  1.00  1.39  90.413783  85.595289
4         2010  1.15  1.08  0.99  1.39  90.450256  85.471377
5         2011  1.18  1.07  1.05  1.39  90.268246  85.244063
6         2012  1.15  0.95  1.09  1.41  90.355464  84.948179
7         2013  1.19  0.97  1.18  1.44  90.522325  84.948179
8         2014  1.37  1.01  1.30  1.67  90.627827  84.238087
9         2015  1.30  1.04  1.26  1.66  90.390419  84.410977

In [214]:
ee_eu_payments = eu_payments[eu_payments['Country'] == 'EE'].copy()

ee_eu_payments['EU_Payment_annual'] = pd.to_numeric(ee_eu_payments['EU_Payment_annual'].str.replace(',', ''))

ee_eu_payments_2007_2015 = ee_eu_payments[ee_eu_payments['Programming_Period'] == '2007-2013'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

ee_eu_payments_2007_2015  = ee_eu_payments_2007_2015.rename({"Year":"TIME_PERIOD"}, axis=1)

ee_eu_payments_2007_2015 = ee_eu_payments_2007_2015.loc[0:8]

In [215]:
ee_eu_payments_2007_2015

   TIME_PERIOD  EU_Payment_annual
0         2007           73827848
1         2008          113621099
2         2009          474611080
3         2010          527916818
4         2011          239059742
5         2012          658762433
6         2013          678590982
7         2014          376167074
8         2015           90729480

In [216]:
df_ee_2007_2015 = df_ee.loc[7:15]

df_ee_2007_2015 = pd.merge(df_ee_2007_2015, ee_context_2007_2015, on='TIME_PERIOD', how='outer')

df_ee_2007_2015 = pd.merge(df_ee_2007_2015, ee_eu_payments_2007_2015, on='TIME_PERIOD', how='outer')

df_ee_2007_2015['EUPC'] = df_ee_2007_2015['EU_Payment_annual'] / (df_ee_2007_2015['PS'] * 1000000)

df_ee_2007_2015 = df_ee_2007_2015.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [217]:
df_ee_2007_2015.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/ee_2007_2015_bn.csv', index=True)

In [218]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_ee_2007_2015.values)

df_ee_2007_2015_scaled = pd.DataFrame(scaled_features, index=df_ee_2007_2015.index, columns=df_ee_2007_2015.columns)

In [219]:
df_ee_2007_2015_scaled.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/ee_2007_2015_tcdf.csv')

In [220]:
df_lv.columns.equals(df_ee.columns)

True

In [395]:
column_index = df_ee_2007_2015_scaled.columns.get_loc('SSB')
print(column_index)

21

In [222]:
13,2,0
14,12,2
13,14,1
17,20,3
11,21,2
14,21,0

(14, 19, 2)

In [223]:
df_ee_2016_2022 = df_ee.loc[16:22]

In [224]:
df_ee_2016_2022

,TIME_PERIOD,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,REST,CO2,EBSG,FDI,GGFC,LBGD,PC,ARP,PS
16,2016,16863.602095,3.063011,23.23,77.0,-1.000000,4.5,4.7,14.13,1404.000000,29.232,20.5878,3.207492,3.77,19.332394,-0.181622,-0.2,21.7,1.32
17,2017,18457.882440,5.506857,23.18,79.2,8.000000,5.1,4.7,12.18,902.000000,29.538,21.9647,3.975466,6.32,18.874982,-0.229889,2.7,21.0,1.32
18,2018,19999.192119,3.339409,23.29,79.7,-13.000000,4.6,4.7,12.08,-1081.000000,29.970,23.6488,2.315765,4.08,18.762851,-0.760256,4.3,21.9,1.32
19,2019,21457.612416,3.341964,22.31,80.5,7.000000,4.6,4.7,11.62,-5643.000000,31.730,15.4629,3.686161,9.77,19.081933,0.196333,3.1,21.7,1.33
20,2020,20954.364802,-3.075480,21.77,79.1,-10.000000,4.6,4.7,18.42,-2976.000000,30.069,12.1329,-1.083534,12.01,20.508689,-5.358715,0.8,20.7,1.33
21,2021,23634.746178,7.040926,22.65,79.3,4.000000,4.6,4.7,16.62,-642.928571,37.342,12.9256,-1.302298,20.31,19.815687,-2.149653,1.3,20.6,1.33
22,2022,27017.885739,-1.268031,23.34,81.9,-0.733333,4.6,4.7,18.39,-642.928571,38.542,15.0182,-1.236321,4.89,19.291309,-0.692318,25.3,22.8,1.35

In [225]:
ee_context_2016_2022 = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Estonia_2016_2022.csv")

ee_context_2016_2022 = ee_context_2016_2022[["TIME_PERIOD", 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT']]

ee_context_2016_2022

   TIME_PERIOD   ROL    GE   COC    RQ        SSB         PT
0         2016  1.19  1.05  1.23  1.69  94.560514  89.528500
1         2017  1.25  1.07  1.20  1.63  94.623643  89.378009
2         2018  1.20  1.15  1.47  1.54  94.652164  89.609849
3         2019  1.24  1.14  1.53  1.58  94.752132  89.609849
4         2020  1.34  1.30  1.58  1.53  94.661131  89.909583
5         2021  1.39  1.34  1.51  1.55  94.689166  89.331854
6         2022  1.43  1.34  1.54  1.56  94.689166  89.331854

In [226]:
ee_eu_payments_2016_2022 = ee_eu_payments[ee_eu_payments['Programming_Period'] == '2014-2020'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

ee_eu_payments_2016_2022  = ee_eu_payments_2016_2022.rename({"Year":"TIME_PERIOD"}, axis=1)

ee_eu_payments_2016_2022 = ee_eu_payments_2016_2022.loc[2:8]

ee_eu_payments_2016_2022

   TIME_PERIOD  EU_Payment_annual
2         2016          192914599
3         2017          284117863
4         2018          435232587
5         2019          500627021
6         2020          511141090
7         2021          570113413
8         2022          546809658

In [227]:
df_ee_2016_2022 = pd.merge(df_ee_2016_2022, ee_context_2016_2022, on='TIME_PERIOD', how='outer')

df_ee_2016_2022 = pd.merge(df_ee_2016_2022, ee_eu_payments_2016_2022, on='TIME_PERIOD', how='outer')

df_ee_2016_2022['EUPC'] = df_ee_2016_2022['EU_Payment_annual'] / (df_ee_2016_2022['PS'] * 1000000)

df_ee_2016_2022 = df_ee_2016_2022.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [228]:
df_ee_2016_2022.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/ee_2016_2022_bn.csv')

In [229]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_ee_2016_2022.values)

df_ee_2016_2022_scaled = pd.DataFrame(scaled_features, index=df_ee_2016_2022.index, columns=df_ee_2016_2022.columns)

In [230]:
df_ee_2016_2022_scaled.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/ee_2016_2022_tcdf.csv')

In [401]:
column_index = df_ee_2016_2022_scaled.columns.get_loc('LBGD')
print(column_index)

14

In [232]:
8,3,1
16,14,0
11,20,1

(14, 19, 1)

===================================================================================================================

In [233]:
df_fi = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/Finland.csv")

df_fi = df_fi.loc[6:22]

df_fi

,Unnamed: 0,REF_AREA_LABEL,TIME_PERIOD,HI,LF,UR,URFF,YUA,FDI,QOR,...,NINA,LBGD,PA,CO2,EMP,LTU,FEM,REST,PC,ARP
6,6,Finland,2006,NaN,2.72,8.94,9.14,25.77,2.14,5.45,...,1.520488,4.305193,1816.0,69.8556,:,:,NaN,NaN,4.1,12.6
7,7,Finland,2007,NaN,2.68,6.85,7.19,16.43,8.57,5.64,...,1.650190,5.292982,1804.0,68.0689,:,:,:,29.561,4.4,13.0
8,8,Finland,2008,NaN,2.72,6.37,6.69,16.34,6.79,5.84,...,1.635209,4.569814,1799.0,59.8279,:,:,:,31.071,4.9,13.6
9,9,Finland,2009,NaN,2.69,8.25,7.57,21.38,-3.48,5.89,...,1.816013,-1.860401,1806.0,57.0808,72.6,1.7,71.5,31.045,4.7,13.8
10,10,Finland,2010,NaN,2.67,8.39,7.64,21.29,4.90,5.86,...,1.599064,-2.369424,1731.0,65.8469,71.9,2.5,70.3,32.166,4.4,13.1
11,11,Finland,2011,NaN,2.69,7.78,7.10,19.93,-2.18,5.83,...,1.606380,-0.488730,1650.0,58.2223,72.7,2.2,70.7,32.532,4.8,13.7
12,12,Finland,2012,NaN,2.70,7.69,7.05,18.87,1.92,6.09,...,1.762605,-1.104413,1698.0,52.3267,73.0,2.1,71.3,34.222,4.7,13.2
13,13,Finland,2013,7.39,2.69,8.19,7.52,19.82,-1.83,6.10,...,1.773043,-1.825088,1596.0,53.3313,72.5,2.1,71.0,36.630,4.5,11.8
14,14,Finland,2014,NaN,2.68,8.66,7.95,20.45,6.42,5.87,...,1.721723,-2.267616,1419.0,49.4416,72.2,2.4,71.2,38.633,3.8,12.8
15,15,Finland,2015,7.41,2.69,9.38,8.84,22.30,7.54,5.78,...,1.472224,-1.810725,1289.0,45.9758,71.8,2.9,70.7,39.230,2.8,12.4
16,16,Finland,2016,7.41,2.69,8.82,8.58,20.06,2.19,5.70,...,1.541867,-1.298460,1260.0,48.8071,72.4,2.9,70.8,38.943,2.9,11.6
17,17,Finland,2017,7.47,2.71,8.64,8.39,20.04,6.66,5.40,...,NaN,-0.443691,1390.0,46.0759,73.2,2.6,71.3,40.857,1.8,11.5
18,18,Finland,2018,7.63,2.75,7.36,7.30,16.96,-3.84,5.30,...,NaN,-0.006899,1387.0,47.4392,75.3,2.0,73.4,41.185,0.9,12.0
19,19,Finland,2019,7.77,2.75,6.70,6.17,17.13,6.10,5.30,...,NaN,0.316119,1321.0,44.1412,76.2,1.5,74.5,42.807,1.3,11.6
20,20,Finland,2020,7.84,2.74,7.76,7.49,21.19,-0.94,NaN,...,NaN,-5.502841,1588.0,39.4740,75.5,1.5,73.8,43.939,1.5,12.2
21,21,Finland,2021,7.82,2.80,7.62,7.04,17.06,8.01,NaN,...,NaN,-2.322281,1557.0,39.3124,76.8,1.8,75.8,42.819,2.6,10.8
22,22,Finland,2022,7.80,2.85,6.72,6.37,14.14,4.67,NaN,...,NaN,-0.031939,NaN,37.1238,78.4,1.5,77.8,47.740,2.8,12.7

In [234]:
df_fi = df_fi.copy()
df_fi['LFG'] = df_fi['LF'].diff()
# df_fi['EPFRG'] = df_fi['EPFR'].diff()
df_fi['GGAG'] = df_fi['GGA'].diff()
df_fi['PAG'] = df_fi['PA'].diff()
df_fi = df_fi.drop(6)

In [235]:
# df_fi = df_fi.drop(["Unnamed: 0", "REF_AREA_LABEL", "HI", "OCTB", "NINA", "LF", "EPFR", "GGA", "EIA", "GDP", "UR", "URFF", "YUA", "P014", "P65"], axis=1)

In [236]:
df_fi = df_fi[["TIME_PERIOD", "GDPC", "GDPCG", "VABI", "EMP", "PAG", "QOA", "QOR", "YUA", "GGAG", "REST", "CO2",
             "EBSG", "FDI", "GGFC", "LBGD", "PC", "ARP", "PS"]]

In [237]:
df_fi["EMP"] = df_fi["EMP"].replace(':', np.nan)
# df_fi["LTU"] = df_fi["LTU"].replace(':', np.nan)
# df_fi["FEM"] = df_fi["FEM"].replace(':', np.nan)

In [238]:
missing_values(df_fi)

TIME_PERIOD - 0 - 0.0 %
GDPC - 0 - 0.0 %
GDPCG - 0 - 0.0 %
VABI - 0 - 0.0 %
EMP - 2 - 12.5 %
PAG - 1 - 6.2 %
QOA - 3 - 18.8 %
QOR - 3 - 18.8 %
YUA - 0 - 0.0 %
GGAG - 2 - 12.5 %
REST - 0 - 0.0 %
CO2 - 0 - 0.0 %
EBSG - 0 - 0.0 %
FDI - 0 - 0.0 %
GGFC - 0 - 0.0 %
LBGD - 0 - 0.0 %
PC - 0 - 0.0 %
ARP - 0 - 0.0 %
PS - 0 - 0.0 %

In [239]:
df_fi = df_fi.copy()
fill_with_mode(df_fi, ["QOR", "QOA"])

fill_with_mean(df_fi, ["EMP", "PAG", "GGAG"])

In [240]:
fi_context_2007_2015 = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Finland_2007_2015.csv")

fi_context_2007_2015 = fi_context_2007_2015[["TIME_PERIOD", 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT']]

fi_context_2007_2015

   TIME_PERIOD   ROL    GE   COC    RQ        SSB         PT
0         2007  1.90  1.97  2.39  1.55  92.336906  68.824462
1         2008  1.91  2.04  2.32  1.61  92.303567  68.783401
2         2009  1.96  2.23  2.24  1.81  92.332122  68.783401
3         2010  1.96  2.22  2.15  1.87  92.345580  76.827451
4         2011  1.94  2.24  2.19  1.81  92.292541  80.247713
5         2012  1.94  2.21  2.23  1.82  92.333827  88.839006
6         2013  1.96  2.18  2.20  1.84  92.363760  88.088291
7         2014  2.12  2.03  2.16  1.88  92.362866  88.454135
8         2015  2.05  1.84  2.22  1.83  92.360986  88.355975

In [241]:
fi_eu_payments = eu_payments[eu_payments['Country'] == 'FI'].copy()

fi_eu_payments['EU_Payment_annual'] = pd.to_numeric(fi_eu_payments['EU_Payment_annual'].str.replace(',', ''))

fi_eu_payments_2007_2015 = fi_eu_payments[fi_eu_payments['Programming_Period'] == '2007-2013'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

fi_eu_payments_2007_2015  = fi_eu_payments_2007_2015.rename({"Year":"TIME_PERIOD"}, axis=1)

fi_eu_payments_2007_2015 = fi_eu_payments_2007_2015.loc[0:8]

fi_eu_payments_2007_2015 = fi_eu_payments_2007_2015.rename({"Year":"TIME_PERIOD"}, axis=1)

In [242]:
fi_eu_payments_2007_2015

   TIME_PERIOD  EU_Payment_annual
0         2007           31919318
1         2008           47878976
2         2009          184114804
3         2010          147719657
4         2011          241478104
5         2012          220369451
6         2013          334713129
7         2014          215151249
8         2015           92469029

In [243]:
df_fi_2007_2015 = df_fi.loc[7:15]

In [244]:
df_fi_2007_2015 = pd.merge(df_fi_2007_2015, fi_context_2007_2015, on='TIME_PERIOD', how='outer')

df_fi_2007_2015 = pd.merge(df_fi_2007_2015, fi_eu_payments_2007_2015, on='TIME_PERIOD', how='outer')

df_fi_2007_2015['EUPC'] = df_fi_2007_2015['EU_Payment_annual'] / (df_fi_2007_2015['PS'] * 1000000)

df_fi_2007_2015 = df_fi_2007_2015.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [245]:
df_fi_2007_2015

,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,REST,...,LBGD,PC,ARP,ROL,GE,COC,RQ,SSB,PT,EUPC
0,35369.427763,4.865721,30.67,73.892857,-12.0,6.31,5.64,16.43,-2010.0,29.561,...,5.292982,4.4,13.0,1.90,1.97,2.39,1.55,92.336906,68.824462,6.033898
1,36559.083931,0.316321,29.57,73.892857,-5.0,6.43,5.84,16.34,-8272.0,31.071,...,4.569814,4.9,13.6,1.91,2.04,2.32,1.61,92.303567,68.783401,9.016756
2,34039.968375,-8.514605,25.66,72.600000,7.0,6.33,5.89,21.38,-3519.0,31.045,...,-1.860401,4.7,13.8,1.96,2.23,2.24,1.81,92.332122,68.783401,34.478428
3,35080.114078,2.697377,26.19,71.900000,-75.0,6.15,5.86,21.29,8024.0,32.166,...,-2.369424,4.4,13.1,1.96,2.22,2.15,1.87,92.345580,76.827451,27.559638
4,36682.446617,1.916853,25.04,72.700000,-81.0,6.16,5.83,19.93,-7687.0,32.532,...,-0.488730,4.8,13.7,1.94,2.24,2.19,1.81,92.292541,80.247713,44.801132
5,37011.280629,-1.990291,23.36,73.000000,48.0,6.20,6.09,18.87,-5657.0,34.222,...,-1.104413,4.7,13.2,1.94,2.21,2.23,1.82,92.333827,88.839006,40.733725
6,37414.607025,-1.434902,23.30,72.500000,-102.0,6.22,6.10,19.82,770.0,36.630,...,-1.825088,4.5,11.8,1.96,2.18,2.20,1.84,92.363760,88.088291,61.528149
7,37691.943183,-0.888802,23.06,72.200000,-177.0,6.17,5.87,20.45,-4059.0,38.633,...,-2.267616,3.8,12.8,2.12,2.03,2.16,1.88,92.362866,88.454135,39.404991
8,38359.487336,0.136128,23.30,71.800000,-130.0,6.05,5.78,22.30,-3477.0,39.230,...,-1.810725,2.8,12.4,2.05,1.84,2.22,1.83,92.360986,88.355975,16.873910

In [246]:
df_fi_2007_2015.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/fi_2007_2015_bn.csv')

In [247]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_fi_2007_2015.values)

df_fi_2007_2015_scaled = pd.DataFrame(scaled_features, index=df_fi_2007_2015.index, columns=df_fi_2007_2015.columns)

In [248]:
df_fi_2007_2015_scaled.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/fi_2007_2015_tcdf.csv')

In [249]:
df_ee.columns.equals(df_fi.columns)

True

In [408]:
column_index = df_fi_2007_2015_scaled.columns.get_loc('GGFC')
print(column_index)

13

In [251]:
19,0,0
19,6,0
23,12,0
19,13,0

(10, 23, 1)

In [252]:
df_fi_2016_2022 = df_fi.loc[16:22]

In [253]:
df_fi_2016_2022

,TIME_PERIOD,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,REST,CO2,EBSG,FDI,GGFC,LBGD,PC,ARP,PS
16,2016,39254.796323,2.277544,23.48,72.4,-29.000000,6.2,5.7,20.06,2692.000000,38.943,48.8071,-1.055550,2.19,23.868773,-1.298460,2.9,11.6,5.50
17,2017,40794.711317,3.061232,24.47,73.2,130.000000,6.3,5.4,20.04,-2859.000000,40.857,46.0759,0.393848,6.66,22.949098,-0.443691,1.8,11.5,5.51
18,2018,42045.861455,1.058843,24.11,75.3,-3.000000,6.2,5.3,16.96,1157.000000,41.185,47.4392,-0.845174,-3.84,23.055130,-0.006899,0.9,12.0,5.52
19,2019,43197.214723,1.238121,24.15,76.2,-66.000000,6.3,5.3,17.13,-3437.000000,42.807,44.1412,0.672486,6.10,23.318576,0.316119,1.3,11.6,5.52
20,2020,42749.825799,-2.630999,24.23,75.5,267.000000,6.2,5.3,21.19,-5023.000000,43.939,39.4740,0.244091,-0.94,24.420548,-5.502841,1.5,12.2,5.53
21,2021,44895.007541,2.463731,24.23,76.8,-31.000000,6.2,5.3,17.06,-2382.642857,42.819,39.3124,0.054268,8.01,24.795388,-2.322281,2.6,10.8,5.54
22,2022,47899.554112,0.489395,25.18,78.4,-17.266667,6.2,5.3,14.14,-2382.642857,47.740,37.1238,-1.992973,4.67,24.149022,-0.031939,2.8,12.7,5.56

In [254]:
fi_context_2016_2022 = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Finland_2016_2022.csv")

fi_context_2016_2022 = fi_context_2016_2022[["TIME_PERIOD", 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT']]

In [255]:
fi_context_2016_2022

   TIME_PERIOD   ROL    GE   COC    RQ        SSB         PT
0         2016  2.01  1.84  2.19  1.81  92.372939  90.309544
1         2017  2.02  1.98  2.16  1.81  92.393599  90.234946
2         2018  2.03  2.01  2.17  1.78  92.410229  90.135735
3         2019  2.01  1.97  2.11  1.84  92.431874  90.641569
4         2020  2.02  1.90  2.17  1.85  92.473111  90.897460
5         2021  2.01  1.92  2.24  1.89  92.615013  90.443851
6         2022  1.96  1.75  2.25  1.78  92.615013  90.443851

In [256]:
fi_eu_payments_2016_2022 = fi_eu_payments[fi_eu_payments['Programming_Period'] == '2014-2020'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

fi_eu_payments_2016_2022  = fi_eu_payments_2016_2022.rename({"Year":"TIME_PERIOD"}, axis=1)

fi_eu_payments_2016_2022 = fi_eu_payments_2016_2022.loc[2:8]

fi_eu_payments_2016_2022

   TIME_PERIOD  EU_Payment_annual
2         2016           99461071
3         2017          137852680
4         2018          185187826
5         2019          155710017
6         2020          146257401
7         2021          226744273
8         2022          181427308

In [257]:
df_fi_2016_2022 = pd.merge(df_fi_2016_2022, fi_context_2016_2022, on='TIME_PERIOD', how='outer')

df_fi_2016_2022 = pd.merge(df_fi_2016_2022, fi_eu_payments_2016_2022, on='TIME_PERIOD', how='outer')

df_fi_2016_2022['EUPC'] = df_fi_2016_2022['EU_Payment_annual'] / (df_fi_2016_2022['PS'] * 1000000)

df_fi_2016_2022 = df_fi_2016_2022.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [258]:
df_fi_2016_2022.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/fi_2016_2022_bn.csv')

In [259]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_fi_2016_2022.values)

df_fi_2016_2022_scaled = pd.DataFrame(scaled_features, index=df_fi_2016_2022.index, columns=df_fi_2016_2022.columns)

In [260]:
df_fi_2016_2022_scaled.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/fi_2016_2022_tcdf.csv')

In [410]:
column_index = df_fi_2016_2022_scaled.columns.get_loc('RQ')
print(column_index)

20

In [262]:
22,20,1

(18, 24, 0)

===================================================================================================================

In [263]:
df_se = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/Sweden.csv")

df_se = df_se.loc[6:22]

df_se

,Unnamed: 0,REF_AREA_LABEL,TIME_PERIOD,HI,LF,UR,URFF,YUA,FDI,QOR,...,NINA,LBGD,PA,CO2,EMP,LTU,FEM,REST,PC,ARP
6,6,Sweden,2006,NaN,4.77,7.07,7.26,21.48,5.22,5.50,...,2.498465,1.972020,2446.0,55.0985,78.4,1.0,NaN,NaN,7.2,12.3
7,7,Sweden,2007,NaN,4.84,6.16,6.47,19.26,9.42,5.65,...,2.407499,3.214195,2527.0,52.8433,79.7,0.8,76.5,43.224,7.6,10.5
8,8,Sweden,2008,NaN,4.90,6.24,6.57,20.21,8.05,5.63,...,2.438199,2.032230,2549.0,51.7125,80.0,0.8,76.7,43.922,8.0,13.5
9,9,Sweden,2009,NaN,4.91,8.35,8.01,25.02,2.06,5.69,...,2.561376,-0.614954,2186.0,46.9207,77.9,1.1,75.1,47.024,9.1,14.4
10,10,Sweden,2010,NaN,4.94,8.61,8.52,24.76,0.13,5.71,...,2.592290,-0.240938,2196.0,52.8835,77.7,1.5,74.4,46.099,8.0,14.8
11,11,Sweden,2011,NaN,5.00,7.80,7.76,22.78,1.22,5.66,...,2.433631,0.015331,2004.0,48.4621,79.0,1.4,76.0,47.632,7.1,15.4
12,12,Sweden,2012,NaN,5.03,7.98,7.71,23.61,0.78,5.58,...,2.455194,-0.914026,2288.0,45.7287,79.1,1.4,76.4,49.403,7.7,15.2
13,13,Sweden,2013,7.48,5.09,8.05,7.89,23.52,0.25,5.52,...,2.346443,-1.371356,2332.0,43.9685,79.4,1.4,76.7,50.153,9.3,16.0
14,14,Sweden,2014,NaN,5.13,7.95,7.70,22.82,-1.05,5.50,...,2.229543,-1.129253,1984.0,42.7792,79.6,1.3,77.2,51.151,10.6,15.6
15,15,Sweden,2015,7.36,5.18,7.43,7.29,20.36,1.95,5.36,...,2.098638,0.377740,2038.0,42.9009,80.1,1.3,77.9,52.220,10.6,16.3
16,16,Sweden,2016,7.29,5.25,6.99,6.59,18.90,3.01,5.30,...,2.109440,1.576112,2032.0,42.4900,80.8,1.2,78.7,52.597,14.5,16.2
17,17,Sweden,2017,7.28,5.33,6.72,6.44,17.88,4.53,5.50,...,NaN,1.661827,1992.0,41.8362,81.4,1.1,79.2,53.390,12.4,15.8
18,18,Sweden,2018,7.31,5.40,6.36,6.24,17.40,-0.13,5.60,...,NaN,1.473616,1838.0,39.6483,82.0,0.9,79.7,53.916,10.8,16.4
19,19,Sweden,2019,7.34,5.46,6.83,6.96,20.09,2.98,5.30,...,NaN,1.471518,1802.0,39.4951,81.7,0.8,79.1,55.785,9.5,17.1
20,20,Sweden,2020,7.36,5.47,8.29,8.28,23.90,3.40,NaN,...,NaN,-2.994377,1764.0,38.0388,80.2,1.0,77.5,60.124,5.0,16.1
21,21,Sweden,2021,7.38,5.52,8.72,9.05,24.60,9.10,NaN,...,NaN,-0.653958,1771.0,40.4785,80.4,1.8,77.7,62.527,7.0,15.7
22,22,Sweden,2022,7.40,5.60,7.39,7.91,21.61,9.30,NaN,...,NaN,0.754005,NaN,37.7526,82.0,1.9,79.1,66.287,6.6,16.0

In [264]:
df_se = df_se.copy()
# df_se['LFG'] = df_se['LF'].diff()
# df_se['EPFRG'] = df_se['EPFR'].diff()
df_se['GGAG'] = df_se['GGA'].diff()
df_se['PAG'] = df_se['PA'].diff()
df_se = df_se.drop(6)

In [265]:
# df_se = df_se.drop(["Unnamed: 0", "REF_AREA_LABEL", "HI", "OCTB", "NINA", "LF", "EPFR", "GGA", "EIA", "GDP",
#                    "UR", "URFF", "YUA", "P014", "P65"], axis=1)

In [266]:
df_se = df_se[["TIME_PERIOD", "GDPC", "GDPCG", "VABI", "EMP", "PAG", "QOA", "QOR", "YUA", "GGAG", "REST", "CO2",
             "EBSG", "FDI", "GGFC", "LBGD", "PC", "ARP", "PS"]]

In [267]:
df_se["EMP"] = df_se["EMP"].replace(':', np.nan)
# df_se["LTU"] = df_se["LTU"].replace(':', np.nan)
# df_se["FEM"] = df_se["FEM"].replace(':', np.nan)

In [268]:
missing_values(df_se)

TIME_PERIOD - 0 - 0.0 %
GDPC - 0 - 0.0 %
GDPCG - 0 - 0.0 %
VABI - 0 - 0.0 %
EMP - 0 - 0.0 %
PAG - 1 - 6.2 %
QOA - 3 - 18.8 %
QOR - 3 - 18.8 %
YUA - 0 - 0.0 %
GGAG - 2 - 12.5 %
REST - 0 - 0.0 %
CO2 - 0 - 0.0 %
EBSG - 0 - 0.0 %
FDI - 0 - 0.0 %
GGFC - 0 - 0.0 %
LBGD - 0 - 0.0 %
PC - 0 - 0.0 %
ARP - 0 - 0.0 %
PS - 0 - 0.0 %

In [269]:
df_se = df_se.copy()
fill_with_mode(df_se, ["QOR"])

fill_with_mean(df_se, ["QOA", "PAG", "GGAG"])

In [270]:
se_context_2007_2015 = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Sweden_2007_2015.csv")

se_context_2007_2015 = se_context_2007_2015[["TIME_PERIOD", 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT']]

se_eu_payments = eu_payments[eu_payments['Country'] == 'SE'].copy()

se_eu_payments['EU_Payment_annual'] = pd.to_numeric(se_eu_payments['EU_Payment_annual'].str.replace(',', ''))

se_eu_payments_2007_2015 = se_eu_payments[se_eu_payments['Programming_Period'] == '2007-2013'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

se_eu_payments_2007_2015  = se_eu_payments_2007_2015.rename({"Year":"TIME_PERIOD"}, axis=1)

se_eu_payments_2007_2015 = se_eu_payments_2007_2015.loc[0:8]

In [271]:
se_eu_payments_2007_2015

   TIME_PERIOD  EU_Payment_annual
0         2007           32521830
1         2008           48782752
2         2009          181387148
3         2010          175258079
4         2011          318545277
5         2012          110051001
6         2013          250369417
7         2014          344723150
8         2015           78408753

In [272]:
df_se_2007_2015 = df_se.loc[7:15]

df_se_2007_2015 = pd.merge(df_se_2007_2015, se_context_2007_2015, on='TIME_PERIOD', how='outer')

df_se_2007_2015 = pd.merge(df_se_2007_2015, se_eu_payments_2007_2015, on='TIME_PERIOD', how='outer')

df_se_2007_2015['EUPC'] = df_se_2007_2015['EU_Payment_annual'] / (df_se_2007_2015['PS'] * 1000000)

df_se_2007_2015 = df_se_2007_2015.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [273]:
df_se_2007_2015.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/se_2007_2015_bn.csv')

In [274]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_se_2007_2015.values)

df_se_2007_2015_scaled = pd.DataFrame(scaled_features, index=df_se_2007_2015.index, columns=df_se_2007_2015.columns)

In [275]:
df_se_2007_2015_scaled.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/se_2007_2015_tcdf.csv')

In [276]:
df_fi.columns.equals(df_se.columns)

True

In [418]:
column_index = df_se_2007_2015_scaled.columns.get_loc('COC')
print(column_index)

19

In [278]:
18,8,1
17,15,2
17,16,0
16,17,0
23,19,0

(19, 21, 1)

In [279]:
se_context_2016_2022 = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Sweden_2016_2022.csv")

se_context_2016_2022 = se_context_2016_2022[["TIME_PERIOD", 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT']]

df_se_2016_2022 = df_se.loc[16:22]

se_eu_payments_2016_2022 = se_eu_payments[se_eu_payments['Programming_Period'] == '2014-2020'].groupby('Year')['EU_Payment_annual'].sum().reset_index()

se_eu_payments_2016_2022  = se_eu_payments_2016_2022.rename({"Year":"TIME_PERIOD"}, axis=1)

se_eu_payments_2016_2022 = se_eu_payments_2016_2022.loc[1:7]

df_se_2016_2022 = pd.merge(df_se_2016_2022, se_context_2016_2022, on='TIME_PERIOD', how='outer')

df_se_2016_2022 = pd.merge(df_se_2016_2022, se_eu_payments_2016_2022, on='TIME_PERIOD', how='outer')

df_se_2016_2022['EUPC'] = df_se_2016_2022['EU_Payment_annual'] / (df_se_2016_2022['PS'] * 1000000)

df_se_2016_2022 = df_se_2016_2022.drop(['TIME_PERIOD', 'PS', 'EU_Payment_annual'], axis=1)

In [280]:
df_se_2016_2022.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/se_2016_2022_bn.csv')

In [281]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(df_se_2016_2022.values)

df_se_2016_2022_scaled = pd.DataFrame(scaled_features, index=df_se_2016_2022.index, columns=df_se_2016_2022.columns)

In [282]:
df_se_2016_2022_scaled.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/se_2016_2022_tcdf.csv')

In [283]:
column_index = df_se_2016_2022_scaled.columns.get_loc('COC')
print(column_index)

19

In [284]:
19,9,3
17,14,0
26,23,1
22,26,0

(22, 26, 0)

,GDPC,GDPCG,VABI,EMP,PAG,QOA,QOR,YUA,GGAG,REST,...,LBGD,PC,ARP,ROL,GE,COC,RQ,SSB,PT,EUPC
0,-1.239145,0.023949,-0.746097,-0.597209,0.800310,-1.404269,-0.615457,-0.654305,1.022072,-1.071009,...,0.689893,1.613453,0.033041,2.049654,0.337764,0.987829,1.224292,0.921582,0.593867,-2.073523
1,-0.917667,-0.256874,-0.469032,0.267714,0.094852,-0.104284,1.107823,-1.041038,1.104027,-0.907891,...,0.743345,0.949090,-0.892105,0.427754,0.863175,0.359211,0.400249,0.965462,-0.887788,-0.763319
2,-0.506535,-0.135354,-0.427472,1.132637,-2.270509,-0.104284,1.969464,-1.223031,-2.130250,-0.799694,...,0.625975,0.442909,0.495614,-0.071292,0.600469,0.987829,1.059484,1.010294,-0.887788,0.838819
3,-0.004276,0.228304,-0.288940,0.700176,0.177847,-1.404269,-0.615457,-0.203116,0.372290,-0.415245,...,0.624667,0.031636,2.114620,0.053469,0.600469,-0.269408,0.400249,-1.465833,-0.887788,0.059960
4,-0.131253,-1.718990,-0.953896,-1.462132,0.136349,1.005702,-0.615457,1.241446,-0.221881,0.477277,...,-2.160303,-1.391999,-0.198246,-0.196054,0.600469,-0.269408,-1.412645,-1.431505,2.069497,0.544264
5,0.934824,1.973560,0.777762,-1.173824,1.070044,1.005702,-0.615457,1.506852,-0.073129,0.971569,...,-0.700798,-0.759272,-1.123392,-1.069385,-0.975763,0.359211,-0.258985,0.000000,0.000000,0.429438
6,1.864052,-0.114595,2.107676,1.132637,-0.008892,1.005702,-0.615457,0.373192,-0.073129,1.744992,...,0.177220,-0.885817,-0.429532,-1.194146,-2.026584,-2.155264,-1.412645,0.000000,0.000000,0.964361