In [123]:
import warnings
from causalnex.structure import StructureModel
warnings.filterwarnings("ignore")  # silence warnings
from causalnex.structure.notears import from_pandas
from causalnex.plots import plot_structure, NODE_STYLE, EDGE_STYLE
from causalnex.network import BayesianNetwork
import pandas as pd
from causalnex.discretiser import Discretiser
import numpy as np
from sklearn.model_selection import train_test_split
from causalnex.structure.notears import from_pandas_lasso
from IPython.display import Image
from causalnex.evaluation import classification_report
from causalnex.evaluation import roc_auc
from causalnex.inference import InferenceEngine
from causalnex.evaluation import classification_report
import copy
import networkx as nx
import turtorial_utils as utils

In [124]:
df_dk = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/dk_bn_no_context.csv")

df_dk = df_dk.drop(["Unnamed: 0"], axis = 1)

df_dk

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,319173.149269,22.06,76.414286,6.45,6.42,7.49,17.747,2.747300,24.277939,5.548536,3.69,5.3,11.7,0.000010,304.029304,1.866582
1,329422.223703,22.61,76.414286,6.44,6.23,9.47,18.543,3.471527,24.986449,3.835619,0.62,6.5,11.8,0.000009,297.632058,2.784574
2,313144.896657,19.85,76.100000,6.43,6.06,13.44,19.948,4.602963,27.815694,-2.111442,1.17,4.2,13.1,0.000009,275.000000,6.041840
3,326784.316443,19.37,74.900000,6.37,6.17,15.55,21.888,6.793833,27.336108,-2.441067,-3.57,4.7,13.3,0.000009,292.972973,7.495645
4,331838.652835,19.85,74.800000,6.32,6.29,16.31,23.389,6.154324,26.540559,-1.887012,3.94,3.6,12.1,0.000008,282.585278,16.993114
5,338534.135302,19.85,74.300000,5.97,5.73,15.77,25.465,5.799405,26.500323,-3.257951,-5.00,4.0,12.0,0.000007,251.520572,6.354829
6,344715.698783,19.73,74.300000,5.64,5.45,14.77,27.173,6.229005,25.928504,-1.181728,0.20,4.4,11.9,0.000007,239.037433,8.319061
7,350893.947080,19.40,74.700000,5.56,5.43,14.20,29.310,6.455948,25.797420,1.252108,1.86,5.8,12.1,0.000006,244.148936,23.835000
8,357211.575191,19.56,75.400000,5.58,5.59,12.15,30.469,6.498281,25.546356,-1.143677,0.61,8.4,12.2,0.000006,257.394366,12.745287
9,366884.878867,20.23,76.000000,5.80,5.70,12.15,31.715,6.035122,24.942915,-0.070663,2.50,7.2,11.9,0.000006,270.855148,0.401479
10,379808.676526,20.42,76.600000,6.10,5.50,12.38,34.387,6.476226,24.449662,1.457031,1.09,5.6,12.4,0.000006,258.680556,10.241162
11,387242.522658,20.58,77.500000,5.80,5.50,10.52,35.159,5.152751,24.381107,0.801500,2.47,4.3,12.7,0.000006,217.962003,6.781235
12,396193.582956,20.64,78.300000,5.80,5.60,10.04,37.020,6.009741,24.204777,4.079333,-1.10,2.9,12.5,0.000005,232.530120,8.928446
13,398976.348406,19.56,77.800000,5.80,5.50,11.59,31.681,5.640362,24.679988,0.081707,0.36,3.0,12.1,0.000005,216.295026,8.953195
14,438387.741596,19.80,79.000000,5.80,5.50,10.81,41.494,6.236804,23.845550,3.868870,4.16,5.7,12.3,0.000005,186.006826,13.806881
15,481824.514568,20.84,80.100000,5.80,5.50,10.53,41.368,9.553789,21.681084,3.323468,7.67,10.0,12.4,0.000005,244.112994,12.717471

In [125]:
dk = pd.DataFrame()
dk = df_dk.copy()
dk['FDI_3'] = dk['FDI'].shift(3)

In [126]:
dk = dk.dropna()

In [127]:
sm = StructureModel()

In [128]:
sm.add_edges_from([
     ('EUPC', 'ARP'),
    ('FDI_3', 'EUPC')
])

In [129]:
sm.edges

OutEdgeView([('EUPC', 'ARP'), ('FDI_3', 'EUPC')])

In [130]:
viz = plot_structure(
    sm,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)

viz.toggle_physics(False)
viz.show("Graphs/fully_connected_dk_1.html")

Graphs/fully_connected_dk_1.html

In [131]:
bn = BayesianNetwork(sm)

In [132]:
discretised_dk = pd.DataFrame(index=dk.index)

for col in dk.columns:
    no_unique = dk[col].nunique()
    
    if no_unique <= 1:
        discretised_dk[col] = 0
    else:
        try:
            discretised_dk[col] = pd.qcut(
                dk[col], 
                q=min(3, no_unique),  
                labels=False,
                duplicates='drop'
            ).astype(int)
        except ValueError:
            discretised_dk[col] = dk[col].rank(method='dense').astype(int) - 1

print("Discretised data:")
print(discretised_dk)

Discretised data:
    GDPC  VABI  EMP  QOA  QOR  YUA  REST  EBSG  GGFC  LBGD  FDI  PC  ARP  \
3      0     0    0    1    2    2     0     2     2     0    0   1    2
4      0     1    0    1    2    2     0     1     2     0    2   0    0
5      0     1    0    1    2    2     0     0     2     0    0   0    0
6      0     0    0    0    0    2     0     1     2     0    0   1    0
7      0     0    0    0    0    1     0     1     1     1    1   2    0
8      1     0    1    0    1    1     1     2     1     0    1   2    1
9      1     1    1    0    2    1     1     0     1     1    2   2    0
10     1     2    1    1    0    1     1     2     0     2    1   1    1
11     1     2    1    0    0    0     2     0     0     1    1   0    2
12     2     2    2    0    1    0     2     0     0     2    0   0    2
13     2     0    2    0    0    0     1     0     1     1    0   0    0
14     2     1    2    0    0    0     2     1     0     2    2   1    1
15     2     2    2    0    0    0     2     2     0     2    2   2    1

    CO2C  PAM  EUPC  FDI_3
3      2    2     0      2
4      2    2     2      1
5      2    1     0      1
6      2    0     0      0
7      1    1     2      2
8      1    1     2      0
9      1    2     0      0
10     1    2     1      1
11     0    0     0      0
12     0    0     1      2
13     0    0     1      1
14     0    0     2      2
15     0    1     1      0

In [133]:
discretised_dk = discretised_dk.reset_index(drop=True)
bn.fit_node_states(discretised_dk)
baseline_auc = utils.get_avg_auc_all_info(discretised_dk, bn)
print(f"Baseline AUC: {baseline_auc}")

Processing fold 0 using 7 cores takes 4.959877252578735 seconds
Processing fold 1 using 7 cores takes 4.786325216293335 seconds
Processing fold 2 using 7 cores takes 4.763715982437134 seconds
Processing fold 3 using 7 cores takes 4.886023283004761 seconds
Processing fold 4 using 7 cores takes 4.677830219268799 seconds
Baseline AUC: 0.37962962962962965

In [134]:
edges_to_add = [('LV', 'EUPC'), ('LV', 'ARP')]
edges_to_remove = [('EUPC', 'ARP')]

bn_with_lv = copy.deepcopy(bn)
bn_with_lv.add_node(
    "LV",
    edges_to_add=edges_to_add,
    edges_to_remove=edges_to_remove,
)

In [135]:
viz = utils.plot_pretty_structure(bn_with_lv.structure, edges_to_highlight=edges_to_add)
viz.show("Graphs/node_added_dk_1.html")

Graphs/node_added_dk_1.html

In [136]:
discretised_dk['LV'] = None
lv_states = [0, 1, 2, 3, 4]

proposed_auc = utils.get_avg_auc_lvs(discretised_dk, bn_with_lv, lv_states)
print(f"AUC from adding LV between 'EUPC' and 'ARP': {proposed_auc}")

Processing fold 0 using 7 cores takes 4.96149206161499 seconds
Processing fold 1 using 7 cores takes 4.897172212600708 seconds
Processing fold 2 using 7 cores takes 4.828013896942139 seconds
Processing fold 3 using 7 cores takes 4.674705982208252 seconds
Processing fold 4 using 7 cores takes 4.693077087402344 seconds
AUC from adding LV between 'EUPC' and 'ARP': 0.3162037037037037

In [137]:
edges_to_add = [('LV', 'FDI_3'), ('LV', 'EUPC')]
edges_to_remove = [('FDI_3', 'EUPC')]

bn_with_lv = copy.deepcopy(bn)
bn_with_lv.add_node(
    "LV",
    edges_to_add=edges_to_add,
    edges_to_remove=edges_to_remove,
)

In [138]:
viz = utils.plot_pretty_structure(bn_with_lv.structure, edges_to_highlight=edges_to_add)
viz.show("Graphs/node_added_dk_3.html")

Graphs/node_added_dk_3.html

In [139]:
lv_states = [0, 1, 2, 3, 4]

proposed_auc = utils.get_avg_auc_lvs(discretised_dk, bn_with_lv, lv_states)
print(f"AUC from adding LV between 'FDI_3' and 'EUPC': {proposed_auc}")

Processing fold 0 using 7 cores takes 4.9235310554504395 seconds
Processing fold 1 using 7 cores takes 4.784772872924805 seconds
Processing fold 2 using 7 cores takes 5.299471139907837 seconds
Processing fold 3 using 7 cores takes 4.949821949005127 seconds
Processing fold 4 using 7 cores takes 4.789653062820435 seconds
AUC from adding LV between 'FDI_3' and 'EUPC': 0.3949074074074074

In [151]:
import warnings
from causalnex.structure import StructureModel
warnings.filterwarnings("ignore")  # silence warnings
from causalnex.structure.notears import from_pandas
from causalnex.plots import plot_structure, NODE_STYLE, EDGE_STYLE
from causalnex.network import BayesianNetwork
import pandas as pd
from causalnex.discretiser import Discretiser
import numpy as np
from sklearn.model_selection import train_test_split
from causalnex.structure.notears import from_pandas_lasso
from IPython.display import Image
from causalnex.evaluation import classification_report
from causalnex.evaluation import roc_auc
from causalnex.inference import InferenceEngine
from causalnex.evaluation import classification_report
import copy
import networkx as nx
import turtorial_utils as utils

In [152]:
df_dk = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/dk_bn_no_context.csv")

df_dk = df_dk.drop(["Unnamed: 0"], axis = 1)

df_dk

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,319173.149269,22.06,76.414286,6.45,6.42,7.49,17.747,2.747300,24.277939,5.548536,3.69,5.3,11.7,0.000010,304.029304,1.866582
1,329422.223703,22.61,76.414286,6.44,6.23,9.47,18.543,3.471527,24.986449,3.835619,0.62,6.5,11.8,0.000009,297.632058,2.784574
2,313144.896657,19.85,76.100000,6.43,6.06,13.44,19.948,4.602963,27.815694,-2.111442,1.17,4.2,13.1,0.000009,275.000000,6.041840
3,326784.316443,19.37,74.900000,6.37,6.17,15.55,21.888,6.793833,27.336108,-2.441067,-3.57,4.7,13.3,0.000009,292.972973,7.495645
4,331838.652835,19.85,74.800000,6.32,6.29,16.31,23.389,6.154324,26.540559,-1.887012,3.94,3.6,12.1,0.000008,282.585278,16.993114
5,338534.135302,19.85,74.300000,5.97,5.73,15.77,25.465,5.799405,26.500323,-3.257951,-5.00,4.0,12.0,0.000007,251.520572,6.354829
6,344715.698783,19.73,74.300000,5.64,5.45,14.77,27.173,6.229005,25.928504,-1.181728,0.20,4.4,11.9,0.000007,239.037433,8.319061
7,350893.947080,19.40,74.700000,5.56,5.43,14.20,29.310,6.455948,25.797420,1.252108,1.86,5.8,12.1,0.000006,244.148936,23.835000
8,357211.575191,19.56,75.400000,5.58,5.59,12.15,30.469,6.498281,25.546356,-1.143677,0.61,8.4,12.2,0.000006,257.394366,12.745287
9,366884.878867,20.23,76.000000,5.80,5.70,12.15,31.715,6.035122,24.942915,-0.070663,2.50,7.2,11.9,0.000006,270.855148,0.401479
10,379808.676526,20.42,76.600000,6.10,5.50,12.38,34.387,6.476226,24.449662,1.457031,1.09,5.6,12.4,0.000006,258.680556,10.241162
11,387242.522658,20.58,77.500000,5.80,5.50,10.52,35.159,5.152751,24.381107,0.801500,2.47,4.3,12.7,0.000006,217.962003,6.781235
12,396193.582956,20.64,78.300000,5.80,5.60,10.04,37.020,6.009741,24.204777,4.079333,-1.10,2.9,12.5,0.000005,232.530120,8.928446
13,398976.348406,19.56,77.800000,5.80,5.50,11.59,31.681,5.640362,24.679988,0.081707,0.36,3.0,12.1,0.000005,216.295026,8.953195
14,438387.741596,19.80,79.000000,5.80,5.50,10.81,41.494,6.236804,23.845550,3.868870,4.16,5.7,12.3,0.000005,186.006826,13.806881
15,481824.514568,20.84,80.100000,5.80,5.50,10.53,41.368,9.553789,21.681084,3.323468,7.67,10.0,12.4,0.000005,244.112994,12.717471

In [153]:
dk = pd.DataFrame()
dk = df_dk.copy()
dk['EUPC_2'] = dk['EUPC'].shift(2)
dk['VABI_1'] = dk['VABI'].shift(1)

In [154]:
dk = dk.dropna()

In [155]:
sm = StructureModel()

In [156]:
sm.add_edges_from([
     ('EUPC_2', 'FDI'),
    ('VABI_1', 'FDI')
])

In [157]:
sm.edges

OutEdgeView([('EUPC_2', 'FDI'), ('VABI_1', 'FDI')])

In [158]:
viz = plot_structure(
    sm,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)

viz.toggle_physics(False)
viz.show("Graphs/fully_connected_dk_2.html")

Graphs/fully_connected_dk_2.html

In [159]:
bn = BayesianNetwork(sm)

In [160]:
discretised_dk = pd.DataFrame(index=dk.index)

for col in dk.columns:
    no_unique = dk[col].nunique()
    
    if no_unique <= 1:
        discretised_dk[col] = 0
    else:
        try:
            discretised_dk[col] = pd.qcut(
                dk[col], 
                q=min(3, no_unique),  
                labels=False,
                duplicates='drop'
            ).astype(int)
        except ValueError:
            discretised_dk[col] = dk[col].rank(method='dense').astype(int) - 1

print("Discretised data:")
print(discretised_dk)

Discretised data:
    GDPC  VABI  EMP  QOA  QOR  YUA  REST  EBSG  GGFC  LBGD  FDI  PC  ARP  \
2      0     1    1    2    2    1     0     0     2     0    1   0    2
3      0     0    0    2    2    2     0     2     2     0    0   1    2
4      0     1    0    2    2    2     0     1     2     0    2   0    0
5      0     1    0    2    2    2     0     0     2     0    0   0    0
6      0     0    0    0    0    2     0     1     2     0    0   1    0
7      1     0    0    0    0    2     1     2     1     2    1   2    0
8      1     0    1    0    1    1     1     2     1     1    1   2    1
9      1     2    1    0    2    1     1     1     1     1    2   2    0
10     1     2    1    2    0    1     2     2     0     2    1   1    1
11     2     2    2    0    0    0     2     0     0     1    2   1    2
12     2     2    2    0    1    0     2     0     0     2    0   0    2
13     2     0    2    0    0    0     1     0     1     1    0   0    0
14     2     1    2    0    0    0     2     1     0     2    2   2    1
15     2     2    2    0    0    0     2     2     0     2    2   2    1

    CO2C  PAM  EUPC  EUPC_2  VABI_1
2      2    2     0       0       2
3      2    2     0       0       1
4      2    2     2       0       0
5      2    1     0       1       1
6      2    0     1       2       1
7      1    1     2       0       0
8      1    1     2       1       0
9      1    2     0       2       0
10     1    2     1       2       2
11     0    0     0       0       2
12     0    0     1       2       2
13     0    0     1       1       2
14     0    0     2       1       0
15     0    1     2       2       1

In [161]:
discretised_dk = discretised_dk.reset_index(drop=True)
bn.fit_node_states(discretised_dk)
baseline_auc = utils.get_avg_auc_all_info(discretised_dk, bn)
print(f"Baseline AUC: {baseline_auc}")

Processing fold 0 using 7 cores takes 4.98591685295105 seconds
Processing fold 1 using 7 cores takes 4.785043954849243 seconds
Processing fold 2 using 7 cores takes 4.6137800216674805 seconds
Processing fold 3 using 7 cores takes 4.9484617710113525 seconds
Processing fold 4 using 7 cores takes 5.048918962478638 seconds
Baseline AUC: 0.33379629629629626

In [162]:
edges_to_add = [('LV', 'EUPC_2'), ('LV', 'FDI')]
edges_to_remove = [('EUPC_2', 'FDI')]

bn_with_lv = copy.deepcopy(bn)
bn_with_lv.add_node(
    "LV",
    edges_to_add=edges_to_add,
    edges_to_remove=edges_to_remove,
)

In [163]:
viz = utils.plot_pretty_structure(bn_with_lv.structure, edges_to_highlight=edges_to_add)
viz.show("Graphs/node_added_dk_4.html")

Graphs/node_added_dk_4.html

In [164]:
lv_states = [0, 1, 2, 3, 4]

proposed_auc = utils.get_avg_auc_lvs(discretised_dk, bn_with_lv, lv_states)
print(f"AUC from adding LV between 'EUPC_2' and 'FDI': {proposed_auc}")

Processing fold 0 using 7 cores takes 5.2115702629089355 seconds
Processing fold 1 using 7 cores takes 4.974379062652588 seconds
Processing fold 2 using 7 cores takes 5.060289144515991 seconds
Processing fold 3 using 7 cores takes 4.861015796661377 seconds
Processing fold 4 using 7 cores takes 4.681355953216553 seconds
AUC from adding LV between 'EUPC_2' and 'FDI': 0.437037037037037