In [1]:
import warnings
from causalnex.structure import StructureModel
warnings.filterwarnings("ignore") 
from causalnex.structure.notears import from_pandas
from causalnex.plots import plot_structure, NODE_STYLE, EDGE_STYLE
from causalnex.network import BayesianNetwork
import pandas as pd
from causalnex.discretiser import Discretiser
import numpy as np
from sklearn.model_selection import train_test_split
from causalnex.structure.notears import from_pandas_lasso
from IPython.display import Image
from causalnex.evaluation import classification_report
from causalnex.evaluation import roc_auc
from causalnex.inference import InferenceEngine
from causalnex.evaluation import classification_report
import copy
import networkx as nx
import turtorial_utils as utils
from sklearn.cluster import KMeans

WARNING:root:MDLP was not imported successfully

In [2]:
def calculate_bic(bn, data):
    """
    Calculates BIC score for a CausalNex BayesianNetwork.
    Formula: BIC = k * ln(n) - 2 * ln(L)
    Returns: bic, log_likelihood
    """
    log_likelihood = 0
    k = 0
    n = len(data)

    for node in bn.nodes:
        cpd = bn.cpds[node]
        
        probs = bn.predict_probability(data, node)
        
        true_values = data[node]
        
        y_dummies = pd.get_dummies(true_values)
        
        y_dummies = y_dummies.reindex(columns=probs.columns, fill_value=0)
        
        p_actual = (probs * y_dummies).sum(axis=1)
        
        log_likelihood += np.sum(np.log(p_actual + 1e-9))

        num_parent_configs = cpd.shape[0]
        num_node_states = cpd.shape[1]
        k += num_parent_configs * (num_node_states - 1)

    bic = k * np.log(n) - 2 * log_likelihood
    
    return bic, log_likelihood

In [3]:
from sklearn.mixture import GaussianMixture # <--- NEW IMPORT
from sklearn.preprocessing import StandardScaler
import itertools

def add_latent_variable_gmm(bn_baseline, sm_baseline, children_cols, discretised_data, raw_data=None):
    
    if raw_data is None:
        raise ValueError("You must provide the continuous 'raw_data' to accurately estimate the Latent Variable.")
        
    subset_data = raw_data[children_cols].loc[discretised_data.index].copy()
    
    
    print(f"Estimating LV based on continuous GMM distributions in: {children_cols}")

    scaler = StandardScaler()
    subset_data_scaled = scaler.fit_transform(subset_data)
    
    gmm = GaussianMixture(n_components=2, random_state=42, n_init=10)
    proxy_lv = gmm.fit_predict(subset_data_scaled)
    
    discretised_with_lv = discretised_data.copy()
    discretised_with_lv['LV'] = proxy_lv
    discretised_with_lv['LV'] = discretised_with_lv['LV'].map({0: "State0", 1: "State1"})
    
    sm_with_lv = sm_baseline.copy()
    sm_with_lv.add_node('LV')
    
    for child in children_cols:
        sm_with_lv.add_edge('LV', child)
        
    for u, v in itertools.permutations(children_cols, 2):
        if sm_with_lv.has_edge(u, v):
            print(f"  - Removing direct edge: {u} -> {v}")
            sm_with_lv.remove_edge(u, v)

    bn_with_lv = BayesianNetwork(sm_with_lv)
    bn_with_lv.fit_node_states(discretised_with_lv)
    bn_with_lv.fit_cpds(discretised_with_lv, method="BayesianEstimator", bayes_prior="K2")
    
    bic_lv, ll_lv = calculate_bic(bn_with_lv, discretised_with_lv)
    print(f"LV Model BIC: {bic_lv:.2f} (LogLikelihood: {ll_lv:.2f})")
    
    return bn_with_lv, discretised_with_lv, bic_lv

In [4]:
df_ee = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/ee_bn_no_context.csv")

df_ee = df_ee.drop(["Unnamed: 0"], axis = 1)

df_ee

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,12234.211743,26.84,76.05,4.99,3.78,10.10,17.139,-8.790011,15.899159,3.169094,13.51,-3.3,19.4,0.000017,32.835821,55.095409
1,12429.172307,26.13,76.05,5.10,4.00,12.03,18.811,-3.904339,18.436467,-2.025402,8.12,-2.0,19.5,0.000016,46.268657,84.791865
2,10590.021094,23.28,70.50,4.87,4.22,27.41,23.009,4.963764,20.533284,-2.239512,9.51,-1.8,19.7,0.000013,57.142857,356.850436
3,11071.755760,24.03,67.60,4.55,4.53,32.94,24.575,6.420120,19.561652,-0.609832,13.28,-2.7,15.8,0.000017,63.157895,396.929938
4,12612.147903,25.35,71.00,4.39,4.49,22.39,25.515,5.793163,18.294990,0.526226,4.80,-3.3,17.5,0.000017,46.616541,179.744167
5,13674.010506,24.63,73.10,4.46,4.22,20.86,25.586,1.640113,18.024258,-0.123296,7.69,-3.8,17.5,0.000016,15.151515,499.062449
6,14539.662078,24.68,74.10,4.14,4.20,18.70,25.356,2.306589,18.399173,0.273440,4.31,-3.3,18.6,0.000018,18.939394,514.084077
7,15492.493600,24.11,75.00,3.78,4.39,14.98,26.130,3.225526,18.439013,0.975175,6.59,-1.9,21.8,0.000017,33.587786,287.150438
8,15972.915607,23.12,76.70,3.73,4.53,14.34,28.987,3.561763,19.223265,0.119938,-3.07,0.8,21.6,0.000016,22.727273,79.744303
9,16863.602095,23.23,77.00,4.50,4.70,14.13,29.232,3.207492,19.332394,-0.181622,3.77,-0.2,21.7,0.000016,21.969697,146.147423
10,18457.882440,23.18,79.20,5.10,4.70,12.18,29.538,3.975466,18.874982,-0.229889,6.32,2.7,21.0,0.000017,28.030303,215.240805
11,19999.192119,23.29,79.70,4.60,4.70,12.08,29.970,2.315765,18.762851,-0.760256,4.08,4.3,21.9,0.000018,18.181818,329.721657
12,21457.612416,22.31,80.50,4.60,4.70,11.62,31.730,3.686161,19.081933,0.196333,9.77,3.1,21.7,0.000012,23.308271,489.642208
13,20954.364802,21.77,79.10,4.60,4.70,18.42,30.069,-1.083534,20.508689,-5.358715,12.01,0.8,20.7,0.000009,15.789474,399.035305
14,23634.746178,22.65,79.30,4.60,4.70,16.62,37.342,-1.302298,19.815687,-2.149653,20.31,1.3,20.6,0.000010,18.796992,428.656702
15,27017.885739,23.34,81.90,4.60,4.70,18.39,38.542,-1.236321,19.291309,-0.692318,4.89,25.3,22.8,0.000011,30.320988,405.044191

In [5]:
ee = pd.DataFrame()
ee = df_ee.copy()
ee['EUPC_3'] = ee['EUPC'].shift(3)
ee['CO2C_3'] = ee['CO2C'].shift(3)
ee['QOA_1'] = ee['QOA'].shift(1)

In [6]:
ee = ee.dropna()

In [7]:
discretised_ee = pd.DataFrame(index=ee.index)

for col in ee.columns:
    no_unique = ee[col].nunique()
    
    if no_unique <= 1:
        discretised_ee[col] = 0
    else:
        try:
            discretised_ee[col] = pd.qcut(
                ee[col], 
                q=min(2, no_unique),  
                labels=False,
                duplicates='drop'
            ).astype(int)
        except ValueError:
            discretised_ee[col] = ee[col].rank(method='eense').astype(int) - 1
    num_states = discretised_ee[col].nunique()
    
    if num_states == 2:
        discretised_ee[col] = discretised_ee[col].map({0: "Low", 1: "High"})
    elif num_states == 3:
        discretised_ee[col] = discretised_ee[col].map({0: "Low", 1: "Medium", 2: "High"})
    else:
        discretised_ee[col] = discretised_ee[col].astype(str)

print("Discretised data:")
print(discretised_ee)

Discretised data:
    GDPC  VABI   EMP   QOA QOR   YUA  REST  EBSG  GGFC  LBGD   FDI    PC  \
3    Low  High   Low   Low   0  High   Low  High  High   Low  High   Low
4    Low  High   Low   Low   0  High   Low  High   Low  High   Low   Low
5    Low  High   Low   Low   0  High   Low   Low   Low  High  High   Low
6    Low  High   Low   Low   0  High   Low   Low   Low  High   Low   Low
7    Low  High   Low   Low   0   Low   Low  High   Low  High  High   Low
8    Low   Low   Low   Low   0   Low   Low  High  High  High   Low   Low
9    Low   Low   Low   Low   0   Low   Low   Low  High   Low   Low   Low
10  High   Low  High  High   0   Low  High  High   Low   Low   Low  High
11  High   Low  High  High   0   Low  High   Low   Low   Low   Low  High
12  High   Low  High  High   0   Low  High  High   Low  High  High  High
13  High   Low  High  High   0  High  High   Low  High   Low  High   Low
14  High   Low  High  High   0   Low  High   Low  High   Low  High  High
15  High  High  High  High   0  High  High   Low  High   Low   Low  High

     ARP  CO2C   PAM  EUPC EUPC_3 CO2C_3 QOA_1
3    Low  High  High   Low    Low   High  High
4    Low  High  High   Low    Low    Low   Low
5    Low   Low   Low  High   High    Low   Low
6    Low  High   Low  High   High   High   Low
7   High  High  High   Low    Low   High   Low
8   High   Low   Low   Low   High    Low   Low
9   High   Low   Low   Low   High   High   Low
10   Low  High  High   Low    Low   High   Low
11  High  High   Low   Low    Low    Low  High
12  High   Low  High  High    Low    Low  High
13   Low   Low   Low  High    Low    Low  High
14   Low   Low   Low  High   High   High  High
15  High   Low  High  High   High    Low  High

In [8]:
sm = StructureModel()

In [9]:
sm.add_edges_from([  
    ('EUPC_3', 'EBSG'),
    ('QOR', 'EBSG'),
    ('REST', 'EBSG'),
    ('GGFC', 'QOR'),
    ('GGFC', 'LBGD'),
    ('CO2C_3', 'LBGD'),
    ('CO2C_3', 'FDI'),
    ('CO2C_3', 'PC'),
    ('QOA_1', 'LBGD'),
    ('QOA_1', 'PAM')
])

In [10]:
sm.edges

OutEdgeView([('EUPC_3', 'EBSG'), ('QOR', 'EBSG'), ('REST', 'EBSG'), ('GGFC', 'QOR'), ('GGFC', 'LBGD'), ('CO2C_3', 'LBGD'), ('CO2C_3', 'FDI'), ('CO2C_3', 'PC'), ('QOA_1', 'LBGD'), ('QOA_1', 'PAM')])

In [11]:
viz = plot_structure(
    sm,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)

viz.toggle_physics(False)
viz.show("Graphs/fully_connected_dk_1.html")

Graphs/fully_connected_dk_1.html

In [12]:
bn = BayesianNetwork(sm)

bn.fit_node_states(discretised_ee)

bn.fit_cpds(discretised_ee, method="BayesianEstimator", bayes_prior="K2")

bic_baseline, ll_baseline = calculate_bic(bn, discretised_ee)
print(f"Baseline BIC: {bic_baseline:.2f} (LogLikelihood: {ll_baseline:.2f})")

Baseline BIC: 5996.11 (LogLikelihood: -2963.43)

In [13]:
bn_with_lv, data_with_lv, bic_lv = add_latent_variable_gmm(
    bn_baseline=bn,
    sm_baseline=sm,
    children_cols=['EUPC_3', 'EBSG'],  # Replace with your specific nodes
    discretised_data=discretised_ee,
    raw_data=ee
)

Estimating LV based on continuous GMM distributions in: ['EUPC_3', 'EBSG']
  - Removing direct edge: EUPC_3 -> EBSG
LV Model BIC: 6540.04 (LogLikelihood: -3232.83)

In [49]:
import warnings
from causalnex.structure import StructureModel
warnings.filterwarnings("ignore") 
from causalnex.structure.notears import from_pandas
from causalnex.plots import plot_structure, NODE_STYLE, EDGE_STYLE
from causalnex.network import BayesianNetwork
import pandas as pd
from causalnex.discretiser import Discretiser
import numpy as np
from sklearn.model_selection import train_test_split
from causalnex.structure.notears import from_pandas_lasso
from IPython.display import Image
from causalnex.evaluation import classification_report
from causalnex.evaluation import roc_auc
from causalnex.inference import InferenceEngine
from causalnex.evaluation import classification_report
import copy
import networkx as nx
import turtorial_utils as utils
from sklearn.cluster import KMeans

In [50]:
df_ee = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/ee_bn_no_context.csv")

df_ee = df_ee.drop(["Unnamed: 0"], axis = 1)

df_ee

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,12234.211743,26.84,76.05,4.99,3.78,10.10,17.139,-8.790011,15.899159,3.169094,13.51,-3.3,19.4,0.000017,32.835821,55.095409
1,12429.172307,26.13,76.05,5.10,4.00,12.03,18.811,-3.904339,18.436467,-2.025402,8.12,-2.0,19.5,0.000016,46.268657,84.791865
2,10590.021094,23.28,70.50,4.87,4.22,27.41,23.009,4.963764,20.533284,-2.239512,9.51,-1.8,19.7,0.000013,57.142857,356.850436
3,11071.755760,24.03,67.60,4.55,4.53,32.94,24.575,6.420120,19.561652,-0.609832,13.28,-2.7,15.8,0.000017,63.157895,396.929938
4,12612.147903,25.35,71.00,4.39,4.49,22.39,25.515,5.793163,18.294990,0.526226,4.80,-3.3,17.5,0.000017,46.616541,179.744167
5,13674.010506,24.63,73.10,4.46,4.22,20.86,25.586,1.640113,18.024258,-0.123296,7.69,-3.8,17.5,0.000016,15.151515,499.062449
6,14539.662078,24.68,74.10,4.14,4.20,18.70,25.356,2.306589,18.399173,0.273440,4.31,-3.3,18.6,0.000018,18.939394,514.084077
7,15492.493600,24.11,75.00,3.78,4.39,14.98,26.130,3.225526,18.439013,0.975175,6.59,-1.9,21.8,0.000017,33.587786,287.150438
8,15972.915607,23.12,76.70,3.73,4.53,14.34,28.987,3.561763,19.223265,0.119938,-3.07,0.8,21.6,0.000016,22.727273,79.744303
9,16863.602095,23.23,77.00,4.50,4.70,14.13,29.232,3.207492,19.332394,-0.181622,3.77,-0.2,21.7,0.000016,21.969697,146.147423
10,18457.882440,23.18,79.20,5.10,4.70,12.18,29.538,3.975466,18.874982,-0.229889,6.32,2.7,21.0,0.000017,28.030303,215.240805
11,19999.192119,23.29,79.70,4.60,4.70,12.08,29.970,2.315765,18.762851,-0.760256,4.08,4.3,21.9,0.000018,18.181818,329.721657
12,21457.612416,22.31,80.50,4.60,4.70,11.62,31.730,3.686161,19.081933,0.196333,9.77,3.1,21.7,0.000012,23.308271,489.642208
13,20954.364802,21.77,79.10,4.60,4.70,18.42,30.069,-1.083534,20.508689,-5.358715,12.01,0.8,20.7,0.000009,15.789474,399.035305
14,23634.746178,22.65,79.30,4.60,4.70,16.62,37.342,-1.302298,19.815687,-2.149653,20.31,1.3,20.6,0.000010,18.796992,428.656702
15,27017.885739,23.34,81.90,4.60,4.70,18.39,38.542,-1.236321,19.291309,-0.692318,4.89,25.3,22.8,0.000011,30.320988,405.044191

In [51]:
ee = pd.DataFrame()
ee = df_ee.copy()
ee['VABI_2'] = ee['VABI'].shift(2)
ee['PAM_1'] = ee['PAM'].shift(1)

In [52]:
ee = ee.dropna()

In [53]:
discretised_ee = pd.DataFrame(index=ee.index)

for col in ee.columns:
    no_unique = ee[col].nunique()
    
    if no_unique <= 1:
        discretised_ee[col] = 0
    else:
        try:
            discretised_ee[col] = pd.qcut(
                ee[col], 
                q=min(2, no_unique),  
                labels=False,
                duplicates='drop'
            ).astype(int)
        except ValueError:
            discretised_ee[col] = ee[col].rank(method='eense').astype(int) - 1
    num_states = discretised_ee[col].nunique()
    
    if num_states == 2:
        discretised_ee[col] = discretised_ee[col].map({0: "Low", 1: "High"})
    elif num_states == 3:
        discretised_ee[col] = discretised_ee[col].map({0: "Low", 1: "Medium", 2: "High"})
    else:
        discretised_ee[col] = discretised_ee[col].astype(str)

print("Discretised data:")
print(discretised_ee)

Discretised data:
    GDPC  VABI   EMP   QOA   QOR   YUA  REST  EBSG  GGFC  LBGD   FDI    PC  \
2    Low   Low   Low  High   Low  High   Low  High  High   Low  High   Low
3    Low  High   Low   Low   Low  High   Low  High  High   Low  High   Low
4    Low  High   Low   Low   Low  High   Low  High   Low  High   Low   Low
5    Low  High   Low   Low   Low  High   Low   Low   Low  High  High   Low
6    Low  High   Low   Low   Low  High   Low   Low   Low  High   Low   Low
7    Low  High   Low   Low   Low   Low   Low  High   Low  High  High   Low
8    Low   Low   Low   Low   Low   Low   Low  High  High  High   Low  High
9   High   Low  High   Low  High   Low  High   Low  High  High   Low   Low
10  High   Low  High  High  High   Low  High  High   Low   Low   Low  High
11  High  High  High  High  High   Low  High   Low   Low   Low   Low  High
12  High   Low  High  High  High   Low  High  High   Low  High  High  High
13  High   Low  High  High  High  High  High   Low  High   Low  High  High
14  High   Low  High  High  High   Low  High   Low  High   Low  High  High
15  High  High  High  High  High  High  High   Low  High   Low   Low  High

     ARP  CO2C   PAM  EUPC VABI_2 PAM_1
2    Low   Low  High   Low   High  High
3    Low  High  High  High   High  High
4    Low  High  High   Low    Low  High
5    Low  High   Low  High   High  High
6    Low  High   Low  High   High   Low
7   High  High  High   Low   High   Low
8   High   Low   Low   Low   High  High
9   High   Low   Low   Low   High   Low
10  High  High  High   Low    Low   Low
11  High  High   Low   Low    Low  High
12  High   Low  High  High    Low   Low
13   Low   Low   Low  High    Low  High
14   Low   Low   Low  High    Low   Low
15  High   Low  High  High    Low   Low

In [54]:
sm_1 = StructureModel()

In [55]:
sm_1.add_edges_from([
    ('PAM_1', 'EUPC'),
    ('VABI_2', 'EUPC'),
])

In [56]:
sm_1.edges

OutEdgeView([('PAM_1', 'EUPC'), ('VABI_2', 'EUPC')])

In [57]:
viz = plot_structure(
    sm_1,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)

viz.toggle_physics(False)
viz.show("Graphs/fully_connected_dk_2.html")

Graphs/fully_connected_dk_2.html

In [58]:
bn_1 = BayesianNetwork(sm_1)

bn_1.fit_node_states(discretised_ee)

bn_1.fit_cpds(discretised_ee, method="BayesianEstimator", bayes_prior="K2")

bic_baseline, ll_baseline = calculate_bic(bn_1, discretised_ee)
print(f"Baseline BIC: {bic_baseline:.2f} (LogLikelihood: {ll_baseline:.2f})")

Baseline BIC: 1756.59 (LogLikelihood: -870.38)

In [59]:
bn_with_lv_1, data_with_lv_1, bic_lv_1 = add_latent_variable_gmm(
    bn_baseline=bn_1,
    sm_baseline=sm_1,
    children_cols=['PAM_1', 'EUPC'],  # Replace with your specific nodes
    discretised_data=discretised_ee,
    raw_data=ee
)

Estimating LV based on continuous GMM distributions in: ['PAM_1', 'EUPC']
  - Removing direct edge: PAM_1 -> EUPC
LV Model BIC: 2342.12 (LogLikelihood: -1160.50)

In [61]:
bn_with_lv_2, data_with_lv_2, bic_lv_2 = add_latent_variable_gmm(
    bn_baseline=bn_1,
    sm_baseline=sm_1,
    children_cols=['VABI_2', 'EUPC'],  # Replace with your specific nodes
    discretised_data=discretised_ee,
    raw_data=ee
)

Estimating LV based on continuous GMM distributions in: ['VABI_2', 'EUPC']
  - Removing direct edge: VABI_2 -> EUPC
LV Model BIC: 2342.12 (LogLikelihood: -1160.50)