In [2]:
import warnings
from causalnex.structure import StructureModel
warnings.filterwarnings("ignore")  # silence warnings
from causalnex.structure.notears import from_pandas
from causalnex.plots import plot_structure, NODE_STYLE, EDGE_STYLE
from causalnex.network import BayesianNetwork
import pandas as pd
from causalnex.discretiser import Discretiser
import numpy as np
from sklearn.model_selection import train_test_split
from causalnex.structure.notears import from_pandas_lasso
from IPython.display import Image
from causalnex.evaluation import classification_report
from causalnex.evaluation import roc_auc
from causalnex.inference import InferenceEngine
from causalnex.evaluation import classification_report
import copy
import networkx as nx

In [3]:
def calculate_bic(bn, data):
    """
    Calculates BIC score for a fitted CausalNex BayesianNetwork.
    Formula: BIC = k * ln(n) - 2 * ln(L)
    Returns: bic, log_likelihood
    """
    log_likelihood = 0
    k = 0
    n = len(data)
    
    for node in bn.nodes:
        cpd = bn.cpds[node]
        num_node_states = cpd.shape[0]
        num_parent_configs = cpd.shape[1]
        k += num_parent_configs * (num_node_states - 1)
        parents = list(bn.structure.predecessors(node))
        
        if len(parents) == 0:
            probs = data[node].map(cpd.iloc[:, 0]).values
        else:
            cpd_series = cpd.unstack()
            parent_order = sorted(parents)
            lookup_cols = parent_order + [node]
            lookup_df = data[lookup_cols]
            lookup_keys = [tuple(x) for x in lookup_df.to_numpy()]
            probs = cpd_series.loc[lookup_keys].values
            
        log_likelihood += np.sum(np.log(probs + 1e-9))
    
    bic = k * np.log(n) - 2 * log_likelihood
    
    return bic, log_likelihood

In [4]:
from sklearn.mixture import GaussianMixture
from sklearn.preprocessing import StandardScaler
import itertools

def add_latent_variable_gmm(bn_baseline, sm_baseline, children_cols, discretised_data, raw_data=None):
    
    if raw_data is None:
        raise ValueError("You must provide the continuous 'raw_data' to accurately estimate the Latent Variable.")
        
    subset_data = raw_data[children_cols].loc[discretised_data.index].copy()
    
    print(f"Estimating LV based on continuous GMM distributions in: {children_cols}")

    scaler = StandardScaler()
    subset_data_scaled = scaler.fit_transform(subset_data)
    
    gmm = GaussianMixture(n_components=2, random_state=42, n_init=10)
    proxy_lv = gmm.fit_predict(subset_data_scaled)
    discretised_with_lv = discretised_data.copy()
    discretised_with_lv['LV'] = proxy_lv
    discretised_with_lv['LV'] = discretised_with_lv['LV'].map({0: "State0", 1: "State1"})
    
    sm_with_lv = sm_baseline.copy()
    sm_with_lv.add_node('LV')
    
    for child in children_cols:
        sm_with_lv.add_edge('LV', child)
        
    for u, v in itertools.permutations(children_cols, 2):
        if sm_with_lv.has_edge(u, v):
            print(f"  - Removing direct edge: {u} -> {v}")
            sm_with_lv.remove_edge(u, v)

    bn_with_lv = BayesianNetwork(sm_with_lv)
    bn_with_lv.fit_node_states(discretised_with_lv)
    bn_with_lv.fit_cpds(discretised_with_lv, method="BayesianEstimator", bayes_prior="K2")
    
    bic_lv, ll_lv = calculate_bic(bn_with_lv, discretised_with_lv)
    print(f"LV Model BIC: {bic_lv:.2f} (LogLikelihood: {ll_lv:.2f})")
    
    return bn_with_lv, discretised_with_lv, bic_lv

In [5]:
def discretize_data(df):
    discretised_df = pd.DataFrame(index=df.index)
    TARGET_BINS = 3

    for col in df.columns:
        if df[col].isna().all():
            discretised_df[col] = "Missing"
            continue
        
        no_unique = df[col].nunique()
    
        if no_unique <= 1:
            discretised_df[col] = "Constant"
            continue
    
        if no_unique <= TARGET_BINS:
            discretised_df[col] = df[col].rank(method='dense') - 1
        else:
            try:
                discretised_df[col] = pd.qcut(df[col], q=TARGET_BINS, labels=False, duplicates='drop')
            except (ValueError, TypeError):
                try:
                    discretised_df[col] = pd.cut(df[col], bins=TARGET_BINS, labels=False, include_lowest=True)
                except (ValueError, TypeError):
                    discretised_df[col] = pd.qcut(df[col].rank(method='first'), q=TARGET_BINS, labels=False, duplicates='drop')

        if pd.api.types.is_numeric_dtype(discretised_df[col]):
            valid_values = sorted(discretised_df[col].dropna().unique())
            num_states = len(valid_values)
            
            if num_states == 2:
                label_map = {valid_values[0]: "Low", valid_values[1]: "High"}
            elif num_states == 3:
                label_map = {valid_values[0]: "Low", valid_values[1]: "Medium", valid_values[2]: "High"}
            elif num_states == 4:
                label_map = {valid_values[0]: "VeryLow", valid_values[1]: "Low", valid_values[2]: "High", valid_values[3]: "VeryHigh"}
            else:
                label_map = {val: f"State{int(val)}" for val in valid_values}
            
            discretised_df[col] = discretised_df[col].map(label_map)
            
            discretised_df[col] = discretised_df[col].fillna("Unknown")

    print("Data types after discretization:")
    print(discretised_df.dtypes.value_counts())

    print("\nUnique states per column:")
    print(discretised_df.nunique())

    print("\nDiscretised data preview:")
    print(discretised_df.head())

    if discretised_df.isna().any().any():
        print("\n⚠️ Warning: Some NaN values remain!")
        print(discretised_df.isna().sum()[discretised_df.isna().sum() > 0])
    
    return discretised_df

In [6]:
df_ee = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/ee_bn_no_context.csv")

df_ee = df_ee.drop(["Unnamed: 0"], axis = 1)

df_ee

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,15790.0,26.84,76.05,4.99,3.78,10.10,17.139,-8.790011,15.899159,3.169094,13.51,-3.3,19.4,0.000017,32.835821,55.095409
1,15030.0,26.13,76.05,5.10,4.00,12.03,18.811,-3.904339,18.436467,-2.025402,8.12,-2.0,19.5,0.000016,46.268657,84.791865
2,12850.0,23.28,70.50,4.87,4.22,27.41,23.009,4.963764,20.533284,-2.239512,9.51,-1.8,19.7,0.000013,57.142857,356.850436
3,13190.0,24.03,67.60,4.55,4.53,32.94,24.575,6.420120,19.561652,-0.609832,13.28,-2.7,15.8,0.000017,63.157895,396.929938
4,14240.0,25.35,71.00,4.39,4.49,22.39,25.515,5.793163,18.294990,0.526226,4.80,-3.3,17.5,0.000017,46.616541,179.744167
5,14810.0,24.63,73.10,4.46,4.22,20.86,25.586,1.640113,18.024258,-0.123296,7.69,-3.8,17.5,0.000016,15.151515,499.062449
6,15130.0,24.68,74.10,4.14,4.20,18.70,25.356,2.306589,18.399173,0.273440,4.31,-3.3,18.6,0.000018,18.939394,514.084077
7,15680.0,24.11,75.00,3.78,4.39,14.98,26.130,3.225526,18.439013,0.975175,6.59,-1.9,21.8,0.000017,33.587786,287.150438
8,16000.0,23.12,76.70,3.73,4.53,14.34,28.987,3.561763,19.223265,0.119938,-3.07,0.8,21.6,0.000016,22.727273,79.744303
9,16460.0,23.23,77.00,4.50,4.70,14.13,29.232,3.207492,19.332394,-0.181622,3.77,-0.2,21.7,0.000016,21.969697,146.147423
10,17390.0,23.18,79.20,5.10,4.70,12.18,29.538,3.975466,18.874982,-0.229889,6.32,2.7,21.0,0.000017,28.030303,215.240805
11,17990.0,23.29,79.70,4.60,4.70,12.08,29.970,2.315765,18.762851,-0.760256,4.08,4.3,21.9,0.000018,18.181818,329.721657
12,18580.0,22.31,80.50,4.60,4.70,11.62,31.730,3.686161,19.081933,0.196333,9.77,3.1,21.7,0.000012,23.308271,489.642208
13,17990.0,21.77,79.10,4.60,4.70,18.42,30.069,-1.083534,20.508689,-5.358715,12.01,0.8,20.7,0.000009,15.789474,399.035305
14,19450.0,22.65,79.30,4.60,4.70,16.62,37.342,-1.302298,19.815687,-2.149653,20.31,1.3,20.6,0.000010,18.796992,428.656702
15,19190.0,23.34,81.90,4.60,4.70,18.39,38.542,-1.236321,19.291309,-0.692318,4.89,25.3,22.8,0.000011,30.320988,405.044191

In [7]:
ee = pd.DataFrame()
ee = df_ee.copy()
ee['EUPC_3'] = ee['EUPC'].shift(3)

In [9]:
ee = ee.dropna()

In [10]:
discretised_ee = discretize_data(ee)

Data types after discretization:
object    17
Name: count, dtype: int64

Unique states per column:
GDPC      3
VABI      3
EMP       3
QOA       3
QOR       2
YUA       3
REST      3
EBSG      3
GGFC      3
LBGD      3
FDI       3
PC        3
ARP       3
CO2C      3
PAM       3
EUPC      3
EUPC_3    3
dtype: int64

Discretised data preview:
  GDPC    VABI  EMP     QOA  QOR     YUA REST    EBSG  GGFC    LBGD     FDI  \
3  Low  Medium  Low  Medium  Low    High  Low    High  High  Medium    High
4  Low    High  Low     Low  Low    High  Low    High   Low    High     Low
5  Low    High  Low     Low  Low    High  Low     Low   Low  Medium    High
6  Low    High  Low     Low  Low    High  Low  Medium   Low    High     Low
7  Low    High  Low     Low  Low  Medium  Low  Medium   Low    High  Medium

       PC   ARP    CO2C   PAM    EUPC  EUPC_3
3     Low   Low  Medium  High  Medium     Low
4     Low   Low    High  High     Low     Low
5     Low   Low  Medium   Low    High    High
6     Low   Low    High   Low    High    High
7  Medium  High    High  High  Medium  Medium

In [11]:
sm = StructureModel()

In [12]:
sm.add_edges_from([
    ('EUPC_3', 'EBSG')
])

In [13]:
sm.edges

OutEdgeView([('EUPC_3', 'EBSG')])

In [14]:
viz = plot_structure(
    sm,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)

viz.toggle_physics(False)
viz.show("Graphs/fully_connected_dk_1.html")

Graphs/fully_connected_dk_1.html

In [15]:
sm_baseline = sm.copy()
bn_baseline = BayesianNetwork(sm_baseline)
bn_baseline.fit_node_states(discretised_ee)
bn_baseline.fit_cpds(discretised_ee, method="BayesianEstimator", bayes_prior="K2")
baseline_bic, _ = calculate_bic(bn_baseline, discretised_ee)
print(f"BASELINE BIC: {baseline_bic:.2f}")

# ==========================================
# TEST #1: (EUPC_3  -> EBSG)
# ==========================================
print("\n--- Testing EUPC_3 -> EBSG ---")

sm_test_1 = sm_baseline.copy()

bn_with_lv_1, data_with_lv_1, bic_lv_1 = add_latent_variable_gmm(
    bn_baseline=bn_baseline,
    sm_baseline=sm_test_1,
    children_cols=['EUPC_3', 'EBSG'], 
    discretised_data=discretised_ee,
    raw_data=ee
)

BASELINE BIC: 73.82

--- Testing EUPC_3 -> EBSG ---
Estimating LV based on continuous GMM distributions in: ['EUPC_3', 'EBSG']
  - Removing direct edge: EUPC_3 -> EBSG
LV Model BIC: 84.89 (LogLikelihood: -30.90)

In [17]:
df_ee = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/ee_bn_no_context.csv")

df_ee = df_ee.drop(["Unnamed: 0"], axis = 1)

df_ee

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,15790.0,26.84,76.05,4.99,3.78,10.10,17.139,-8.790011,15.899159,3.169094,13.51,-3.3,19.4,0.000017,32.835821,55.095409
1,15030.0,26.13,76.05,5.10,4.00,12.03,18.811,-3.904339,18.436467,-2.025402,8.12,-2.0,19.5,0.000016,46.268657,84.791865
2,12850.0,23.28,70.50,4.87,4.22,27.41,23.009,4.963764,20.533284,-2.239512,9.51,-1.8,19.7,0.000013,57.142857,356.850436
3,13190.0,24.03,67.60,4.55,4.53,32.94,24.575,6.420120,19.561652,-0.609832,13.28,-2.7,15.8,0.000017,63.157895,396.929938
4,14240.0,25.35,71.00,4.39,4.49,22.39,25.515,5.793163,18.294990,0.526226,4.80,-3.3,17.5,0.000017,46.616541,179.744167
5,14810.0,24.63,73.10,4.46,4.22,20.86,25.586,1.640113,18.024258,-0.123296,7.69,-3.8,17.5,0.000016,15.151515,499.062449
6,15130.0,24.68,74.10,4.14,4.20,18.70,25.356,2.306589,18.399173,0.273440,4.31,-3.3,18.6,0.000018,18.939394,514.084077
7,15680.0,24.11,75.00,3.78,4.39,14.98,26.130,3.225526,18.439013,0.975175,6.59,-1.9,21.8,0.000017,33.587786,287.150438
8,16000.0,23.12,76.70,3.73,4.53,14.34,28.987,3.561763,19.223265,0.119938,-3.07,0.8,21.6,0.000016,22.727273,79.744303
9,16460.0,23.23,77.00,4.50,4.70,14.13,29.232,3.207492,19.332394,-0.181622,3.77,-0.2,21.7,0.000016,21.969697,146.147423
10,17390.0,23.18,79.20,5.10,4.70,12.18,29.538,3.975466,18.874982,-0.229889,6.32,2.7,21.0,0.000017,28.030303,215.240805
11,17990.0,23.29,79.70,4.60,4.70,12.08,29.970,2.315765,18.762851,-0.760256,4.08,4.3,21.9,0.000018,18.181818,329.721657
12,18580.0,22.31,80.50,4.60,4.70,11.62,31.730,3.686161,19.081933,0.196333,9.77,3.1,21.7,0.000012,23.308271,489.642208
13,17990.0,21.77,79.10,4.60,4.70,18.42,30.069,-1.083534,20.508689,-5.358715,12.01,0.8,20.7,0.000009,15.789474,399.035305
14,19450.0,22.65,79.30,4.60,4.70,16.62,37.342,-1.302298,19.815687,-2.149653,20.31,1.3,20.6,0.000010,18.796992,428.656702
15,19190.0,23.34,81.90,4.60,4.70,18.39,38.542,-1.236321,19.291309,-0.692318,4.89,25.3,22.8,0.000011,30.320988,405.044191

In [18]:
ee = pd.DataFrame()
ee = df_ee.copy()
ee['PAM_1'] = ee['PAM'].shift(1)
ee['QOA_2'] = ee['QOA'].shift(2)
ee['VABI_2'] = ee['VABI'].shift(2)

In [19]:
ee = ee.dropna()

In [20]:
discretised_ee = discretize_data(ee)

Data types after discretization:
object    19
Name: count, dtype: int64

Unique states per column:
GDPC      3
VABI      3
EMP       3
QOA       3
QOR       2
YUA       3
REST      3
EBSG      3
GGFC      3
LBGD      3
FDI       3
PC        3
ARP       3
CO2C      3
PAM       3
EUPC      3
PAM_1     3
QOA_2     3
VABI_2    3
dtype: int64

Discretised data preview:
  GDPC    VABI  EMP     QOA   QOR   YUA REST  EBSG  GGFC    LBGD     FDI  \
2  Low  Medium  Low    High   Low  High  Low  High  High     Low    High
3  Low    High  Low  Medium  High  High  Low  High  High  Medium    High
4  Low    High  Low     Low   Low  High  Low  High   Low    High     Low
5  Low    High  Low     Low   Low  High  Low   Low   Low  Medium  Medium
6  Low    High  Low     Low   Low  High  Low   Low   Low    High     Low

       PC  ARP    CO2C   PAM    EUPC PAM_1   QOA_2  VABI_2
2  Medium  Low     Low  High  Medium  High    High    High
3     Low  Low    High  High  Medium  High    High    High
4     Low  Low    High  High     Low  High    High  Medium
5     Low  Low  Medium   Low    High  High  Medium  Medium
6     Low  Low    High   Low    High   Low     Low    High

In [21]:
sm = StructureModel()

In [22]:
sm.add_edges_from([
    ('PAM_1', 'EUPC'),
    ('QOA_2', 'EUPC'),
    ('VABI_2', 'EUPC')    
])

In [23]:
sm.edges

OutEdgeView([('PAM_1', 'EUPC'), ('QOA_2', 'EUPC'), ('VABI_2', 'EUPC')])

In [24]:
viz = plot_structure(
    sm,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)

viz.toggle_physics(False)
viz.show("Graphs/fully_connected_dk_1.html")

Graphs/fully_connected_dk_1.html

In [25]:
sm_baseline = sm.copy()
bn_baseline = BayesianNetwork(sm_baseline)
bn_baseline.fit_node_states(discretised_ee)
bn_baseline.fit_cpds(discretised_ee, method="BayesianEstimator", bayes_prior="K2")
baseline_bic, _ = calculate_bic(bn_baseline, discretised_ee)
print(f"BASELINE BIC: {baseline_bic:.2f}")

# ==========================================
# TEST #1: (PAM_1  -> EUPC)
# ==========================================
print("\n--- Testing PAM_1 -> EUPC ---")

sm_test_1 = sm_baseline.copy()

bn_with_lv_1, data_with_lv_1, bic_lv_1 = add_latent_variable_gmm(
    bn_baseline=bn_baseline,
    sm_baseline=sm_test_1,
    children_cols=['PAM_1', 'EUPC'], 
    discretised_data=discretised_ee,
    raw_data=ee
)

# ==========================================
# TEST #2: (QOA_2 -> EUPC)
# ==========================================
print("\n--- Testing QOA_2 -> EUPC ---")

sm_test_2 = sm_baseline.copy()

bn_with_lv_2, data_with_lv_2, bic_lv_2 = add_latent_variable_gmm(
    bn_baseline=bn_baseline,
    sm_baseline=sm_test_2,
    children_cols=['QOA_2', 'EUPC'], 
    discretised_data=discretised_ee,
    raw_data=ee
)

# ==========================================
# TEST #3: (VABI_2 -> EUPC)
# ==========================================
print("\n--- Testing VABI_2 -> EUPC ---")

sm_test_3 = sm_baseline.copy()

bn_with_lv_3, data_with_lv_3, bic_lv_3 = add_latent_variable_gmm(
    bn_baseline=bn_baseline,
    sm_baseline=sm_test_3,
    children_cols=['VABI_2', 'EUPC'], 
    discretised_data=discretised_ee,
    raw_data=ee
)

BASELINE BIC: 269.04

--- Testing PAM_1 -> EUPC ---
Estimating LV based on continuous GMM distributions in: ['PAM_1', 'EUPC']
  - Removing direct edge: PAM_1 -> EUPC
LV Model BIC: 238.91 (LogLikelihood: -60.07)

--- Testing QOA_2 -> EUPC ---
Estimating LV based on continuous GMM distributions in: ['QOA_2', 'EUPC']
  - Removing direct edge: QOA_2 -> EUPC
LV Model BIC: 238.69 (LogLikelihood: -59.96)

--- Testing VABI_2 -> EUPC ---
Estimating LV based on continuous GMM distributions in: ['VABI_2', 'EUPC']
  - Removing direct edge: VABI_2 -> EUPC
LV Model BIC: 243.73 (LogLikelihood: -62.49)