In [9]:
import warnings
from causalnex.structure import StructureModel
warnings.filterwarnings("ignore")  # silence warnings
from causalnex.structure.notears import from_pandas
from causalnex.plots import plot_structure, NODE_STYLE, EDGE_STYLE
from causalnex.network import BayesianNetwork
import pandas as pd
from causalnex.discretiser import Discretiser
import numpy as np
from sklearn.model_selection import train_test_split
from causalnex.structure.notears import from_pandas_lasso
from IPython.display import Image
from causalnex.evaluation import classification_report
from causalnex.evaluation import roc_auc
from causalnex.inference import InferenceEngine
from causalnex.evaluation import classification_report
import copy
import networkx as nx

In [10]:
def calculate_bic(bn, data):
    """
    Calculates BIC score for a fitted CausalNex BayesianNetwork.
    Formula: BIC = k * ln(n) - 2 * ln(L)
    Returns: bic, log_likelihood
    """
    log_likelihood = 0
    k = 0
    n = len(data)
    
    for node in bn.nodes:
        cpd = bn.cpds[node]
        num_node_states = cpd.shape[0]
        num_parent_configs = cpd.shape[1]
        k += num_parent_configs * (num_node_states - 1)
        parents = list(bn.structure.predecessors(node))
        
        if len(parents) == 0:
            probs = data[node].map(cpd.iloc[:, 0]).values
        else:
            cpd_series = cpd.unstack()
            parent_order = sorted(parents)
            lookup_cols = parent_order + [node]
            lookup_df = data[lookup_cols]
            lookup_keys = [tuple(x) for x in lookup_df.to_numpy()]
            probs = cpd_series.loc[lookup_keys].values
            
        log_likelihood += np.sum(np.log(probs + 1e-9))
    
    bic = k * np.log(n) - 2 * log_likelihood
    
    return bic, log_likelihood

In [11]:
from sklearn.mixture import GaussianMixture
from sklearn.preprocessing import StandardScaler
import itertools

def add_latent_variable_gmm(bn_baseline, sm_baseline, children_cols, discretised_data, raw_data=None):
    
    if raw_data is None:
        raise ValueError("You must provide the continuous 'raw_data' to accurately estimate the Latent Variable.")
        
    subset_data = raw_data[children_cols].loc[discretised_data.index].copy()
    
    print(f"Estimating LV based on continuous GMM distributions in: {children_cols}")

    scaler = StandardScaler()
    subset_data_scaled = scaler.fit_transform(subset_data)
    
    gmm = GaussianMixture(n_components=2, random_state=42, n_init=10)
    proxy_lv = gmm.fit_predict(subset_data_scaled)
    discretised_with_lv = discretised_data.copy()
    discretised_with_lv['LV'] = proxy_lv
    discretised_with_lv['LV'] = discretised_with_lv['LV'].map({0: "State0", 1: "State1"})
    
    sm_with_lv = sm_baseline.copy()
    sm_with_lv.add_node('LV')
    
    for child in children_cols:
        sm_with_lv.add_edge('LV', child)
        
    for u, v in itertools.permutations(children_cols, 2):
        if sm_with_lv.has_edge(u, v):
            print(f"  - Removing direct edge: {u} -> {v}")
            sm_with_lv.remove_edge(u, v)

    bn_with_lv = BayesianNetwork(sm_with_lv)
    bn_with_lv.fit_node_states(discretised_with_lv)
    bn_with_lv.fit_cpds(discretised_with_lv, method="BayesianEstimator", bayes_prior="K2")
    
    bic_lv, ll_lv = calculate_bic(bn_with_lv, discretised_with_lv)
    print(f"LV Model BIC: {bic_lv:.2f} (LogLikelihood: {ll_lv:.2f})")
    
    return bn_with_lv, discretised_with_lv, bic_lv

In [12]:
def discretize_data(df):
    discretised_df = pd.DataFrame(index=df.index)
    TARGET_BINS = 3

    for col in df.columns:
        if df[col].isna().all():
            discretised_df[col] = "Missing"
            continue
        
        no_unique = df[col].nunique()
    
        if no_unique <= 1:
            discretised_df[col] = "Constant"
            continue
    
        if no_unique <= TARGET_BINS:
            discretised_df[col] = df[col].rank(method='dense') - 1
        else:
            try:
                discretised_df[col] = pd.qcut(df[col], q=TARGET_BINS, labels=False, duplicates='drop')
            except (ValueError, TypeError):
                try:
                    discretised_df[col] = pd.cut(df[col], bins=TARGET_BINS, labels=False, include_lowest=True)
                except (ValueError, TypeError):
                    discretised_df[col] = pd.qcut(df[col].rank(method='first'), q=TARGET_BINS, labels=False, duplicates='drop')

        if pd.api.types.is_numeric_dtype(discretised_df[col]):
            valid_values = sorted(discretised_df[col].dropna().unique())
            num_states = len(valid_values)
            
            if num_states == 2:
                label_map = {valid_values[0]: "Low", valid_values[1]: "High"}
            elif num_states == 3:
                label_map = {valid_values[0]: "Low", valid_values[1]: "Medium", valid_values[2]: "High"}
            elif num_states == 4:
                label_map = {valid_values[0]: "VeryLow", valid_values[1]: "Low", valid_values[2]: "High", valid_values[3]: "VeryHigh"}
            else:
                label_map = {val: f"State{int(val)}" for val in valid_values}
            
            discretised_df[col] = discretised_df[col].map(label_map)
            
            discretised_df[col] = discretised_df[col].fillna("Unknown")

    print("Data types after discretization:")
    print(discretised_df.dtypes.value_counts())

    print("\nUnique states per column:")
    print(discretised_df.nunique())

    print("\nDiscretised data preview:")
    print(discretised_df.head())

    if discretised_df.isna().any().any():
        print("\n⚠️ Warning: Some NaN values remain!")
        print(discretised_df.isna().sum()[discretised_df.isna().sum() > 0])
    
    return discretised_df

In [13]:
df_fi = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/fi_bn_no_context.csv")

df_fi = df_fi.drop(["Unnamed: 0"], axis = 1)

df_fi

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,41650.0,30.67,73.892857,6.310000,5.64,16.43,29.561,4.794744,20.768314,5.292982,8.57,4.4,13.0,0.000013,341.020794,6.033898
1,41780.0,29.57,73.892857,6.430000,5.84,16.34,31.071,3.615903,21.566205,4.569814,6.79,4.9,13.6,0.000011,338.794727,9.016756
2,38230.0,25.66,72.600000,6.330000,5.89,21.38,31.045,2.038683,24.069112,-1.860401,-3.48,4.7,13.8,0.000011,338.202247,34.478428
3,39260.0,26.19,71.900000,6.150000,5.86,21.29,32.166,1.364890,23.685735,-2.369424,4.90,4.4,13.1,0.000012,322.947761,27.559638
4,40010.0,25.04,72.700000,6.160000,5.83,19.93,32.532,-0.781159,23.401887,-0.488730,-2.18,4.8,13.7,0.000011,306.122449,44.801132
5,39210.0,23.36,73.000000,6.200000,6.09,18.87,34.222,-1.560551,24.176307,-1.104413,1.92,4.7,13.2,0.000010,313.863216,40.733725
6,38650.0,23.30,72.500000,6.220000,6.10,19.82,36.630,-0.984781,24.635744,-1.825088,-1.83,4.5,11.8,0.000010,293.382353,61.528149
7,38300.0,23.06,72.200000,6.170000,5.87,20.45,38.633,-1.015764,24.631415,-2.267616,6.42,3.8,12.8,0.000009,259.890110,39.404991
8,38350.0,23.30,71.800000,6.050000,5.78,22.30,39.230,-0.398683,24.522817,-1.810725,7.54,2.8,12.4,0.000008,235.218978,16.873910
9,39230.0,23.48,72.400000,6.200000,5.70,20.06,38.943,-1.055550,23.868773,-1.298460,2.19,2.9,11.6,0.000009,229.090909,18.148198
10,40430.0,24.47,73.200000,6.300000,5.40,20.04,40.857,0.393848,22.949098,-0.443691,6.66,1.8,11.5,0.000008,252.268603,38.082226
11,40860.0,24.11,75.300000,6.200000,5.30,16.96,41.185,-0.845174,23.055130,-0.006899,-3.84,0.9,12.0,0.000009,251.268116,33.548519
12,41370.0,24.15,76.200000,6.300000,5.30,17.13,42.807,0.672486,23.318576,0.316119,6.10,1.3,11.6,0.000008,239.311594,28.720087
13,40270.0,24.23,75.500000,6.232308,5.30,21.19,43.939,0.244091,24.420548,-5.502841,-0.94,1.5,12.2,0.000007,287.160940,26.447993
14,41270.0,24.23,76.800000,6.232308,5.30,17.06,42.819,0.054268,24.795388,-2.322281,8.01,2.6,10.8,0.000007,281.046931,40.928569
15,41470.0,25.18,78.400000,6.232308,5.30,14.14,47.740,-1.992973,24.149022,-0.031939,4.67,2.8,12.7,0.000007,279.316547,32.630811

In [14]:
fi = pd.DataFrame()
fi = df_fi.copy()
fi['EUPC_3'] = fi['EUPC'].shift(3)

In [15]:
fi = fi.dropna()

In [16]:
discretised_fi = discretize_data(fi)

Data types after discretization:
object    17
Name: count, dtype: int64

Unique states per column:
GDPC      3
VABI      3
EMP       3
QOA       3
QOR       2
YUA       3
REST      3
EBSG      3
GGFC      3
LBGD      3
FDI       3
PC        3
ARP       3
CO2C      3
PAM       3
EUPC      3
EUPC_3    3
dtype: int64

Discretised data preview:
     GDPC  VABI     EMP     QOA   QOR     YUA REST    EBSG    GGFC    LBGD  \
3  Medium  High     Low     Low  High    High  Low    High     Low     Low
4  Medium  High  Medium     Low   Low  Medium  Low  Medium     Low    High
5     Low   Low  Medium     Low  High     Low  Low     Low  Medium  Medium
6     Low   Low     Low  Medium  High  Medium  Low     Low    High  Medium
7     Low   Low     Low     Low  High    High  Low     Low    High     Low

      FDI    PC   ARP    CO2C     PAM    EUPC  EUPC_3
3  Medium  High  High    High    High     Low     Low
4     Low  High  High    High    High    High     Low
5  Medium  High  High    High    High    High  Medium
6     Low  High   Low    High    High    High  Medium
7    High  High  High  Medium  Medium  Medium    High

In [17]:
sm = StructureModel()

In [18]:
sm.add_edges_from([
    ('EUPC_3', 'YUA')
])

In [19]:
sm.edges

OutEdgeView([('EUPC_3', 'YUA')])

In [20]:
viz = plot_structure(
    sm,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)

viz.toggle_physics(False)
viz.show("Graphs/fully_connected_dk_1.html")

Graphs/fully_connected_dk_1.html

In [21]:
sm_baseline = sm.copy()
bn_baseline = BayesianNetwork(sm_baseline)
bn_baseline.fit_node_states(discretised_fi)
bn_baseline.fit_cpds(discretised_fi, method="BayesianEstimator", bayes_prior="K2")
baseline_bic, _ = calculate_bic(bn_baseline, discretised_fi)
print(f"BASELINE BIC: {baseline_bic:.2f}")

# ==========================================
# TEST #1: (EUPC_3  -> YUA)
# ==========================================
print("\n--- Testing EUPC_3 -> YUA ---")

sm_test_1 = sm_baseline.copy()

bn_with_lv_1, data_with_lv_1, bic_lv_1 = add_latent_variable_gmm(
    bn_baseline=bn_baseline,
    sm_baseline=sm_test_1,
    children_cols=['EUPC_3', 'YUA'], 
    discretised_data=discretised_fi,
    raw_data=fi
)

BASELINE BIC: 71.28

--- Testing EUPC_3 -> YUA ---
Estimating LV based on continuous GMM distributions in: ['EUPC_3', 'YUA']
  - Removing direct edge: EUPC_3 -> YUA
LV Model BIC: 86.52 (LogLikelihood: -31.72)

In [51]:
df_fi = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/fi_bn_no_context.csv")

df_fi = df_fi.drop(["Unnamed: 0"], axis = 1)

df_fi

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,41650.0,30.67,73.892857,6.310000,5.64,16.43,29.561,4.794744,20.768314,5.292982,8.57,4.4,13.0,0.000013,341.020794,6.033898
1,41780.0,29.57,73.892857,6.430000,5.84,16.34,31.071,3.615903,21.566205,4.569814,6.79,4.9,13.6,0.000011,338.794727,9.016756
2,38230.0,25.66,72.600000,6.330000,5.89,21.38,31.045,2.038683,24.069112,-1.860401,-3.48,4.7,13.8,0.000011,338.202247,34.478428
3,39260.0,26.19,71.900000,6.150000,5.86,21.29,32.166,1.364890,23.685735,-2.369424,4.90,4.4,13.1,0.000012,322.947761,27.559638
4,40010.0,25.04,72.700000,6.160000,5.83,19.93,32.532,-0.781159,23.401887,-0.488730,-2.18,4.8,13.7,0.000011,306.122449,44.801132
5,39210.0,23.36,73.000000,6.200000,6.09,18.87,34.222,-1.560551,24.176307,-1.104413,1.92,4.7,13.2,0.000010,313.863216,40.733725
6,38650.0,23.30,72.500000,6.220000,6.10,19.82,36.630,-0.984781,24.635744,-1.825088,-1.83,4.5,11.8,0.000010,293.382353,61.528149
7,38300.0,23.06,72.200000,6.170000,5.87,20.45,38.633,-1.015764,24.631415,-2.267616,6.42,3.8,12.8,0.000009,259.890110,39.404991
8,38350.0,23.30,71.800000,6.050000,5.78,22.30,39.230,-0.398683,24.522817,-1.810725,7.54,2.8,12.4,0.000008,235.218978,16.873910
9,39230.0,23.48,72.400000,6.200000,5.70,20.06,38.943,-1.055550,23.868773,-1.298460,2.19,2.9,11.6,0.000009,229.090909,18.148198
10,40430.0,24.47,73.200000,6.300000,5.40,20.04,40.857,0.393848,22.949098,-0.443691,6.66,1.8,11.5,0.000008,252.268603,38.082226
11,40860.0,24.11,75.300000,6.200000,5.30,16.96,41.185,-0.845174,23.055130,-0.006899,-3.84,0.9,12.0,0.000009,251.268116,33.548519
12,41370.0,24.15,76.200000,6.300000,5.30,17.13,42.807,0.672486,23.318576,0.316119,6.10,1.3,11.6,0.000008,239.311594,28.720087
13,40270.0,24.23,75.500000,6.232308,5.30,21.19,43.939,0.244091,24.420548,-5.502841,-0.94,1.5,12.2,0.000007,287.160940,26.447993
14,41270.0,24.23,76.800000,6.232308,5.30,17.06,42.819,0.054268,24.795388,-2.322281,8.01,2.6,10.8,0.000007,281.046931,40.928569
15,41470.0,25.18,78.400000,6.232308,5.30,14.14,47.740,-1.992973,24.149022,-0.031939,4.67,2.8,12.7,0.000007,279.316547,32.630811

In [52]:
fi = pd.DataFrame()
fi = df_fi.copy()

In [53]:
fi = fi.dropna()

In [54]:
discretised_fi = discretize_data(fi)

Data types after discretization:
object    16
Name: count, dtype: int64

Unique states per column:
GDPC    3
VABI    3
EMP     3
QOA     3
QOR     3
YUA     3
REST    3
EBSG    3
GGFC    3
LBGD    3
FDI     3
PC      3
ARP     3
CO2C    3
PAM     3
EUPC    3
dtype: int64

Discretised data preview:
     GDPC    VABI     EMP   QOA     QOR     YUA REST    EBSG    GGFC    LBGD  \
0    High    High  Medium  High  Medium     Low  Low    High     Low    High
1    High    High  Medium  High  Medium     Low  Low    High     Low    High
2     Low    High     Low  High    High    High  Low    High  Medium     Low
3  Medium    High     Low   Low    High    High  Low    High  Medium     Low
4  Medium  Medium  Medium   Low  Medium  Medium  Low  Medium     Low  Medium

      FDI      PC     ARP  CO2C     PAM    EUPC
0    High  Medium  Medium  High    High     Low
1    High    High    High  High    High     Low
2     Low    High    High  High    High  Medium
3  Medium  Medium    High  High    High     Low
4     Low    High    High  High  Medium    High

In [55]:
sm = StructureModel()

In [56]:
sm.add_edges_from([
    ('EUPC', 'FDI'),
    ('EUPC', 'ARP')
])

In [57]:
sm.edges

OutEdgeView([('EUPC', 'FDI'), ('EUPC', 'ARP')])

In [58]:
viz = plot_structure(
    sm,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)

viz.toggle_physics(False)
viz.show("Graphs/fully_connected_dk_1.html")

Graphs/fully_connected_dk_1.html

In [59]:
sm_baseline = sm.copy()
bn_baseline = BayesianNetwork(sm_baseline)
bn_baseline.fit_node_states(discretised_fi)
bn_baseline.fit_cpds(discretised_fi, method="BayesianEstimator", bayes_prior="K2")
baseline_bic, _ = calculate_bic(bn_baseline, discretised_fi)
print(f"BASELINE BIC: {baseline_bic:.2f}")

# ==========================================
# TEST #1: (EUPC  -> FDI)
# ==========================================
print("\n--- Testing EUPC -> FDI ---")

sm_test_1 = sm_baseline.copy()

bn_with_lv_1, data_with_lv_1, bic_lv_1 = add_latent_variable_gmm(
    bn_baseline=bn_baseline,
    sm_baseline=sm_test_1,
    children_cols=['EUPC', 'FDI'], 
    discretised_data=discretised_fi,
    raw_data=fi
)

# ==========================================
# TEST #2: (EUPC -> ARP)
# ==========================================
print("\n--- Testing EUPC -> ARP ---")

sm_test_2 = sm_baseline.copy()

bn_with_lv_2, data_with_lv_2, bic_lv_2 = add_latent_variable_gmm(
    bn_baseline=bn_baseline,
    sm_baseline=sm_test_2,
    children_cols=['EUPC', 'ARP'], 
    discretised_data=discretised_fi,
    raw_data=fi
)

# # ==========================================
# # TEST #3: (ARP -> EUPC)
# # ==========================================
# print("\n--- Testing ARP -> EUPC ---")

# sm_test_3 = sm_baseline.copy()

# bn_with_lv_3, data_with_lv_3, bic_lv_3 = add_latent_variable_gmm(
#     bn_baseline=bn_baseline,
#     sm_baseline=sm_test_3,
#     children_cols=['ARP', 'EUPC'], 
#     discretised_data=discretised_fi,
#     raw_data=fi
# )

BASELINE BIC: 137.71

--- Testing EUPC -> FDI ---
Estimating LV based on continuous GMM distributions in: ['EUPC', 'FDI']
  - Removing direct edge: EUPC -> FDI
LV Model BIC: 147.59 (LogLikelihood: -53.00)

--- Testing EUPC -> ARP ---
Estimating LV based on continuous GMM distributions in: ['EUPC', 'ARP']
  - Removing direct edge: EUPC -> ARP
LV Model BIC: 157.13 (LogLikelihood: -57.77)

In [61]:
df_fi = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/fi_bn_no_context.csv")

df_fi = df_fi.drop(["Unnamed: 0"], axis = 1)

df_fi

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,41650.0,30.67,73.892857,6.310000,5.64,16.43,29.561,4.794744,20.768314,5.292982,8.57,4.4,13.0,0.000013,341.020794,6.033898
1,41780.0,29.57,73.892857,6.430000,5.84,16.34,31.071,3.615903,21.566205,4.569814,6.79,4.9,13.6,0.000011,338.794727,9.016756
2,38230.0,25.66,72.600000,6.330000,5.89,21.38,31.045,2.038683,24.069112,-1.860401,-3.48,4.7,13.8,0.000011,338.202247,34.478428
3,39260.0,26.19,71.900000,6.150000,5.86,21.29,32.166,1.364890,23.685735,-2.369424,4.90,4.4,13.1,0.000012,322.947761,27.559638
4,40010.0,25.04,72.700000,6.160000,5.83,19.93,32.532,-0.781159,23.401887,-0.488730,-2.18,4.8,13.7,0.000011,306.122449,44.801132
5,39210.0,23.36,73.000000,6.200000,6.09,18.87,34.222,-1.560551,24.176307,-1.104413,1.92,4.7,13.2,0.000010,313.863216,40.733725
6,38650.0,23.30,72.500000,6.220000,6.10,19.82,36.630,-0.984781,24.635744,-1.825088,-1.83,4.5,11.8,0.000010,293.382353,61.528149
7,38300.0,23.06,72.200000,6.170000,5.87,20.45,38.633,-1.015764,24.631415,-2.267616,6.42,3.8,12.8,0.000009,259.890110,39.404991
8,38350.0,23.30,71.800000,6.050000,5.78,22.30,39.230,-0.398683,24.522817,-1.810725,7.54,2.8,12.4,0.000008,235.218978,16.873910
9,39230.0,23.48,72.400000,6.200000,5.70,20.06,38.943,-1.055550,23.868773,-1.298460,2.19,2.9,11.6,0.000009,229.090909,18.148198
10,40430.0,24.47,73.200000,6.300000,5.40,20.04,40.857,0.393848,22.949098,-0.443691,6.66,1.8,11.5,0.000008,252.268603,38.082226
11,40860.0,24.11,75.300000,6.200000,5.30,16.96,41.185,-0.845174,23.055130,-0.006899,-3.84,0.9,12.0,0.000009,251.268116,33.548519
12,41370.0,24.15,76.200000,6.300000,5.30,17.13,42.807,0.672486,23.318576,0.316119,6.10,1.3,11.6,0.000008,239.311594,28.720087
13,40270.0,24.23,75.500000,6.232308,5.30,21.19,43.939,0.244091,24.420548,-5.502841,-0.94,1.5,12.2,0.000007,287.160940,26.447993
14,41270.0,24.23,76.800000,6.232308,5.30,17.06,42.819,0.054268,24.795388,-2.322281,8.01,2.6,10.8,0.000007,281.046931,40.928569
15,41470.0,25.18,78.400000,6.232308,5.30,14.14,47.740,-1.992973,24.149022,-0.031939,4.67,2.8,12.7,0.000007,279.316547,32.630811

In [62]:
fi = pd.DataFrame()
fi = df_fi.copy()

In [63]:
fi = fi.dropna()

In [64]:
discretised_fi = discretize_data(fi)

Data types after discretization:
object    16
Name: count, dtype: int64

Unique states per column:
GDPC    3
VABI    3
EMP     3
QOA     3
QOR     3
YUA     3
REST    3
EBSG    3
GGFC    3
LBGD    3
FDI     3
PC      3
ARP     3
CO2C    3
PAM     3
EUPC    3
dtype: int64

Discretised data preview:
     GDPC    VABI     EMP   QOA     QOR     YUA REST    EBSG    GGFC    LBGD  \
0    High    High  Medium  High  Medium     Low  Low    High     Low    High
1    High    High  Medium  High  Medium     Low  Low    High     Low    High
2     Low    High     Low  High    High    High  Low    High  Medium     Low
3  Medium    High     Low   Low    High    High  Low    High  Medium     Low
4  Medium  Medium  Medium   Low  Medium  Medium  Low  Medium     Low  Medium

      FDI      PC     ARP  CO2C     PAM    EUPC
0    High  Medium  Medium  High    High     Low
1    High    High    High  High    High     Low
2     Low    High    High  High    High  Medium
3  Medium  Medium    High  High    High     Low
4     Low    High    High  High  Medium    High

In [65]:
sm = StructureModel()

In [66]:
sm.add_edges_from([
    ('ARP', 'EUPC')
])

In [67]:
sm.edges

OutEdgeView([('ARP', 'EUPC')])

In [68]:
viz = plot_structure(
    sm,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)

viz.toggle_physics(False)
viz.show("Graphs/fully_connected_dk_1.html")

Graphs/fully_connected_dk_1.html

In [69]:
sm_baseline = sm.copy()
bn_baseline = BayesianNetwork(sm_baseline)
bn_baseline.fit_node_states(discretised_fi)
bn_baseline.fit_cpds(discretised_fi, method="BayesianEstimator", bayes_prior="K2")
baseline_bic, _ = calculate_bic(bn_baseline, discretised_fi)
print(f"BASELINE BIC: {baseline_bic:.2f}")


# ==========================================
# TEST #3: (ARP -> EUPC)
# ==========================================
print("\n--- Testing ARP -> EUPC ---")

sm_test_3 = sm_baseline.copy()

bn_with_lv_3, data_with_lv_3, bic_lv_3 = add_latent_variable_gmm(
    bn_baseline=bn_baseline,
    sm_baseline=sm_test_3,
    children_cols=['ARP', 'EUPC'], 
    discretised_data=discretised_fi,
    raw_data=fi
)

BASELINE BIC: 89.81

--- Testing ARP -> EUPC ---
Estimating LV based on continuous GMM distributions in: ['ARP', 'EUPC']
  - Removing direct edge: ARP -> EUPC
LV Model BIC: 109.17 (LogLikelihood: -42.11)