In [5]:
import warnings
from causalnex.structure import StructureModel
warnings.filterwarnings("ignore") 
from causalnex.structure.notears import from_pandas
from causalnex.plots import plot_structure, NODE_STYLE, EDGE_STYLE
from causalnex.network import BayesianNetwork
import pandas as pd
from causalnex.discretiser import Discretiser
import numpy as np
from sklearn.model_selection import train_test_split
from causalnex.structure.notears import from_pandas_lasso
from IPython.display import Image
from causalnex.evaluation import classification_report
from causalnex.evaluation import roc_auc
from causalnex.inference import InferenceEngine
from causalnex.evaluation import classification_report
import copy
import networkx as nx
import turtorial_utils as utils
from sklearn.cluster import KMeans

In [61]:
def calculate_bic(bn, data):
    """
    Calculates BIC score for a CausalNex BayesianNetwork.
    Formula: BIC = k * ln(n) - 2 * ln(L)
    Returns: bic, log_likelihood
    """
    log_likelihood = 0
    k = 0
    n = len(data)

    for node in bn.nodes:
        cpd = bn.cpds[node]
        
        probs = bn.predict_probability(data, node)
        
        true_values = data[node]
        
        y_dummies = pd.get_dummies(true_values)
        
        y_dummies = y_dummies.reindex(columns=probs.columns, fill_value=0)
        
        p_actual = (probs * y_dummies).sum(axis=1)
        
        log_likelihood += np.sum(np.log(p_actual + 1e-9))

        num_parent_configs = cpd.shape[0]
        num_node_states = cpd.shape[1]
        k += num_parent_configs * (num_node_states - 1)

    bic = k * np.log(n) - 2 * log_likelihood
    
    return bic, log_likelihood

In [7]:
from sklearn.mixture import GaussianMixture # <--- NEW IMPORT
from sklearn.preprocessing import StandardScaler
import itertools

def add_latent_variable_gmm(bn_baseline, sm_baseline, children_cols, discretised_data, raw_data=None):
    
    if raw_data is None:
        raise ValueError("You must provide the continuous 'raw_data' to accurately estimate the Latent Variable.")
        
    subset_data = raw_data[children_cols].loc[discretised_data.index].copy()
    
    
    print(f"Estimating LV based on continuous GMM distributions in: {children_cols}")

    scaler = StandardScaler()
    subset_data_scaled = scaler.fit_transform(subset_data)
    
    gmm = GaussianMixture(n_components=2, random_state=42, n_init=10)
    proxy_lv = gmm.fit_predict(subset_data_scaled)
    
    discretised_with_lv = discretised_data.copy()
    discretised_with_lv['LV'] = proxy_lv
    discretised_with_lv['LV'] = discretised_with_lv['LV'].map({0: "State0", 1: "State1"})
    
    sm_with_lv = sm_baseline.copy()
    sm_with_lv.add_node('LV')
    
    for child in children_cols:
        sm_with_lv.add_edge('LV', child)
        
    for u, v in itertools.permutations(children_cols, 2):
        if sm_with_lv.has_edge(u, v):
            print(f"  - Removing direct edge: {u} -> {v}")
            sm_with_lv.remove_edge(u, v)

    bn_with_lv = BayesianNetwork(sm_with_lv)
    bn_with_lv.fit_node_states(discretised_with_lv)
    bn_with_lv.fit_cpds(discretised_with_lv, method="BayesianEstimator", bayes_prior="K2")
    
    bic_lv, ll_lv = calculate_bic(bn_with_lv, discretised_with_lv)
    print(f"LV Model BIC: {bic_lv:.2f} (LogLikelihood: {ll_lv:.2f})")
    
    return bn_with_lv, discretised_with_lv, bic_lv

In [8]:
df_fi = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/fi_bn_no_context.csv")

df_fi = df_fi.drop(["Unnamed: 0"], axis = 1)

df_fi

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,35369.427763,30.67,73.892857,6.310000,5.64,16.43,29.561,4.794744,20.768314,5.292982,8.57,4.4,13.0,0.000013,341.020794,6.033898
1,36559.083931,29.57,73.892857,6.430000,5.84,16.34,31.071,3.615903,21.566205,4.569814,6.79,4.9,13.6,0.000011,338.794727,9.016756
2,34039.968375,25.66,72.600000,6.330000,5.89,21.38,31.045,2.038683,24.069112,-1.860401,-3.48,4.7,13.8,0.000011,338.202247,34.478428
3,35080.114078,26.19,71.900000,6.150000,5.86,21.29,32.166,1.364890,23.685735,-2.369424,4.90,4.4,13.1,0.000012,322.947761,27.559638
4,36682.446617,25.04,72.700000,6.160000,5.83,19.93,32.532,-0.781159,23.401887,-0.488730,-2.18,4.8,13.7,0.000011,306.122449,44.801132
5,37011.280629,23.36,73.000000,6.200000,6.09,18.87,34.222,-1.560551,24.176307,-1.104413,1.92,4.7,13.2,0.000010,313.863216,40.733725
6,37414.607025,23.30,72.500000,6.220000,6.10,19.82,36.630,-0.984781,24.635744,-1.825088,-1.83,4.5,11.8,0.000010,293.382353,61.528149
7,37691.943183,23.06,72.200000,6.170000,5.87,20.45,38.633,-1.015764,24.631415,-2.267616,6.42,3.8,12.8,0.000009,259.890110,39.404991
8,38359.487336,23.30,71.800000,6.050000,5.78,22.30,39.230,-0.398683,24.522817,-1.810725,7.54,2.8,12.4,0.000008,235.218978,16.873910
9,39254.796323,23.48,72.400000,6.200000,5.70,20.06,38.943,-1.055550,23.868773,-1.298460,2.19,2.9,11.6,0.000009,229.090909,18.148198
10,40794.711317,24.47,73.200000,6.300000,5.40,20.04,40.857,0.393848,22.949098,-0.443691,6.66,1.8,11.5,0.000008,252.268603,38.082226
11,42045.861455,24.11,75.300000,6.200000,5.30,16.96,41.185,-0.845174,23.055130,-0.006899,-3.84,0.9,12.0,0.000009,251.268116,33.548519
12,43197.214723,24.15,76.200000,6.300000,5.30,17.13,42.807,0.672486,23.318576,0.316119,6.10,1.3,11.6,0.000008,239.311594,28.720087
13,42749.825799,24.23,75.500000,6.232308,5.30,21.19,43.939,0.244091,24.420548,-5.502841,-0.94,1.5,12.2,0.000007,287.160940,26.447993
14,44895.007541,24.23,76.800000,6.232308,5.30,17.06,42.819,0.054268,24.795388,-2.322281,8.01,2.6,10.8,0.000007,281.046931,40.928569
15,47899.554112,25.18,78.400000,6.232308,5.30,14.14,47.740,-1.992973,24.149022,-0.031939,4.67,2.8,12.7,0.000007,279.316547,32.630811

In [9]:
fi = pd.DataFrame()
fi = df_fi.copy()
fi['EUPC_3'] = fi['EUPC'].shift(3)
fi['GGFC_3'] = fi['GGFC'].shift(3)
fi['QOR_2'] = fi['QOR'].shift(2)
fi['CO2C_1'] = fi['CO2C'].shift(1)

In [10]:
fi = fi.dropna()

In [11]:
discretised_fi = pd.DataFrame(index=fi.index)

for col in fi.columns:
    no_unique = fi[col].nunique()
    
    if no_unique <= 1:
        discretised_fi[col] = 0
    else:
        try:
            discretised_fi[col] = pd.qcut(
                fi[col], 
                q=min(2, no_unique),  
                labels=False,
                duplicates='drop'
            ).astype(int)
        except ValueError:
            discretised_fi[col] = fi[col].rank(method='lvnse').astype(int) - 1
    num_states = discretised_fi[col].nunique()
    
    if num_states == 2:
        discretised_fi[col] = discretised_fi[col].map({0: "Low", 1: "High"})
    elif num_states == 3:
        discretised_fi[col] = discretised_fi[col].map({0: "Low", 1: "Medium", 2: "High"})
    else:
        discretised_fi[col] = discretised_fi[col].astype(str)

print("Discretised data:")
print(discretised_fi)

Discretised data:
    GDPC  VABI   EMP   QOA   QOR   YUA  REST  EBSG  GGFC  LBGD   FDI    PC  \
3    Low  High   Low   Low  High  High   Low  High   Low   Low  High  High
4    Low  High   Low   Low  High   Low   Low   Low   Low  High   Low  High
5    Low   Low   Low   Low  High   Low   Low   Low  High  High   Low  High
6    Low   Low   Low  High  High   Low   Low   Low  High   Low   Low  High
7    Low   Low   Low   Low  High  High   Low   Low  High   Low  High  High
8    Low   Low   Low   Low  High  High   Low  High  High   Low  High   Low
9    Low   Low   Low   Low   Low  High   Low   Low   Low   Low   Low  High
10  High  High  High  High   Low  High  High  High   Low  High  High   Low
11  High   Low  High   Low   Low   Low  High   Low   Low  High   Low   Low
12  High   Low  High  High   Low   Low  High  High   Low  High  High   Low
13  High  High  High  High   Low  High  High  High  High   Low   Low   Low
14  High  High  High  High   Low   Low  High  High  High   Low  High   Low
15  High  High  High  High   Low   Low  High   Low   Low  High   Low   Low

     ARP  CO2C   PAM  EUPC EUPC_3 GGFC_3 QOR_2 CO2C_1
3   High  High  High   Low    Low    Low  High   High
4   High  High  High  High    Low    Low  High   High
5   High  High  High  High   High   High  High   High
6    Low  High  High  High    Low    Low   Low   High
7   High  High   Low  High   High    Low  High   High
8   High   Low   Low   Low   High   High  High   High
9    Low  High   Low   Low   High   High  High    Low
10   Low   Low   Low  High   High   High   Low    Low
11   Low   Low   Low   Low    Low   High   Low    Low
12   Low   Low   Low   Low    Low   High   Low    Low
13   Low   Low  High   Low   High    Low   Low    Low
14   Low   Low  High  High    Low    Low   Low    Low
15  High   Low   Low   Low    Low    Low   Low    Low

In [12]:
sm = StructureModel()

In [13]:
sm.add_edges_from([  
    ('EUPC_3', 'YUA'),
     ('LBGD', 'YUA'),
    ('QOA', 'LBGD'),
     ('GGFC_3', 'LBGD'),
    ('QOR_2', 'QOA'),
    ('CO2C_1', 'QOA'),
    ('CO2C_1', 'GGFC')
])

In [14]:
sm.edges

OutEdgeView([('EUPC_3', 'YUA'), ('LBGD', 'YUA'), ('QOA', 'LBGD'), ('GGFC_3', 'LBGD'), ('QOR_2', 'QOA'), ('CO2C_1', 'QOA'), ('CO2C_1', 'GGFC')])

In [15]:
viz = plot_structure(
    sm,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)

viz.toggle_physics(False)
viz.show("Graphs/fully_connected_dk_1.html")

Graphs/fully_connected_dk_1.html

In [16]:
bn = BayesianNetwork(sm)

bn.fit_node_states(discretised_fi)

bn.fit_cpds(discretised_fi, method="BayesianEstimator", bayes_prior="K2")

bic_baseline, ll_baseline = calculate_bic(bn, discretised_fi)
print(f"Baseline BIC: {bic_baseline:.2f} (LogLikelihood: {ll_baseline:.2f})")

Baseline BIC: 4361.74 (LogLikelihood: -2155.22)

In [19]:
bn_with_lv_1, data_with_lv_1, bic_lv_1 = add_latent_variable_gmm(
    bn_baseline=bn,
    sm_baseline=sm,
    children_cols=['EUPC_3', 'YUA'],
    discretised_data=discretised_fi,
    raw_data=fi
)

Estimating LV based on continuous GMM distributions in: ['EUPC_3', 'YUA']
  - Removing direct edge: EUPC_3 -> YUA
LV Model BIC: 4905.67 (LogLikelihood: -2424.62)

In [32]:
import warnings
from causalnex.structure import StructureModel
warnings.filterwarnings("ignore") 
from causalnex.structure.notears import from_pandas
from causalnex.plots import plot_structure, NODE_STYLE, EDGE_STYLE
from causalnex.network import BayesianNetwork
import pandas as pd
from causalnex.discretiser import Discretiser
import numpy as np
from sklearn.model_selection import train_test_split
from causalnex.structure.notears import from_pandas_lasso
from IPython.display import Image
from causalnex.evaluation import classification_report
from causalnex.evaluation import roc_auc
from causalnex.inference import InferenceEngine
from causalnex.evaluation import classification_report
import copy
import networkx as nx
import turtorial_utils as utils
from sklearn.cluster import KMeans

In [33]:
df_fi = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/fi_bn_no_context.csv")

df_fi = df_fi.drop(["Unnamed: 0"], axis = 1)

df_fi

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,35369.427763,30.67,73.892857,6.310000,5.64,16.43,29.561,4.794744,20.768314,5.292982,8.57,4.4,13.0,0.000013,341.020794,6.033898
1,36559.083931,29.57,73.892857,6.430000,5.84,16.34,31.071,3.615903,21.566205,4.569814,6.79,4.9,13.6,0.000011,338.794727,9.016756
2,34039.968375,25.66,72.600000,6.330000,5.89,21.38,31.045,2.038683,24.069112,-1.860401,-3.48,4.7,13.8,0.000011,338.202247,34.478428
3,35080.114078,26.19,71.900000,6.150000,5.86,21.29,32.166,1.364890,23.685735,-2.369424,4.90,4.4,13.1,0.000012,322.947761,27.559638
4,36682.446617,25.04,72.700000,6.160000,5.83,19.93,32.532,-0.781159,23.401887,-0.488730,-2.18,4.8,13.7,0.000011,306.122449,44.801132
5,37011.280629,23.36,73.000000,6.200000,6.09,18.87,34.222,-1.560551,24.176307,-1.104413,1.92,4.7,13.2,0.000010,313.863216,40.733725
6,37414.607025,23.30,72.500000,6.220000,6.10,19.82,36.630,-0.984781,24.635744,-1.825088,-1.83,4.5,11.8,0.000010,293.382353,61.528149
7,37691.943183,23.06,72.200000,6.170000,5.87,20.45,38.633,-1.015764,24.631415,-2.267616,6.42,3.8,12.8,0.000009,259.890110,39.404991
8,38359.487336,23.30,71.800000,6.050000,5.78,22.30,39.230,-0.398683,24.522817,-1.810725,7.54,2.8,12.4,0.000008,235.218978,16.873910
9,39254.796323,23.48,72.400000,6.200000,5.70,20.06,38.943,-1.055550,23.868773,-1.298460,2.19,2.9,11.6,0.000009,229.090909,18.148198
10,40794.711317,24.47,73.200000,6.300000,5.40,20.04,40.857,0.393848,22.949098,-0.443691,6.66,1.8,11.5,0.000008,252.268603,38.082226
11,42045.861455,24.11,75.300000,6.200000,5.30,16.96,41.185,-0.845174,23.055130,-0.006899,-3.84,0.9,12.0,0.000009,251.268116,33.548519
12,43197.214723,24.15,76.200000,6.300000,5.30,17.13,42.807,0.672486,23.318576,0.316119,6.10,1.3,11.6,0.000008,239.311594,28.720087
13,42749.825799,24.23,75.500000,6.232308,5.30,21.19,43.939,0.244091,24.420548,-5.502841,-0.94,1.5,12.2,0.000007,287.160940,26.447993
14,44895.007541,24.23,76.800000,6.232308,5.30,17.06,42.819,0.054268,24.795388,-2.322281,8.01,2.6,10.8,0.000007,281.046931,40.928569
15,47899.554112,25.18,78.400000,6.232308,5.30,14.14,47.740,-1.992973,24.149022,-0.031939,4.67,2.8,12.7,0.000007,279.316547,32.630811

In [34]:
fi = pd.DataFrame()
fi = df_fi.copy()
fi['EUPC_2'] = fi['EUPC'].shift(2)

In [35]:
fi = fi.dropna()

In [36]:
discretised_fi = pd.DataFrame(index=fi.index)

for col in fi.columns:
    no_unique = fi[col].nunique()
    
    if no_unique <= 1:
        discretised_fi[col] = 0
    else:
        try:
            discretised_fi[col] = pd.qcut(
                fi[col], 
                q=min(2, no_unique),  
                labels=False,
                duplicates='drop'
            ).astype(int)
        except ValueError:
            discretised_fi[col] = fi[col].rank(method='finse').astype(int) - 1
    num_states = discretised_fi[col].nunique()
    
    if num_states == 2:
        discretised_fi[col] = discretised_fi[col].map({0: "Low", 1: "High"})
    elif num_states == 3:
        discretised_fi[col] = discretised_fi[col].map({0: "Low", 1: "Medium", 2: "High"})
    else:
        discretised_fi[col] = discretised_fi[col].astype(str)

print("Discretised data:")
print(discretised_fi)

Discretised data:
    GDPC  VABI   EMP   QOA   QOR   YUA  REST  EBSG  GGFC  LBGD   FDI    PC  \
2    Low  High   Low  High  High  High   Low  High   Low   Low   Low  High
3    Low  High   Low   Low  High  High   Low  High   Low   Low  High  High
4    Low  High   Low   Low  High   Low   Low   Low   Low  High   Low  High
5    Low   Low  High   Low  High   Low   Low   Low  High  High   Low  High
6    Low   Low   Low  High  High   Low   Low   Low  High   Low   Low  High
7    Low   Low   Low   Low  High  High   Low   Low  High   Low  High  High
8    Low   Low   Low   Low  High  High  High  High  High   Low  High   Low
9   High   Low   Low   Low   Low  High   Low   Low   Low  High   Low  High
10  High  High  High  High   Low  High  High  High   Low  High  High   Low
11  High   Low  High   Low   Low   Low  High   Low   Low  High   Low   Low
12  High   Low  High  High   Low   Low  High  High   Low  High  High   Low
13  High  High  High  High   Low  High  High  High  High   Low   Low   Low
14  High  High  High  High   Low   Low  High  High  High   Low  High   Low
15  High  High  High  High   Low   Low  High   Low  High  High  High   Low

     ARP  CO2C   PAM  EUPC EUPC_2
2   High  High  High  High    Low
3   High  High  High   Low    Low
4   High  High  High  High   High
5   High  High  High  High    Low
6    Low  High  High  High   High
7   High  High   Low  High   High
8   High   Low   Low   Low   High
9    Low  High   Low   Low   High
10   Low   Low   Low  High    Low
11   Low   Low   Low   Low    Low
12   Low   Low   Low   Low   High
13   Low   Low  High   Low   High
14   Low   Low  High  High    Low
15  High   Low   Low   Low    Low

In [37]:
sm = StructureModel()

In [38]:
sm.add_edges_from([
    ('EUPC_2', 'FDI'),
    ('EUPC_2', 'ARP'),
])

In [39]:
sm.edges

OutEdgeView([('EUPC_2', 'FDI'), ('EUPC_2', 'ARP')])

In [40]:
viz = plot_structure(
    sm,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)

viz.toggle_physics(False)
viz.show("Graphs/fully_connected_dk_2.html")

Graphs/fully_connected_dk_2.html

In [41]:
bn = BayesianNetwork(sm)

bn.fit_node_states(discretised_fi)

bn.fit_cpds(discretised_fi, method="BayesianEstimator", bayes_prior="K2")

bic_baseline, ll_baseline = calculate_bic(bn, discretised_fi)
print(f"Baseline BIC: {bic_baseline:.2f} (LogLikelihood: {ll_baseline:.2f})")

Baseline BIC: 1751.31 (LogLikelihood: -870.38)

In [42]:
bn_with_lv, data_with_lv, bic_lv = add_latent_variable_gmm(
    bn_baseline=bn,
    sm_baseline=sm,
    children_cols=['EUPC_2', 'FDI'],
    discretised_data=discretised_fi,
    raw_data=fi
)

Estimating LV based on continuous GMM distributions in: ['EUPC_2', 'FDI']
  - Removing direct edge: EUPC_2 -> FDI
LV Model BIC: 2336.84 (LogLikelihood: -1160.50)

In [45]:
bn_with_lv, data_with_lv, bic_lv = add_latent_variable_gmm(
    bn_baseline=bn,
    sm_baseline=sm,
    children_cols=['EUPC_2', 'ARP'],
    discretised_data=discretised_fi,
    raw_data=fi
)

Estimating LV based on continuous GMM distributions in: ['EUPC_2', 'ARP']
  - Removing direct edge: EUPC_2 -> ARP
LV Model BIC: 2336.84 (LogLikelihood: -1160.50)

In [46]:
import warnings
from causalnex.structure import StructureModel
warnings.filterwarnings("ignore") 
from causalnex.structure.notears import from_pandas
from causalnex.plots import plot_structure, NODE_STYLE, EDGE_STYLE
from causalnex.network import BayesianNetwork
import pandas as pd
from causalnex.discretiser import Discretiser
import numpy as np
from sklearn.model_selection import train_test_split
from causalnex.structure.notears import from_pandas_lasso
from IPython.display import Image
from causalnex.evaluation import classification_report
from causalnex.evaluation import roc_auc
from causalnex.inference import InferenceEngine
from causalnex.evaluation import classification_report
import copy
import networkx as nx
import turtorial_utils as utils
from sklearn.cluster import KMeans

In [47]:
df_fi = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/fi_bn_no_context.csv")

df_fi = df_fi.drop(["Unnamed: 0"], axis = 1)

df_fi

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,35369.427763,30.67,73.892857,6.310000,5.64,16.43,29.561,4.794744,20.768314,5.292982,8.57,4.4,13.0,0.000013,341.020794,6.033898
1,36559.083931,29.57,73.892857,6.430000,5.84,16.34,31.071,3.615903,21.566205,4.569814,6.79,4.9,13.6,0.000011,338.794727,9.016756
2,34039.968375,25.66,72.600000,6.330000,5.89,21.38,31.045,2.038683,24.069112,-1.860401,-3.48,4.7,13.8,0.000011,338.202247,34.478428
3,35080.114078,26.19,71.900000,6.150000,5.86,21.29,32.166,1.364890,23.685735,-2.369424,4.90,4.4,13.1,0.000012,322.947761,27.559638
4,36682.446617,25.04,72.700000,6.160000,5.83,19.93,32.532,-0.781159,23.401887,-0.488730,-2.18,4.8,13.7,0.000011,306.122449,44.801132
5,37011.280629,23.36,73.000000,6.200000,6.09,18.87,34.222,-1.560551,24.176307,-1.104413,1.92,4.7,13.2,0.000010,313.863216,40.733725
6,37414.607025,23.30,72.500000,6.220000,6.10,19.82,36.630,-0.984781,24.635744,-1.825088,-1.83,4.5,11.8,0.000010,293.382353,61.528149
7,37691.943183,23.06,72.200000,6.170000,5.87,20.45,38.633,-1.015764,24.631415,-2.267616,6.42,3.8,12.8,0.000009,259.890110,39.404991
8,38359.487336,23.30,71.800000,6.050000,5.78,22.30,39.230,-0.398683,24.522817,-1.810725,7.54,2.8,12.4,0.000008,235.218978,16.873910
9,39254.796323,23.48,72.400000,6.200000,5.70,20.06,38.943,-1.055550,23.868773,-1.298460,2.19,2.9,11.6,0.000009,229.090909,18.148198
10,40794.711317,24.47,73.200000,6.300000,5.40,20.04,40.857,0.393848,22.949098,-0.443691,6.66,1.8,11.5,0.000008,252.268603,38.082226
11,42045.861455,24.11,75.300000,6.200000,5.30,16.96,41.185,-0.845174,23.055130,-0.006899,-3.84,0.9,12.0,0.000009,251.268116,33.548519
12,43197.214723,24.15,76.200000,6.300000,5.30,17.13,42.807,0.672486,23.318576,0.316119,6.10,1.3,11.6,0.000008,239.311594,28.720087
13,42749.825799,24.23,75.500000,6.232308,5.30,21.19,43.939,0.244091,24.420548,-5.502841,-0.94,1.5,12.2,0.000007,287.160940,26.447993
14,44895.007541,24.23,76.800000,6.232308,5.30,17.06,42.819,0.054268,24.795388,-2.322281,8.01,2.6,10.8,0.000007,281.046931,40.928569
15,47899.554112,25.18,78.400000,6.232308,5.30,14.14,47.740,-1.992973,24.149022,-0.031939,4.67,2.8,12.7,0.000007,279.316547,32.630811

In [51]:
fi = pd.DataFrame()
fi = df_fi.copy()

In [52]:
fi = fi.dropna()

In [53]:
discretised_fi = pd.DataFrame(index=fi.index)

for col in fi.columns:
    no_unique = fi[col].nunique()
    
    if no_unique <= 1:
        discretised_fi[col] = 0
    else:
        try:
            discretised_fi[col] = pd.qcut(
                fi[col], 
                q=min(2, no_unique),  
                labels=False,
                duplicates='drop'
            ).astype(int)
        except ValueError:
            discretised_fi[col] = fi[col].rank(method='finse').astype(int) - 1
    num_states = discretised_fi[col].nunique()
    
    if num_states == 2:
        discretised_fi[col] = discretised_fi[col].map({0: "Low", 1: "High"})
    elif num_states == 3:
        discretised_fi[col] = discretised_fi[col].map({0: "Low", 1: "Medium", 2: "High"})
    else:
        discretised_fi[col] = discretised_fi[col].astype(str)

print("Discretised data:")
print(discretised_fi)

Discretised data:
    GDPC  VABI   EMP   QOA   QOR   YUA  REST  EBSG  GGFC  LBGD   FDI    PC  \
0    Low  High  High  High   Low   Low   Low  High   Low  High  High  High
1    Low  High  High  High  High   Low   Low  High   Low  High  High  High
2    Low  High   Low  High  High  High   Low  High  High   Low   Low  High
3    Low  High   Low   Low  High  High   Low  High   Low   Low  High  High
4    Low  High   Low   Low  High  High   Low   Low   Low  High   Low  High
5    Low   Low   Low   Low  High   Low   Low   Low  High  High   Low  High
6    Low   Low   Low   Low  High   Low   Low   Low  High   Low   Low  High
7    Low   Low   Low   Low  High  High   Low   Low  High   Low  High  High
8   High   Low   Low   Low  High  High  High   Low  High   Low  High   Low
9   High   Low   Low   Low   Low  High  High   Low   Low   Low   Low   Low
10  High  High  High  High   Low  High  High  High   Low  High  High   Low
11  High   Low  High   Low   Low   Low  High   Low   Low  High   Low   Low
12  High   Low  High  High   Low   Low  High  High   Low  High  High   Low
13  High   Low  High  High   Low  High  High  High  High   Low   Low   Low
14  High   Low  High  High   Low   Low  High  High  High   Low  High   Low
15  High  High  High  High   Low   Low  High   Low  High  High   Low   Low

     ARP  CO2C   PAM  EUPC
0   High  High  High   Low
1   High  High  High   Low
2   High  High  High  High
3   High  High  High   Low
4   High  High  High  High
5   High  High  High  High
6    Low  High  High  High
7   High  High   Low  High
8    Low   Low   Low   Low
9    Low   Low   Low   Low
10   Low   Low   Low  High
11   Low   Low   Low  High
12   Low   Low   Low   Low
13   Low   Low  High   Low
14   Low   Low   Low  High
15  High   Low   Low   Low

In [54]:
sm = StructureModel()

In [55]:
sm.add_edges_from([
    ('ARP', 'EUPC'),
])

In [56]:
sm.edges

OutEdgeView([('ARP', 'EUPC')])

In [57]:
viz = plot_structure(
    sm,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)

viz.toggle_physics(False)
viz.show("Graphs/fully_connected_dk_2.html")

Graphs/fully_connected_dk_2.html

In [58]:
bn = BayesianNetwork(sm)

bn.fit_node_states(discretised_fi)

bn.fit_cpds(discretised_fi, method="BayesianEstimator", bayes_prior="K2")

bic_baseline, ll_baseline = calculate_bic(bn, discretised_fi)
print(f"Baseline BIC: {bic_baseline:.2f} (LogLikelihood: {ll_baseline:.2f})")

Baseline BIC: 1331.83 (LogLikelihood: -663.14)

In [60]:
bn_with_lv_5, data_with_lv_5, bic_lv_5 = add_latent_variable_gmm(
    bn_baseline=bn,
    sm_baseline=sm,
    children_cols=['ARP', 'EUPC'],
    discretised_data=discretised_fi,
    raw_data=fi
)

Estimating LV based on continuous GMM distributions in: ['ARP', 'EUPC']
  - Removing direct edge: ARP -> EUPC
LV Model BIC: 2000.52 (LogLikelihood: -994.72)